### ISSUE TITLE
Make "Glyphs" table be synchronized with the font texture.

### ISSUE THREAD

**Issue by VladiStep** [krzys-h/UndertaleModTool#1021]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

It would be neat if there would be a rectangle that points to the selected glyph in the "Glyphs" table (and vice versa) in the font editor.
Similar as it's done for the tileset (GMS 2) editor.

**Comment by Miepee** [comment]
Duplicate of #124
