### ISSUE TITLE
[Decompiler] [GMS 2.3] Duplicate Decompiled Function Names

### ISSUE THREAD

**Issue by steviegt6** [krzys-h/UndertaleModTool#1035]
### Describe the bug

*I haven't tested for this issue on anything other than a game using GMS 2.3, so I am unsure of which versions are affected.*

~~*This is all tested on the latest commit; the latest official release, of course, does not play well with GMS 2.3.*~~ These happen to sub-functions, which are a GMS 2.3 feature.

Decompiling `gml_GlobalScript`s with multiple functions results in every function present in that `gml_GlobalScript` taking on the name of the very last defined function. Originally, I believed this to be an issue with anonymous functions, but it occurs regardless of their presence.

A specific example:
```
function ValidKeysOnly() //gml_Script_key_to_string
{
	// ...
}

function ValidKeysOnly(argument0) //gml_Script_ValidKeysOnly
{
	// ...
}
```

Both functions take on the same name, you can see that only the second one is the one that is correctly named.

Disassembly:
```
> gml_Script_key_to_string (locals=2, argc=0)
; ...

> gml_Script_ValidKeysOnly (locals=2, argc=1)
; ...
```

### Reproducing steps

Since I tested this with [HoloCure](https://kay-yu.itch.io/holocure), I'll describe the reproduction steps using HoloCure.

1. Open up HoloCure using UMT built from commit 85430c57acde4b98897570623a87c46eabc5d717.
2. Navigate to a `gml_GlobalScript` with multiple functions. A good example is `gml_GlobalScript_shell_scripts`; a more concise one is `gml_GlobalScript_key_to_string`.
3. Observe:
   1. Duplicated function names.
   2. The fact that the duplicated names come from the very last function name declared in the script.

### Setup Details

- Tested on latest UMT commit: 85430c57acde4b98897570623a87c46eabc5d717
- Tested on a Windows 10 machine, can probably test on Arch Linux later.
- HoloCure - [get it here](https://kay-yu.itch.io/holocure).

**Comment by khronii** [comment]
I figured out that these are functions which are instance variables, so maybe it should be decompiled like
```
foo = function ()
{
}
```

Sorry if I misunderstood how GML works.

**Comment by Dobby233Liu** [comment]
> ```
> foo = function ()
> {
> }
> ```
> 
> instead of
> 
> ```
> function wrongName () // gml_Script_foo_gml_Object_bar
> {
> }
> ```

Pretty sure `function foo()` will compile, I actually did it once:
![image](https://user-images.githubusercontent.com/28653235/177298224-c1cfa48a-da53-49dd-aaf5-35a013306112.png)

**Comment by khronii** [comment]
> Pretty sure `function foo()` also works (and compiles with GM), I actually did it once:

I just followed this [document](https://manual.yoyogames.com/GameMaker_Language/GML_Overview/Method_Variables.htm) to create a function as an instance variable as it is accessed via `anInstanceOfBar.foo()`
