### ISSUE TITLE
The tool cannot open the game, previous versions can

### ISSUE THREAD

**Issue by sirenboke** [krzys-h/UndertaleModTool#1040]
### Describe the bug

![A6C3FFBC-209F-4F7B-8473-E78FCA3D55A6](https://user-images.githubusercontent.com/71312853/177913300-a5fb9019-8162-4fa9-b631-64bcbf29fb70.png)
This is a display issue

### Reproducing steps

Attempts to open the game will be displayed

### Setup Details

Undertalemodtool：0.4.0.4
Win10
Game：https://erohz.itch.io/tpdr/purchase?initiator=mobile              Dungeon Raiders v3.25.3

**Comment by Grossley** [comment]
This error does not occur on latest prerelease. Please update your version to the latest prerelease. Closing.
