### ISSUE TITLE
Unable to cast UndertaleGeneralInfo to UndertaleExtensionFile

### ISSUE THREAD

**Issue by iconmaster5326** [krzys-h/UndertaleModTool#1049]
### Describe the bug

When I attempt to open up the data.win file for the game [Siralim Ultimate](https://store.steampowered.com/app/1289810/Siralim_Ultimate/), I get the following error:

```
An error occured while trying to load: Unable to cast object of type 'UndertaleModLib.Models.UndertaleGeneralInfo' to type 'UndertaleModLib.Models.UndertaleExtensionFile'.

at 00000718 while reading object UndertaleModLib.UndertalePointerList'1 [[UndertaleModLib.Mo dels.UndertaleExtensionFile, UndertaleModLib, Version=0.4.0.4, Culture=neutral, PublicKeyToken=null]]
at 00000718 while reading object UndertaleModLib.Models.UndertaleExtension while reading item 1 of 3 in a list of UndertaleModLib.Models.UndertaleExtension in chunk EXTN 
```

### Reproducing steps

1. Open Siralim Ultimate's `data.win` file in the tool.
2. You now see the above error message.

### Setup Details

1. 0.4.0.4
2. Windows 10
3. [Siralim Ultimate](https://store.steampowered.com/app/1289810/Siralim_Ultimate/)

**Comment by VladiStep** [comment]
Just checked - 0.4.0.4 is actually has this error, but the current release 0.5.0.0 hasn't.
Download it here - https://github.com/krzys-h/UndertaleModTool/releases/tag/0.5.0.0.
