### ISSUE TITLE
Cannot add custom textures to a sprite

### ISSUE THREAD

**Issue by warestarstuff** [krzys-h/UndertaleModTool#105]
I'm currently attempting to add a new sprite to the game, and I'm having a bit of a rough time. If you hover over one of the buttons, [it displays a message saying I should drag something there.](https://i.imgur.com/8Rb2f44.png) No matter what I do, it doesn't seem to change however...

**Comment by colinator27** [comment]
I think you need to use the "double click to add" button first, and then drag onto the new item on the list.

**Comment by warestarstuff** [comment]
I already used the button, thats why theres an empty "slot" there. I tried making a new one anyway, but no dice.

**Comment by krzys-h** [comment]
That should have worked, looks like a bug. Will check in a moment.

**Comment by krzys-h** [comment]
Oh, I see now, you are dragging the whole "embedded texture" instead of "texture page ITEM". An embedded texture is a whole sheet of sprites, a texture page item is a single sprite cut out of that - just look at how all other sprites work.
