### ISSUE TITLE
NewTextureRepacker scrambles graphics on UMT bleeding edge

### ISSUE THREAD

**Issue by Cl0v3rDev** [krzys-h/UndertaleModTool#1051]
### Describe the bug

I somehow messed up the textures in Deltarune by using the NewTextureRepacker script on the latest bleeding edge of UMT. This doesn't happen on the stable release as I tried it there too, and the game runs like normal. I have provided a video to give a better picture of what happened:

https://user-images.githubusercontent.com/96222837/180708750-951edb33-d6f5-4dd7-a99b-15944e78bf97.mp4

### Reproducing steps

1. Edit [NewTextureRepacker.csx](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/Scripts/Resource%20Repackers/NewTextureRepacker.csx) and leave all settings to their default, but uncomment the chapter 1 grouping.
2. Open Deltarune v1.10 with the UMT bleeding edge release and run the script
3. Save
4. Start the game

### Setup Details

1. UndertaleModTool version used:
Bleeding edge (commit 674c5d8630f254368f54167330d6347574fb3e20)
2. Operating System used:
Windows 11 Home 64-bit, Version 21H2
3. Game used:
[Deltarune Chapter 1&2 v1.10 (itch.io release)](https://tobyfox.itch.io/deltarune)

**Comment by VladiStep** [comment]
Uncommenting the chapter 1 grouping doesn't change anything.
This issue is related to DPI (system display scaling) feature - with 100% scale, script works fine.
