### ISSUE TITLE
pasting GML code on top of EXCEPTION comment will crash UMT

### ISSUE THREAD

**Issue by themabus** [krzys-h/UndertaleModTool#1054]
### Describe the bug

open data.win and go to code that failed parsing and has EXCEPTION comment
paste GML code on top of it
UML will display error dialog and crash 

### Reproducing steps

1. copy sole GML string from object0.Draw
2. select all EXCEPTION comment in object0.Create so you would replace it when pasting
3. paste

[test.zip](https://github.com/krzys-h/UndertaleModTool/files/9179006/test.zip)

### Setup Details

674c5d8
Win10 x64

**Comment by Miepee** [comment]
> UML will display error dialog and crash

Post the error dialog that it displays please.

**Comment by themabus** [comment]
strangely I could not get it to display error dialog any more, it just closes now
but I'm pretty sure it was the same thing that's in those crash.txt logs
I remember it was a lot of 'at this' and 'at that bla bla bla'
so I attached those
[crash_logs.zip](https://github.com/krzys-h/UndertaleModTool/files/9180916/crash_logs.zip)

**Comment by Jacky720** [comment]
Seems like the error is triggered at [UndertaleCodeEditor.xaml.cs:1117](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/Editors/UndertaleCodeEditor.xaml.cs#L1117). It could be a null parent with a null CurrentLocals, but it'll require more testing in a debug environment to be sure.

**Comment by themabus** [comment]
I had error message pop up again and it is indeed the same thing that's in 'crash.txt'
![crash](https://user-images.githubusercontent.com/83443578/181193962-c495c292-3854-4c27-9299-c8439258b874.png)
also looks like this only happens when this is done through 'Game objects' object's events but not through 'Code'
