### ISSUE TITLE
CLI: replace all embedded textures bug

### ISSUE THREAD

**Issue by suphamster** [krzys-h/UndertaleModTool#1058]
### Describe the bug

I can't get to work cli mass embed textures import after cli dump command

But single embed texture replace is working: "UndertaleModCli replace -t "Texture 0=./EmbeddedTextures/Texture 0.png" -o temp.win data.win"

If I'm doing import all emb textures in GUI it works (but after renaming "Texture 0.png" -> "0.png" and etc.) but in cli still not.

P.S. It look like that UMT_REPLACE_ALL command doesn't "cuts" extension .png from replace command so it interprets single step as "UndertaleModCli replace -t "**Texture 0.png**=./EmbeddedTextures/Texture 0.png" but correct command should be ""UndertaleModCli replace -t "**Texture 0**=./EmbeddedTextures/Texture 0.png" -o temp.win data.win""
P.P.S. **I've fixed it manually** in dnSpy (UndertaleModCli.dll file) by adding before string (in dnSpy it looks a bit different) "UndertaleEmbeddedTexture texture = Data.EmbeddedTextures.ByName(textureEntry);" this code: 
"int fileExtPos = textureEntry.LastIndexOf(".");
 if (fileExtPos >= 0)
 {
   textureEntry = textureEntry.Substring(0, fileExtPos);
 }"  
in "UndertaleModCli/Program.cs" file.

### Reproducing steps

dump embed textures: "UndertaleModCli dump -t data.win"
import 'em back with: "UndertaleModCli replace -t UMT_REPLACE_ALL=./EmbeddedTextures -o temp.win data.win"

Getting errors like:
Data file does not contain an embedded texture named Texture 0.png!
Data file does not contain an embedded texture named Texture 1.png!

### Setup Details

using Win10x64 and this version https://github.com/krzys-h/UndertaleModTool/releases/download/bleeding-edge/CLI-windows-latest-isBundled-true.zip

**Comment by suphamster** [comment]
I dunno how to properly add commits and if it even would work and I'm almost total noob in github so I just leave my fix there
https://github.com/krzys-h/UndertaleModTool/commit/0bd291245334e470751fe187f6f133561c70bc88

**Comment by Miepee** [comment]
Can you please reopen the issue?
It's still broken in master.

**Comment by suphamster** [comment]
> Can you please reopen the issue? It's still broken in master.

No, sorry don't have need rights for it - only repository owner https://github.com/krzys-h can do it.

**Comment by suphamster** [comment]
> > Can you please reopen the issue? It's still broken in master.
> 
> No, sorry don't have needed rights for it - only repository owner krzys-h can do it.

**Comment by suphamster** [comment]
reopne

**Comment by Miepee** [comment]
Thanks

**Comment by suphamster** [comment]
> Thanks

Thank you too for this https://github.com/krzys-h/UndertaleModTool/pull/1064 - seems to work fine too.

Can I ask u a question about CLI version - it loads data file about 10-20 times slower (especially very big files) than GUI version. Is it normal or I should create new issue for it.

**Comment by Miepee** [comment]
Create a new issue for it, and I'll try to look into it whenever I have time.

**Comment by suphamster** [comment]
> Create a new issue for it, and I'll try to look into it whenever I have time.

Ok, thanks for info. Last question is sounds dump/replace is planned in CLI?

**Comment by Miepee** [comment]
Make a feature request for it.
Issues are not the place for support questions/discussions, they should be catered around the issue themselves.
If you want to have real-time discussion, either join the Discord server, ask on the subreddit (, wait for the discussion feature to be enabled, or ask any maintainers to add an alternative way of communication).
