### ISSUE TITLE
Error saving (FONT, after add glyph)

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#106]
@colinator27 
Starting from version 0.1.20 you cannot save the project after adding the glyph to the font
Check steps:
- open *.win
- open any font tab
- add glyph
- save project
error: http://i.prntscr.com/0vl3ml5vSY2hZnKl5Q3YHg.png

I guess the problem started here. https://github.com/krzys-h/UndertaleModTool/commit/a10df976f9d768548ded709e73250afbe3fbd8de

**Comment by colinator27** [comment]
Oh my goodness I suck at initializing stuff I guess....

**Comment by colinator27** [comment]
I'll push a fix in a little

**Comment by LinXP** [comment]
@colinator27 @krzys-h 
Now it works, thanks
https://i106.fastpic.ru/big/2018/1201/b6/_729705bcc7b0ad2878fa5b01fe6328b6.png
