### ISSUE TITLE
Font importing doesn't work.

### ISSUE THREAD

**Issue by ArdaKurucim** [krzys-h/UndertaleModTool#1060]
### Describe the bug

When I try to import fonts that i exported and edited before it gives me an error.

### Reproducing steps

1. Import fonts via script ImportFontData.csx
2. See error.

### Setup Details

![image](https://user-images.githubusercontent.com/48387425/181071858-f2d20537-a5b8-448b-9f49-e8125fab8ccd.png)

**Comment by ArdaKurucim** [comment]
I think someone made a typo in codes which it skips "\" on file directory.

**Comment by ArdaKurucim** [comment]
Because the folder name is Export_Fonts

**Comment by Miepee** [comment]
Which UMT version?

**Comment by ArdaKurucim** [comment]
Latest one v4.0.4 I think.

**Comment by Miepee** [comment]
This bug should be fixed on master, check the development builds.

**Comment by ArdaKurucim** [comment]
I am already using the master build.

**Comment by ArdaKurucim** [comment]
Where can I find the dev builds?

**Comment by ArdaKurucim** [comment]
Nope, didn't work, Still the same issue.

**Comment by ArdaKurucim** [comment]
Okay, I fixed it by downloading the app again it was my own dumbness lmao. Thanks for helping.
