### ISSUE TITLE
UndertaleModLib.Models.UndertaleFon in chunk FONT Error

### ISSUE THREAD

**Issue by 4kumano** [krzys-h/UndertaleModTool#1061]
### Describe the bug

When I attempt to open up the data.win file for the game [HoloCure](https://kay-yu.itch.io/holocure), I get the following error:

![image](https://user-images.githubusercontent.com/54392161/181148871-9ec82b29-985f-4497-8cee-e933607a0fa3.png)

### Reproducing steps

1. Open HoloCure's data.win file in the tool.
2. You now see the above error message.

### Setup Details

1. UndertaleModTool 0.4.0.4
2. Win 10
3.  GMS 1.4.9999
4. GMS 2 2022.6.0.23
5. Graphviz Windows 10 5.0.0 win32

**Comment by Jacky720** [comment]
Please update to the [cutting-edge builds](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge). I'm not sure what the last version to fail in FONT was, but it's most likely been fixed by now.

**Comment by 4kumano** [comment]
Thank you for the info

**Comment by lynrayy** [comment]
![image](https://user-images.githubusercontent.com/59417884/222978640-3c078d6d-0e7d-434d-b6b1-08cc3ac12ec7.png)

**Comment by VladiStep** [comment]
> ![image](https://user-images.githubusercontent.com/59417884/222978640-3c078d6d-0e7d-434d-b6b1-08cc3ac12ec7.png)

I suppose it's not HoloCure?
Then you should open a separate issue (or at least say the name of the game if you really don't want to do that).

**Comment by VladiStep** [comment]
@lynrayy
