### ISSUE TITLE
Sprite editing issue

### ISSUE THREAD

**Issue by Armin2TT** [krzys-h/UndertaleModTool#1073]
### Describe the bug

adding/editing/importing a new texture to Embended textures makes whole sprites based on the same embended textures go invisible when running the game 

### Reproducing steps

.

### Setup Details

bleeding edge

**Comment by Jacky720** [comment]
The Reproducing Steps are there for a reason. Could you provide the exact game name (or GMS version of said game)? And do you know if this affects ImportGraphics or only manually adding texture pages?

**Comment by Armin2TT** [comment]
affects both import graphics and manually adding texture ... the game is called stoneshard version 0.8+ ... it wasnt like that on previous versions

**Comment by Armin2TT** [comment]
gms version 0.2

**Comment by Jacky720** [comment]
Can you paste this into the tool console to get a more accurate version? The "2.0" hasn't been updated in quite some time.
```
Data.GM2022_6 ? "2022.6" : Data.GM2022_5 ? "2022.5" : Data.GM2022_3 ? "2022.3" : Data.GMS2022_2 ? "2022.2" : Data.GMS2022_1 ? "2022.1" : Data.GMS2_3_2 ? "2.3.2" : Data.GMS2_3_1 ? "2.3.1" : Data.GMS2_3 ? "2.3.0" : Data.GMS2_2_2_302 ? "2.2" : "2.0"
```
![image](https://user-images.githubusercontent.com/32578221/184519761-556bf205-b1d4-4bc3-b6bd-7c689bc14f26.png)

**Comment by Armin2TT** [comment]
the result was " 2022.5 "

**Comment by Dobby233Liu** [comment]
This sounds similar to #1042
