### ISSUE TITLE
data.win to project.gmx

### ISSUE THREAD

**Issue by pikakid98** [krzys-h/UndertaleModTool#1081]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

The title says it all.. Not sure how possible this is but is there a possibility to just allow us to export the files in a way that lays all of the files and folders out to re-create the project file?.. I'm perfectly aware how tedious this would be to implement so this request will likely be ignored, instantly closed or someone will just reitterate what I just said and then close the request. I've been trying to decompile a few of my old Game Maker Studio games due to the fact that I broke my external hard drive and lost most of my source code

**Comment by Grossley** [comment]
@pikakid98 This will not be implemented. However, please contact me on Discord at Grossley#2869 if you would like assistance as I may be able to help you.
