### ISSUE TITLE
Can't use the macOS client version

### ISSUE THREAD

**Issue by omarc08** [krzys-h/UndertaleModTool#1088]
### Describe the bug

When I open the UndertaleModToolCLI file, it opens in Terminal and runs a bunch of stuff. Then is says "Process Completed". But I can't type anything. This is my first time using this so I probably did something wrong. 

Thanks!

https://user-images.githubusercontent.com/95196282/196548714-2581394e-cfe8-4aa0-916e-a9832dbfa3eb.mov

### Reproducing steps

Open the UndertaleModToolCLI file
Wait for everything to run
Then the bug happens

### Setup Details

UndertaleModTool latest bleeding edge version 
macOS client version

**Comment by Miepee** [comment]
Yes. That typically looks somewhat like this:

- open terminal app
- `cd ~/Downloads/UndertaleModCli`
- `./UndertaleModCli load <path to your game.ios file>`

Also keep in mind that the CLI is a *command line interface*. It's usage is meant to be done with a terminal and to be minimal, so you will not see a fancy graphical interface like UndertaleModTool shows for Windows.

**Comment by omarc08** [comment]
Awesome. I got it working. Thanks!

**Comment by omarc08** [comment]
What do you mean by game.ios file. I thought I was supposed to open a data.win. Also would this be correct?

/Users/omarcamara/Downloads/CLI-macOS-latest/UndertaleModCli load data.win

**Comment by omarc08** [comment]
It says it loaded, but how do I add things inside the file? Sorry if I am asking lots of questions by the way, I'm kinda new to using the command line.

**Comment by omarc08** [comment]
Nevermind. I will just use Wine to use the GUI version.
