### ISSUE TITLE
Incrementing/decrementing operators do not always decompile correctly

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#109]
As far as I know, there are no issues with these in Undertale or Deltarune.

Basically, see the example code I gave in #108. Removing the last two lines that use the strange instruction, the decompiler output is this (the first two lines are irrelevant):
```gml
self.a = (self.a + 1)
self.a.b.c = (self.a.b.c + 1)
self.a = (self.a + 1)
show_message(self.a)
self.a = (self.a + 1)
show_message((self.a + 1))
```

The first one is meant to be a++, and the second is ++a. According to the [docs](https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/401_04_expressions.html), 
```
++a will increment the variable and return the incremented value.
a++ will increment the variable but return the value before it was incremented.
```
...as you would expect.

**Comment by colinator27** [comment]
So basically the issue here lies in expressions.

Also, to make this simpler, I guess `pop.e.v 5` decompiler support could be added with this if possible.

**Comment by krzys-h** [comment]
I think I get why this happens. The code for the pre-increment is something like this:
```gml
_tempvar = self.a
self.a = _tempvar + 1
show_message(_tempvar + 1)
```
but the decompiler has a function that checks if it's safe to repeat an expression (for readability, it's required in most cases), and since that first assignment is just tempvar = variable it collapses that to
```gml
self.a = self.a + 1
show_message(self.a + 1)
```
which has a different meaning. To fix this, we need to check if the variable was not assigned to in between the expressions.

For post-increment it's the same with
```gml
_tempvar = self.a
self.a = _tempvar + 1
show_message(_tempvar)
```
getting collapsed incorrectly

**Comment by colinator27** [comment]
I feel like we should try to avoid tempvars as much as possible though, because sometime we'll probably want to make the output all GML-compatible, which would mean they need to stop existing altogether.

**Comment by krzys-h** [comment]
Yeah, but they are basically unavoidable internally, especially without hardcoding the compiler patterns (which could change in future versions). The output with tempvars is always correct technically, just not clean looking. They should be gone from final output though.

**Comment by Kneesnap** [comment]
A band-aid fix is included in https://github.com/krzys-h/UndertaleModTool/pull/162

However, this should not be seen as a permanent fix. We should fix the root of the problem, which is mentioned above in this issue.

**Comment by colinator27** [comment]
Full fix (though hacky) included in https://github.com/Kneesnap/UndertaleModTool/commit/600378c4815150fe3d471d287efd50050ac88db4

Will wait to close until that is all merged.

**Comment by colinator27** [comment]
I'm going to close this now, it's all fixed now.
