### ISSUE TITLE
Invalid spine format bersion number, expected 2 or 1, got 3 - error while loading data.win

### ISSUE THREAD

**Issue by donsoyer** [krzys-h/UndertaleModTool#1095]
### Which component should be improved?

Compiler

### Describe your feature suggestion in more detail

![image](https://user-images.githubusercontent.com/96090807/198672352-26998474-687f-4424-b4d6-35b083775c9d.png)

**Comment by Dobby233Liu** [comment]
What game are you trying to load?

**Comment by donsoyer** [comment]
But not sure.

**Comment by donsoyer** [comment]
Sorry, it should be a bug anyway.

**Comment by nkrapivin** [comment]
Some GameMaker update introduced QOI textures and better caching for Spine and this broke ModTool. Can be fixed though.

**Comment by nkrapivin** [comment]
Please try this nightly build of ModTool.

https://nightly.link/krzys-h/UndertaleModTool/actions/artifacts/415929907.zip

This is only for save & load support, the preview won't show any Spine textures, and you cannot edit the exported Spine sprites manually unless you own a legal copy of the matching Spine version (they have a hash inside the json).

Spine is proprietary software which is more expensive than GM so nobody can help you with that, sorry.

**Comment by donsoyer** [comment]
thanks, it does work perfectly.
