### ISSUE TITLE
Saving GMS2 is not tested yet

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#11]
I added GMS2 saving support in a9889e3d9dc118ee9797fecada300d3566a770e4 but I need somebody with access to the Switch version to make sure it works correctly. Open the data file, save it with no changes and make sure the files are identical.

ping @NarryG

**Comment by D3fau4** [comment]
![captura](https://user-images.githubusercontent.com/19638408/45690928-c5ce9880-bb57-11e8-9afb-460ef9df0c24.PNG)

**Comment by krzys-h** [comment]
You are using version 0.1.4, the saving is added to 0.1.5 released literally 10 minutes ago.

But still, it should not have crashed on STRG, I have never seen that before. Could you open the file with a hex editor and show what's around offset 0x012F894B? The only way this could have happened is if character count on one of the strings didn't match actual length...

**Comment by D3fau4** [comment]
![captura](https://user-images.githubusercontent.com/19638408/45692170-72aa1500-bb5a-11e8-89ee-5570588590ee.PNG)

**Comment by krzys-h** [comment]
you are a little bit too far, this is offset 0x012F8994 ;)
Nothing looks suspicious here.

**Comment by D3fau4** [comment]
XD I do not know how to find it in this program, any recommendation

**Comment by krzys-h** [comment]
It's like 5 lines above what you looked at previously. Or just `Search > Goto`

**Comment by D3fau4** [comment]
![captura](https://user-images.githubusercontent.com/19638408/45693872-5b6d2680-bb5e-11e8-97db-43063c1b50cd.PNG)
![captura1](https://user-images.githubusercontent.com/19638408/45693873-5b6d2680-bb5e-11e8-91c0-5a9505c84c67.PNG)

**Comment by Mc-muffin** [comment]
Just tested the Switch version on the latest release (0.1.5) got this error: 
![image](https://user-images.githubusercontent.com/8714476/45702399-5fd21900-bb37-11e8-8e26-5452f22c950a.png)

The error doesn't show up in 0.1.4 nor in 0.0.3 it loads normally.

**Comment by krzys-h** [comment]
@Mc-muffin patched in 0.1.6, try again

**Comment by D3fau4** [comment]
@krzys-h and if I pass the game.win would be faster, my editor does not find that line or I'm an idiot. XD

**Comment by krzys-h** [comment]
@D3fau4 because lines are always 16 bytes long, so the line labels always have 0 at the end. Look for line with the 0x012F8940 label.

Actually, if somebody sent me the game.win file it would be way easier as I would at least have something to work with, but technically that would be piracy so I don't know

**Comment by D3fau4** [comment]
Obviously publicly I'm not going to pass it on, either an email or a discord message

**Comment by krzys-h** [comment]
@D3fau4 okay, send it to me and I'll take a look. My email is in the github profile or krzys_h on Discord

**Comment by Mc-muffin** [comment]
@krzys-h It opened fine now, just tested the saving and...
```
427520A97DB28C87DA4220ABB3A334C1  -> game.win
427520A97DB28C87DA4220ABB3A334C1  -> savedgame.win
```

Match!

**Comment by krzys-h** [comment]
@Mc-muffin great! There may still be some problems on bigger edits because not all of the new data format is known (and I didn't even start updating the editors because of that), but this means that basic patching functionality should now work.

@D3fau4 Is your data file modified or did Undertale get a Spanish translation? ;) Whatever tool you used didn't properly update the string lengths, your file says that the string "CONFIGURACION DE BOTONES" is 14 characters long which is obviously not the case. UndertaleModTool is designed to be very strict about mismatches like this because it does not modify the file, it actually rebuilds it from scratch when you save and some data would be lost if I didn't read it properly.

As the saving is confrmed to work, I will now close this issue.
