### ISSUE TITLE
function for add bg and tilesets?

### ISSUE THREAD

**Issue by JustinGdnz** [krzys-h/UndertaleModTool#111]
I want to add some tilesets in the game but there's not option for add them in the backgrounds and tilesets section. I will be glad if you add that option

**Comment by krzys-h** [comment]
Oh, that's a bug, it's supposed to be there

**Comment by Grossley** [comment]
Was this fixed? This still seems to not be possible in release version 0.2.0 (not tested on a newer dev build of the game yet).

**Comment by Kneesnap** [comment]
Closing unless further information is provided.

**Comment by Grossley** [comment]
Seems pretty clear cut to me. What more information do you need?

**Comment by Kneesnap** [comment]
I misunderstood what you said as "I am unable to reproduce this in 0.2.0. My mistake. Will re-open."

**Comment by Grossley** [comment]
This bug is present on release 0.2.0. I am simply unsure if it ever was fixed.

**Comment by Grossley** [comment]
This bug still exists in the most recent dev branch commit 17a318c .

**Comment by Kneesnap** [comment]
Upon further inspection, there isn't an easy way to allow adding new tiles, because of how each tile uses its sprite-sheet. However, I will look into making it easier to clone an existing tile.

**Comment by Kneesnap** [comment]
Just select a tile, do Ctrl + C, then Ctrl + V, to make a new tile. It now gets placed outside the room so no matter the layer you 'll see it.

**Comment by Kneesnap** [comment]
Ugh. Nevermind. It seems this issue was not explained perfectly. I assumed this was about adding tiles and backgrounds into a room, because it's the only type which needs duplicating, instead of adding. Am looking into adding to the game now

**Comment by Kneesnap** [comment]
Fixed. Tilesets + backgrounds will be possible to create next push.
