### ISSUE TITLE
error while loading data.win file, latest undertale, game created in 2017

### ISSUE THREAD

**Issue by donsoyer** [krzys-h/UndertaleModTool#1112]
### Describe the bug

![image](https://user-images.githubusercontent.com/96090807/200648334-a255fc9c-bb2f-4b29-92ff-aeeec7f95034.png)
error while loading data.win file, latest undertale, game created in 2017
https://gamejolt.com/games/HELLFIGHTER/244900

### Reproducing steps

error while loading data.win file, latest undertale, game created in 2017

### Setup Details

error while loading data.win file, latest undertale, game created in 2017

**Comment by Miepee** [comment]
Do you mean "latest UndertaleModTool version"? If yes, that's not specific, please specify the actual version (or commit) you used.

**Comment by donsoyer** [comment]
![image](https://user-images.githubusercontent.com/96090807/200743870-ab468a5a-aecc-45d1-b313-ed87dea4f934.png)
this one
