### ISSUE TITLE
Sprites Origins Messed Up For Deltarune

### ISSUE THREAD

**Issue by roxy260** [krzys-h/UndertaleModTool#1114]
### Describe the bug

i can't edit any sprite cause the origins on sprites are messed up, i can edit textures though
![image](https://user-images.githubusercontent.com/94108153/201263603-704e7c11-ff14-408d-b744-e67554e1717d.png)
(supposed to be the spamton NEO heart)
![image](https://user-images.githubusercontent.com/94108153/201263678-b5a5b15a-8198-47ad-bdb7-5b9c7259464d.png)
if i change the sprite it changes what shows it replaces in the first image

### Reproducing steps

Download Any Version After Chapter 2 Support
Open Any Sprite
Go To The Texture File For Said Sprite

### Setup Details

UndertaleModTool Version: 0.4.0.4
OS: Windows 11
GameMaker Version: I Just Use The Current Version On Steam So
![image](https://user-images.githubusercontent.com/94108153/201264281-f3628b6f-0dd5-475c-a9e2-fa2ba0ca44b1.png)

**Comment by Dobby233Liu** [comment]
Is the DPI scaling setting in your system set to a value higher than 100%?

**Comment by roxy260** [comment]
yes but if i set it to 100 i cannot see literally anything at all

**Comment by Dobby233Liu** [comment]
I believe this problem is fixed in the [bleeding edge build](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge)

**Comment by roxy260** [comment]
yep that fixed it, thanks!
