### ISSUE TITLE
Newest GMS Version Issue

### ISSUE THREAD

**Issue by Red1Fouad** [krzys-h/UndertaleModTool#1130]
### Describe the bug

Adding new assets doesn't work anymore because of the new game maker update, that includes sprites and audio.

Sprites: when adding new sprites, they're invisible in the game.

Audio, when adding a sound, the game doesn't recognize it and gives an error of the requested audio not existing.

Game: Megaman Maker

### Reproducing steps

1. Open Megaman Maker 1.8 Data
2. Use the AddASound script to add a .wav sound
3. Try to use that sound in the game
4. The game doesn't load the sound saying it doesn't exist

### Setup Details

1. The latest UMT Bleeding edge was used.
2. Windows 10 (x64).
3. The current Gamemaker Studio 2 version.

**Comment by Jacky720** [comment]
Is this still an issue?

**Comment by Red1Fouad** [comment]
> Is this still an issue?

nope! it works now
