### ISSUE TITLE
Newly added scripts fail to disassemble

### ISSUE THREAD

**Issue by warestarstuff** [krzys-h/UndertaleModTool#114]
Add in a new script under the "Code" category, and you'll always get this message in the disassembly tab no matter what you do: `Code failed to disassemble- likely due to unsupported bytecode version.`

edit: i cant believe 2 minutes of creating this issue, i get it to work. going under the "code locals" section you can create a new thingy for the recently created script you just made. though i personally think the error message should include the fact you need to add a code local for those making custom scripts, its a bit vague

**Comment by colinator27** [comment]
Whoops, I guess my error applies to more scenarios than I thought...

**Comment by Kneesnap** [comment]
To add a script properly,

1. Create a new Code Local, named gml_Script_SCRIPTNAME. (Ex: gml_Script_myscript) Change string in all places when it asks. Add a new local variable at index 0, named "arguments". (Add other local variables which will be used in the script too, incrementing the index each time).

2. Create a new script, and give it a name. (Ex: myscript).

3. Create a new code entry, and drag it onto the "Code" text box in the Script object you just made. Set the locals count to the number of locals you added in the locals entry. Name it the same thing you named the code local entry. 

4. Done. Load another script then load the one you just made. It needs to be reloaded for you to see the changes. It should now look something like this:

![image](https://user-images.githubusercontent.com/6562913/61327248-53f1ca80-a7cd-11e9-9b68-ad061f1ade7b.png)

**Comment by colinator27** [comment]
Oh yeah, I forgot to update this issue, but in the more recent versions (either 0.2.0 or the `dev` branch), the warning message is updated and also doesn't exist in bytecode <= 14.
