### ISSUE TITLE
Not a bug report but i need help quick.

### ISSUE THREAD

**Issue by ZankTheHank** [krzys-h/UndertaleModTool#1145]
### Describe the bug

i cant even figure out how to get it to work, i watched so many tutorials and i just wanna repaint the sprites + change dialogue (in deltarune) but i cant even open up the menu thing, even when i click data on deltarune it just dont pop up. i would like some awnsers pretty quick, because i have limited time.

### Reproducing steps

well i mean i just cant get it to open soo..

### Setup Details

I think apart of the problem could be idk what version to install, im windows 10 but one says mac and i just cant figure it outnor get it to work.

**Comment by ZankTheHank** [comment]
If sombody could get me a slow step by step for windows 10 thats actully up to date then please do.

**Comment by ZankTheHank** [comment]
I'll check back in like in hour.

**Comment by BenjaminUrquhart** [comment]
quick question, if it's not a bug why did you add the bug label
