### ISSUE TITLE
Trying to open Undertale in Game Maker Studio

### ISSUE THREAD

**Issue by SheepCheap** [krzys-h/UndertaleModTool#115]
Hello, I'm fairly new in this forum and I hope my question is not to stupid.

I wanted to decompile Undertale for the sole purpose of learning from Tobys code for my own project.

So, I opened the Underale data.win in my steam steamapps folder, and I got every script, texture, etc.. So far, so good. Now, I wanted to use GM 1.4.9999 to open Undertale. So, I clicked on "Files" and " Export to Game Maker Project" and... a black screen appeared with the Toby Fox dog and funny music:

https://user-images.githubusercontent.com/45600487/49451502-9981fa00-f7df-11e8-8e77-d8633c1478fa.png

I tried to find a solution for this but I couldn't, so I'm wondering if it'S impossible toopen Undertale (and for that matter, Delta Rune) in GM with this tool. Or am I just too dense to see my errors.

I hope I don't bother you.

**Comment by krzys-h** [comment]
GameMaker export is not a thing for legal reasons and that option is there just to troll people who keep asking me for it, sorry.

Besides, you wouldn't get "Toby's code", just a messy decompiled version of it, definitely not a good thing to learn from :P (and Toby's coding style is sometimes not a best thing to learn from either)
