### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fnfloverredimpostor** [krzys-h/UndertaleModTool#1150]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

Tutorial for people that dont know how to use this 
like me if there will be a tutorial it would be more
better.        e

**Comment by NatKromer** [comment]
> Yes, there are some tutorials on YouTube: [search "UndertaleModTool"](https://www.youtube.com/results?search_query=undertalemodtool) or go to [this playlist](https://www.youtube.com/playlist?list=PLTZJJRPYg1wJMS6VMPKAjOlX9Ee6gbvpP) .

I don't think a primer on GML is going to be enough. What we really need is a guide to how UNDERTALE and/or deltarune's code works.
