### ISSUE TITLE
Cannot Read Latest HoloCure Version

### ISSUE THREAD

**Issue by steviegt6** [krzys-h/UndertaleModTool#1171]
### Describe the bug

GMS 2023.1 removes spine sprites from texture groups, which UndertaleModTool does not properly handle. This is observable in the latest release of HoloCure:
![image](https://user-images.githubusercontent.com/27323911/218008881-53554bdf-54eb-4199-8232-a015c1a821f8.png)
![image](https://user-images.githubusercontent.com/27323911/218008895-9efb16ca-2eb1-4667-a324-c759e6fea6c3.png)
![image](https://user-images.githubusercontent.com/27323911/218008940-21c67bf7-e576-4bcf-85e2-bbbda54931da.png)

### Reproducing steps

1. Attempt to read the attached file.

### Setup Details

UMT version: Latest bleeding edge
OS: Windows 10
GM Version: 2023.1+

[data.zip](https://github.com/krzys-h/UndertaleModTool/files/10703970/data.zip)

**Comment by steviegt6** [comment]
Full archive can be downloaded [here](https://kay-yu.itch.io/holocure).

**Comment by Dobby233Liu** [comment]
Seems like a pointer was removed from TexturePageInfo objects
![image](https://user-images.githubusercontent.com/28653235/218050611-2b59d5a0-1c99-4363-b5d5-5578231bbd58.png)

**Comment by steviegt6** [comment]
Hmm, interesting.

**Comment by steviegt6** [comment]
Updated issue in accordance with new information.

**Comment by MShrimp4** [comment]
> Seems like a pointer was removed from TexturePageInfo objects ![image](https://user-images.githubusercontent.com/28653235/218050611-2b59d5a0-1c99-4363-b5d5-5578231bbd58.png)

This works, but serializing also needs not write Tilesets to open modified version.
UMT probably needs to check version and then choose whether it should read/write one or not.

**Comment by khronii** [comment]
> Seems like a pointer was removed from TexturePageInfo objects ![image](https://user-images.githubusercontent.com/28653235/218050611-2b59d5a0-1c99-4363-b5d5-5578231bbd58.png)

This works, but serializing also needs not write Tilesets to open modified version.
UMT probably needs to check version and then choose whether it should read/write one or not.

(Reposted because I posted with the wrong Github account :D)

**Comment by 38boss38** [comment]
I also encountered the same problem. When I tried to translate HoloCure5.0, I found that data.win could not be opened. If you have a solution, please let me know, thank you very much! ! !

**Comment by steviegt6** [comment]
https://github.com/steviegt6/undertalemodtool/tree/holocure
I am maintaining a fork not fit for merging that remedies this and a few other issues present when messing with HoloCure.
