### ISSUE TITLE
Reading out of bounds while opening Game Pass Undertale 

### ISSUE THREAD

**Issue by Monday555** [krzys-h/UndertaleModTool#1175]
### Describe the bug

![Screenshot_20230212_100403](https://user-images.githubusercontent.com/108072667/218319039-0ff80516-3aa1-4242-93f0-c454c6a88290.png)
Error occurs when attempting to open the data.win from Xbox Game Pass version of Undertale. Typically happens almost as soon as the file is selected. 

### Reproducing steps

1. Get the save from opening file location of the Game Pass version of Undertale using task manager (or just go to C:\Users\NAME\AppData\Local\Temp\ and my folder was called IXP000.TMP)
Edit: Upon reinstalling the game, the previous temp folder remained, however my files were now in IXP001.TMP, and upon closing the game, the entire folder disappears (this might be a part of any recent update, due to Xbox saying the game was updated on the 19th), so keep that in mind.
2. Take the data.win from just inside there
3. Attempt to open it with the mod tool
4. As soon as it is selected error occurs.

### Setup Details

1. I attempted it with both 0.5.0.0 and with the Bleeding Edge version
3. I use Windows 11
4. Xbox Game Pass version of Undertale

**Comment by Dobby233Liu** [comment]
You should move the game files out of the temp folder while the game is running if you didn't already, as the game can delete them at any second

**Comment by Monday555** [comment]
I have done that while opening it, also the data.win file is one of 4 files the game doesnt delete in that folder while closed (that I could see).

**Comment by Jacky720** [comment]
What is the size of the data.win file?

**Comment by Monday555** [comment]
> What is the size of the data.win file?

60,045 KB

**Comment by Monday555** [comment]
> What is the size of the data.win file?

It is about 60Mb

**Comment by Grossley** [comment]
Please send the game copy for analysis.

**Comment by Monday555** [comment]
> Please send the game copy for analysis.

I'll attach a Google Drive link to the IXP001.TMP folder, seeing as I'm unable to send a folder or rar file through here.
https://drive.google.com/file/d/1b8ZA8aXqrUL1_7biweYZGCf-nJALem8y/view?usp=sharing

**Comment by Jacky720** [comment]
Loads fine on my machine. In fact, it's a completely fine 1.08 DRM-free data.win down to the last byte. Maybe something about the folder structure?

**Comment by Monday555** [comment]
> Loads fine on my machine. In fact, it's a completely fine 1.08 DRM-free data.win down to the last byte. Maybe something about the folder structure?

Extracting it from the rar file, it now works with the editor, with the one I got from the IXP001.TEMP being a bit larger than the one before, so maybe the update patched out whatever issue was had? Either way, it seems to have been fixed in the most recent versions of it.
