### ISSUE TITLE
Dono's Tale Failing Decompilation

### ISSUE THREAD

**Issue by PhantomSlash64** [krzys-h/UndertaleModTool#1176]
### Describe the bug

So, I found a game that interested me and wanted to mod it, but UMT had an error opening the .data file, here is the message in question.

![Dono's Tale Error 2-12-2023](https://user-images.githubusercontent.com/112286996/218342932-c25570cb-7b02-4264-be33-5b8c55d90ed2.png)

### Reproducing steps

Download Dono's Tale in UMT
Error involving SEQN

### Setup Details

I was using the Bleeding Edge Build

I was using Windows 11 Build 22000. 1455

I am not sure how to retrieve info about what version of GMS the game was built on, if you could. Please send me a tutorial on how to retrieve GMS Engine Version.

**Comment by VladiStep** [comment]
The reason is this game uses the text sequence track which was introduced in GM 2022.2 (https://gamemaker.io/ru/blog/release-2022-2), and UTMT currently does not support that.
