### ISSUE TITLE
Decompiling certain disassembly causes UndertaleModTool to freeze.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#1179]
### Describe the bug

It looks like some kind of infinite loop is occurring that is using a lot of RAM and CPU. On one person's computer it caused the machine to completely lock up. The code block in ``UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs`` from lines 2354-2379 appears to be involved, as removing it prevents the infinite loop from occurring. The script ``gml_GlobalScript_scr_player_mach3`` in Pizza Tower causes this issue upon decompilation. However, the attached decompiled code can also trigger this. This is provided in a ZIP file (also including the resulting ASM) and is likely preferable for debugging as the original GML code and the resulting ASM is known and provided. 

### Reproducing steps

Paste the GML or ASM provided here into the appropriate box of a compatible GMS 2.3+ data file or Pizza Tower code entry [gml_GlobalScript_scr_player_mach3.zip](https://github.com/krzys-h/UndertaleModTool/files/10726622/gml_GlobalScript_scr_player_mach3.zip)

### Setup Details

1. UndertaleModTool commit 88ba165
2. Windows 11
3. Pizza Tower (Steam), but the GML/ASM should work on any empty GMS 2.3 data file which supports that syntax.

**Comment by VladiStep** [comment]
I think this caused by line 2357:
`UndertaleCode functionBody = context.GlobalContext.Data.Code.First(x => x.Name.Content == argCodeFunc.Target.Name.Content);`

Basically, it iterates through *all* code entries on each instruction of type `Opcode.Call`.

**Comment by Radix-Comet** [comment]
From my own research, I'm not terribly experienced with the codebase or GML, but the issues seems to be on line 2539 of ``Decompiler.cs`` : ``Block switchEnd = DetermineSwitchEnd(temp, end, meetPoint);``, when called the function never exits and infinitely adds blocks to ``Queue<Block> blocks`` on line 3867 of ``Decompiler.cs``
A small temporary patch I added (that seems to work???) is I made an early return at the beginning of the function that just returned the ``meetpoint``. After some testing, none of the scripts that originally had switch statements seemed to break, and matched and I was able to decompile the script in question.
