### ISSUE TITLE
some things to add

### ISSUE THREAD

**Issue by Bigpro19000** [krzys-h/UndertaleModTool#118]
You should add an interactable object that can then make your character to a animation, I'm not sure if there is already a way to do this or not though.

You could also add a way of adding sprites into a room.

Thanks :)

**Comment by krzys-h** [comment]
Anything that refers to interactable objects you have to do yourself, as that is part of the game itself, and not the data.win file format which is common for all game maker games.

For adding sprites to a room, the standard way to do it is to create a game object, then assign the sprite to it, then add the object to the room (you can just drag and drop it onto the room view to place it). Directly adding sprites to rooms was added only in GMS2, and is not supported yet (see #130)
