### ISSUE TITLE
Certain games' data.win will get UTMT to load seemingly indefinitely

### ISSUE THREAD

**Issue by Cephalobyte** [krzys-h/UndertaleModTool#1185]
### Describe the bug

Metroid Planets 1.29a, a fan game made in Game Maker using YYC was the first experimental build for the latest update.
However upon attempting to load its data.win with UTMT Bleeding edge, this loading screen pops up and no matter how long you wait (approximatively 8 hours tested), it doesn't budge.
![image](https://user-images.githubusercontent.com/60610075/219879374-4be310b1-b759-4f4a-8322-2486e3335379.png)

Upon further inspection with UTMT v.5.0.0, it does not seem to freeze, as the loading screen will sometimes stop and resume, as if it was working on something, and checking Task Manager reveals that this process takes a noticeable amount of processing power.
The window also will not close when attempting to press the red "X" button, the only way to end its suffering is through manual shutdown with Task Manager.

### Reproducing steps

1. Download version [1.29a](https://drive.google.com/file/d/1BZTaLK0H7GGcu-gyYc2zn57ppU0oJs71/view?usp=sharing) of Metroid Planets (don't tell Nintendo about it).
2. Extract it in your favorite folder (except `Desktop`, I don't condone war crimes).
3. Launch your preferred up-to-date version of Undertale Mod Tool (v.5.0.0 or Bleeding Edge)
4. Load `data.win` located inside the extracted zip (if you see the word `desktop` in the file path, you did something wrong).
5. Wait for the loading window to last for too long.
6. Do something else while you wait.
7. When your patience runs out, you've reproduced the behavior!
8. Launch Task Manager (hover on the task bar > right-click > Task Manager **OR** Ctrl+Alt+Del > Task Manager)
9. In the Processes tab, find and click on UndertaleModTool, then click on the End task button on the bottom right corner.

### Setup Details

1. UTMT v.5.0.0 or Bleeding Edge
2. Microsoft Windows 10 Home (Version 10.0.19044 Build 19044)
3. [Metroid Planets 1.29a](https://drive.google.com/file/d/1BZTaLK0H7GGcu-gyYc2zn57ppU0oJs71/view?usp=sharing)

**Comment by VladiStep** [comment]
Actually, it _does_ read the code entries.
But there are too many "gray" code entries (90% out of 10K), so UTMT struggles with that.
