### ISSUE TITLE
[SCRIPT] Texture Export/Import

### ISSUE THREAD

**Issue by nixxo** [krzys-h/UndertaleModTool#119]
Not really an issue.

I wrote a couple of script that can be useful to someone, maybe.

Export all Embedded Textures.

> ```
> string subPath = "TXTR";
> bool exists = System.IO.Directory.Exists(subPath);
> if(!exists) System.IO.Directory.CreateDirectory(subPath);
> var i = 0;
> foreach(var txtr in Data.EmbeddedTextures) {
>     UndertaleEmbeddedTexture target = txtr as UndertaleEmbeddedTexture;
>     try {
>         File.WriteAllBytes(subPath + "\\" + i + ".png", target.TextureData.TextureBlob);
>     }
>     catch (Exception ex) {
>         ScriptMessage("Failed to export file: " + ex.Message);
>     }
>     i++;
> }
> ```

Import all Embedded Textures.

> ```
> string subPath = "TXTR";
> bool exists = System.IO.Directory.Exists(subPath);
>if(exists) {
>	var i = 0;
>	foreach(var txtr in Data.EmbeddedTextures) {
>	    UndertaleEmbeddedTexture target = txtr as UndertaleEmbeddedTexture;
>	    try {
>	        byte[] data = File.ReadAllBytes(subPath + "\\" + String.Format("{0:00}", i) + ".png");
>	        target.TextureData.TextureBlob = data;
>	    }
>	    catch (Exception ex) {
>	        ScriptMessage("Failed to import file: " + ex.Message);
>	    }
>	    i++;
>	}
>}
>else {
>	ScriptMessage(subPath + " folder not found!");
>}
> ```

**Comment by krzys-h** [comment]
Since this is not an issue I will close this - I linked your script in the relevant issue (#92)
