### ISSUE TITLE
Alien XENOCIDE (Kickstarter Demo) won't open

### ISSUE THREAD

**Issue by DerpyMario** [krzys-h/UndertaleModTool#1190]
### Describe the bug

Had to open the data.win file, then these errors like reading misaligned during the reading of the TGIN chunk at 001AF8F8 and then a resource id invalid value error appeared at 00000015, plus it didn't load the win file.

![image](https://user-images.githubusercontent.com/88537784/221524946-d3a44a60-e79e-468d-833f-8a67c41f95e5.png)

### Reproducing steps

Opened it, two warnings apeared and then an error had to prevent me from opening the file and it suddenly ignored it.

### Setup Details

UndertaleModTool v0.5.0.0 (both release and bleeding edge)

Win10_Pro_22H2

GMS 2

**Comment by Jacky720** [comment]
Are you sure it's just GMS2? When was this demo published?

**Comment by DerpyMario** [comment]
4 weeks ago

**Comment by Jacky720** [comment]
It's most likely on GM2022.3. You can try [this unstable build](https://github.com/steviegt6/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Release-isBundled-true-isSingleFile-true.zip), designed for Holocure.
([source](https://github.com/steviegt6/UndertaleModTool/releases/tag/bleeding-edge))
