### ISSUE TITLE
Update BorderEnabler

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#12]
BorderEnabler will need to be updated whenever the next PC update happens.

The checks have changed from
```
    if (self.os_type == 14)
        scr_draw_background_ps4(some_other_number_im_too_lazy_to_check, 0, 0)
```
to
```
    if (self.os_type == 14)
        _temp_local_var_1 = 1
    else
        _temp_local_var_1 = (self.os_type == 20)
    if _temp_local_var_1
        scr_draw_background_ps4(2814, 0, 0)
```

which broke the pattern detection

**Comment by Kneesnap** [comment]
It does not appear there will be a PC release beyond 1.08. If a PC release happens though, this will need to be re-opened.
