### ISSUE TITLE
Load error: Unknown chunk PSEM

### ISSUE THREAD

**Issue by gilberto-torrezan** [krzys-h/UndertaleModTool#1209]
### Describe the bug

When trying to load the data.win file from [The Slormancer](https://store.steampowered.com/app/1104280/The_Slormancer/), I get this error:

![image](https://user-images.githubusercontent.com/7464735/223412350-99ba29e4-3d55-4893-a572-1a5f0f9cd285.png)

### Reproducing steps

1. Open UndertaleModTool
2. Open the data.win file in the tool
3. Wait a bit
4. The error happens
5. The file is not loaded, so nothing can be done in the tool

Loading the same file again makes the error repeat again. Restarting the application has no effect.

### Setup Details

- Using UndertaleModTool v:0.5.0.0 Git 31ec11b
- Windows 10
- Game: [The Slormancer](https://store.steampowered.com/app/1104280/The_Slormancer/)

Note: the tool was working normally until a recent update from the game developers. I don't know what has changed that made the mod tool break. It used to work until today.

**Comment by Dobby233Liu** [comment]
The devs may have switched to 2022.2 beta. The support for that version of the engine is not there yet

**Comment by gilberto-torrezan** [comment]
> The devs may have switched to 2023.2 beta. The support for that version of the engine is not there yet

Is there a quick and dirty way to check the GameMaker version, just to confirm it? Since I can't use the mod tool for it, can it be checked with a HEX editor?

**Comment by VladiStep** [comment]
> > The devs may have switched to 2023.2 beta. The support for that version of the engine is not there yet
> 
> Is there a quick and dirty way to check the GameMaker version, just to confirm it? Since I can't use the mod tool for it, can it be checked with a HEX editor?

I don't think that's a false positive, and, unfortunately, there's no actual value in data that says the exact GM version.

**Comment by Dobby233Liu** [comment]
@/colinator27 have determined that PSxx chunks were added in 2023.2 in our Discord server so I don't think you need to do that. Also, there's no quick way now
