### ISSUE TITLE
Undertale mod tool not opening.

### ISSUE THREAD

**Issue by Sub2ItzTreeGamer** [krzys-h/UndertaleModTool#1218]
### Describe the bug

When I try to open undertale mod tool, it almost instantly crashes. I'm not sure if I'm opening it wrong or if there is a problem with my computer. I opened the only exe file that was there when i downloaded it, "UndertaleModToolCli.exe". Am i opening the wrong exe file? When I open it, there is text, but only a few milliseconds to read it before it crashes. The text says, 

"Required command was not provided.

UndertaleModCli
 CLI tool for modding, decompiling, and unpacking Undertale (and other Game Maker: Studio games)!"
 
![undertale mod tool glitch](https://user-images.githubusercontent.com/92230177/224804311-af4f251d-1eba-4bdb-93ed-4079f833998b.PNG)

### Reproducing steps

As soon as i open UndertaleModToolCli.exe

### Setup Details

Using windows 10

**Comment by Jacky720** [comment]
CLI stands for "Command Line Interface". It's not crashing; command line tools generally close automatically when you run them with no parameters. You need to download the GUI version for regular tool usage. (The CLI can still be used for certain scripting techniques, but to do that you have to run it via Command Prompt and pass parameters.)

**Comment by Sub2ItzTreeGamer** [comment]
Thanks @Jacky720 but I'm still kind of confused. Is that the exe file I'm supposed to run in order to open Undertale mod tool or is there a different exe file?

**Comment by Jacky720** [comment]
There is a different file. Download one of the GUI zips, it'll contain UndertaleMod**Tool**.exe.

**Comment by Sub2ItzTreeGamer** [comment]
Thank you! It works now
