### ISSUE TITLE
Request: Change assembler behavior when string is referenced only by ID

### ISSUE THREAD

**Issue by a-felix** [krzys-h/UndertaleModTool#123]
Currently, when entering code like this:

    push.s @3444

in the disassembly tab, it gets interpreted as if it were written like this:

    push.s ""@3444

No matter what string there was with ID 3444 in this case, it gets changed into an empty string **everywhere**.

I think it would be way more useful if the assembler looked for the current value of the string and inserted it automatically instead. Or, better said, a string shouldn't be overwritten if it is only referenced by its ID.

For a 100% unaltered data.win from Deltarune, for example, the resulting disassembly when entering `push.s @3444` would be:

    push.s "あいうえお　まみむめも　ぁぃぅぇぉ"@3444

**Comment by krzys-h** [comment]
I'm pretty sure my original intent was to make the behavior exactly what you suggested, so this is probably a bug.
