### ISSUE TITLE
how do I export it into game maker studio

### ISSUE THREAD

**Issue by Harlan124** [krzys-h/UndertaleModTool#1230]
### Describe the bug

I want to be able to edit it in game maker studio how do I export it into it 

### Reproducing steps

i try to do it but it doesnt work 

### Setup Details

newest model of everything

**Comment by Jacky720** [comment]
Due to legal issues (the GameMaker project format copyright, mainly), we do not support or condone reversing games into GameMaker. Yes, the mod tool is often less convenient. Yes, it's a new workflow. Yes, sometimes the compiler just dies. No, we can't do that.
