### ISSUE TITLE
[REQUEST] Show where GameMaker: Studio will look when searching for a letter

### ISSUE THREAD

**Issue by BreakinBenny** [krzys-h/UndertaleModTool#124]
I've done a modified data.win with the Scandinavian and extra letters for translations, but I am confused and concerned about making GameMaker: Studio find the letters.

How about showing a marker or highlight in UndertaleModTool that precisely shows you which position will be used for the respective characters? Also, since I had to move the fnt_main.png and fnt_mainbig.png images around to accomodate for the extra letters, I have to tweak the Font settings accordingly to make them still use the letters already included.

I'll provide a picture for how it would look like...
![fnt_main example](https://user-images.githubusercontent.com/4566768/49828449-3cacb380-fd8c-11e8-92c9-e33383cc2bab.png)

**Comment by krzys-h** [comment]
Yup, would be useful

**Comment by Grossley** [comment]
I have made a utility similar to this, if you are interested, I may be able to make a script or some other tool that can do this. @BreakinBenny
