### ISSUE TITLE
i just have an small issue here

### ISSUE THREAD

**Issue by Gbiel99** [krzys-h/UndertaleModTool#1240]
### Describe the bug

i actually don't know if you can modify that weapons like empty have only 1 bar and  the bar goes fast, thats it

### Reproducing steps

no steps, its just an question

### Setup Details

no.

**Comment by Jacky720** [comment]
sure, it's in the code. `scr_attack` chooses to generate `obj_target` or `obj_shoetargettest` based on your weapon, which in turn create different objects, and so on.

**Comment by Gbiel99** [comment]
actually, if i try to change the attack of the empty gun of obj_shoetargettest -> obj_target , the game softlocks because no bars even spawn to attack

**Comment by Jacky720** [comment]
That's because `obj_target` has a check for whether you have the Stick, for whether you have the Toy Knife, Torn Notebook, Worn Dagger, or Real Knife, and for whether you have the Tough Glove or Burnt Pan (yes, the Pan normally uses the multi-bar pattern). You'll need to add an option for the gun- ID 49- to make it do something.

**Comment by Gbiel99** [comment]
game's code:
if (global.weapon == 3 || global.weapon == 13 || global.weapon == 14 || global.weapon == 51 || global.weapon == 52)
    instance_create((global.idealborder[0] + 6), (global.idealborder[2] + 6), obj_target)
if (global.weapon == 25 || global.weapon == 49 || global.weapon == 47 || global.weapon == 45)
    instance_create((global.idealborder[0] + 6), (global.idealborder[2] + 6), obj_shoetargettest)
code i've used:
if (global.weapon == 3 || global.weapon == 13 || global.weapon == 14 || global.weapon == 51 || global.weapon == 52|| global.weapon == 49)
    instance_create((global.idealborder[0] + 6), (global.idealborder[2] + 6), obj_target)
if (global.weapon == 25 || global.weapon == 47 || global.weapon == 45)
    instance_create((global.idealborder[0] + 6), (global.idealborder[2] + 6), obj_shoetargettest)

**Comment by Jacky720** [comment]
well, that's `scr_attack`, and you'll have to edit `obj_target`'s code.

**Comment by Gbiel99** [comment]
oh i get it

**Comment by Gbiel99** [comment]
it worked, thank you!
