### ISSUE TITLE
Can't delete objects when selecting them

### ISSUE THREAD

**Issue by Possiblycoolperson** [krzys-h/UndertaleModTool#1247]
### Describe the bug

when I select an object and press the delete key, it will not delete the object, but it bring me to the room I was previously editing.

### Reproducing steps

what I said before

### Setup Details

I am on undertale mod tool 0.5.1.0.

**Comment by Jacky720** [comment]
You mean, deleting an object instance from a room? I want to be clear that completely deleting an object from the sidebar is a bad idea because of how the game references by index.

**Comment by Possiblycoolperson** [comment]
what I mean is that it does not delete the object in the room and the list at all, (and also I have tried selecting it from the room editor & the object list and neither work.

**Comment by VladiStep** [comment]
It's weird.
Can you check if your "Delete" key works properly?
You can open WordPad (or any editable text field), select/highlight a text, and press "Delete" - it should delete the selected text.

**Comment by Possiblycoolperson** [comment]
I will show you a video of my problem
https://www.youtube.com/watch?v=fW_DI2TwMNM

**Comment by Possiblycoolperson** [comment]
Also, with other things, like text in Undertale mod tool, my delete key works fine

**Comment by VladiStep** [comment]
> I will show you a video of my problem https://www.youtube.com/watch?v=fW_DI2TwMNM

It's _really_ weird.
On the video, when you press `Delete`, a "spr_plug" sprite opens.
Was it the previous opened object (have you opened it before opening the room) ?

**Comment by VladiStep** [comment]
Anyway, I think there should be a context menu option for that.
I'll create a separate issue for it.

**Comment by Possiblycoolperson** [comment]
the plug was my previously opened object.
(also were is the context menu options?)

**Comment by VladiStep** [comment]
So, you can delete the object by right-clicking it now (it's in the "Bleeding edge" version).

**Comment by Possiblycoolperson** [comment]
ok
