### ISSUE TITLE
[REQUEST] Mass import/export

### ISSUE THREAD

**Issue by StayFrozty** [krzys-h/UndertaleModTool#125]
Hi there,

I'd like to request the ability to mass import/export decompiled scripts and object code into separate folders + text files.

This would allow users to edit code in their choice of text editor (read 'Notepad++') and then load it back into the program.

**Comment by colinator27** [comment]
Editing of high level code isn't even supported yet... Though it is definitely in the works.

For now this would just be editing the assembly manually.

**Comment by krzys-h** [comment]
Duplicate of #92
