### ISSUE TITLE
Cannot Decompile Antonblast data.win (Kickstarter Demo)

### ISSUE THREAD

**Issue by TheHenshinGamer** [krzys-h/UndertaleModTool#1251]
### Describe the bug

Upon trying to decompile, it throws this error.
![image](https://user-images.githubusercontent.com/129347902/228706294-c60222f8-568e-4c44-8d9b-efb06c0b7fef.png)
I am able to load the audiogroup2.dat file, but not the main data.win

### Reproducing steps

1. Open Data.Win
2. Error

### Setup Details

1. Version 0.5.1.0
2. Windows 11
3. https://summitsphere.itch.io/antonblast-kickstarter-demo

**Comment by VladiStep** [comment]
> Having the same issue, specifically seems to be something sequence related.
> 
> ![image](https://user-images.githubusercontent.com/49070403/228780733-a9ca2c57-d6f5-42d3-bdba-182cb2cf1b15.png)

It doesn't seems like the same issue, how you assumed that's related to sequences?

**Comment by VladiStep** [comment]
@TrashBandatcoot, how did you reproduce that error?

**Comment by VladiStep** [comment]
Oh, I see the cause of the crash now.
I just made [a separate issue](https://github.com/krzys-h/UndertaleModTool/issues/1252).

**Comment by TheHenshinGamer** [comment]
> Oh, I see the cause of the crash now. I just made [a separate issue](https://github.com/krzys-h/UndertaleModTool/issues/1252).

Cool, now we just need to hope the original issue I had gets fixed too.

**Comment by VladiStep** [comment]
In this case, you could downgrade to release 0.5.0.0, because this error was introduced on March, 3.

**Comment by TrashBandatcoot** [comment]
Core issue is either back or was never fixed. Got the same error on git 2257a2e, but this time with different offsets(?)

![image](https://user-images.githubusercontent.com/49070403/230114620-efbe12a1-fea4-44b7-94dd-85d6b74c2d63.png)

**Comment by VladiStep** [comment]
What a coincidence, that's the last unimplemented track type after I've reverted the group track regression.

**Comment by VladiStep** [comment]
Should be fixed now, try the latest "Bleeding edge".
