### ISSUE TITLE
There's no way to remove room objects without using the "Del[ete]" key.

### ISSUE THREAD

**Issue by VladiStep** [krzys-h/UndertaleModTool#1290]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

There should be a context menu option for every room object in the list, so you can delete the object only using mouse.

**Comment by zivmaor** [comment]
If I'm understanding what you've described correctly then that's already a feature. Right click on the room you want to delete to open the context menu.
![image](https://user-images.githubusercontent.com/63353113/230804483-7f2242e2-e206-49be-9eae-a2665513cf51.png)

**Comment by VladiStep** [comment]
> If I'm understanding what you've described correctly then that's already a feature. Right click on the room you want to delete to open the context menu. ![image](https://user-images.githubusercontent.com/63353113/230804483-7f2242e2-e206-49be-9eae-a2665513cf51.png)

> ... remove **room** objects

Yes, you didn't understand it correctly - it's for room editor.
