### ISSUE TITLE
Update MixMod dependency list

### ISSUE THREAD

**Issue by leo60228** [krzys-h/UndertaleModTool#131]
Just installed it and UNDERTALE crashes on startup with this exception:

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at GMWebExtension.GMWebExtension.__webextension_native_init()
```

**Comment by leo60228** [comment]
You could add the dependency to the docs, maybe?

**Comment by krzys-h** [comment]
Might be a good idea. Not sure why it's required though since I used VS2017 and you are the first one to report this problem.

**Comment by Kneesnap** [comment]
I don't know what issue this is. I had no issue using the script after updating it, by following the guide. I will close this issue unless there is any disagreement.
