### ISSUE TITLE
Game's graphics' placement going haywire after using ImportGraphics.csx

### ISSUE THREAD

**Issue by Sonatee** [krzys-h/UndertaleModTool#1326]
### Describe the bug

Graphics' placement is completely broken
![Scampton The Great 17 04 2023 13_56_35](https://user-images.githubusercontent.com/89305185/232463885-de45f0c0-572d-4e46-b231-99e14f652716.png)
![Scampton The Great 15 04 2023 20_39_58](https://user-images.githubusercontent.com/89305185/232463951-5fcdd508-391f-45b9-a56c-600a1aaa87ff.png)

### Reproducing steps

I extracted images using ExportSprites.csx, added extra graphics and imported using ImportGraphics.csx

### Setup Details

I used latest version 5.1.0 (Bleeding Edge)

**Comment by VladiStep** [comment]
Have you answered "Yes" to the "Export all sprites unpadded?" question?
