### ISSUE TITLE
Unable to use this

### ISSUE THREAD

**Issue by giorgigongladze** [krzys-h/UndertaleModTool#133]
I need some help. I tried to use UndertaleModTool but when I open it up it says _**Root chunk is not FORM**_. How can I fix this? Please tell me!

**Comment by colinator27** [comment]
That can only mean that the data file you open is corrupt or invalid... Are you sure you're opening the `data.win`/`data.*` file and not the EXE itself? If you only have an EXE, be sure to extract it first to get the data files out of it.

**Comment by krzys-h** [comment]
Yeah, you are probably opening a wrong file. Make sure to open the data.win file and not the .exe
