### ISSUE TITLE
Cannot modify functions I previously created

### ISSUE THREAD

**Issue by kenan238** [krzys-h/UndertaleModTool#1344]
### Describe the bug

![image](https://user-images.githubusercontent.com/73741117/233777302-e0c827aa-d37c-4da0-a72d-6bac137c6c41.png)
It just throws this when trying to modify a function I previously created
And when I try disassembly, It crashes with 
![image](https://user-images.githubusercontent.com/73741117/233777322-9d80e102-3192-47a8-ad42-f2afe8e87c94.png)

### Reproducing steps

1. Make a function
2. Restart UMT
3. Try to modify it

### Setup Details

1. UndertaleModTool v:0.5.1.0 commit 
2. Windows 10
3. Pizza Tower, but happens on all other game maker games I've tried

**Comment by VladiStep** [comment]
Do you mean "modify the function contents" or "modify the function name" ?

**Comment by kenan238** [comment]
Function contents

**Comment by kenan238** [comment]
Also it would be great to make it not crash on disassembly and show the error as a comment

**Comment by VladiStep** [comment]
> Also it would be great to make it not crash on disassembly and show the error as a comment

This was fixed recently, you can update to the latest "Bleeding edge".

**Comment by kenan238** [comment]
But back to my original issue, what do we do about that?

**Comment by kenan238** [comment]
Apparently it duplicates the function's script, but deleting the duplicate doesn't help

**Comment by kenan238** [comment]
Any updates? This is a core part of modding, and I ability to modify functions is quite vital.
I forked the UMT source and try-catched all the errors, it seems to make me able to modify functions again, but has it's own bugs with it
