### ISSUE TITLE
Adding to non-objects is currently unsupported while selected to "Game Object"

### ISSUE THREAD

**Issue by PlanetSat0rn** [krzys-h/UndertaleModTool#1345]
### Describe the bug

Trying to add Creation Code onto a Game Object Results in a error saying "Adding to non-objects is currently unsupported"

### Reproducing steps

Trying to add Creation Code onto a Game Object

### Setup Details

Bleeding Edge
Windows 10
Pizza Tower

**Comment by zivmaor** [comment]
Are you referring this?
![image](https://user-images.githubusercontent.com/63353113/233806241-152d1afb-72ed-4f37-94e4-38ad289a3244.png)

**Comment by PlanetSat0rn** [comment]
Yes

**Comment by zivmaor** [comment]
What you were trying to add creation code to is a Game Object Instance - that specific instance of the object in that room, and not the Game Object. That creation code will only be run when that instance is created, as opposed to the creation code of the Game Object which will be run when any instance of the object is created.

A Game Object Instance is not a Game Object and adding to it is not currently supported, as the error message says.
If you want it to be supported you can make an enhancement issue about it.
You can currently add creation code for the instance manually by creating a new code entry and dragging it into the creation code field.

**Comment by PlanetSat0rn** [comment]
alright thanks for answering me about that
