### ISSUE TITLE
Malware thing..?

### ISSUE THREAD

**Issue by charadreemurr** [krzys-h/UndertaleModTool#135]
I tried to open the UndertaleModTool, but since I have Windows Defender, it keeps saying ''Windows protected your PC
Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk''
And there's a button where it says "Don't Run"
I decide to run it, but I don't know how to open it with Windows Defender being on.
How can I run it?

**Comment by BreakinBenny** [comment]
Looks like some kind of false positive...

**Comment by Govorunb** [comment]
You can click "More info" and then "Run anyway".

SmartScreen just checks Microsoft servers with every executable you run to see if it's (a) digitally signed (sort of like a marker for an 'official' application) and (b) used by a large enough number of people. The mod tool, by comparison to most other applications, is not very commonly run, so SmartScreen pops up the "unrecognized" warning.

**Comment by krzys-h** [comment]
Yup, it's basically what @Govorunb said, SmartScreen doesn't like small apps from developers who didn't buy  Authenticode certificates...
