### ISSUE TITLE
which file do i download

### ISSUE THREAD

**Issue by MrBendyRift** [krzys-h/UndertaleModTool#1350]
### Describe the bug

ok so there are like 8 files, which one do i download? like which file name do i download or something?

### Reproducing steps

go to releases and look at it those are the steps

### Setup Details

please help

**Comment by VladiStep** [comment]
> CLI
> 
> its not rocket science

Wrong, unless you actually want to use the command line.
You need one of the GUI ones - probably "[GUI-windows-latest-Debug-isBundled-true-isSingleFile-true.zip](https://github.com/krzys-h/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Debug-isBundled-true-isSingleFile-true.zip)".

**Comment by PlanetSat0rn** [comment]
> > CLI
> > its not rocket science
> 
> Wrong, unless you actually want to use the command line. You need one of the GUI ones - probably "[GUI-windows-latest-Debug-isBundled-true-isSingleFile-true.zip](https://github.com/krzys-h/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Debug-isBundled-true-isSingleFile-true.zip)".

yeah i may be a idiot
