### ISSUE TITLE
REQUEST - Update TTFFonts.csx to include better fonts

### ISSUE THREAD

**Issue by Tendali** [krzys-h/UndertaleModTool#136]
Hi, I'm translating Undertale and I heavily use TTFFonts.csx. Recently I found this [website](https://www.behance.net/gallery/31268855/Determination-Better-Undertale-Font) talking about a better font for Undertale. (See the website for the font comparisons.) I'm translating to Czech and this new "Determination" font has even more chracters implemented.
Please, could you update the TTFFonts script to use this font?

Thank you so much,
Tendali

**Comment by BreakinBenny** [comment]
Andreyyshore helped me out by adding extra Unicode characters to the Undertale/Deltarune glyphs, but not all of them at this point.

…Regardless, this would be pretty sweet.

**Comment by Kneesnap** [comment]
This does not appear to be in .ttf format. Also, the new TTFFonts.csx is very easy to modify. If you want to support these fonts, try getting them in a font format that gamemaker supports, then modifying the new TTFFonts.csx
