### ISSUE TITLE
Load error (Unknown chunk PSEM)

### ISSUE THREAD

**Issue by BAP00tato** [krzys-h/UndertaleModTool#1362]
### I tried to open the Sucker for love : Date to die for demo's data.win file.

**I get through a bunch of warning that are this**

![image](https://user-images.githubusercontent.com/112852330/236356745-37cbcc5c-b900-438f-9cb0-c1d1923764c2.png)

**But then I get this error after**
![image](https://user-images.githubusercontent.com/112852330/236356243-ede6e25a-d33b-49c9-89a9-1dc5708c573e.png)

The data does not load at all.

Is there something I'm doing wrong or is this game too new?

### Reproducing steps

1 -  Load the games Data.win file
2 - Go through the warnings
3 - Error appears

### Setup Details

1 - v0.5.0.0
2 - Windows 10 home
3 - Unknown

**Comment by Jacky720** [comment]
Please try the [Bleeding Edge](https://github.com/krzys-h/UndertaleModTool/releases/bleeding-edge) version. PSEM (particles? I don't recall off the top of my head) was added in GM 2023.2 which wasn't out at the time v0.5.0.0 released.

**Comment by BAP00tato** [comment]
> Please try the [Bleeding Edge](https://github.com/krzys-h/UndertaleModTool/releases/bleeding-edge) version. PSEM (particles? I don't recall off the top of my head) was added in GM 2023.2 which wasn't out at the time v0.5.0.0 released.

I just did and it worked. Interesting
