### ISSUE TITLE
ImportGraphics.csx does not account for indexes with leading zeroes

### ISSUE THREAD

**Issue by naether** [krzys-h/UndertaleModTool#1368]
### Describe the bug

Using the ImportGraphics.csx script with any multiple-frame sprite png that has leading zeroes (0000, 0001, 0002) stops the script, with the popup;

![image](https://user-images.githubusercontent.com/60763676/236610237-4223e7f7-b3f5-410b-8a1c-58d614d3fcd2.png)

### Reproducing steps

1. Run ImportGraphics.csx
2. Select any sprite folder with any sprite that has leading zeroes in its index
3. is no work😥

### Setup Details

UT Mod Tool version: 0.5.1.0/bleeding edge commit b3e180ce15a4f968ee8ebe452999b1b1f19092b4
GUI-windows-latest-Release-isBundled-true-isSingleFile-true

Windows 8

Pizza Tower

**Comment by VladiStep** [comment]
If you are importing a multi-frame sprite, the first frame must have a zero index in the name.
How did you got the files, by the way?

**Comment by VladiStep** [comment]
Wait, how the files are named? It should be "spr_player_crouch**_**0000.png", "spr_player_crouch**_**0001.png", etc.

**Comment by VladiStep** [comment]
Nevermind all of the above, I see the problem now.
