### ISSUE TITLE
Optimizations on RAM Usage from decompiling?

### ISSUE THREAD

**Issue by Reycko** [krzys-h/UndertaleModTool#1372]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

![image](https://user-images.githubusercontent.com/78082869/236673544-eb0e57e1-47fe-4c0f-b8f7-48c5a89f0f4a.png)
My PC froze for 5 minutes while decompiling a script.

**Comment by VladiStep** [comment]
Let me guess - was it "gml_GlobalScript_scr_player_mach3" from "Pizza Tower" ?
If yes, then it's a duplicate - https://github.com/krzys-h/UndertaleModTool/issues/1179

**Comment by Reycko** [comment]
Oh okay
