### ISSUE TITLE
export texture with bounding box

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [krzys-h/UndertaleModTool#1378]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

it doesn't export the bounding box only the texture

**Comment by VladiStep** [comment]
Hmm, but what is the use case of this?

**Comment by H-A-M-G-E-R** [comment]
as a script

**Comment by H-A-M-G-E-R** [comment]
ExportAllTextures.csx with padding
