### ISSUE TITLE
"Margin" misspelled in sprite viewer

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#138]
![image](https://user-images.githubusercontent.com/8469545/51808507-9d635300-2249-11e9-805e-3d9d1b5dd9ef.png)

**Comment by BreakinBenny** [comment]
Leave it to me!
https://github.com/BreakinBenny/UndertaleModTool/commit/2c7e804902efc8df5144618c617ac3f2677267a3

**Comment by Myriachan** [comment]
looks fixed

**Comment by BreakinBenny** [comment]
No worries.
