### ISSUE TITLE
Loading Warning when Opening some games

### ISSUE THREAD

**Issue by skeltonmod** [krzys-h/UndertaleModTool#1381]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/25955908/2780ea1f-9ec7-436e-8eee-abdec417de4a)

Some data.win files are having this problem, not really sure what the cause is. But in this case it's the [Destructivator 2 Demo](https://gamejolt.com/games/destructivator2demo/309337)

### Reproducing steps

1. Open UndertaleModTool
2. Open the game's  `data.win` file
3. `Loading warning` pops up

### Setup Details

1. UndertaleModTool Version: Both bleeding edge and Stable 0.5.1.0
2. Operating System: Windows 10 Pro 22H2 (Build 19045.2965)
3. Gamemaker Game: https://gamejolt.com/games/destructivator2demo/309337
4. Gamemaker Game Version: Unknown

**Comment by xiaweichuliang** [comment]
hi~ does the developer repair it? i use v:0.5.1.0 and it still have unending loading warning like below
![image](https://github.com/krzys-h/UndertaleModTool/assets/71426054/d734f0b2-c567-44b7-b5c6-27f7c3da8e22)

**Comment by Jacky720** [comment]
I've just confirmed that the game can indeed open given several minutes of closing warnings with the Enter key. I'll look into this further. Note that the tool estimates its version as GMS 2.2.1, and all the warnings were in the ROOM chunk.

**Comment by xiaweichuliang** [comment]
I'm not a developer so i don't understand what's your meaning, this is all the information
![image](https://github.com/krzys-h/UndertaleModTool/assets/71426054/bfb35f18-d0db-45ff-8861-0a9f7b4495bd)
![image](https://github.com/krzys-h/UndertaleModTool/assets/71426054/a4943697-bd36-44cc-954a-d2abbc0bdc01)
![image](https://github.com/krzys-h/UndertaleModTool/assets/71426054/fbb58dbc-f7da-4bb4-bb7a-acd9e8b06877)
So do you mean it will be fixed in the next version?

**Comment by xiaweichuliang** [comment]
#1550 This works normally! thank u

**Comment by xiaweichuliang** [comment]
but how can I extract the stuff? for example I want to extract the walking action from the Sprites

**Comment by Jacky720** [comment]
Scripts (from the top bar) > Unpackers > ExportAllSprites.csx will export sprites as PNGs, and then you can search through them for walking animations.

**Comment by xiaweichuliang** [comment]
> Scripts (from the top bar) > Unpackers > ExportAllSprites.csx will export sprites as PNGs, and then you can search through them for walking animations.

thanks, and is there any user guide? i don't need to ask u for some basic help with that

**Comment by Jacky720** [comment]
No, unfortunately. The Underminers Discord is a good place to find info, though, even if it isn't super well-organized. And you can ask for help there.
