### ISSUE TITLE
"Code locals" not unused in Mega Man Maker

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#139]
The "Code locals" option actually has meaningful data when UndertaleModTool is used on Mega Man Maker (which works great, by the way!).
![image](https://user-images.githubusercontent.com/8469545/51818964-8a6e7400-2285-11e9-9f75-6f39fcddb78f.png)

I guess Undertale and Deltarune don't use the local variable feature...?

**Comment by krzys-h** [comment]
It does have content, but nothing seems to change if you remove it - this is what I meant by "unused". And while it doesn't seem used by the actual game, it's probably useful for the GMS debugger and my decompiler to resolve local variables. It may be a good idea to remove that misleading label.

**Comment by Kneesnap** [comment]
This is not a bug, by the looks of things. Undertale and Deltarune use this too, it's just that because Toby never uses local vars there's rarely any meaningful data.
