### ISSUE TITLE
MenuItem thinks that underscores in resource names are for bold, italic, etc.

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#14]
In context menu that appears when clicking on a number/resource in the code editor, it seems that the MenuItems interpret the resource names put into the Header field as formatted. This is a problem because then the names can lose characters/underscores and change appearance for no apparent reason.

The problem seems to occur at https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/Editors/UndertaleCodeEditor.xaml.cs#L382. Perhaps something could be done to format the string (like escaping all underscores?).

Here is an image of this problem occurring:
![Problem](https://user-images.githubusercontent.com/17358554/45719155-6e3b2780-bb6d-11e8-99b9-0ca3ca1c13e7.png)

**Comment by krzys-h** [comment]
I noticed that recently too. I think _ is actually used for marking the standard windows alt+<some letter> menu navigation.
