### ISSUE TITLE
Suggestion: Uncheck "Prefer 32-bit"

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#140]
I wrote a script to dump out all the sprite bitmaps, and the script runs out of memory, even though the allocated memory at any time is only 200 MB.  It seems that the garbage collector isn't working because the native heap became fragmented.

This problem goes away if I uncheck the "Prefer 32-bit" box in the .exe properties, because then it runs as a 64-bit program.

**Comment by krzys-h** [comment]
I thought I already did that because the decompiler tests kept failing for the same reason. I'll double-check though.
