### ISSUE TITLE
SURVEY_PROGRAM gml_Object_obj_mainchara_Step_0 recompiled isn't the same as the original

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [krzys-h/UndertaleModTool#1413]
### Describe the bug

it's non-matching

### Reproducing steps

recompile the decompiled gml_Object_obj_mainchara_Step_0 in the SURVEY_PROGRAM demo

### Setup Details

commit [35eb010](https://github.com/krzys-h/UndertaleModTool/commit/35eb010e62c29c12fc7f9571f552988bfca6d8aa)
Windows 10
SURVEY_PROGRAM of vanilla deltarune or [deltarune repainted](https://gamejolt.com/games/nudealert/496504)

**Comment by Jacky720** [comment]
Duplicate of #224.
