### ISSUE TITLE
About the font

### ISSUE THREAD

**Issue by zellfy** [krzys-h/UndertaleModTool#142]
![1](https://user-images.githubusercontent.com/45615697/51965106-7902b300-24a3-11e9-8602-da6c390aaa3f.png)
![2](https://user-images.githubusercontent.com/45615697/51965110-7c963a00-24a3-11e9-9516-ca451e1c77d9.png)

hey brother, I'm just translating this game from English to Chinese, but I found that I can't set up the size of font correctly, no matter what  I did, it can only cut a part of the font PNG. 
Please do me a favor.

**Comment by zellfy** [comment]
Thanks for your reply @Mc-muffin first!
Forgive my poor English second! I will make it clear by all means.
①I've made a 4096×3584 PNG, included all the Chinese Characters and the other symbols that UT-game needed with photoshop. And then I devided 6 font areas from the PNG.
②Upload the 4096×3584 PNG.(the second photo I uploaded)
③The 1st font which size is 4096×1024, I have it like what you replied:

              Field              | X | Y | Width | Height
Source position/size   | 0 | 0 | 4096   | 1024
Target position/size    | 0 | 0 | 4096   | 1024

BUT BUT BUT in the first photo which I uploaded you can see that this modtool just cut less than 4096×1024. So it is not the whole area which font1 needed. 

How to solve this problem, waiting for your reply :)

**Comment by Mc-muffin** [comment]
Thanks for the extra details. 
Now the tool is cutting the correct amount of pixels but at the wrong location so you will need to modify the 2 first values:

|Field| X | Y | Width | Height |
|-|-|--|--|-|
|Source position/size | **128** | **256** | 4096 | 1024|
|Target position/size | 0 | 0 | 4096 | 1024|

The 128 and 256 number I used are an asumption, you would use the X and Y coordinates of your charactermap. Use a program like photoshop to know where they are, or experiment a little with these values.

I hope this time it was more understandable.

**Comment by zellfy** [comment]
Hmmmmm, thanks for your reply.  @Mc-muffin 
But I think this tool doesn't cut the correct pixels, it cut pixels smaller that 4096×1024, which I can't understand.
No matter what coordinates I use for X and Y, I can't cut a complete area from a uncomplete charactermap.

**Comment by zellfy** [comment]
![333](https://user-images.githubusercontent.com/45615697/52053892-a2037080-2595-11e9-8237-4561b9c832d4.png)
This is 4096×1024 pixels, you can see that it is bigger than the tool cut from my charactermap.

**Comment by zellfy** [comment]
![bbc](https://user-images.githubusercontent.com/45615697/52098709-0d3b5a00-260b-11e9-9bf9-03fb61611a46.png)

Of course.

**Comment by zellfy** [comment]
And I set up it at Fonts not texture page items.Do I do it wrong?

**Comment by zellfy** [comment]
Or I should create a new “texturepageitems”, and import the 4096×3584 PNG as a charectermap, and then drop the "texturepageitems" to the font?

**Comment by zellfy** [comment]
![1](https://user-images.githubusercontent.com/45615697/52105093-3dddbc80-2628-11e9-840a-cd1df6aa934d.png)
I'm so sad that.

**Comment by zellfy** [comment]
@Mc-muffin I've found what mistake I take. I was just doing wrong with pixels/cm and pixels/in when I make the charectermap in photoshop so....

**Comment by Mc-muffin** [comment]
> @Mc-muffin I've found what mistake I take. I was just doing wrong with pixels/cm and pixels/in when I make the charectermap in photoshop so....

Ah, funny mistake x) well I think you have resolved your own problem now, feel free to close the issue.

And much luck with translating the game!
