### ISSUE TITLE
Profile Mode is disabled in GameMaker 2.3 games.

### ISSUE THREAD

**Issue by Romualdo666** [krzys-h/UndertaleModTool#1423]
### Describe the bug

Basically, I found out that Profile Mode is disabled on any GameMaker 2.3 games. I brute forced undertale mod tool to work with it and there aren't any problems so I think that line of code is just a leftover to be removed.

### Reproducing steps

1. Activate Profile Mode.
2. Try to make a // message inside a code, for example.
3. Decompiler still removes it.

### Setup Details

1. Undertale Mod Tool Bleeding Edge.
2. Windows 11.
3. Deltarune.

**Comment by Miepee** [comment]
This is not an issue anymore, it was fixed by https://github.com/krzys-h/UndertaleModTool/pull/1424
