### ISSUE TITLE
Error on load Unable to find function ossafe_file_exists

### ISSUE THREAD

**Issue by Nardeem** [krzys-h/UndertaleModTool#1429]
### Describe the bug

I can't open undertale cus it can't find the function "ossafe_file_exists". But I checked and the function is still there?

### Reproducing steps

No idea what caused it, when I launch the game it does that.

### Setup Details

I am using undertalemodtool v0.5.1.0.
I am using Undertale GOG version.
I am using windows 11 on a laptop with intel core i5 intel iRISx GRAPHICS

**Comment by Jacky720** [comment]
When you run the game, it attempts to load every function in the functions list. Some of them are found in the game runner, some of them are found in the data.win scripts. But if it finds it in neither, you get that crash.

One of two things has happened:
* You're playing an old version of the game that doesn't have ossafe scripts, and imported some code intended for a newer version, which generated the function entry but not the script. Get rid of that code, then delete the function entry.
* You're playing a modern version of the game that does have ossafe scripts, but you deleted one of the scripts without deleting the function. In this case, even deleting the function wouldn't get rid of all the references to the script; put the script back.

**Comment by Nardeem** [comment]
So do I delete the folder thing in data.win called function? Or do I just delete ossafe_file_exists, because I think your first point is the one that happened.

**Comment by Jacky720** [comment]
With the data opened in UTMT, open the "Functions" dropdown, scroll to the end, and delete ossafe_file_exists from there. Also, delete it anywhere else it appears.

**Comment by Nardeem** [comment]
I tried that, then I opened and it didn't work, then I tried to delete the whole thing but it didn't work? Now it can't find function ossafe_file_text_open_read instead, but the file exists issue is fixed, I'll try delete and I'll see

**Comment by Nardeem** [comment]
Ok, so I deleted the files it says it couldn't find, with ossafe it just gave more errors, then it did an SCR file, I deleted it and used temprun instead, now it just gives no error but it still crashes? is there anything in undertale that can just let me repair the data.win file?

**Comment by Nardeem** [comment]
Ok, so I just reinstalled the game and it's fine now, thank you for tryna help, now I know what to do in the future!
