### ISSUE TITLE
Saving a data.win that have EXTN doesn't produce a 1:1 file

### ISSUE THREAD

**Issue by Mc-muffin** [krzys-h/UndertaleModTool#143]
Opening a data.win file that has the EXTN chunk and saving it (without modifying anything) produces a file with different EXTN chunk lenght. For most purpouses it should be fine, but a PS-Vita game may be affected by this slight change (As the PS-Vita runner is more sensitive to malformed .win files)

Tested it and both the PC version (Bytecode 15) and the Vita version (Bytecode 16) and both produced files with different EXTN chunk lenghts (and the pointers shifted by this).

The PC version runs just fine with the PC runner, but the Vita version crashes just as it opens on the console (using the game.win with a PC runner works just fine).

EDIT: Whoops pushed issue before writing a description

**Comment by colinator27** [comment]
Is there any other information you can give? Theoretically it should work already... Are the chunk lengths greater or less, and is it possible to figure out what exactly changes in them?

**Comment by Mc-muffin** [comment]
Well, the only extension is GMFilesyStem, as for he chunk lenghts they are less, by exactly 16 bytes. The EXTN of the original file has a length of `AC 01 00 00` while the saved one has `9C 01 00 00`.

The only difference I found (apart from the changed offsets pointing to strings, as the new lenght of EXTN shifted them) was the last 16 bytes that are missing from the saved .win file, I don't know how useful they are by themselves, but here they are: `31 0E FD 34 44 E6 FA 15 E2 31 2E EA 55 1B 2C 76`

**Comment by colinator27** [comment]
Hmm. Any chance you could give me the GameMaker version they use? My calculation to detect whether those last 16 bytes exist is probably wrong (for reference, see [this](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModLib/UndertaleChunks.cs#L112)).

**Comment by Mc-muffin** [comment]
Based on the version listed on "General Info" GM Version 1.0.0.1541 for the PS-Vita version (A weird version, the closest I can find is 1.0.0.1542) and GM 1.0.0.1757 for the PC version.

**Comment by colinator27** [comment]
Well... that's quite strange I guess. I don't exactly remember, but I checked multiple compiler versions for this code and it probably didn't exist on a certain one... But maybe it's around some build version closer to 1541. In that case just changing the `9999` on that line of code I linked to that number should fix it (the 9999 refers to build number 9999). However we probably need to check if it breaks anything in any games previously known to work with UndertaleModTool to begin with, because there may be some other unknown factor (but as far as I know, this stuff is hardcoded into the compiler).

**Comment by Mc-muffin** [comment]
Yep, changing it make the chunk in the two versions the same lenght, but oddly enough now the TPAG chunk is 2 Bytes shorter ._.

**Comment by Mc-muffin** [comment]
That padding seems important, if those 2 bytes are missing the game refuses to launch on PS-Vita.

**Comment by krzys-h** [comment]
Did you ever figure out what exactly causes this and how to fix it?

**Comment by Mc-muffin** [comment]
> Did you ever figure out what exactly causes this and how to fix it?

For the Vita edition, TPAG **NEEDS** to be padded to end on a 4-byte boundary or else it would crash at startup, I didn't test with other games, but the extra 16-bytes on EXTN also seemed important.

**Comment by colinator27** [comment]
I just wanted to say that in the latest GMS2 version, this EXTN padding may no longer be present, along with other updated formats that seem to have broken the reader (seems to be in the ROOM chunk, but I'm not sure, I haven't looked into it. just a ton of misaligned reading warnings).

**Comment by colinator27** [comment]
(figured that problem out above, they added two new variables to instances)

**Comment by Kneesnap** [comment]
Related: https://github.com/krzys-h/UndertaleModTool/issues/169

**Comment by Grossley** [comment]
I am also having this issue, resaving [this demo](https://www.dropbox.com/s/kz6e77y0j5b7tjj/text_to_speech_demo.exe?dl=0) does not produce a 1 to 1 copy. I managed to fix the missing 16 bytes by lowering the threshold version number at which it would read the product ID, but it still does not produce a 1 to 1 save.

**Comment by Grossley** [comment]
I believe this is resolved through the implementation of alignment detection, and the alignment toggler script for manual correction. If this issue is still a problem, please feel free to reopen the issue.
