### ISSUE TITLE
ExportAllRoomsToPng.csx fails with a "Value cannot be null" error

### ISSUE THREAD

**Issue by Fried-Potato-Chip** [krzys-h/UndertaleModTool#1430]
### Describe the bug

When running the script 'ExportAllRoomsToPng.csx', the first 2ish rooms render successfully but after that the script throws an exception. This isn't a script issue either, as my custom script (which worked until I updated UMT) also stopped working.

![2023-07-09_16-13-01](https://github.com/krzys-h/UndertaleModTool/assets/95540809/052b202b-4733-4d82-908f-0f13e51fa956)

### Reproducing steps

1. Click scripts at the top of the window
2. Run "Resource Unpackers/ExportAllRoomsToPng.csx"
3. Some rooms will render, but eventually the script throws System.ArgumentNullException.

### Setup Details

1. UndertaleModTool commit 32cd3ea (bleeding-edge)
2. Windows 11 22H2 Build 22621.1928
3. DELTARUNE Chapter 1&2 1.00 (itch.io)

**Comment by Fried-Potato-Chip** [comment]
Here is a larger stacktrace that my script shows (sorry for using an screenshot instead of text, I cannot figure out how to copy it).
After this, UndertaleModTool crashes instantly.

![2023-07-09_16-27-38](https://github.com/krzys-h/UndertaleModTool/assets/95540809/71ba7449-687a-467c-8086-409af9f85cca)

**Comment by XCXDSHS** [comment]
Me too, have you solved it?

**Comment by XCXDSHS** [comment]
> > 我也是，你解决了吗？
> 
> 不是真的，我只是降级到 5.0.0，它又工作了。我不使用新功能。

I asked other people and they told me this script only works for tobyfox games undertale and deltarune 1&2

**Comment by XCXDSHS** [comment]
> > 我也是，你解决了吗？
> 
> 不是真的，我只是降级到5.0.0，它又工作了。我不使用新功能。

According to your test, it seems that currently only version 5.0 of deltarune 1&2 can use the script, while any version of undertale is valid. After all, this tool is mainly aimed at the game undertale.
