### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by pisstowel** [krzys-h/UndertaleModTool#1451]
### Describe the bug

When i added      if (obj_player.movespeed < 2.4)
    draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 2.4 && obj_player.movespeed < 4.8)
    draw_sprite_ext(spr_speedbar, 1, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 4.8 && obj_player.movespeed < 7.2)
    draw_sprite_ext(spr_speedbar, 2, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 7.2 && obj_player.movespeed < 9.6)
    draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 9.6 && obj_player.movespeed < 12)
    draw_sprite_ext(spr_speedbar, 4, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 12) && obj_player.movespeed < 16)
    draw_sprite_ext(spr_speedbar, 5, 125, 140, 1, 1, 1, c_white, alpha)

else if (obj_player.movespeed >= 16) draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)
to gml_Object_obj_camera_Draw_64
underneath var ry = (hud_yy - 22)
it said "Errors parsing code while trying to compile gml_Object_obj_camera_Draw_64 Unexpected token in expression around line 80, column 66. Malformed assignment statement"

### Reproducing steps

    open a pizza tower data.win file
    go to gml_Object_obj_camera_Draw_64
    find var ry = (hud_yy - 22)
    make a new line
    paste this code: if (obj_player.movespeed < 2.4)
    draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 2.4 && obj_player.movespeed < 4.8)
    draw_sprite_ext(spr_speedbar, 1, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 4.8 && obj_player.movespeed < 7.2)
    draw_sprite_ext(spr_speedbar, 2, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 7.2 && obj_player.movespeed < 9.6)
    draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 9.6 && obj_player.movespeed < 12)
    draw_sprite_ext(spr_speedbar, 4, 125, 140, 1, 1, 1, c_white, alpha)
    else if (obj_player.movespeed >= 12) && obj_player.movespeed < 16)
    draw_sprite_ext(spr_speedbar, 5, 125, 140, 1, 1, 1, c_white, alpha)

else if (obj_player.movespeed >= 16) draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)

### Setup Details

Bleeding edge
Windows 11
Gamemaker 2

**Comment by Jacky720** [comment]
The error tells you where it is. You have an extra parenthesis on line 80.

**Comment by pisstowel** [comment]
thanks

**Comment by pisstowel** [comment]
where is  it though in line 80?

**Comment by Jacky720** [comment]
`else if (obj_player.movespeed >= 12) && obj_player.movespeed < 16)`
It's the closing parenthesis after >= 12.

**Comment by pisstowel** [comment]
can you add the corrected code because i cant find the parenthesis

**Comment by pisstowel** [comment]
draw_sprite_ext(spr_speedbar, 5, 125, 140, 1, 1, 1, c_white, alpha)
this was the code in line 80

**Comment by Jacky720** [comment]
No. That was the code in line 81. Line 80, which I quoted for you, is the line above it. It has 3 parentheses: 1 opening, 2 closing. See?
