### ISSUE TITLE
UndertaleModLib.Models. Undertale Font in chunk FONT

### ISSUE THREAD

**Issue by OPkokakola** [krzys-h/UndertaleModTool#1453]
### Describe the bug

I create a project in gamemaker, add the desired font there, run the project, run game.unx and this error appears (tried several fonts, update doesn't help)

An error occured while trying to load: First list item starts inside the pointer list?!?!
at 00000320 while reading object
UndertaleModLib.Undertale PointerList`1[[UndertaleModLib.M odels.UndertaleFont+Glyph,
UndertaleModLib,
Version=0.5.1.0, Culture=neutral, PublicKeyToken=null]]
at 00000320 while reading object UndertaleModLib.Models. UndertaleFont
while reading item 1 of 1 in a list of
UndertaleModLib.Models. Undertale Font in chunk FONT

![Снимок экрана 2023-08-04 142834](https://github.com/krzys-h/UndertaleModTool/assets/125770351/971090b8-9c03-483d-a03d-da08ae8b5f89)

### Reproducing steps

1. Create a project in gamemaker
2. Add a font
3. Start the project
4. Go to the path C:\Users\Admin\AppData\Local\GameMakerStudio2\GMS2TEMP
5. Go to the project folder
6. Open game.unx
7. Error

### Setup Details

tried on versions 0.5.1.0, 0.5.0.0, 0.4.0.4
win 11
gamemaker 2

**Comment by Jacky720** [comment]
Reproduced on GM2023.6 but not GM2023.4. Will investigate for any changes in the FONT structure (which may be useful to detect 2023.6).

**Comment by OPkokakola** [comment]
> Reproduced on GM2023.6 but not GM2023.4. Will investigate for any changes in the FONT structure (which may be useful to detect 2023.6).

does not work on 2023.4 either, but on 2023.2.1 it worked, thanks for the help
