### ISSUE TITLE
TTFFonts. csx cannot be used, it pops up an error, on line 22

### ISSUE THREAD

**Issue by bingbingmasdhg** [krzys-h/UndertaleModTool#1464]
### Describe the bug

TTFFonts. csx cannot be used, it pops up an error, on line 22, did I access the code for instantiation? I don't know, has anyone successfully run it? Please tell me the method. Thank you!

### Reproducing steps

Run the TTFFonts.csx script directly

### Setup Details

The latest version,
Windows 10.
![无标题+740+941+01+A+S9D40++111+ASD0+9410+++0++AS9D0](https://github.com/krzys-h/UndertaleModTool/assets/140364654/d42b9f57-8b3b-4f76-8c87-0d9a5240f4ba)

**Comment by XCXDSHS** [comment]
Me too, have you solved it?
