### ISSUE TITLE
Bad decompilation of UT/DR "item get" functions

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#147]
The "item get" scripts in Undertale and Deltarune are decompiled incorrectly.

Undertale `scr_itemget`: If `self.i` is `8`, it doesn't simply break; it does `script_execute` on whatever script `91` is.  Also, if `global.item[self.i] == 0`, the code should be doing `global.item[self.i] = argument0`.

Deltarune has the same problem in its `scr_itemget`, `scr_litemget`, `scr_keyitemget`, `scr_weaponget`, `scr_armorget`, and `scr_phoneadd` functions, except that instead of calling a script if the inventory is full, `self.noroom` is set to `1`.

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/pull/162
