### ISSUE TITLE
make the decopiler do the exact opposite of undertalemodtool's compiler

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [krzys-h/UndertaleModTool#1470]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

to give 100% accuracy

**Comment by Jacky720** [comment]
You can't just "do the opposite" of a compiler. There are several sequences that compile down to very similar sequences in the bytecode and the best way to detect those is *not* a lookup table of every possible bytecode sequence.

Requesting this issue be closed.
