### ISSUE TITLE
I found that Export all strings can only export single-line strings. Is there a way to export and import multi-line strings?

### ISSUE THREAD

**Issue by XCXDSHS** [krzys-h/UndertaleModTool#1477]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

like this，Strings longer than one line are not exported. It is troublesome to make a game translation. I can only paste it in line by line. Do you have any suggestions on this?
![image](https://github.com/krzys-h/UndertaleModTool/assets/83395555/9de16262-46b2-4b65-b0e8-aa0dc0eeb8bf)

**Comment by VladiStep** [comment]
Yes, there's a "ExportAllStringsBetter.csx" script that exports all strings in JSON, it's located in "Community Scripts" folder.

**Comment by XCXDSHS** [comment]
> 是的，有一个“ExportAllStringsBetter.csx”脚本可以导出 JSON 中的所有字符串，它位于“Community Scripts”文件夹中。

Indeed, thank you very much!

**Comment by VladiStep** [comment]
Glad to help.
You should close the issue now.
