### ISSUE TITLE
what are things like @@CopyStatic@@ or @@try_hook@@

### ISSUE THREAD

**Issue by XDOneDude** [krzys-h/UndertaleModTool#1495]
### Describe the bug

im doing a research of the kickstarter antonblast demo code and i found it things like @@CopyStatic@@ or @@try_hook@@, what it would mean exactly

### Reproducing steps

1. download antonblast kickstarter demo 
2. open it on utmt
3. open ob_remapmenu
4. go to its creation event's code
5. see what happens when decompiling

### Setup Details

1. UTMTCE latest commit
2. Windows 10
3. Antonblast

**Comment by Archie-osu** [comment]
\@\@try_hook\@\@ is just the beginning of a try {} block. A subsequent \@\@try_unhook\@\@ call is the end of the try {} block.
