### ISSUE TITLE
Cannot find game executable path

### ISSUE THREAD

**Issue by SuperKirbylover** [krzys-h/UndertaleModTool#1496]
### Describe the bug

when going to file>temp run game on a pizza tower data.win file, i get the following error:

![image](https://github.com/krzys-h/UndertaleModTool/assets/37816816/25e68aec-88a5-4e9c-872d-57cd8979529d)
_"Cannot find game executable path, expected: C:\Program Files\(x86)\Steam\steamapps\common\PizzaTower_GM2.exe"_
i never modified the name of the game executable, and it's titled "PizzaTower.exe". the simple fix WOULD to just be to rename the executable, but upon doing that, i get this:

![image](https://github.com/krzys-h/UndertaleModTool/assets/37816816/e2b317f4-e888-4bd9-9d94-b2a40910230e)
_"An error occcured while updating Pizza Tower (missing executable): C:\Program Files (x86)\Steam\steamapps\common\Pizza Tower\PizzaTower.exe"_

### Reproducing steps

1. Check to see if the Pizza Tower executable is named "PizzaTower.exe"
2. Open a Pizza Tower data.win
3. File > Temp run game
4. Wait for it to compile
5. An error should be thrown

### Setup Details

i believe i'm using the latest UTModTool release. using windows 10. and i was using the latest (at the time of writing) version of [pizza tower.](https://store.steampowered.com/app/2231450/Pizza_Tower/)

**Comment by Jacky720** [comment]
This is Pizza Tower's problem. The data.win is made for Pizza Tower GM2.exe, but the developers changed it out without changing the data.win and set the Steam integration to require it. You could either change the game name in data.win's General Info to match the executable, or remove steam_api.dll and hence disable the Steam integration.

**Comment by SuperKirbylover** [comment]
ahh, gotcha! how would i change the game name in the data.win?

**Comment by Jacky720** [comment]
It's in the General Info section (like where you see Code and Sprites, but the first option), with a couple variations of "game name". That also controls save data iirc but if you copy the save folder you should be safe changing all the values that look like the game title.

**Comment by SuperKirbylover** [comment]
OHH, alright, i was looking elsewhere for some reason
thank you! :>

**Comment by CST1229** [comment]
> This is Pizza Tower's problem. The data.win is made for Pizza Tower GM2.exe, but the developers changed it out without changing the data.win and set the Steam integration to require it. You could either change the game name in data.win's General Info to match the executable, or remove steam_api.dll and hence disable the Steam integration.

This might not actually be Pizza Tower's problem (at most it might be GameMaker's). You can set the executable name in the export options in GameMaker, and that doesn't change anything in the data.win at all (this project's FileName is `test`):

![](https://github.com/user-attachments/assets/13a6d1f7-f90c-4c7f-8978-062a43373c46)

So I'd argue it should at least let you pick the executable path if it can't find it.
