### ISSUE TITLE
Heuristics in decompile result in invalid comments left

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#15]
The heuristics are goofing up a bit and treating numeric values as if they're references.  

Some examples

```
if _temp_local_var_236
{
    1180.sprite_index = 1764 // 1180 = obj_alphys_npc (UndertaleGameObject)
    self.follow = 0
    self.al.image_speed = 0.2 // 0 = obj_backgrounder_parent (UndertaleGameObject)
    self.al.hspeed = -1
    self.con = 67
    self.alarm[4] = 40
}
if (self.con == 68)
{
    self.al.image_speed = 0
    self.al.speed = 0
    self.con = 68.1 // 68 = obj_coremusic (UndertaleGameObject)
    self.alarm[4] = 60
}
if (self.con == 69.1) // 69 = obj_sansmusic (UndertaleGameObject)
    self.con = 69
```

The first comment is correct, but it picked up the normal condition checks as if they were objects. 
`
    self.al.image_speed = 0.3334 // 0 = obj_backgrounder_parent (UndertaleGameObject)`

**Comment by krzys-h** [comment]
The comment is not actually part of the decompiler itself, but the syntax highlighter - which does just that, additionally attaching these comments and the click-on-the-number context menu. As it's a syntax highlighter, it just parses the text form of the decompiler output. I guess I should make sure that the thing after the dot is a valid identifier.
