### ISSUE TITLE
I want to change the xy coordinates of a certain sprite in the game interface, what should I do?

### ISSUE THREAD

**Issue by XCXDSHS** [krzys-h/UndertaleModTool#1500]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

What can be changed in the sprite and texture page item directories under Data does not seem to have anything to do with where the sprite appears in the game.

**Comment by XCXDSHS** [comment]
I made Chinese translations for some games. The differences between English and Chinese were so great that I had to change the position and size of some sprites in the game.

**Comment by XCXDSHS** [comment]
I thought the sprite's coordinates might be in some create or draw code, but I couldn't find anything when searching globally for the sprite's name.

**Comment by Jacky720** [comment]
Offsets like that are generally handled with the "Origin" value on the sprite, which represents the coordinate on the sprite that matches the coordinates game code tries to draw it at. It defaults to the top left corner, but if, for instance, you wanted to center the sprite on its coordinates (maybe for some more precise aiming, so stuff can point at it and it'll be aiming at the center?) you would set the X to half the width and the Y to half the height.

Positive numbers move the sprite up or left, while negative ones shift down or right. You can experiment if this doesn't make a lot of sense.

**Comment by XCXDSHS** [comment]
> 像这样的偏移通常使用精灵上的“原点”值来处理，该值表示精灵上与游戏代码尝试绘制它的坐标相匹配的坐标。它默认位于左上角，但是，例如，如果您想让精灵在其坐标上居中（也许是为了更精确的瞄准，所以东西可以指向它并且它会瞄准中心？）您会将 X 设置为宽度的一半，将 Y 设置为高度的一半。
> 
> 正数使精灵向上或向左移动，而负数则向下或向右移动。如果这没有多大意义，您可以尝试一下。

Thank you
