### ISSUE TITLE
error when editing some variables (Operation not valid due to state of object)

### ISSUE THREAD

**Issue by HEYimHeroic** [krzys-h/UndertaleModTool#151]
i get the following error when trying to edit my Undertale Switch 1.09 dump (tried to edit line 00012 of gml_Object_obj_introimage_Alarm_2 turning the 1 into a 1.2):
![Capture](https://user-images.githubusercontent.com/48461034/54168045-b6f7dd00-443a-11e9-8f56-5b74c90486ab.PNG)

so... yeah. not sure why, but it only allowed me to edit some variables and not others.
for example, i couldn't change the variable i listed above, but i could change a variable like the call text on line 00053. not sure why this happens.

**Comment by Mc-muffin** [comment]
Not sure if this will fix it, but you are changing the value of the instruction without changing its type, ``push.i.e`` pushes an *integer* value while ``push.d.e`` pushes a *double* with that in mind you code change to 00012 should be ``push.d.e 1.2``
