### ISSUE TITLE
Object reference not set to instance of an object.

### ISSUE THREAD

**Issue by gavinops** [krzys-h/UndertaleModTool#1523]
### Describe the bug

When saving a room in my (don't lock me up sugary devs, if anyone of you is in here) Sugary Spire P-Rank Build mod, I was adding a new room, and when I saved with a new layer added, even with nothing in the layer, it still didn't save.
![Screenshot 2023-11-13 210833](https://github.com/krzys-h/UndertaleModTool/assets/72882252/0304bae3-41d5-440c-9894-4eb89218ed2f)

### Reproducing steps

1. Add new room to P-Rank Build with Candied Chasedown installed.
2. Add layer to that room.
3. Save.
4. Error that I thought was already fixed.

### Setup Details

1. UMT Version: Latest Bleeding Edge, also tested with a UMT:CE in the Pizza Tower gamebanana.
2. OS: Windows.
3. GameMaker Game: Sugary Spire: P-Rank Build that was leaked. Not sure if I can even talk about this here, but I'm definitely not linking to it. If uploading the .win is required (probably will be) then I guess I'm either jailed, or quitting attempting to add the room.

**Comment by gavinops** [comment]
More info about this, I tested with UMT 5.1 and the inability to save only happened when I added an asset layer. With only an instance layer, it's fine.

**Comment by VladiStep** [comment]
Hmm, I feel it's some bug that could be easily fixed

**Comment by gavinops** [comment]
I was told by the lead dev of Candied Chasedown that it's unfixable because it's something with how UMT edits code, and can only be fixed with an update.

**Comment by VladiStep** [comment]
> I was told by the lead dev of Candied Chasedown that it's unfixable because it's something with how UMT edits code, and can only be fixed with an update.

The error doesn't seem to be related to code

**Comment by gavinops** [comment]
well then how might I fix it? If you know, of course.

**Comment by Jacky720** [comment]
I assume VladiStep is referring to a fix to UTMT's code being relatively easy, but that's for someone who has the experience with the codebase to know where to look and what to look for.

**Comment by gavinops** [comment]
Yeah, I know for a fact I'm not a someone with experience with the codebase.

**Comment by gavinops** [comment]
Going to (attempt) to merge this into a build and report back if it works.

**Comment by gavinops** [comment]
Thanks for everyone's assistance on this, this is fixed with #1526!
