### ISSUE TITLE
Please add grid system to the rooms.

### ISSUE THREAD

**Issue by Animelici804** [krzys-h/UndertaleModTool#153]
We can fortunately put objects into the rooms or the rooms that we created, but we can't unfortunately set the grid like 20x20 (default undertale and deltarune tileset size). If you do, I would appreciate.

**Comment by krzys-h** [comment]
You can hold down some buttons to enable snap to grid with different grid sizes - I don't remember which ones though D: Try ctrl/shift/alt

**Comment by krzys-h** [comment]
The default is snapping to a 5x5 grid. Hold down ctrl while moving for 20x20. Hold down shift for 10x10. Hold down both to disable the grid (== 1x1 grid)

**Comment by Animelici804** [comment]
Oh ok thanks

**Comment by Animelici804** [comment]
Also, you could add a grid button that it adjusts the grid when it's clicked. Like:

First click = 5x5
Second click = 10x10
Third click = 20x20

Or you could add a slider bar instead of adding button. For example when the slider goes right, the grid size goes up, and when the slider goes left, the grid size goes down. 

Or you could add a number typing bar that it adjusts the grid. That would be a lot easier.
Or you could add a documentary...

Well, I prefer number typing bar and slider bar instead of button. I leave the choice to you.
Well, it's your opinion.

**Comment by Kneesnap** [comment]
This issue appears resolved, and likely can be closed.
