### ISSUE TITLE
hey there I have an idea to bring the end of suzy updates so the fan of bits and pieces can be satisfied

### ISSUE THREAD

**Issue by TeamWarshi** [krzys-h/UndertaleModTool#1545]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

as you may know that in the suzy updates theres a meat factory that is only found in the hotter lands and the only way to get up there is to go through all the way from the hotterlands to the end of the ancient void titan mechanical body until you reached it to the finsl boss that the player aka chara aka frisk and suzy have to fight the final boss and after you defeated it they both go back to the hotlands heights.

just keep it in mind that I will be making the tilesets sprite, overworld sprites, and the battle sprites, so feel free to contact me on discord: warshi99

![an anceint void titan mecahnica body map](https://github.com/krzys-h/UndertaleModTool/assets/116447897/2fc292d6-ba84-4425-9b31-853d4c08361b)

**Comment by colinator27** [comment]
This has nothing to do with development of UndertaleModTool.

**Comment by Yule42** [comment]
This is for the development of UndertaleModTool, not for development of mods made with UndertaleModTool.
