### ISSUE TITLE
System.OutOfMemoryException thrown

### ISSUE THREAD

**Issue by AM7999** [krzys-h/UndertaleModTool#1548]
### Describe the bug

attempting to load a win in Undertale Mod Tool, i receive a System.OutOfMemoryException thrown error from the tool

### Reproducing steps

1. Open Undertale Mod Tool
2. Drag the .win into Undertale Mod Tool
3. wait there for a bit
4. see the crash

### Setup Details

Undertale Mod Tool version 0.5.1.0
Windows 11
the nintendo switch version of Undertale

**Comment by Jacky720** [comment]
Can you check the MD5 or SHA hash of the game.win file? I was unable to reproduce with either version of 0.5.1.0 nor the GUI Release single-file version of the latest bleeding edge, on Switch version 1.11 (MD5 `113ef42e8cb91e5faf780c426679ec3a`, SHA1 `fab4ff275cb66a30886e3ca79979640a20e11bda`).

It's also possible your computer is just out of memory. Does Task Manager show anything out of the ordinary? Does rebooting help?

**Comment by AM7999** [comment]
I was using 1.09, i had modified some bytes to enable debug mode, i have 16 GB of ram and when i would go to look at task manager it was reportadly using ~12gb of ram

**Comment by Jacky720** [comment]
In that case, I would guess that you had the wrong debug offsets and caused an infinite loop. Try going back to a raw 1.09, UTMT has its own debug features.

You can run Switch versions on PC using the [Deltarune Chapter 1 (SURVEY_PROGRAM) runner file](deltarune.com/download/win/en).

**Comment by AM7999** [comment]
it does look like there were issues with what debug offsets i was using, after re-copying the game.win to my computer from my switch UTMT does load the win
