### ISSUE TITLE
Is it possible to add new Functions in data.win?

### ISSUE THREAD

**Issue by Gittourarmy** [krzys-h/UndertaleModTool#155]
(I hope I use correct terms to describe my issue because It seems like data.win just contains only linking information about the functions not all declaration of them.)

For example, if original data.win doens't contain "audio_play_sound" function and "choose" function. (Instead, I contains "action_sound".), could I import these functions? Is there any way to do this on the recent version?

**Comment by krzys-h** [comment]
Yes! If it's a builtin function that is just not imported it should be simple - just right-click on the "Functions" in the object tree, select Add and give it a proper name. If you want to do it inside a script, look for `Data.Functions.EnsureDefined()` in my example ones.

**Comment by Gittourarmy** [comment]
Thanks It works.

**Comment by Mc-muffin** [comment]
Awesome, now that it worked for you, you can close this issue.
