### ISSUE TITLE
UndertaleModTool can't run- v0.5.1.0

### ISSUE THREAD

**Issue by WizardSpriter** [krzys-h/UndertaleModTool#1551]
### Describe the bug

I downloaded v0.5.1.0 of UndertaleModTool, and have the Corrections, Scripts, and Updater folders as well as "LICENSE" "README" and "SCRIPTS", and the UndertaleModTool application all in a folder labeled "UndertaleModTool". When I double-click to try to open up the UndertaleModTool application, I'm met with: "This app can't run on your PC. To find a version for your PC, check with the software publisher." 

### Reproducing steps

I have no idea why this is happening, so I can't tell you how to recreate the behavior. I haven't been able to find anything that says the system requirements for this application (and I'm assuming that my computer is the problem), so I can't easily figure out if that's actually the issue or not.

### Setup Details

SYSTEM INFORMATION:
OS Name: Microsoft Windows 10 Pro
Version: 10.0.19045 Build 19045

**Comment by Jacky720** [comment]
That sounds like the source code. [This](https://github.com/krzys-h/UndertaleModTool/releases/tag/0.5.1.0) is the 0.5.1.0 release, and [this](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge) is the current bleeding edge (of which you would want the last GUI download). If you ever need to find the releases page in general, you want the "Releases" button on the right of the main page, not the "Code" button more towards the center.

**Comment by WizardSpriter** [comment]
I clicked on your link to go to the 0.5.1.0 release, and used that link. I'm pretty sure that that was the link that I originally used. I downloaded the "UndertaleModTool_v0.5.1.0-SingleFile.zip" file, which I loaded up in 7-Zip once it eventually downloaded. In fact, when I downloaded it, it said "Replace a file in this destination?" because I had forgotten to get rid of the original .zip file, which (I think) confirms that I downloaded the correct file the first time. When I opened up the new application I got the same message I did before.

**Comment by Jacky720** [comment]
Oh. Have you tried the non-single file version?

**Comment by Dobby233Liu** [comment]
> ### Setup Details
> SYSTEM INFORMATION: OS Name: Microsoft Windows 10 Pro Version: 10.0.19045 Build 19045

Please provide your computer's processor architecture too, IIRC UMT only provides x86-64 builds right now

**Comment by WizardSpriter** [comment]
After I downloaded the non-single file version, it still didn't work. I don't know how to see my processor architecture.

**Comment by WizardSpriter** [comment]
I think I have a... 32-bit operating system and x64-based processor?

**Comment by Jacky720** [comment]
I suppose that would explain it. UndertaleModTool has been transitioning to x64 and we don't have any 32-bit builds newer than 0.4.0 (32-bit also being known as x86, that is).

**Comment by Dobby233Liu** [comment]
> I think I have a... 32-bit operating system and x64-based processor?

That would do it, I suggest to either reinstall a 64bit OS or build a x86 version of UMT yourself (and risk getting out of memory errors)
