### ISSUE TITLE
First list item starts inside the pointer list?!?! error

### ISSUE THREAD

**Issue by Possiblycoolperson** [krzys-h/UndertaleModTool#1567]
### Describe the bug

when I try to open the data.win file for BOOM! Buster Xmas Demo by tallglass I get an error saying: "First list item starts inside the pointer list?!?!"(I did not add the exlamation and question marks that is what it said)

### Reproducing steps

what I said before

### Setup Details

version 0.5.1.0

**Comment by Jacky720** [comment]
Opens with #1550.
