### ISSUE TITLE
Importing sprites in a fangame makes a sprite's body part go to the top left

### ISSUE THREAD

**Issue by EnderNon** [krzys-h/UndertaleModTool#1568]
### Describe the bug

I found this bug when trying to add coloured sprites to Shanghaivania https://gamejolt.com/games/11871/528229 
After exporting sprites, editing Sans' body sprites, and re-importing using import graphics, Sans' body ends up at the top left. No idea what causes this, i just want to make a sprite edit mod.
![image](https://github.com/krzys-h/UndertaleModTool/assets/106776384/c734f0b0-55dc-4605-aa5c-8d52b456465b)

### Reproducing steps

1) open data.win of shanghaivania with UTModTool
2) export sprites
3) edit sans body sprites (not ink sans, regular undertale sans)
4) use "import graphics" and import edited sprites
5) play the game and survive first turn
6) sans' body ends up in the top left
![image](https://github.com/krzys-h/UndertaleModTool/assets/106776384/f81ee028-b41d-4938-8900-c37228b64eb8)

### Setup Details

UTMT v0.5.10
Windows 11 (with rectify11 if that matters)
https://gamejolt.com/games/11871/528229

**Comment by Jacky720** [comment]
UndertaleModTool doesn't have a way of automatically handling sprite Origin values, though if you selected to export the sprites with padding it would at least handle those. I'm not sure which are in play here, but the best remedy is to either change the values on the sprite entry yourself or just use a different import method for sprites that use Origin.

**Comment by EnderNon** [comment]
> UndertaleModTool doesn't have a way of automatically handling sprite Origin values, though if you selected to export the sprites with padding it would at least handle those. I'm not sure which are in play here, but the best remedy is to either change the values on the sprite entry yourself or just use a different import method for sprites that use Origin.

alright manual import works thanks
