### ISSUE TITLE
creating more than one UndertaleEmbededTexture will scale it down less than 3x

### ISSUE THREAD

**Issue by HEYimHeroic** [krzys-h/UndertaleModTool#157]
the first UndertaleEmbededTexture i created and imported went great, but the second and any others i add after that will no longer import correctly. the image instead imports to less than 3 times its original size. i tried to scale the image by 2 and import it that way, yet the import was too small still. scaling the image by 3 made it slightly too big. as i said earlier, the first UndertaleEmbededTexture i added and imported went fine, and was scaled properly, yet the second one didn't. this isn't a visual thing either, as any UndertalePageItems will not function with the actual coordinates (ie, the image is actually being scaled when importing)

i've been trying to do this with a 1024x1024 image, which is the same size as the first UndertaleEmbededTexture. i also tried to draw a 1 pixel border around, thinking it may be because there's lots  of transparency on the sides, but no luck.

**Comment by HEYimHeroic** [comment]
probably should've added this is using Undertale Switch 1.09 btw :p

**Comment by Kneesnap** [comment]
Cannot reproduce. Could you film a video of this issue?

**Comment by Kneesnap** [comment]
This issue will be closed if no further information is provided.
