### ISSUE TITLE
ExportAllStrings.csx cannot be used

### ISSUE THREAD

**Issue by sirenboke** [krzys-h/UndertaleModTool#1572]
### Describe the bug

ExportAllStrings.csx cannot be used

### Reproducing steps

Run the ExportAllStrings.csx script directly

### Setup Details

Bleeding Edge
Windows 10.
![屏幕截图 2023-12-17 122017](https://github.com/krzys-h/UndertaleModTool/assets/71312853/2dece12a-992d-49c5-88d9-211969cb2f41)
![屏幕截图 2023-12-17 121953](https://github.com/krzys-h/UndertaleModTool/assets/71312853/7faa0969-f186-4b60-8045-2b2614b5ace5)

**Comment by Nonstopgaming75** [comment]
Same

**Comment by VladiStep** [comment]
You can fix it locally by adding `)` at the end of line 14, so the line looks like `if (File.Exists(stringsPath))`
