### ISSUE TITLE
Make different language fonts

### ISSUE THREAD

**Issue by RobinDoingGood** [krzys-h/UndertaleModTool#1578]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

So I decided to make deltarune in Arabic so I need an Arabic font and I don't know how to upload a different language font but someone made Undertale Arabic when I tried to go into the files to get the font And it didn't work Because it isn't coded in another languages so can you do ii please? 🥺

**Comment by Jacky720** [comment]
This is a problem with using UndertaleModTool, not developing it. I'd be happy to help on the Underminers Discord, but please close this issue.

**Comment by RobinDoingGood** [comment]
So What Should I Do And Where Is The Discord?
