### ISSUE TITLE
Expanding name input

### ISSUE THREAD

**Issue by BreakinBenny** [krzys-h/UndertaleModTool#158]
I would like to expand gml_Script_scr_84_name_input_setup to make it useful for other translations, but the local.menu items can only hold up to 10 letters when Japanese is not the set language (and I assume it will also be the case with Chinese, Thai, and Korean, depending on if Deltarune gets localized in those languages as well), and I am forced to add two extra local.menu arrays through the disassembly...

...But I think I need to study this stuff more due to my lacking skill. Here's what it looks like now.

```
if (self.LANGSUBTYPE == 0)
{
    local.xoff = 68
    local.yoff = 70
    local.xstep = 20
    local.ystep = 20
    self.PLAYERNAMEY = 40
    local.menu[0] = "ABCDEFGHIJ"
    local.menu[1] = "KLMNOPQRST"
    local.menu[2] = "UVWXYZ < <"
    self.CURX = 0
    self.CURY = 0
}
```

…And here's what it should look like, at least if you exclude additional letters like the accented ones. Additional local.menu arrays can include the extra characters, like those seen [here](https://docs.yoyogames.com/source/dadiospice/002_reference/game%20assets/fonts/font_tables.html):

```
if (self.LANGSUBTYPE == 0)
{
    local.xoff = 68
    local.yoff = 70
    local.xstep = 20
    local.ystep = 20
    self.PLAYERNAMEY = 40
    local.menu[0] = "ABCDEFGHIJ"
    local.menu[1] = "KLMNOPQRST"
    local.menu[2] = "UVWXYZÅÄÖ"
    local.menu[3] = "       < <"
    self.CURX = 0
    self.CURY = 0
```

**Comment by Animelici804** [comment]
Oh, it seems like you are creating your own fan chapters too.

**Comment by Animelici804** [comment]
Here, replace the code and then edit it:
```
var menu = 0
var xoff = 0
var yoff = 0
var xstep = 0
var ystep = 0
if (LANGSUBTYPE == 0)
{
    xoff = 68
    yoff = 70
    xstep = 20
    ystep = 20
    PLAYERNAMEY = 40
    menu[0] = "ABCDEFGHIJ"
    menu[1] = "KLMNOPQRST"
    menu[2] = "UVWXYZ < <"
	CURX = 0
    CURY = 0
}
YMAX = (array_length_1d(menu) - 1)
j = 0
while(true)
{
    if (j <= YMAX)
    {
        str = menu[j]
        XMAX = (string_length(str) - 1)
        i = 0
        while(true)
        {
            if (i <= XMAX)
            {
                NAME[i,j] = string_char_at(str, (i + 1))
                NAMEX[i,j] = (xoff + (i * xstep))
                NAMEY[i,j] = (yoff + (j * ystep))
                i = (i + 1)
                continue
            }
            break
        }
        j = (j + 1)
        continue
    }
    break
}
if (LANGSUBTYPE == 0)
{
    NAME[6,2] = "(B)BACK"
    NAME[8,2] = "(E)END"
}
HEARTX = ((NAMEX[CURX,CURY] + (string_width(NAME[CURX,CURY]) / 2)) - 10)
HEARTY = NAMEY[CURX,CURY]


```

**Comment by BreakinBenny** [comment]
It's clear that Deltarune was definitely not made for potentially extra localizations, but I'd probably imagine Toby's guys taking care of that for the full version... If they end up having any such plans.

**Comment by Animelici804** [comment]
Okay.

**Comment by BreakinBenny** [comment]
@Animelici804 I've managed to do just that, as in add another menu array for the Å Ä Ö characters while moving the BACK and END to the fourth one.

`if (self.LANGSUBTYPE == 0)
{
    local.xoff = 68
    local.yoff = 70
    local.xstep = 20
    local.ystep = 20
    self.PLAYERNAMEY = 40
    local.menu[0] = "ABCDEFGHIJ"
    local.menu[1] = "KLMNOPQRST"
    local.menu[2] = "UVWXYZÅÄÖ "
    local.menu[3] = "       < <"
    self.CURX = 0
    self.CURY = 0
`
The next issue is giving BACK and END their own line, so it doesn't cut off the extra letters.
![0_shot](https://user-images.githubusercontent.com/4566768/56091379-80d0d180-5eae-11e9-8967-abeb29d8a277.png)

**Comment by Kneesnap** [comment]
What is the purpose of this issue? Forgive me, but I don't see the action we're supposed to take.
