### ISSUE TITLE
Script menu options open to the left, making it impossible to click them

### ISSUE THREAD

**Issue by leopardheart982** [krzys-h/UndertaleModTool#1589]
### Describe the bug

When I attempt to use the Resource Unpacker options (or any other option, really), the context menu opens to the left rather than the right where the arrows indicate, and there's just enough of a gap that if you move the cursor off of it, the options go away before you can actually click any of them. A brief delay before the context menu goes away would be welcome, regardless of whether or not this is patched, because the context menu disappearing immediately isn't very user friendly. Also maybe the options should be clicked to open the context menu rather than hovered over.

EDIT: This can be worked around by pushing the window to the left enough that the context menu is forced to appear on the right hand side.

### Reproducing steps

1. Click Scripts
2. Hover over any of the options
3. Try and fail to press any of the further options

### Setup Details

Latest multiple-file debug branch, as of time of writing.

**Comment by VladiStep** [comment]
Weird:
1) It opens on the left only if there is not enough space to the right:
![image](https://github.com/krzys-h/UndertaleModTool/assets/45438625/98457bca-d2ee-4743-8664-56e48244bc8e)

2) Yes, if you move the cursor to the gap, it closes.
But, I can do it only if I move the cursor really slow, otherwise it doesn't close.

**Comment by VladiStep** [comment]
Also, all of that is a default behavior of standard `MenuItem` element of WPF, so it's probably not so easy to change that.

**Comment by leopardheart982** [comment]
![image](https://github.com/krzys-h/UndertaleModTool/assets/54118364/087bf5f8-764b-46bc-a77b-b2e5b064f697)

For me, it opens to the left by default. The gap is also wide enough that it's almost impossible to keep it open if I try to move my mouse over to it. Definitely not with any level of precision required to actually get into what I need.

**Comment by VladiStep** [comment]
Okay, I found how can you fix that for UTMT (and for other apps too if that's the case):
> Press the Windows key + R to bring up the Run dialog box. In the Open line, copy/paste the following line of text.
> 
> `shell:::{80F3F1D5-FECA-45F3-BC32-752C152E456E}`
> 
> Press OK.
> 
> This will start the Tablet PC Settings configuration dialog (Even if you do not have a Tablet PC).
> 
> Select the Other Tab.
> 
> In the Handedness section, place a check mark in the Left Handed option.
> 
> Click OK.

https://stackoverflow.com/a/25109673/12136394
