### ISSUE TITLE
Bad decompilation of UT gml_Object_obj_giftgen_Step_0

### ISSUE THREAD

**Issue by Myriachan** [krzys-h/UndertaleModTool#159]
The generated code is a mess, but there's one part that's actually just wrong:

    _temp_local_var_1 = (_temp_local_var_1 - 1);
    if (_temp_local_var_1 - 1)
    {
        continue;
    }
    break;

The "if" statement should just be "if (_temp_local_var_1)", because it's comparing the new value of the unnamed stack variable to 0.

**Comment by krzys-h** [comment]
Duplicate of #109?
