### ISSUE TITLE
Attempting to select a large amount of text crashes UndertaleModTool

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#160]
Selecting a large amount of text crashes the program. For example, try to select all of gml_Script_SCR_TEXT at once and it will crash. This occurs both with the decompiled and assembly tabs.

**Comment by Kneesnap** [comment]
Text selecting seems to be O(N ^ 2) where N is the text selection size. I haven't look that far into it though, I  believe @Myriachan might be able to give some more insight.

**Comment by Kneesnap** [comment]
A workaround is inadvertently added in my fork, when I added by @colinator27's compiler. If you enter into code edit mode, you select without issue.

**Comment by Kneesnap** [comment]
Fixed in https://github.com/Kneesnap/UndertaleModTool/commit/b195347b4d77d057cd47bec8143d9aacc5a02882
