### ISSUE TITLE
error: reading beyond end of stream

### ISSUE THREAD

**Issue by supernovasquid** [krzys-h/UndertaleModTool#1607]
### Describe the bug

so, undertalemodtool is not opening data.win. it gives me this error 
![fsdfsf](https://github.com/krzys-h/UndertaleModTool/assets/155487390/df1615ed-1e7a-4e49-9fbe-c9b7bdf8d4d7)
and when i actually try to open the game itself, this happens.
![Untitled](https://github.com/krzys-h/UndertaleModTool/assets/155487390/76e5824b-afe1-450a-8fd7-5c40c3eb4c51)
why is this happening please help me please i really need help ive been working on this undertale mod for like a 4 years now, also, the data.win has 0 bytes now?

### Reproducing steps

1. open data.win in undertalemodtool
2. get error "reading beyond end of stream"
3. try to open game
4. game crashes on the splash screen, also the window resolution is different and the window title is "Made on GameMaker: Studio"

### Setup Details

1. v0.3.6
2. windows 10
3. undertale

**Comment by Miepee** [comment]
>  i really need help ive been working on this undertale mod for like a 4 years now, also, the data.win has 0 bytes now?

I hope you made a backup. Something has corrupted there (too vague to know what and why), and the data.win is essentially gone now.

**Comment by Jacky720** [comment]
If the data.win is 0 bytes, that means it failed to save. Do you see a MyMod.temp file, and is it bigger than 0 bytes?

**Comment by supernovasquid** [comment]
> Refere

like, a copy of the file? there's a data.win.bak file but i have no idea what that is

**Comment by Jacky720** [comment]
Rename that file to data.win and start making backup copies of the data file on a regular basis.

**Comment by supernovasquid** [comment]
ok, thanks but uhmm... problem. this .bak file was probably created alot earlier, and like all the stuff i changed (i dunno about all of it, havent really checked) like items, text, sounds are not changed anymore.

**Comment by supernovasquid** [comment]
yeah this was created back in july...

**Comment by supernovasquid** [comment]
but, i still have the corrupted data.win... is there anyway to fix that? or not

**Comment by supernovasquid** [comment]
i dont want to redo everything

**Comment by supernovasquid** [comment]
wait it has 0 bytes how would i get that back

**Comment by Miepee** [comment]
You can't. You have to redo the progress you lost.
