### ISSUE TITLE
The scr_storageget and scr_phoneget scripts are decompiled incorrectly.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#161]
These scripts as decompiled do not work. Similar issue to https://github.com/krzys-h/UndertaleModTool/issues/147#issue-411701894 .

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/pull/162

**Comment by Grossley** [comment]
> 
> 
> Fixed in #162

I'm closing this issue considering that the new bug fixes and improvements will be added soon.
