### ISSUE TITLE
i can't mod any game now :(

### ISSUE THREAD

**Issue by BrandonZG** [krzys-h/UndertaleModTool#1619]
### Describe the bug

even if i did a fresh folder

### Reproducing steps

ready to do a rework on my mod and then this pops up

### Setup Details

![Screenshot 2024-01-07 204617](https://github.com/krzys-h/UndertaleModTool/assets/117795515/c671a020-ff62-4c91-9723-94adb67ba569)

**Comment by VladiStep** [comment]
I can't understand, is it the same game version, and you can't open it after updating UTMT?
Or is it only the game that was updated?

**Comment by BrandonZG** [comment]
> I can't understand, is it the same game version, and you can't open it after updating UTMT? Or is it only the game that was updated?

i was trying to rework my mod on Sonic.exe The Disaster 2D Remake and never saw any update on UTMT

**Comment by VladiStep** [comment]
I mean, could you open this version of the game before?

**Comment by BrandonZG** [comment]
> I mean, could you open this version of the game before?

it actually worked the first time i used it i even have the mod here https://gamejolt.com/games/test/866396

**Comment by VladiStep** [comment]
I suggest you to try [the "Bleeding edge" version of UTMT ](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge)

**Comment by BrandonZG** [comment]
> I suggest you to try [the "Bleeding edge" version of UTMT ](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge), you probably need [GUI-windows-latest-Debug-isBundled-true-isSingleFile-false.zip](https://github.com/krzys-h/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Debug-isBundled-true-isSingleFile-false.zip)

do i delete the old ones

**Comment by VladiStep** [comment]
Then you should close this issue
