### ISSUE TITLE
UTY doesnt work

### ISSUE THREAD

**Issue by jmxamongusmodder** [krzys-h/UndertaleModTool#1620]
### Describe the bug

UTY isnt working on the tool it just doesnt wanna load

### Reproducing steps

1, use this
2, open UTY's data win thing
3, crash

### Setup Details

i used 5.1.0 or whatever AND YET IT SHOULD SUPPORT IT BUT IT DOESNT >:(

**Comment by Jacky720** [comment]
Update to the Bleeding Edge release, this is already fixed and a duplicate of several closed issues.
