### ISSUE TITLE
[Question] Could we get that Decompiled > CLI Code bois

### ISSUE THREAD

**Issue by KadePcGames** [krzys-h/UndertaleModTool#163]
Bascily, type anything in the decompiled tab, and it works like typing it in the other tab. Just vice versa.

More or less that would be gucci, but again i suck at decompiling so i got no idea if this would work.

**Comment by colinator27** [comment]
It's in the works, at least kind of. I wrote a GML compiler, so theoretically it's *almost* possible with [this pull request](https://github.com/krzys-h/UndertaleModTool/pull/162). It just needs UI integration.

**Comment by KadePcGames** [comment]
So an eta?

**Comment by Kneesnap** [comment]
PR has been merged, presumably this will be implemented soon.

**Comment by Kneesnap** [comment]
Integrated in https://github.com/Kneesnap/UndertaleModTool/commit/c583548ec8e8bf37aa961ebb7555a0e3aa450269

**Comment by KadePcGames** [comment]
Thank you <3
