### ISSUE TITLE
heya I have some issue with HgPatcher when I export or patch any gms, and included gms2.0.6

### ISSUE THREAD

**Issue by WarshiDevs** [krzys-h/UndertaleModTool#1639]
### Describe the bug

I was wanting to export gms2.0.6 into an actual project so it can get more work done smoothly without clicking on data.win of opening too many times, which it's a hassle for me and my team so if you can fix this issue or just show me an alternative way so I can get the HgExport and HgPatch being fully turn into an project, and yes I'm using undertale bnp mod but I will be changing fews things and sprites is included as well, without further of due here is an image
![image_2024-01-12_221415621](https://github.com/krzys-h/UndertaleModTool/assets/116447897/d984cb3f-5162-46a0-952e-4d2f6a9d0d46)
![image_2024-01-12_221450800](https://github.com/krzys-h/UndertaleModTool/assets/116447897/0c3e2095-deea-4f47-bdee-cd93257ad31b)

### Reproducing steps

1. I install/download HG Patcher from the zip folder
2. I open undermodtool with data.win
3. I click on script and click on run other script
4. I click on HgExport or HgPatch
5. and now it show me an compile error

### Setup Details

here is what exactly I wanted to do with ut bnp:

1. I install/download HG Patcher from the zip folder
2. I open undermodtool with data.win
3. I click on script and click on run other script
4. I click on HgExport or HgPatch
5. and then it turn into .yy or .ypp or just .gmx

**Comment by BenjaminUrquhart** [comment]
Exporting to a project file is unsupported and is a gray area legally.
