### ISSUE TITLE
Is there a way to Export all Embedded audio?

### ISSUE THREAD

**Issue by XCXDSHS** [krzys-h/UndertaleModTool#1660]
### Which component should be improved?

UI/UX

### Describe your feature suggestion in more detail

I want to export all the music of a certain audiogroup.DAT audio package separately. I have been manually exporting one by one. This is too time-consuming. There seems to be no export script for Embedded audio.

**Comment by suphamster** [comment]
Did u tried ExportAllSounds.csx script from "Resource Unpackers" folder? U need to answer yes to this question "Group sounds by audio group?" There would be several folders "audiogroup_default" is for audio inside data.win file and other folder(s) that corresponds each of audiogroup*.DAT file but with its own folder naming (that coded inside data.win).

**Comment by XCXDSHS** [comment]
> 您是否尝试过“Resource Unpackers”文件夹中的 ExportAllSounds.csx 脚本？您需要对“按音频组对声音进行分组？”这个问题回答是。会有几个文件夹：“audiogroup_default”用于 data.win 文件内的音频，以及与每个 audiogroup*.DAT 文件相对应但具有其自己的文件夹命名（在 data.win 内编码）的其他文件夹。
Thank you, I have never tried exporting all the audio in the game data before. Maybe it will be automatically grouped and arranged as you said.
