### ISSUE TITLE
Help (Text Boxes)

### ISSUE THREAD

**Issue by Illia24** [krzys-h/UndertaleModTool#1666]
### Describe the bug

Well every time changing text boxes or adding them and then code decompiling text disappears for example:
global.msg[0] = scr_gettext("string_example") // * Example / and after decompiling this happens:
global.msg[0] = scr_gettext("string_example")
How do i fix this i really need help please

### Reproducing steps

1. Doing text in code
2. Decompiling
3. Text disappears 

### Setup Details

UndertaleToolMod v0.5.1.0
Windows 11

**Comment by Jacky720** [comment]
This is not a bug. The text after `//` is a code comment added for convenience; the real code is only the gettext, which typically invokes the `textdata_en` script. You can fix this by either adding your text to the textdata script, or by ignoring the localization command and simply defining `global.msg[0] = "* Example / and after decompiling this happens:"`

**Comment by Illia24** [comment]
Ok thanks
