### ISSUE TITLE
When I attempt to open up the data.win file for the game The Bunny Graveyard, I get the following error:

### ISSUE THREAD

**Issue by Muzzma** [krzys-h/UndertaleModTool#1670]
### Describe the bug

An error occured while trying to load:
Unable to cast object of type
UndertaleModLib.UndertalePointerList'1[UndertaleModLib.M
odels.UndertaleExtensionOptionj to type 'UndertaleModLib.Models.UndertaleExtensionFile'. at 009E7C0C while reading object UndertaleModLib.UndertalePointerList'1[[UndertaleModLib.M
odels.UndertaleExtensionFile, UndertaleModLib,
Version=0.5.1.0, Culture=neutral, PublicKeyToken=null] at 009E7C0C while reading object
UndertaleModLib.Models.UndertaleExtension while reading item 1 of 4 in a list of
UndertaleModLib.Models.UndertaleExtension in chunk EXTN

### Reproducing steps

1. Open The Bunny Graveyard data.win file in the tool.
2. Error

### Setup Details

1. 0.5.1.0
2. Windows 11
3. [The Bunny Graveyard](https://store.steampowered.com/app/1892420/The_Bunny_Graveyard/)

**Comment by Jacky720** [comment]
Please retry on the bleeding edge build of UndertaleModTool. The general-use build is 
GUI-windows-latest-Release-isBundled-true-isSingleFile-true.

**Comment by Muzzma** [comment]
@Jacky720 It works, but when I save the file (unchanged), the game does not start
