### ISSUE TITLE
Chunk Padding Error (Padding is missing)

### ISSUE THREAD

**Issue by Kneesnap** [krzys-h/UndertaleModTool#169]
@Grossley has an issue opening a Mario Maker game by loypoll in UTMT v0.2.0

![image](https://user-images.githubusercontent.com/6562913/57737090-3d10e980-765f-11e9-9756-d618a1a07563.png)

It may be a GMS v2.2.2 compatibility issue.

**Comment by Kneesnap** [comment]
It may also impact Blazing Beaks, according to YellowAfterLife.

**Comment by Kneesnap** [comment]
Does not affect Blazing Beaks, however, I can confirm this issue myself. It appears like new versions can sometimes go without any type of chunk padding. Also, it appears it's skipping the first chunk upon reading, so it's reading OPTN data as GEN8, LANG data as OPTN, etc.

**Comment by colinator27** [comment]
Don't believe this is GMS 2.2.2, but this is weird. Instead of 16-byte chunk alignment, it's 4-byte chunk alignment like old GM:S 1 builds, but it's GMS 2...

**Comment by krzys-h** [comment]
There is also this file from Discord from a few days ago which seems to be the same issue https://cdn.discordapp.com/attachments/568950566122946580/577166878716330004/data.win

**Comment by Grossley** [comment]
> 
> 
> There is also this file from Discord from a few days ago which seems to be the same issue https://cdn.discordapp.com/attachments/568950566122946580/577166878716330004/data.win

That's an older version of the same game by Loypoll. It's still being worked on so several revisions may come out over the course of time. For some reason Altar.NET seemed to work really well with these data.win files when I was trying to get game contents from it.

**Comment by krzys-h** [comment]
That's because Altar.NET does not intend to be able to reconstruct the file byte-for-byte so it can get away with just ignoring padding errors and unknown data. The parser in UndertaleModTool is more strict in that regard.

**Comment by colinator27** [comment]
Not a 2.2.2 support issue, it's actually runtime 2.1.5.246 apparently.

**Comment by Grossley** [comment]
Specific runtime information: https://media.discordapp.net/attachments/577123876572495875/579223042274885643/unknown.png

**Comment by Kneesnap** [comment]
Do we know what can cause a data.win like this to be built? Is it just using the compiler with runtime 2.1.5.246? So the versions before and after it don't do this?

**Comment by colinator27** [comment]
Nope, that doesn't seem to be it. Just built a project with that version and it has the correct padding.

**Comment by Kneesnap** [comment]
Hrmm. What exactly could the difference be?

**Comment by Kneesnap** [comment]
It appears this happens with GMAssetCompiler v2.1.4.200, according to @colinator27. A band-aid fix was applied in https://github.com/krzys-h/UndertaleModTool/commit/7dfe6cc4c37363cfa3c8afd603783d22d87e3d96
