### ISSUE TITLE
Adding a string or variable in UndertaleModTool consistently causes crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#170]
Adding a string or variable in UndertaleModTool consistently causes the program to crash and immediately close. It doesn't matter if this is a new game or not. It just doesn't work.

**Comment by colinator27** [comment]
Can't reproduce on my computer, likely a compatibility issue or something like that.

**Comment by colinator27** [comment]
Added a fix locally, will make PR soon/eventually with other crash fixes

**Comment by Kneesnap** [comment]
Fixed in https://github.com/Kneesnap/UndertaleModTool/commit/c73134618e80705399ee938333fc076cff0e6a24
