### ISSUE TITLE
Some message defining code in gml_Object_obj_endflowey_regret_Step_0 decompilation from UNDERTALE was badly parsed

### ISSUE THREAD

**Issue by Dobby233Liu** [krzys-h/UndertaleModTool#173]
(The title is so long, how to short it?)
Can be reproduced in 0.2.0
The image is everything
![wtf](https://user-images.githubusercontent.com/28653235/57920744-5e2b4180-78ce-11e9-8362-fdb20c562bfe.PNG)
Seem like broke there:
![wtf2](https://user-images.githubusercontent.com/28653235/57920843-9a5ea200-78ce-11e9-9a09-64b7d0a76688.PNG)

**Comment by Kneesnap** [comment]
What do you believe the proper decompilation should be?

**Comment by Dobby233Liu** [comment]
> What do you believe the proper decompilation should be?

I don't thought about that...

**Comment by Dobby233Liu** [comment]
Oh... It's a feature of `scr_gettext`... Sorry for my disturbing!
