### ISSUE TITLE
how do I edit the strings?

### ISSUE THREAD

**Issue by SPONGEROBERT123** [krzys-h/UndertaleModTool#174]
I am trying to edit the dialogue, but when I double-click on the file in the directory, it doesn't open and show the dialogue.

**Comment by Mc-muffin** [comment]
You'll need to give more detail than that, what did you do? What error showed up? Etc

**Comment by SPONGEROBERT123** [comment]
I don't have any errors. I just want to know how to edit the dialogue, and I don't know where it's located for  undertale. I thought it was in the strings, and I realize that im probably wrong.

**Comment by Mc-muffin** [comment]
Well, all the text is in ``SCR_TEXT`` but you are better off using the scripts over at #26 it will export every string to a .txt file that, after editing, you can import back to the game.

**Comment by Kneesnap** [comment]
If you are using an early Undertale version, it will be in SCR_TEXT. If you are using a later version which has the Japanese language added or Deltarune, it will be in textdata_en. If you're in some other game, it will differ for that game.

**Comment by SPONGEROBERT123** [comment]
I found the dialogue. Also, is there a way to export and import the strings? I can't find anything for doing either, so I wanted to ask.

**Comment by Kneesnap** [comment]
There were scripts linked in an earlier post which let you do that.

**Comment by Kneesnap** [comment]
Issue can be closed.
