### ISSUE TITLE
Creating a new game and immediately running it causes UndertaleModTool to crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#178]
How to perform the crash.
1. Create a new game.
2. Select "Run Game"
It should result in this exception in Visual Studio:
![image](https://user-images.githubusercontent.com/42724744/58202606-dd34c700-7c8c-11e9-931a-19332b1baee5.png)

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/eace128209053e50dda90c788f5d423899c8ab81
