### ISSUE TITLE
Selecting all in "gml_Object_obj_kingcutscene_Step_0" while in edit mode (decompiled code) causes UndertaleModTool to become unresponsive

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#179]
Selecting all while in edit mode (decompiled code) causes UndertaleModTool to crash.

**Comment by Kneesnap** [comment]
This only affects UTMT when run in Visual Studio. I tried for hours to even pinpoint what causes this issue and wae unable to. It's some WPF thing, I eventually gave up since it works perfectly if you run it outside the IDE

**Comment by Grossley** [comment]
What? Really?

**Comment by Grossley** [comment]
Wait, is this the CTRL+A & CTRL+C issue from yesterday or is that something else?

**Comment by Kneesnap** [comment]
No this is that issue

**Comment by Grossley** [comment]
> 
> 
> No this is that issue

I don't think it is, it's just freezing and locking up, not crashing and closing the program.

**Comment by Kneesnap** [comment]
Either way, it's triggered by the same thing.

**Comment by Grossley** [comment]
The CTRL+A & CTRL+C bug triggered an exception within about 5-10 seconds of me doing it. It's been a good minute or two and it's completely unresponsive. Sounds more like the bug that happens when large amounts of text is selected, with a possible similar fix. It only occurs when I select all using CTRL+A. The other bug requires both CTRL+A and CTRL+C.

**Comment by Kneesnap** [comment]
Cannot reproduce anymore. Can you seem to make this happen on the latest build?

**Comment by Grossley** [comment]
There's something going on but the current title as I wrote it is inaccurate. I will create a new issue if I can determine what exactly is causing it. :)
