### ISSUE TITLE
$$$$temp$$$$ has returned.

### ISSUE THREAD

**Issue by Kneesnap** [krzys-h/UndertaleModTool#184]
Game: [Path of the Rabbit](https://ldjam.com/events/ludum-dare/38/$25743)
Script: f_legal_current_tile
Related: https://github.com/krzys-h/UndertaleModTool/issues/164

![image](https://user-images.githubusercontent.com/6562913/58375180-3194ac80-7f02-11e9-90c7-08147be42246.png)

**Comment by Kneesnap** [comment]
Game: TSR (Private)
Script: test_collision

Decompiled Code:
```gml
var object, testX, testY;
object = argument0
testX = argument1
testY = argument2
with (object)
{
    $$$$temp$$$$ = (! place_meeting(testX, testY, obj_solid))
    return $$$$temp$$$$
}
```

Real Code:
```gml
/// @function test_collision(object, x, y)
/// @description Test whether an object can move to a certain position
/// @param {object} object The object to test.
/// @param {real} x The x position to test.
/// @param {real} y The y position to test.
var object = argument0;
var testX = argument1;
var testY = argument2;

with (object)
	return !place_meeting(testX, testY, obj_solid);
```

**Comment by colinator27** [comment]
Should be fixed in https://github.com/krzys-h/UndertaleModTool/commit/b43a73590e439356d56e31936af16fc181278115.
The issue was that the statements ended up being in separate blocks, so it couldn't detect it.
