### ISSUE TITLE
var _temp_local_var -> twice

### ISSUE THREAD

**Issue by Kneesnap** [krzys-h/UndertaleModTool#186]
If you decompile a script that uses _temp_local_var_X as an actual variable in the script (Could happen if you compiled a decompiled script), it can add that var twice to the local var definitions.

Example:
```gml
var length, _temp_local_var_1, _temp_local_var_1;
_temp_local_var_1 = (a.b ? 3 : 4)
is_real(_temp_local_var_1)
```

**Comment by colinator27** [comment]
No real good solution to this, other than making _temp_local_var_X totally obsolete. Like, we should fix all of the problems with it.

**Comment by Kneesnap** [comment]
We can have a simple. bad fix for now, which just doesn't add the var to the var statement, but yeah, I agree. It should be made completely obsolete.

**Comment by Kneesnap** [comment]
A band-aid fix to this was added sometime recently.
