### ISSUE TITLE
Figure out how to decompile blocks which are impossible to reach

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#192]
In GML, it's possible for the compiler to produce blocks which are completely impossible to reach. Take this code for example:
```gml
a = 1;
return;
a = 2;
```
Clearly a = 2 would never run, but it gets compiled anyway. In order for a proper re-compilation after decompiling, we need to take these into account. These can also happen with break, continue, etc., and you can even have several of these control flow statements in conjunction. Even in switch statements.

Not too sure how to approach this- should we find all unused blocks at the end, and somehow merge them back in? All control flow there would be basically broken though, so we need to restore the original context somehow... It's really confusing.

**Comment by colinator27** [comment]
Also, keep in mind that these unused blocks can come one after another, if they have several control flow statements, such as in here:
```gml
switch abc
{
    case 123:
        return 456;
        break
        break
}
```

**Comment by Kneesnap** [comment]
GMDisasm may have fixes for this, unsure.

**Comment by Kneesnap** [comment]
I'm not sure if we should do this. Sure, if we don't, it would not be completely bytecode compatible, but this would be rather difficult to do for something which virtually has no practical use.

**Comment by colinator27** [comment]
I think it's a good idea also for datamining - if the developer throws a few impossible code blocks in there, it might never be seen unless someone analyzes the bytecode itself. I mean, we could decompile the blocks separately, but I think it'd be better to do it completely.

I got `return` mostly working a bit before (my code is gone but it basically just checks for any inaccessible blocks from the current block which has its entry point being the current block) but I'm not completely sure how the implementation of `break` and `continue` works. I imagine it would be similar.

**Comment by Kneesnap** [comment]
Kk. If you want to handle this, feel free. I don't think I'll be working on this though.

**Comment by colinator27** [comment]
The new decompiler will have this feature, beginning with the base implementation in https://github.com/krzys-h/UndertaleModTool/commit/a80b6708978e687de3d0283b2d4798e5b11d0c4d
