### ISSUE TITLE
Make compiler thread-safe

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#193]
Right now the compiler uses static global variables, and these should be properly replaced with contexts so that it can be used from multiple threads.

Theoretically this can be implemented with a kind of `CompileContext`, and would work like this from scripts from then on:
```csharp
CompileContext ctx = new CompileContext(Data);
string asm = Compiler.CompileGMLText("a = 1;", ctx);
ctx.Reset();
// add objects/resources etc.
ctx.UpdateAssets(); // new function to update the asset IDs
string moreAsm = Compiler.CompileGMLText("b = 2;", ctx);
```

The major issue is propagating the CompileContext down pretty much every function, but that shouldn't be *too* difficult.

**Comment by Kneesnap** [comment]
So, I've done most of this, with commit https://github.com/krzys-h/UndertaleModTool/commit/7fac39db967bc5f3a13088840c133d5fe26b60a8
The only thing I did not do was the method "UpdateAssets", since I wasn't quite sure what you wanted to go there.

**Comment by Kneesnap** [comment]
Done.
