### ISSUE TITLE
bytecode 14 ???????

### ISSUE THREAD

**Issue by Salty-Stump** [krzys-h/UndertaleModTool#195]
Only byte code versions 15, 16, and 17 are supported for now, you are trying to load 14, a lot of code is disabled and will likely break something. Saving/exporting is disabled.

What is bytecode 14?????

@krzys-h

**Comment by Kneesnap** [comment]
GameMaker Studio (The engine Undertale was built in), has different versions of its code, and that number basically just says which version it is.

Undertale v1.00 uses v14.
Undertale v1.01 uses v15
Undertale v1.08 uses v16

The good news is that support for v14 has been added on the developer versions, although there is no official release with support for it yet. If you want to check out our discord server, we can help you get a version with v14 support.

**Comment by Salty-Stump** [comment]
ok

**Comment by Salty-Stump** [comment]
whats the discord?

**Comment by Kneesnap** [comment]
https://discord.gg/hqpQvUX
