### ISSUE TITLE
What is this? two temps?

### ISSUE THREAD

**Issue by tarkan809** [krzys-h/UndertaleModTool#198]
Hey there... I know it's odd to ask but I found this code when I try to decompile a different game but I happen to see this:

> if (self.skiddir == 1)
                    _temp_local_var_23 = self.kleft
                else
                    _temp_local_var_23 = 0
                if _temp_local_var_23
                    _temp_local_var_24 = 1
                else
                {
                    if (self.skiddir == -1)
                        _temp_local_var_25 = self.kright
                    else
                        _temp_local_var_25 = 0
                    if _temp_local_var_25
                        _temp_local_var_24 = 1
                    else
                        _temp_local_var_24 = (abs(self.hsp) < 0.5)
                }
                if _temp_local_var_24
                    self.skid = 0

Is there anyone to solve this?

**Comment by colinator27** [comment]
This output is old - I would highly recommend using at least version 0.2.0, but would advise using the `dev` branch if you can build it (the dev branch has other decompilation fixes, a whole compiler meaning that you can edit decompiled code, bytecode 14 support, and other features/fixes).

What this probably represents is an if statement with && and || (etc.) within it, which the older version doesn't decompile completely.

**Comment by tarkan809** [comment]
> This output is old - I would highly recommend using at least version 0.2.0, but would advise using the `dev` branch if you can build it (the dev branch has other decompilation fixes, a whole compiler meaning that you can edit decompiled code, bytecode 14 support, and other features/fixes).
> 
> What this probably represents is an if statement with && and || (etc.) within it, which the older version doesn't decompile completely.

OH! thank you.
