### ISSUE TITLE
UMT Decompiling forever w/ invalid string

### ISSUE THREAD

**Issue by BreakinBenny** [krzys-h/UndertaleModTool#199]
How to replicate:

1. Have lang_en.json open in Notepad++ or whatever.
2. Open UMT and add global.msg[#] = scr_84_get_lang_string("INVALID OR NONEXISTENT STRING adress") somewhere
3. Leave the code edit window. The "Decompiling, please wait... This can take a while on complex scripts [so] Please wait." window should appear.
4. Watch as the decompiling process seems to go on forever.

NOTE: This process cannot be cancelled as UMT needs to be terminated, costing you all your time and work.

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/160475f389194797d54f08aac150d386c744c1e4
