### ISSUE TITLE
Glyph import/export

### ISSUE THREAD

**Issue by CyberSlimp** [krzys-h/UndertaleModTool#20]
Hello. 
Thank You for good tool!
Can You, please, add glyph table import/export? 
In any format (csv, xls, txt, json...)
![undertalemodtool_2018-09-21_00-20-33](https://user-images.githubusercontent.com/3046130/45847692-84471480-bd34-11e8-9245-89120a71f2f6.png)

**Comment by krzys-h** [comment]
That would certainly be useful. Other objects could use that functionality as well for easy diffing and a command line tool.

**Comment by krzys-h** [comment]
```csharp
UndertaleFont font = Selected as UndertaleFont;
using(StreamWriter writer = new StreamWriter("glyphs_"+font.Name.Content+".csv"))
{
	foreach(var g in font.Glyphs)
	{
		writer.WriteLine(g.Character+";"+g.SourceX+";"+g.SourceY+";"+g.SourceWidth+";"+g.SourceHeight+";"+g.Shift+";"+g.Offset);
	}
}
```

```csharp
UndertaleFont font = Selected as UndertaleFont;
using(StreamReader reader = new StreamReader("glyphs_"+font.Name.Content+".csv"))
{
	font.Glyphs.Clear();
	string line;
	while((line = reader.ReadLine()) != null)
	{
		string[] s = line.Split(';');
		font.Glyphs.Add(new UndertaleFont.Glyph() {
			Character = UInt16.Parse(s[0]),
			SourceX = UInt16.Parse(s[1]),
			SourceY = UInt16.Parse(s[2]),
			SourceWidth = UInt16.Parse(s[3]),
			SourceHeight = UInt16.Parse(s[4]),
			Shift = UInt16.Parse(s[5]),
			Offset = UInt32.Parse(s[6]),
		});
	}
}
```

These scripts should help until I implement proper import/export in the tool. Note that these work on the selected object, so make sure to open the font object before running them.

**Comment by krzys-h** [comment]
You will pretty much have to do that manually for now.

1. Right click "Embedded textures" on the left, click "Add" then open the new texture and click "Import", load the new file
2. Open the font. Double click on `(UndertaleTexturePageItem)` - it will open the related TexturePageItem object
3. Drag and drop the added texture from the left onto the texture field in TexturePageItem
4. Edit the TexturePageItem parameters to match the new texture. For a full image you will want 0, 0, texture_width, texture_height in both source and target, and texture_width, texture_height for bounding.

That should be it. Normally, all sprites are packed into big sheets for performance reasons, but it shouldn't matter for just one texture.

Obviously, you can instead just export the whole sheet and replace the fragment in any graphics editing program.

**Comment by CyberSlimp** [comment]
Thank You again! All work.

**Comment by BMatSantos** [comment]
Hey I just wanted to tell you that the import glyph script isn't working on on the latest version 0.1.23, every time I try to use it, it gives me this error
![image](https://user-images.githubusercontent.com/44817023/50318847-fa315800-04aa-11e9-85ef-3571b118e466.png)
It says _It's not possible to implicitly convert type "ushort" to "short". Is there an explicit conversion (Is there a missing conversion)?_

I tried it a couple of times, and this always appears whenever I run the script, even when there's no corresponding csv.

**Comment by krzys-h** [comment]
Oh, we fixed the types in the fonts recently. Shift and Offset may need to be updated to Int16 iirc. I will post an updated script later.

**Comment by zellfy** [comment]
@Mc-muffin @krzys-h 
I just come here to say thank you!!!
With your help I have finished the translation that many chinese players can taste undertale on nintendo switch.
I have signed all your name as a guider.


![1](https://user-images.githubusercontent.com/45615697/52992703-7f55d080-344c-11e9-9567-6c989a22c961.png)

**Comment by Grossley** [comment]
Implemented, closing
