### ISSUE TITLE
UndertaleModTool-dev: clicking on "0x800000" in "gml_Object_obj_jokerbg_triangle_real_Create_0" in Deltarune PC causes UndertaleModTool to crash.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#203]
This occurred in UndertaleModTool-dev (version 96ae564). Clicking on "0x800000" in "gml_Object_obj_jokerbg_triangle_real_Create_0" in Deltarune PC causes UndertaleModTool to crash. It crashes with both right and left clicks

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/fad68d4604dfb6f1e293017db76d3bd46eed71bf
