### ISSUE TITLE
[Script/Other] Changing function -> scripts

### ISSUE THREAD

**Issue by KadePcGames** [krzys-h/UndertaleModTool#204]
So i tested this only on the function `keyboard_check`
so it basicily starts off by checking if any functions in the functions tab are keyboard_check then it makes a script with this code:
```csharp
script.Code.Append( Assembler.Assemble( UndertaleModLib.Compiler.Compiler.CompileGMLText($@"
            var {var} = argument0;
            switch(keyboard_check({var}))
            " + "{" + $@"
            case true:
                {var} = false;
                return true;
                break;
            case false:
                {var} = true;
                return false;
                break;
            " + 
            @"}", Data, script.Code).ResultAssembly, Data));
```
({var} is just a pre-defined variable name)
Then it checks all objects for a regex and illiterates over all of the functions that were changed, if any object contains it then it replaces it. Simple enough.

But you get this error when trying to run the game:
![error image](https://cdn.discordapp.com/attachments/574410846025809920/593626636948340750/unknown.png)

I talked to Colinator27 and he said it might be a compiler bug. And he'd debug but he went away for a bit so im asking if maybe the other dev's wanna try it. Hit me up in dm's if you need the script (its kinda private for now)
(`Ms. Kade#2000`)

# Edit:
## forgot to add im on the latest dev build.
# Edit Number 2:
## Yes i tried converting the code and building it in gml and it worked. So the code works its just UTMT then.

**Comment by Kneesnap** [comment]
Can you show us screenshots of what it looks like in UTMT, what you did to cause this to happen, and why this is not intended?

**Comment by KadePcGames** [comment]
Object:
![image](https://user-images.githubusercontent.com/26305836/60311863-e8bf8180-990d-11e9-9d22-7832d738774e.png)
Script:
![image](https://user-images.githubusercontent.com/26305836/60311887-fa088e00-990d-11e9-845d-313b09af916c.png)

**Comment by KadePcGames** [comment]
So whats happening is that KOu2438 is a script that returns the keyboard_check of the argument0
then it returns that all works in GML but it doesent when its built with the compiler of UTMT.

**Comment by Kneesnap** [comment]
Please just explain everything. From the beginning. What are you trying to do? How are you trying to do it? Why do you think it's not working. Give screenshots for everything to explain. We can't understand what's going on if you don't explain it well.

**Comment by KadePcGames** [comment]
Okay okay, basicily im trying to replace functions to scripts, thats all. Replace function NAMES to SCRIPTS in objects. Thats all really. Theres no other ss' or anything...

**Comment by Kneesnap** [comment]
And what exactly is not working?

**Comment by KadePcGames** [comment]
![image](https://user-images.githubusercontent.com/26305836/60312072-b82c1780-990e-11e9-86c6-91a987eafc53.png)
when the game is run thru utmt i get that, when its run (built thru gamemaker studio 1.4) it works fine with the renamed functions to a script.

**Comment by Kneesnap** [comment]
I don't think this is an issue with UTMT, I think you're misunderstanding how to use UTMT

**Comment by Kneesnap** [comment]
Can you show me the code that is doing this?

**Comment by Kneesnap** [comment]
Oops did not mean to close this.

**Comment by KadePcGames** [comment]
![image](https://user-images.githubusercontent.com/26305836/60312148-04775780-990f-11e9-88e9-f61b54bf07f6.png)
^ thats what colinator said

**Comment by KadePcGames** [comment]
yeah i'll send u it on discord

**Comment by Kneesnap** [comment]
Ok.

**Comment by KadePcGames** [comment]
First issue kneesnap hasn't closed? WOWIE. Ended up finding a compiler bug, so yayaya. Its all gucci now.
