### ISSUE TITLE
gml_Object_obj_time_Draw_77 does not compile correctly resulting in a game crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#205]
Undertale 1.09
Dev version 96ae564

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/56b837b5a03a3007c2dc916b382e169a8e038c30

The bytecode still slightly differs (206 + 207 are an extra block for if fail condition, which don't exist in the actual bytecode. This optimization may have been made in GMS2 / maybe bytecode 17.)
