### ISSUE TITLE
Importing sprites that are the same dimensions (or smaller) as the original directly

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#207]
Currently changing any sprite requires editing the whole texture sheet in an image editing program and then reimporting it. This is much more tedious than it could be. If direct sprite importing were added for sprites of the same dimensions (or smaller) this would not require the sprites to be repacked on the sheet and would save a lot of time. Consider it! :P

**Comment by Kneesnap** [comment]
A temporary solution has been added in https://github.com/krzys-h/UndertaleModTool/commit/b1bb451e62461d162b14530636acffbe7cc66f2f

Eventually, we will have a texture sheet manager which will automatically manage texture pages automatically, and allow for adding new entries.
