### ISSUE TITLE
we fricked up in here with these decomp issues

### ISSUE THREAD

**Issue by KadeDev** [krzys-h/UndertaleModTool#211]
Game Name: Unforgiven
Data.win: https://cdn.discordapp.com/attachments/583466397573709834/604800050291539986/data.win
Stack Trace:
![image](https://user-images.githubusercontent.com/26305836/62000428-8f24b100-b08b-11e9-965f-02914278d3e3.png)

Yes @Grossley , its the newest version >:(

**Comment by Grossley** [comment]
@KadePcGames More information is needed. Which commit version of UndertaleModTool are you using and what code is producing the error? Are you using 96d3e6a38c ?

**Comment by KadePcGames** [comment]
YES GROSSLEY I COMPILED THE NEWEST VERSION, I SAID THAT.

**Comment by KadePcGames** [comment]
![image](https://user-images.githubusercontent.com/26305836/62000449-04908180-b08c-11e9-9742-c6de2d1042bf.png)

**Comment by Grossley** [comment]
What code is producing the error? @KadePcGames

**Comment by KadePcGames** [comment]
idk man, like actually i have no clue. Its just somewhere in it. i was using kneesnap's exporter and he said it was a decomp issue. It never told me where.

**Comment by Grossley** [comment]
I am still having no issues with opening the disassembly or decompiled code of "gml_Object_obj_player_Step_0". Can you please confirm you are using 96d3e6a38c by getting the version in the announcements channel, directly opening the UndertaleModTool.exe of version 96d3e6a38c , opening the data.win provided within the application, and try to reproduce the error? Older versions of UndertaleModTool may be loaded automatically by directly clicking on the data.win which may explain why your error still persists.

**Comment by Grossley** [comment]
Nevermind @KadePcGames I was able to reproduce the issue. I will test out which code is causing your error very soon.

**Comment by Grossley** [comment]
@Kneesnap The code in question is "gml_Script_XGms_ve_getBestWayToSend" and this error is caused due to the values of "00043: push.d -1E+38" and "00050: push.d 1E+38" in the assembly.

**Comment by Kneesnap** [comment]
This sounds like it's very similar to a decompiler bug I fixed earlier. I will attempt to apply the same fix here, by just making sure it can't represent numbers in exponential form when disassembling.

**Comment by colinator27** [comment]
Does this issue still exist?

**Comment by Grossley** [comment]
I just tested it. Yes, this issue still exists.

**Comment by KadeDev** [comment]
s m h. ITS BEEN 9 MONTHS

**Comment by KadeDev** [comment]
Closed due to the new one being more "polite" - Grossley
