### ISSUE TITLE
“Saving” window does not cancel saving when closed

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#215]
Either the “saving” window should cancel the saving upon closing or it should not be allowed to close the window.

**Comment by KadePcGames** [comment]
No, it should be the "manual" hate corruptor amirite?

(ds/gameboy vibes when you take out the cart when its loaded >:|)

**Comment by colinator27** [comment]
This also applies to the loading window. Both windows should not be allowed to close.

**Comment by Grossley** [comment]
Has this been resolved?

**Comment by Grossley** [comment]
This has been resolved for the saving window by preventing closure, but not for the loading window. This issue is resolved, and a new one will be made for the loading window.
