### ISSUE TITLE
Using the troll dogcheck option causes the program to completely lock up, causing a potential loss of work if it hasn’t been saved.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#216]
I think it’s a funny joke. However, I also think that the potential of losing work is a severe oversight that should be addressed. For instance, if there were an option to go back, or if the troll only lasted for a limited time, then the risk of losing work would be eliminated. However, as it is, there is a genuine risk of people losing a lot of work if they don’t know better.

**Comment by Kneesnap** [comment]
Frankly, I think we should remove this.

**Comment by BreakinBenny** [comment]
...All I can say is, the dog was evil all along.

**Comment by LagzTerGD** [comment]
Why was that feature even implemented?

**Comment by BreakinBenny** [comment]
@LagzTerGD A joke attempt, I guess... except not enough foresight was put into it.

**Comment by Kneesnap** [comment]
The code suggests the possibility of eventually implementing the feature

**Comment by Kneesnap** [comment]
However I think The feature is better suited for a script, if it's something we were to add

**Comment by Grossley** [comment]
I looked into it one time and I believe it said something along the lines of “Never implement this, you don’t have legal permission from Toby Fox to do so.” So I don’t see where that would be a possibility unless permission was obtained from Toby.

**Comment by Kneesnap** [comment]
I think it was the readme actually

**Comment by BreakinBenny** [comment]
It _is_ in the readme.

[And I think this, regardless of potential backlash opinions, makes for a good joke regarding "legal reasons..."](https://youtu.be/YL4bjCyk_54)

**Comment by Kneesnap** [comment]
I have decided to remove this feature. It causes confusion with the uninformed, can result in loss of work, and ultimately, doesn't really serve a purpose. If this feature were to be implemented, it would be as a script anyways. If anyone objects to this decision, please speak up now.

**Comment by Grossley** [comment]
I do not object. In fact, I support this decision. Please do.

**Comment by friedplugstudios** [comment]
Yes, and please have a link somewhere. I need to reference some source code from DELTARUNE for my own game.

**Comment by friedplugstudios** [comment]
@Grossley So, do you know anyway to obtain a list of all the items (objects) used in battle? That way, I won't get confused when refrencing, and I can only know what I need to know. (btw thanks for almost instant feedback. sorry i didnt respond, i was napping.)

**Comment by colinator27** [comment]
This seems to have been removed a while ago, not sure why this issue wasn't closed.
