### ISSUE TITLE
The BorderEnabler script does not work on NXTALE data.win files

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#217]
It seems that the menu functionality works for NXTALE but the actual borders themselves do not appear. This script should be updated to work with every version of Undertale.

**Comment by Kneesnap** [comment]
I don't know that NXTALE is supposed to be supported yb BorderEnabler.

**Comment by TML233** [comment]
What are you thinking? The scripts are only for official Undertale/Deltarune games.

**Comment by Grossley** [comment]
It is a official release of the game Undertale for Nintendo Switch.

**Comment by colinator27** [comment]
Doesn't NXTALE already have borders though?

**Comment by Grossley** [comment]
NXTALE contains the border files but does not display them. This is why they must be "enabled".

**Comment by Grossley** [comment]
Resolved
