### ISSUE TITLE
Error reading chunk FONT

### ISSUE THREAD

**Issue by manueltarouca** [krzys-h/UndertaleModTool#218]
This error shows up when opening data.win file.
![image](https://user-images.githubusercontent.com/36767065/62430156-50889980-b710-11e9-9f43-a4b1628dbda3.png)

**Comment by Grossley** [comment]
More information is needed. Which game is this? What UndertaleModTool version?

**Comment by ManuelTarouca16095** [comment]
> More information is needed. Which game is this?
It's from a game I made in 2013, lost the source code. 

> What UndertaleModTool version are you using?
UndertaleModTool-v0.2.0

**Comment by Grossley** [comment]
> > What UndertaleModTool version are you using?
> 
> UndertaleModTool-v0.2.0

Are you using the release or dev branch of UndertaleModTool? 

If you provide the data.win file you're using it would also provide more information but that is up to you.

**Comment by ManuelTarouca16095** [comment]
> Are you using the release or dev branch of UndertaleModTool?

Release branch. I guess the dev branch need to be compiled manually?

**Comment by Grossley** [comment]
Yes, it needs to be compiled manually. Fortunately, I have a build for you that you can use. Download these files and see if it loads, OK? 

https://cdn.discordapp.com/attachments/589826508957286400/604807408094543902/UndertaleModTool-96d3e6a38c.rar

https://cdn.discordapp.com/attachments/589826508957286400/604807447215079424/SampleScripts-96d3e6a38c.rar


I also recommend you join our Discord server here for faster troubleshooting and so I can follow up easier on your issue. However, that is optional. Here's the link: https://discord.gg/hqpQvUX . :)

**Comment by Kneesnap** [comment]
You said this game was made in 2013? That might be a slight problem, if it uses an outdated bytecode. We support Bytecode 14->17, but there are some games that exist that use Bytecode 13. It would be possible to add support for it though.

**Comment by Grossley** [comment]
Wouldn't we need the file to know that @Kneesnap ? Remember, the release of 0.2.0 doesn't have support for bytecode 14 as is, so this could be a bytecode 14 version error.

**Comment by ManuelTarouca16095** [comment]
Thanks, but still shows the same error.
Anyways, I'll hit the discord server tomorrow when I'm free.
Should I close this issue?

**Comment by Grossley** [comment]
No, do not close the issue @ManuelTarouca16095 .

**Comment by Kneesnap** [comment]
If you are willing to share the files, we can look into the issue. If not, then there's nothing we can do, but this may serve as reference for a future issue.

**Comment by colinator27** [comment]
My guess is that since it's from 2013, it's using an older bytecode version and it fails to load.

**Comment by colinator27** [comment]
Right now we only officially support bytecode 14+.

**Comment by Kneesnap** [comment]
I believe the older bytecode thing is not the issue he's seeing. It might be an additional issue, but it's failing to load the FONT chunk, nothing to do with code.

**Comment by colinator27** [comment]
Bytecode affects the entire file structure - and it only shows the bytecode version warning once it finishes deserialization of the file.

**Comment by colinator27** [comment]
You know, that makes me think. Maybe we should just call it the format version instead of the bytecode version, because that's what it actually is.

**Comment by mesmerized21** [comment]
[data.win.zip](https://github.com/krzys-h/UndertaleModTool/files/3465413/data.win.zip)
Here is the file

**Comment by Kneesnap** [comment]
Alright, perfect. We'll be able to look into why this fails.

**Comment by mesmerized21** [comment]
Thanks for the trouble.

**Comment by jonastraducoes** [comment]
> This error shows up when opening data.win file.

In the game "Valdis Story Abyssal City" same problem

**Comment by Grossley** [comment]
The game that was sent previously was bytecode 11, which is not supported. This game could also be an unsupported bytecode version Jona.

**Comment by jonastraducoes** [comment]
> The game that was sent previously was bytecode 11, which is not supported. This game could also be an unsupported bytecode version Jona.

my game is bought at steam.
I want to do the game translation. Can you help me with this?
I need to edit the game font.

**Comment by Grossley** [comment]
I can attempt to help you with this. However, it will take several hours and I cannot guarantee that this game will be ultimately compatible with UndertaleModTool.

**Comment by colinator27** [comment]
Yeah - there's no way it's compatible with UndertaleModTool without a ton of changes to the core deserialization. We only support bytecode 14+ right now, but that might change eventually.

**Comment by jonastraducoes** [comment]
> I can attempt to help you with this. However, it will take several hours and I cannot guarantee that this game will be ultimately compatible with UndertaleModTool.

If you can help me, I'd be happy!

Because in fact I just needed to add characters to the game font to translate!
can you help me with this?
the characters are "ç"

Because in fact I just needed to add characters to the game font to translate!
can you help me with this?
the characters are "áéíóú çêãõ ÁÉíóú ÇÃÕÊ"

**Comment by colinator27** [comment]
I think this issue can be closed now? The data file in question was unsupported, I believe.
