### ISSUE TITLE
Is there anyway to have an actual GameMaker export option?

### ISSUE THREAD

**Issue by jdam7674** [krzys-h/UndertaleModTool#219]
Hi, would it be possible to export a decompiled "data.win" file over to a GameMaker project file so I can use it for debugging? Thanks.

**Comment by Grossley** [comment]
Due to legal reasons this will probably never be implemented. However, you may “Run under Debugger”, which will allow you to debug without decompilation.

**Comment by Kneesnap** [comment]
This is 100% doable if you're willing to make a script to export it yourself. Scripts like this do exist, they're just not public, for legal reasons.

**Comment by jdam7674** [comment]
Yeah... was wondering if it was possible to at least maybe export script files but have the option only when a script file is selected, would be a nice option but yeah, there could be legal problems, thanks guys for the help 👍

**Comment by jdam7674** [comment]
@Kneesnap Mind sharing this script file, please? I tried making one but I was unable to properly export it... Would like to at least properly modify one of my friends old game maker file or restore it properly if that is possible. Thanks.

**Comment by Grossley** [comment]
@jdam7674 This is not public for legal reasons. If you want to modify a game then use UndertaleModTool.

**Comment by jdam7674** [comment]
> @jdam7674 This is not public for legal reasons. If you want to modify a game then use UndertaleModTool.
That does not make any sense... sharing a script file specifically for this tool is not "illegal". If this was the case then the entirety of this UndertaleModTool would be removed.

**Comment by Grossley** [comment]
@jdam7674 This will not be provided. Do not ask again.

**Comment by jdam7674** [comment]
> @jdam7674 This will not be provided. Do not ask again.

And who are you to say this?

**Comment by jdam7674** [comment]
All I am doing is politely asking whether or not it is possible that I may use the script to recover my friends game maker project file that has been slightly corrupted on his hard drive back in 2015. I have tried making a script to export but it would not export everything... either my code is absolutely messed up since I'm a beginner or something else...

**Comment by Grossley** [comment]
Send the game and I’ll look into it.

**Comment by jdam7674** [comment]
No. My friend told me specifically not to lend this over. He is still creating his game and I cannot and will not lend this over to a public website. I don't even know who you even are to tell me what I'm supposed to do.

**Comment by Grossley** [comment]
Then there is not much I can do for you. You may join the Underminers Discord server for more in depth help with whatever you need. However, export scripts will not simply be handed to you because, as you said, this is a public website and me and Kneesnap are not interested in a public release at this time.

**Comment by Kneesnap** [comment]
YoYoGames has a history of going after tools which allow exporting games into projects. They don't seem to have an issue with UndertaleModTool so far, and we'd like to keep it that way. Nobody benefits from having UTMT taken down. This is why we are not releasing the script. If you lost a project, there is a chance we can help you recover it, although there are no guarantees. If you and your friend are willing to send the game over to one of us in a private channel, we might be able to help. If not, then recovering the project is something you'll have to figure out on your own.
