### ISSUE TITLE
Support for older bytecode versions

### ISSUE THREAD

**Issue by Caylie-C** [krzys-h/UndertaleModTool#22]
> An error occured while trying to load:
> Only bytecode version 16 is supported for now, you are trying to 
> load 14
> at 000005D0 while reading object
> UndertaleModLib.Models.UndertaleGeneralInfo in chunk GEN8

**Comment by krzys-h** [comment]
Eventually, probably. But it's hard to say when.
I'm guessing that is not Undertale? If it is, then it's some really old version. Latest ones use bytecode 16.

**Comment by Caylie-C** [comment]
It is. 1.00, to be exact.

**Comment by Caylie-C** [comment]
Is 1.001 going to be supported? In fact, what is the lowest supported ver. of Undertale for this?

**Comment by krzys-h** [comment]
Just checked all versions of Undertale I could get my hands on through Steam to see what bytecode versions they are for future reference:

Undertale version | Bytecode | MD5 checksum of data.win | Other notes
--- | --- | --- | ---
v1.00 | 14 | d0822e279464db858682ca99ec4cbbff | 
v1.001 | 15 | cd48b89b6ac6b2d3977f2f82726e5f12 | 
(anybody know what goes here? PS4/Vita releases I guess?) | | | |
v1.05 | 16 | 856219e69dd39e76deca0586a7f44307 | this is already supported by UndertaleModTool
v1.05a | 16 | 0bf582aa180983a9ffa721aa2be2f273 | 
v1.06 | 16 | 582795ad2037d06cdc8db0c72d9360d5 | 
v1.08 | 16 | 5903fc5cb042a728d4ad8ee9e949c6eb | latest version available on PC right now
v1.09 | 16, GMS2 | 427520a97db28c87da4220abb3a334c1 | the initial Nintendo Switch release
v1.10 | 16, GMS2 | | apparently this was just a version bump (https://www.reddit.com/r/Underminers/comments/9h4d6g/so_it_seems_there_are_two_version_for_nintendo/)
v1.11 | 16, GMS2 | | this was the recent patch to fix the save files getting removed bug on Switch (https://www.reddit.com/r/Underminers/comments/9j2dbj/could_someone_download_the_111_to_see_if_there/)

So literally anything except 1.00 and 1.001 should be supported

**Comment by krzys-h** [comment]
Bytecode version 15 support added in 42b1f229ed73db389ac1afe9a59c412e681aebc0 and released in version 0.1.10 of UndertaleModTool - really not much changed between 15 and 16, so that was easy. Supporting bytecode 14 is going to be way harder as some stuff about the push/pop instructions changed AFAIK.

This means that Undertale 1.001 is supported now, but it's probably going to be a while until 1.00 is supported as well.

I also put that Undertale bytecode versions table on the wiki so that it's easier to update it in the future: https://github.com/krzys-h/UndertaleModTool/wiki/Undertale-versions-and-bytecode

**Comment by Mc-muffin** [comment]
> Just checked all versions of Undertale I could get my hands on through Steam to see what bytecode versions they are for future reference:
> 
> Undertale version	Bytecode	MD5 checksum of data.win	Other notes
> v1.00	14	d0822e279464db858682ca99ec4cbbff	
> v1.001	15	cd48b89b6ac6b2d3977f2f82726e5f12	
> (anybody know what goes here? PS4/Vita releases I guess?)			
> v1.05	16	856219e69dd39e76deca0586a7f44307	this is already supported by UndertaleModTool
> v1.05a	16	0bf582aa180983a9ffa721aa2be2f273	
> v1.06	16	582795ad2037d06cdc8db0c72d9360d5	
> v1.08	16	5903fc5cb042a728d4ad8ee9e949c6eb	latest version available on PC right now
> v1.09	16, GMS2	427520a97db28c87da4220abb3a334c1	the initial Nintendo Switch release
> v1.10	16, GMS2		apparently this was just a version bump (https://www.reddit.com/r/Underminers/comments/9h4d6g/so_it_seems_there_are_two_version_for_nintendo/)
> v1.11	16, GMS2		this was the recent patch to fix the save files getting removed bug on Switch (https://www.reddit.com/r/Underminers/comments/9j2dbj/could_someone_download_the_111_to_see_if_there/)
> So literally anything except 1.00 and 1.001 should be supported

From 1.001 to 1.05 are the PS4/Vita versions, you are correct.

**Comment by krzys-h** [comment]
Thanks! I added all of your data to the table. I kinda expected the checksums to be different across platforms.

I will also try to get all Linux and OSX versions to get their checksums as well. Interestingly, according to steamdb.info the OSX version was updated more frequently than the Windows one, which itself was updated more frequently than Linux (but that is probably because the first Linux release is around a year after the Windows one)

**Comment by krzys-h** [comment]
Aaaand the table is updated with OSX and Linux now: https://github.com/krzys-h/UndertaleModTool/wiki/Undertale-versions-and-bytecode

**Comment by Mc-muffin** [comment]
I managed to extract the remaining PS Vita files, I edited my previous comment, check it out.

**Comment by krzys-h** [comment]
@Mc-muffin added to the wiki, thanks

**Comment by colinator27** [comment]
Hey, guess what! I just added bytecode 14 support that might be buggy or might not be buggy!!!
https://github.com/krzys-h/UndertaleModTool/commit/57574612df04e3562c9c031ed7d3f0f2a63834c2

**Comment by colinator27** [comment]
Documented on the wiki, here: https://github.com/krzys-h/UndertaleModTool/wiki/Bytecode-version-differences

**Comment by colinator27** [comment]
I'd say it's pretty stable now. Fixed a few issues, not sure how many more exist. However, things like InstanceType and VarID need to be removed from variables in the GUI.

**Comment by colinator27** [comment]
So is it in the scope of this project to research bytecode versions < 14, or is it time to close this?

**Comment by nitrocafe** [comment]
Can someone make a executable of the tool with the bytecode 14 support modification made by colinator27? I tried myself but it gives me a lot of error and not build a executable.

[https://imgur.com/a/ztVjLMn](https://imgur.com/a/ztVjLMn)

**Comment by Mc-muffin** [comment]
Use [this link](https://cdn.discordapp.com/attachments/589826508957286400/590614250469195776/UndertaleModTool-afa3ae78bb.rar)

**Comment by Kneesnap** [comment]
I think this would be a fair issue to close.

**Comment by nitrocafe** [comment]
Thank you Mc-muffin!! You saved my life! Working perfectly here. Now I can go into deep secrets of some old games and learn from them.

**Comment by Grossley** [comment]
Considering that bytecode 14 support is now here I think that this issue should be closed, unless the bytecode 14 support is incorrect/lacking in a way that I'm not aware of.

**Comment by Grossley** [comment]
I'm honestly not sure how thoroughly bytecode 14 has been tested.

**Comment by Kneesnap** [comment]
I have not seen any issues with bytecode 14 thus-far, and it has been implemented for while. I will close this issue. If any issues pop up regarding bytecode 14, a new issue should be opened.
