### ISSUE TITLE
When will there be YYC support?

### ISSUE THREAD

**Issue by jdam7674** [krzys-h/UndertaleModTool#221]
Hi, is it possible to get the code from the executable file and decompile it? Was wondering because there are some things that I'd like to mod for the game that I'm testing this tool with. Thanks.

**Comment by Grossley** [comment]
Please refer to https://yal.cc/on-gamemaker-studio-game-decompilation/ regarding YYC decompilation. In short, YYC is a lot more complicated to work with and so it’s a lot more unlikely.

**Comment by Kneesnap** [comment]
Essentially, the YYC support UTMT will have will probably go as far as allowing modding of non-code assets in YYC games, but not further. YYC is transpiled from GML into C++, then compiled and linked directly into the game's executable (exe). In other words, it gets turned directly into assembly. This is much much harder to deal with, and frankly, the only way to do this is by reversing it by hand. In the normal format, the code is actually kept in a compiled GML bytecode, which is very possible to decompile automatically.
