### ISSUE TITLE
Decompiler not displaying do loops properly causes infinite loop freeze (example: Deltarune PC "gml_Object_DEVICE_CHOICE_Step_0")

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#223]
UndertaleModTool version 96d3e6a38c

What it should be:
```
do {
}
until (variable < 0)
```

What it comes out as:
```
while (true)
{
    if (variable < 0)
    {
    }
    else
        continue
}
```

"The compiler compiles it fine but the decompiler doesn't display it properly. When the compiler tries to take that code once you've edited it it treats it as a while loop which gets stuck when ran in game, causing a freeze."

**Comment by Kneesnap** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/6f8c538d3ef9682f4d0c38d3e0a168fddc1b6d23
