### ISSUE TITLE
Can't compile script

### ISSUE THREAD

**Issue by johnwtt** [krzys-h/UndertaleModTool#225]

**Comment by johnwtt** [comment]
Error CS0009: Metadata file 'c:\users\administrator\desktop\undertalemodtool-v0.2.0\undertalemodtool.exe ' could not be opened -- PE image doesn't contain managed metadata.

**Comment by Grossley** [comment]
More information is required to do anything to resolve your issue.

**Comment by Kneesnap** [comment]
Without more information this issue will be closed.

**Comment by Kneesnap** [comment]
This issue has been closed due to a lack of information.
