### ISSUE TITLE
Using "ExportAllCode.csx" on "Megaman Maker" causes UndertaleModTool to crash due to a "System.StackOverflowException" exception

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#226]
Every attempt results in a crash that completely closes UndertaleModTool and a StackOverflow exception partway through export. 

"An unhandled exception of type 'System.StackOverflowException' occurred in UndertaleModLib.dll"

"An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll"

**Comment by Grossley** [comment]
You can get Megaman Maker for free here: https://megamanmaker.com/

**Comment by Grossley** [comment]
This occurs on every version of UndertaleModTool I have tested it on including the latest dev version 6f8c538d3e .

**Comment by Kneesnap** [comment]
This is a duplicate issue of the "Vs Susie" bug. It will most likely be fixed with the decompiler rewrite.
