### ISSUE TITLE
pushvar is probably pushbuiltin

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#23]
Used pushvar.v instead of push.v on a standard member variable and got
```
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_time:

DoPushBuiltin :: variable index is out of range 103910 max is 212
at gml_Object_obj_time_Draw_77
############################################################################################
```

**Comment by colinator27** [comment]
I'm fairly certain this is true now, but at this point we've just accepted that it is that. Is it worth a rename at this point?

**Comment by Kneesnap** [comment]
@colinator27 Please do this and close the issue. Make sure to update all scripts and test cases which use the assembler to use the new name.

**Comment by colinator27** [comment]
Done, renamed to `pushbltn` in https://github.com/krzys-h/UndertaleModTool/commit/17a318c1578f73262385bad3a1fbb10125ce0d5a.
