### ISSUE TITLE
A way to extract all the sprites?

### ISSUE THREAD

**Issue by ychnh** [krzys-h/UndertaleModTool#231]
Is there a way to do this without clicking each sprite individually?

**Comment by Grossley** [comment]
This has been resolved in the “dev” branch of UndertaleModTool. Come to our Discord server to get a build or build it yourself. :)

**Comment by ychnh** [comment]
Ah thanks :). 
I was going to code it to extract resources in order to make a map editor for a game.
Let me verify that it works and I'll close the issue.

**Comment by ychnh** [comment]
Had issues with error messages when building dev-branch.
Downloaded compiled dev-branch code and extracted textures successfully.
Download at the discord https://discord.gg/hqpQvUX
