### ISSUE TITLE
There's a problem when I was loading a win

### ISSUE THREAD

**Issue by tarkan809** [krzys-h/UndertaleModTool#232]
Hey there... I'm not sure if I'm the only one who is seeing an error like this but I found an error that says this:

> An error occured while trying to load: Root chunk is ���� not FORM

Here's an Image of the problem:
<img src="http://share.cherrytree.at/showfile-32747/problem.png" />

Does anyone know what is this?
if so can anyone fix this problem?

**Comment by Animelici804** [comment]
It seems like the game is using an anti-decompiler, like DF.

**Comment by tarkan809** [comment]
Is there a way to **UN**anti-decompile the win? Perhaps?

**Comment by tarkan809** [comment]
Because Although I do want to see what was inside the game.

**Comment by Animelici804** [comment]
Colinator27 did an Unanti-decompiler for data win's. He decided not to share for respecting the owner of DF.

**Comment by tarkan809** [comment]
Well then if that's the case then where's Calinator27?
and where can I find him?

**Comment by tarkan809** [comment]
Perhaps We should ash him here in this topic

@colinator27 Can we talk to you?

**Comment by colinator27** [comment]
Sorry, but I want to respect the anti-decompiler wishes for the game. If you do anything, you'll have to figure it out on your own. This is also out-of-scope for UndertaleModTool, so if you want to talk further, then the Underminers Discord server is a good place for that.

**Comment by tarkan809** [comment]
> Sorry, but I want to respect the anti-decompiler wishes for the game. If you do anything, you'll have to figure it out on your own. This is also out-of-scope for UndertaleModTool, so if you want to talk further, then the Underminers Discord server is a good place for that.

Well why not GameJolt PMS? Because right now I can't reach to discord right now but We could talk it out in the GameJolt PMs. Question: Do you have a Gamejolt account perhaps?

**Comment by colinator27** [comment]
Okay, well, we can talk in GameJolt PMs if you'd like, however I don't check it quite as frequently. My account is the same as here (@colinator27).

**Comment by tarkan809** [comment]
@colinator27 Alrighty then. Thanks... I also sent a friend request too.

**Comment by colinator27** [comment]
So I'll just close this issue now as it no longer pertains to the tool.

**Comment by tarkan809** [comment]
Ok then I'll close it then.
