### ISSUE TITLE
Importing an image only works correctly at 96 dpi (Dev-6f8c538d3e)

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#233]
Reducing the DPI causes the image to become disproportionately large. Increasing the DPI causes the image to become much smaller. 

Examples:

96 DPI (normal):
![image](https://user-images.githubusercontent.com/42724744/66602536-311e4a80-eb5f-11e9-8f8e-ac45b6759b8f.png)

6 DPI (extremely large): 
![image](https://user-images.githubusercontent.com/42724744/66602274-9b82bb00-eb5e-11e9-929f-990319db2c1c.png)

160 DPI (small): 
![image](https://user-images.githubusercontent.com/42724744/66602473-0d5b0480-eb5f-11e9-951d-ed631fe696b4.png)

Here is the normal sized image: 
![spr_sans_d_dark_96_dpi](https://user-images.githubusercontent.com/42724744/66602603-51e6a000-eb5f-11e9-9fef-6922ee31af8c.png)

To test it for yourself please edit the pixels per inch section in paint.net as seen in this example image: 
![image](https://user-images.githubusercontent.com/42724744/66602684-7d698a80-eb5f-11e9-86e8-764b1322c76c.png)

**Comment by Kneesnap** [comment]
Ffs I can't believe this was the problem. C# has been really infuriating when it comes to stuff like this. Thank you for figuring out the problem.

**Comment by farmer-with-shotgun** [comment]
ACTUALLY it was me

jk he formalized and discovered the real problem
It just affected me first

**Comment by Grossley** [comment]
Well if we want to get technical I had this issue several days ago whilst helping Michael King make a patch for his Undertale Remastered. But it’s not a competition. :P

**Comment by farmer-with-shotgun** [comment]
facts

**Comment by Grossley** [comment]
Resolved
