### ISSUE TITLE
Clicking on "287294723489373000000" in "gml_Object_obj_starker_Create_0" crashes UndertaleModTool

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#236]
Clicking on it just crashes the tool. Methinks the number is too big.

**Comment by colinator27** [comment]
Does this bug still exist on the latest release?

**Comment by Grossley** [comment]
Yes. This occurs in "gml_Object_obj_starker_Create_0" in Undertale version 1.08.

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/0ea16229f9da38af72535bde4dc470defc752f9e
