### ISSUE TITLE
Keep getting error after decompelling a win file

### ISSUE THREAD

**Issue by Dogeislove** [krzys-h/UndertaleModTool#238]
Error 000000c4
Undertale.ModLib.Models.UndertaleGeneralInfo in chunk

**Comment by colinator27** [comment]
Is there any other information from the error message, or can you tell us what game it is from? This is nowhere near enough information to work with.

**Comment by Dogeislove** [comment]
Here is the actual error, "An error occured while trying to load: Incorrect padding in FONT at 0018D1FA while reading chunk FONT.

**Comment by Grossley** [comment]
What game is this for @Dogeislove ? Can you provide a link to the game and/or the data.win file in question?

**Comment by Dogeislove** [comment]
i rly dont wann provide a win file

**Comment by Grossley** [comment]
What game is this for @Dogeislove ?

**Comment by Dogeislove** [comment]
uh. I only have the win file. um

**Comment by Dogeislove** [comment]
what can i do?

**Comment by Dogeislove** [comment]
is there anything i can do?

**Comment by Grossley** [comment]
If you are not comfortable sharing the data.win file out here publicly you can send it to me privately on Discord at: Grossley#2869 . But sharing the data.win file and any other files is probably going to be the best and fastest way for you to get help.

**Comment by Grossley** [comment]
I determined the game in question to be https://gamejolt.com/games/sonic-exe-the-game/16239 through MD5 hash comparison. This game probably is too old to be opened by UndertaleModTool. However, I will not be able to confirm this myself right now.

**Comment by Grossley** [comment]
This game is bytecode 13 and so is out of scope of this project. Therefore this issue should be closed.
