### ISSUE TITLE
I want answers of why Toby Fox wants to change his game's programming language.

### ISSUE THREAD

**Issue by Animelici804** [krzys-h/UndertaleModTool#244]
Please let me know why Toby Fox wants to change DELTARUNE's programming language to another one except Game Maker Studio 1 or 2.

**Comment by BreakinBenny** [comment]
I would assume Toby is willing to change programming language because he finds that GameMaker Studio has limits that he doesn't seem capable of working within.

**Comment by Animelici804** [comment]
> 
> 
> I would assume Toby is willing to change programming language because he finds that GameMaker Studio has limits that he doesn't seem capable of working within.

It may be true.
