### ISSUE TITLE
Any way to bulk export textures?

### ISSUE THREAD

**Issue by Tenome** [krzys-h/UndertaleModTool#245]
I found your program a few days ago and it's been useful. However, navigating through textures is a pain (especially since all the textures have the same Undertale filename in the tree). I tried using Batch Decompile, but it [crashes](http://puu.sh/ERp0i/fb354a17c2.png). Perhaps the ability to directly select a texture from a spritesheet by clicking on it as well would be useful? Thanks.

**Comment by Grossley** [comment]
This issue has already been resolved and so should be closed. Newer versions of UndertaleModTool have the ability to export textures in bulk.

**Comment by Grossley** [comment]
@Tenome 
![image](https://user-images.githubusercontent.com/42724744/71231120-55a24b80-22a1-11ea-8f7e-1883b9157e66.png)

**Comment by Kneesnap** [comment]
Issue Closed.

Newer Builds can be found in the Underminers Discord.
