### ISSUE TITLE
top right details doesn't immediately update when opening a room after opening other room

### ISSUE THREAD

**Issue by dominic1111** [krzys-h/UndertaleModTool#247]
[IPG1]
https://user-images.githubusercontent.com/59143273/71324278-fac65980-2517-11ea-9b18-6ed52b5fee20.PNG

[PG2]
https://user-images.githubusercontent.com/59143273/71324319-7a542880-2518-11ea-96ca-878730db678f.PNG

**Comment by Grossley** [comment]
This is a duplicate of #144 and should be closed.
