### ISSUE TITLE
Typing "global." followed by an asset name into the decompiled code editor causes UndertaleModTool to crash.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#250]
Typing "global." followed by an asset name (sprite, object, script, etc.) into the decompiled code editor causes UndertaleModTool to crash.

For example, typing "global.obj_time" into an empty code area into Undertale or Deltarune and compiling the code causes the program to crash. 

Example image:
![image](https://user-images.githubusercontent.com/42724744/71553880-86822f00-29cb-11ea-9b72-b4098648a855.png)

Here is the error produced when ran in Visual Studio:

![image](https://user-images.githubusercontent.com/42724744/71553819-a06f4200-29ca-11ea-935f-c4c2881832bd.png)

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/0ea16229f9da38af72535bde4dc470defc752f9e
