### ISSUE TITLE
How do you undo scripts?

### ISSUE THREAD

**Issue by Username13211** [krzys-h/UndertaleModTool#257]
I enabled the whole world revolving script and it was very hard to focus playing the game after a while, so is there a way to disable that/remove it?

**Comment by BreakinBenny** [comment]
This gets added at the bottom of **gml_Object_obj_time_Step_1**:

```
__view_set(4, 0, ((__view_get(e__VW.Angle, 0) + (sin((global.time / 15)) / 2)) + 1))
__view_set(11, 0, (__view_get(11, 0) + (cos((global.time / 10)) * 1.5)))
__view_set(12, 0, (__view_get(12, 0) + (sin((global.time / 10)) * 1.5)))
```

Remove it and it should undo TheWoldWorldRevolving,

…You may also have to restore these local variables through the Disassembly, as well:
```
.localvar 1 j 4636
.localvar 2 k 4637
.localvar 3 l 4638
```

**Comment by Username13211** [comment]
> This gets added at the bottom of **gml_Object_obj_time_Step_1**:
> 
> ```
> __view_set(4, 0, ((__view_get(e__VW.Angle, 0) + (sin((global.time / 15)) / 2)) + 1))
> __view_set(11, 0, (__view_get(11, 0) + (cos((global.time / 10)) * 1.5)))
> __view_set(12, 0, (__view_get(12, 0) + (sin((global.time / 10)) * 1.5)))
> ```
> 
> Remove it and it should undo TheWoldWorldRevolving,
> 
> …You may also have to restore these local variables through the Disassembly, as well:
> 
> ```
> .localvar 1 j 4636
> .localvar 2 k 4637
> .localvar 3 l 4638
> ```

Uh. There is just one problem. You can't edit anything in UndertaleModTool.

**Comment by BreakinBenny** [comment]
> Uh. There is just one problem. You can't edit anything in UndertaleModTool.
You need to double-click in the code.

**Comment by colinator27** [comment]
> > Uh. There is just one problem. You can't edit anything in UndertaleModTool.
> 
> You need to double-click in the code.

You'd need to use the dev branch version of UndertaleModTool to edit code like that. At least I think that's where I initially added the feature...

**Comment by Username13211** [comment]
> > > Uh. There is just one problem. You can't edit anything in UndertaleModTool.
> > 
> > 
> > You need to double-click in the code.
> 
> You'd need to use the dev branch version of UndertaleModTool to edit code like that. At least I think that's where I initially added the feature...

How do I open the tool after downloading it?

**Comment by BreakinBenny** [comment]
> > > > Uh. There is just one problem. You can't edit anything in UndertaleModTool.
> > > 
> > > 
> > > You need to double-click in the code.
> > 
> > 
> > You'd need to use the dev branch version of UndertaleModTool to edit code like that. At least I think that's where I initially added the feature...
> 
> How do I open the tool after downloading it?
You extract it to somewhere, maybe somewhere close to the Undertale or Deltarune directory (or even INTO those, in another folder like "UndertaleModTool" unless that folder already comes with the build you got.)

Then it's just to open the UndertaleModTool.exe to get the application going. Sorry Mac & Linux users, you're out of luck for the moment.

**Comment by Username13211** [comment]
> > > > > Uh. There is just one problem. You can't edit anything in UndertaleModTool.
> > > > 
> > > > 
> > > > You need to double-click in the code.
> > > 
> > > 
> > > You'd need to use the dev branch version of UndertaleModTool to edit code like that. At least I think that's where I initially added the feature...
> > 
> > 
> > How do I open the tool after downloading it?
> 
> You extract it to somewhere, maybe somewhere close to the Undertale or Deltarune directory (or even INTO those, in another folder like "UndertaleModTool" unless that folder already comes with the build you got.)
> 
> Then it's just to open the UndertaleModTool.exe to get the application going. Sorry Mac & Linux users, you're out of luck for the moment.

Good thing I don't have a mac or linux haha. Thanks benny.

**Comment by colinator27** [comment]
I think this issue is resolved? Not too sure
