### ISSUE TITLE
A missing comma at the end of the line in "lang_en.json" or "lang_ja.json" JSON causes the program to become completely unresponsive and decompile forever (Windows Deltarune).

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#259]
Even code sections that are empty or those that do not contain strings at all such as ``gml_Object_obj_credits_PreCreate_0`` will not load. This issue is similar to #199 .

For example, if you change line 2 of the "lang_en.json" from ``"date": "1540902565549",`` to ``"date": "1540902565549"`` and then open the Decompiled tab of any code section the following should happen:

As said in issue #199:
> The "Decompiling, please wait... This can take a while on complex scripts [so] Please wait." window should appear.
> Watch as the decompiling process seems to go on forever.
> NOTE: This process cannot be cancelled as UMT needs to be terminated, costing you all your time and work.

I believe this could be fixed by implementing a JSON validator that ensures that the contents of the .JSON files are, in fact, valid before loading them, (or perhaps some error handling to omit invalid lines? That could be more error prone though).

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/07d3cb9207536897f1cb881a63467a8d704662c3.
