### ISSUE TITLE
String/dialog/translation editor

### ISSUE THREAD

**Issue by D3fau4** [krzys-h/UndertaleModTool#26]
it would be great if you would make some string editor as if it were a text editor instead of changing the lines of dialogue one by one, you could use for example as the testing scritp.

![captura](https://user-images.githubusercontent.com/19638408/46247331-05279f80-c40a-11e8-896a-6b937fc7a38f.PNG)

You do not know how hard it is to put each line of the characters one by one, I just ask you some option that allows me to copy and paste as if it were the notepad or some way to export and import dialogs

![example](https://user-images.githubusercontent.com/19638408/46247367-85e69b80-c40a-11e8-8252-06837d62d4ce.PNG)

I'm very slow when it comes to adding the dialogues translated to the game by this, if you could make some editor or some way to import it would be very helpful

**Comment by krzys-h** [comment]
I am planing to make an actual editor for this, perhaps even with preview for the dialog control sequences (doing the line breaks manually without preview is probably annoying as well). No promises on when I'll get around to it though.

**Comment by krzys-h** [comment]
Also, it might be faster if you just go through them in the "Strings" list on the left. Related dialogs should be close to each other.

**Comment by D3fau4** [comment]
Ok thank you, is that I'm veeeeeeeeery slow to pass the translation into Spanish

**Comment by krzys-h** [comment]
```csharp
using(StreamWriter writer = new StreamWriter("strings.txt"))
{
	foreach(var str in Data.Strings)
	{
		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
			continue;
		writer.WriteLine(str.Content);
	}
}
```
```csharp
using(StreamReader reader = new StreamReader("strings.txt"))
{
	foreach(var str in Data.Strings)
	{
		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
			continue;
		str.Content = reader.ReadLine();
	}
}
```
These two scripts should be all you need. The first one exports all strings from the currently loaded data.win to strings.txt in UndertaleModTool directory, the second one does the reverse.

To run them either save them as files with .csx extension and use `Scripts > Run other script` or just copy-paste them into the status textbox at the bottom and press enter.

**Comment by D3fau4** [comment]
thank you very much, Now I try it and I give you the results

**Comment by CyberSlimp** [comment]
> ```cs
> using(StreamWriter writer = new StreamWriter("strings.txt"))
> {
> 	foreach(var str in Data.Strings)
> 	{
> 		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
> 			continue;
> 		writer.WriteLine(str.Content);
> 	}
> }
> ```
> 
> ```cs
> using(StreamReader reader = new StreamReader("strings.txt"))
> {
> 	foreach(var str in Data.Strings)
> 	{
> 		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
> 			continue;
> 		str.Content = reader.ReadLine();
> 	}
> }
> ```
> 
> These two scripts should be all you need. The first one exports all strings from the currently loaded data.win to strings.txt in UndertaleModTool directory, the second one does the reverse.
> 
> To run them either save them as files with .csx extension and use `Scripts > Run other script` or just copy-paste them into the status textbox at the bottom and press enter.

Great! Thank You. 
Can You make script for import font glyph (i ask for it on https://github.com/krzys-h/UndertaleModTool/issues/20 )

**Comment by D3fau4** [comment]
> ```cs
> using(StreamWriter writer = new StreamWriter("strings.txt"))
> {
> 	foreach(var str in Data.Strings)
> 	{
> 		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
> 			continue;
> 		writer.WriteLine(str.Content);
> 	}
> }
> ```
> 
> ```cs
> using(StreamReader reader = new StreamReader("strings.txt"))
> {
> 	foreach(var str in Data.Strings)
> 	{
> 		if (str.Content.Contains("\n") || str.Content.Contains("\r"))
> 			continue;
> 		str.Content = reader.ReadLine();
> 	}
> }
> ```
> 
> These two scripts should be all you need. The first one exports all strings from the currently loaded data.win to strings.txt in UndertaleModTool directory, the second one does the reverse.
> 
> To run them either save them as files with .csx extension and use `Scripts > Run other script` or just copy-paste them into the status textbox at the bottom and press enter.

Thanks for the script it works fine but it breaks the fonts, look.

before: 
![captura_de_pantalla_2018-10-02_a_las_11 54 06](https://user-images.githubusercontent.com/19638408/46342891-4acbae80-c63c-11e8-8ef7-b5eae074cf82.png)

After: 
![captura_de_pantalla_2018-10-02_a_las_11 56 40](https://user-images.githubusercontent.com/19638408/46342907-5ae38e00-c63c-11e8-8a89-41eb7890d778.png)

**Comment by krzys-h** [comment]
Are you sure you didn't add/remove a line in strings.txt accidentaly? Looks like everything shifted by one. That script is very basic so it won't warn you if you did.

**Comment by krzys-h** [comment]
@CyberSlimp I have the scripts for you in https://github.com/krzys-h/UndertaleModTool/issues/20#issuecomment-426373612

**Comment by CyberSlimp** [comment]
@D3fau4 script work great, i test it

**Comment by D3fau4** [comment]
@CyberSlimp I know I had a problem and there were 4 spaces in unnecessary targets

**Comment by zellfy** [comment]
@CyberSlimp I have the same problem like you, Can you tell me why this situation happen？

**Comment by SPONGEROBERT123** [comment]
wait, where is undertale mod tool directory?

**Comment by Mc-muffin** [comment]
It's the directory where UndetaleModTool's .exe is located

**Comment by SPONGEROBERT123** [comment]
ok

**Comment by Kneesnap** [comment]
This is resolved(?)
