### ISSUE TITLE
Adding an object to the game "Pizza Tower" causes the game to no longer boot.

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#260]
This also happens if you add or remove a tile.

**Comment by Animelici804** [comment]
It also happens in Undertale Green as well.

**Comment by Animelici804** [comment]
Also happens in SPOOKYTALE.

**Comment by CROUZi** [comment]
Download fixed version from here; https://cdn.discordapp.com/attachments/589826508957286400/677949899618385933/UMT_PizzaTower_V2.rar

Also works with Stoneshard, so I think it would work with other GMS2 games too.

**Comment by Animelici804** [comment]
Ayy thanks a lot, CROUZi! @Grossley , someone finally found a solution for us.

**Comment by JackoT-Bit** [comment]
@CROUZi but how exactly do we fix a game like you did?

**Comment by Grossley** [comment]
@JackoT-Bit He did not make the fix to the room format. The room format fix is in a separate pull request.

**Comment by Mc-muffin** [comment]
Also, this issue can be closed.

**Comment by JackoT-Bit** [comment]
@Grossley oh sorry i got the wrong idea, i thought it was a fixed data.win, not a different version of utmt lol
