### ISSUE TITLE
Can someone please make this tool support Bytecode 14?

### ISSUE THREAD

**Issue by tarkan809** [krzys-h/UndertaleModTool#266]
Yeah... I know some people were trying to open data.win with bytecode 14 files...

But turns out it just give errors...

Can someone please add a bytecode 14 support to the tool?

Here's the game that I was trying to edit/decompile:
[PacMan.zip](https://github.com/krzys-h/UndertaleModTool/files/4206669/PacMan.zip)

I know this isn't related to undertale but... What can I say...

**Comment by Grossley** [comment]
Bytecode 14 support has already been added in the dev branch.

**Comment by tarkan809** [comment]
> Bytecode 14 support has already been added in the dev branch.

I know... but when I use Visual studio somehow it doesn't work at all.

(P.S. I used Visual studio 2010 version at home and Visual studio 2019 at school)
Is there a way to make the data.win from bytecode 14 to bytecode 15?

**Comment by Grossley** [comment]
This build should support bytecode 14:
https://cdn.discordapp.com/attachments/589826508957286400/641761249599946752/UndertaleModTool-6f8c538d3e.zip

**Comment by tarkan809** [comment]
> This build should support bytecode 14:
> https://cdn.discordapp.com/attachments/589826508957286400/641761249599946752/UndertaleModTool-6f8c538d3e.zip

Can you make the link google drive?
Because my internet won't let me connect to discord.

**Comment by Animelici804** [comment]
I can make it link to google Drive for you.

**Comment by tarkan809** [comment]
> I can make it link to google Drive for you.

Thank you, pal. :)

**Comment by Grossley** [comment]
You may use this build @tarkan809 [UndertaleModTool-6f8c538d3e.zip](https://github.com/krzys-h/UndertaleModTool/files/4206767/UndertaleModTool-6f8c538d3e.zip)

**Comment by tarkan809** [comment]
> You may use this build @tarkan809 [UndertaleModTool-6f8c538d3e.zip](https://github.com/krzys-h/UndertaleModTool/files/4206767/UndertaleModTool-6f8c538d3e.zip)

Uh. Ok then. Thanks...?

**Comment by Grossley** [comment]
This issue is resolved and should be closed.
