### ISSUE TITLE
Problem with starting the file?

### ISSUE THREAD

**Issue by nowhed** [krzys-h/UndertaleModTool#271]
I changed a font sprite and now my game won't start. This is what it says:
`############################################################################################
ERROR in
action number 1
of  Step Event1
for object obj_time:

File is not opened for reading.
at gml_Script_ossafe_file_text_read_string
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_ossafe_file_text_read_string (line 0)
gml_Script_scr_load
gml_Object_obj_time_Step_1`

**Comment by Grossley** [comment]
This is not a problem caused by editing the font but rather caused by a missing or invalid save file as indicated by the error. Therefore this is caused by human error rather than the fault of UndertaleModTool. This issue should be closed.
