### ISSUE TITLE
Adding "y = y*5/x" and "y = y+5-x" decompile to "((y*5)*x)" and "((y + 5) + x)" respectively

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#272]
Adding ``"y = y*5/x"`` and ``"y = y+5-x"`` decompile to ``"((y*5)*x)"`` and ``"((y + 5) + x)"`` respectively.
The fact that these basic code operations do not decompile correctly is a shame. Please take a look at these ASAP.

**Comment by colinator27** [comment]
Actually, this seems to be a compiler bug, not a decompiler bug. Big issue though.

**Comment by KadeDev** [comment]
ah yes, division doesn't exist.

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/991f602b7021ba36c4ed8b8fd47fa9d989cc0434, unless I messed up really bad somehow
