### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by edneicabofrio** [krzys-h/UndertaleModTool#273]
Dear krzys_h,

My name is Ednei, I'm from Brazil, and I develop games on Game Maker 2.
I'm making a non-commercial RPG game like the Undertale style.
The game is still in development. It is a role-playing game very focused on large and extensive dialogues.
During development I had the idea of ​​trying to prepare the game to be multilingual.
The problem is that the way I started to develop it, many dialogs (strings) were inside the code in scripts and objects. This makes it difficult to create files to be translated into other languages.

I asked on the yoyogames forum if there is any form or tool that is able to isolate certain strings in quotes and assemble them into a single file for translation. See this topic:

https://forum.yoyogames.com/index.php?threads/generate-translation-file-automatically.73013/#post-430263

After searching the internet I found UndertaleModTool.
I was impressed with what it can do with games created in GM2.

UndertaleModTool does not serve my purpose but it has shown that its creator is an extremely competent person to create the tool I need.

That's why I come here to ask you to create a tool to help me translate my own project in GM2 into other languages.

I am willing to pay for it.

Of course, I'm just an RPG lover who wants to create his own game as a hobby. So I don't have many resources.

Furthermore, I believe that if you make a tool like this available on the Marketplace on the yoyogames website you could make some profit, if you wish.

I would like to get a positive response. So I am sending an excel file attached with an idea of ​​what I would like the program to be able to do.

[Language example.xlsx](https://github.com/krzys-h/UndertaleModTool/files/4416646/Language.example.xlsx)

I await an answer.

Thanks.

Ednei. 

my email is efngames@hotmail.com

**Comment by Grossley** [comment]
This is not a valid issue and so this should be closed.

**Comment by Kneesnap** [comment]
This does not relate to UTMT, and we'll be closing this issue because it is not the place for this.
Message me on discord, Kneesnap#7540, and we can talk about it.

**Comment by edneicabofrio** [comment]
Ok. Sorry.
