### ISSUE TITLE
The modtool wont open and instantly shows the error "Undertalemodtool.exe has stopped working"

### ISSUE THREAD

**Issue by ZackyGameDev** [krzys-h/UndertaleModTool#277]

**Comment by colinator27** [comment]
You need to provide a little bit more information than just that it stopped responding. Like, what device are you running it on, what operating system, etc. Whatever you can give us will help diagnose the issue.

**Comment by Zacky2456** [comment]
okay i will edit them into the description now

**Comment by colinator27** [comment]
Just saw what you put on the Discord server. I don't really know what the issue could be. Perhaps you may need to update some drivers, like your graphics drivers, or maybe you need to update the .NET Framework. I'm not really sure how well WPF (which runs the UI of the application) handles Windows 7 either now.

**Comment by Zacky2456** [comment]
I will try to run this on Windows 8 laptop later but i have updated.NET framework today and i dont think it requires GPU

**Comment by colinator27** [comment]
If you're able to run the application with a different graphics processor (if available), it might do something?

**Comment by colinator27** [comment]
Have you gotten it to run yet?

**Comment by Grossley** [comment]
I assume that this issue has been resolved and so I am closing it. If it has not been resolved, please reopen the issue with a status update @ZackyGameDev
