### ISSUE TITLE
UndertaleModTool replaces "\n" and "\r\n" strings with "#".

### ISSUE THREAD

**Issue by nkrapivin** [krzys-h/UndertaleModTool#280]
It's a bad issue since if you try to recompile ossafe_file_text_read/writeln or file_text_open_read it'll screw the entire script because ossafe scripts use actual newlines and not GM:S newlines.

The problem code is in UndertaleModLib/Models/UndertaleString.cs in function ToString at lines 63 and 65.

```
if (isGMS2)
    return "\"" + Content.Replace("\\", "\\\\").Replace("\r", "\\r").Replace("\n", "\\n").Replace("\"", "\\\"") + "\""; //line 63

return "\"" + Content.Replace("\r\n", "\n").Replace("\n", "#").Replace("\"", "\" + chr(34) + \"") + "\""; // line 65
```

**Comment by colinator27** [comment]
Would removing `.Replace("\r\n", "\n").Replace("\n", "#")` cause any potential issues in the code editor?

**Comment by nkrapivin** [comment]
I made a fixed function
```
        public string ToString(bool isGMS2)
        {
            if (Content == null)
                return "\"null\""; // NPE Fix.

            if (isGMS2)
                return "\"" + Content.Replace("\r", @"\r").Replace("\n", @"\n").Replace("\"", "\\\"") + "\""; // GMS2 can handle \r and \n with " just fine.
            else
            {
                // GMS1 requires some weird tricks.
                var newline = @"chr(10)";
                var carriage = @"chr(13)";
                var quote = @"chr(34)";
                return "\"" + Content
                    .Replace("\"", "\" + " + quote + " + \"")
                    .Replace("\r", "\" + " + carriage + " + \"")
                    .Replace("\n", "\" + " + newline + " + \"")
                    + "\""
                    ;
            }
        }
```

please commit it and we're done.

**Comment by colinator27** [comment]
Not quite sure why you made fields there, but those last couple of lines are broken. Also, if we do this, we should fully support every escape code; full list for GMS2 is here: https://docs2.yoyogames.com/source/_build/3_scripting/4_gml_reference/strings/index.html

**Comment by colinator27** [comment]
This has been changed by now, closing
