### ISSUE TITLE
When I save the data.win file after editing the code, the code stays the exact same.

### ISSUE THREAD

**Issue by Username13211** [krzys-h/UndertaleModTool#282]

**Comment by Mc-muffin** [comment]
After making you changes, click away from the code window, such as the code becomes colored, then you can safely save.

**Comment by Username13211** [comment]
> After making you changes, click away from the code window, such as the code becomes colored, then you can safely save.

What if it still remains the same?

**Comment by Mc-muffin** [comment]
Okay, you'll need to say exactly what are you doing, provide an example or gif of you can

**Comment by Username13211** [comment]
https://dump.video/i/df5vzG.mp4

**Comment by Mc-muffin** [comment]
Ahh, I see the problem, those are comments! Not code, they are put there by the tool to aid you, but they aren't really part of that piece of code (that's why they are preceded by ``//``). If you need to edit the In-game text go to ``scr_get_text`` (very long and laggy) or use the export strings script.

**Comment by Username13211** [comment]
> Ahh, I see the problem, those are comments! Not code, they are put there by the tool to aid you, but they aren't really part of that piece of code (that's why they are preceded by `//`). If you need to edit the In-game text go to `scr_get_text` (very long and laggy) or use the export strings script.

After exporting all strings, what do I do now, I have a notepad file of all the scripts

**Comment by Mc-muffin** [comment]
Once you have the notepad file, just edit the strings you want, just be careful NOT to remove or add strings, just edit them (they can be longer or shorter if needed) and then run the import strings script to import your changes. 
About ``scr_get_text`` yeah it was typo, it should be ``scr_gettext``.

**Comment by Grossley** [comment]
This issue is resolved and will now be closed.
