### ISSUE TITLE
Decompiler breaks on gml_Object_obj_mettatonex_Alarm_6

### ISSUE THREAD

**Issue by Jacky720** [krzys-h/UndertaleModTool#284]
Probably the first _Undertale_ bug in a while, but the decompiler never finishes on `gml_Object_obj_mettatonex_Alarm_6`. At any rate, it takes far longer than any other script of comparable size.

I'm not an avid modder, so I can't really help beyond that.

**Comment by Grossley** [comment]
I just loaded ``gml_Object_obj_mettatonex_Alarm_6`` right now in Undertale v1.08 and I wasn't able to reproduce this issue.

**Comment by Grossley** [comment]
What may cause this is perhaps one of the strings being referenced in the string preview is causing issues and so would be related to #259 .

**Comment by colinator27** [comment]
Yeah, make sure you're running the latest version of the tool, because supposedly #199 is fixed

**Comment by Jacky720** [comment]
Yep, it's fixed in the 0.3.0 update. My mistake, thanks anyway.
