### ISSUE TITLE
Dicord Invite in the ReadMe is not working

### ISSUE THREAD

**Issue by SonicEraZoR** [krzys-h/UndertaleModTool#285]
When I'm trying to join the discord it says that the invitation is expired

**Comment by sailent704** [comment]
You have to email Grossley directly due to recent events.

**Comment by SonicEraZoR** [comment]
@Grossley Can I have an invate to the Discord server? My e-mail is k.iwanilow@yandex.ru

**Comment by colinator27** [comment]
The README is now updated with a new invite link.

**Comment by Grossley** [comment]
Specifically, that link is https://discord.gg/RxXpdwJ @SonicEraZoR

**Comment by SonicEraZoR** [comment]
Cool, thanks!
