### ISSUE TITLE
room preview doesn't take sprite origin into account

### ISSUE THREAD

**Issue by somebody1234** [krzys-h/UndertaleModTool#295]
gml version 1.0.0.466 i think.

the room preview does not appear to take origin into account, meaning the image is offset.

![image](https://user-images.githubusercontent.com/4046547/83325375-2d3a6680-a2af-11ea-83e5-0d1ec4b35b91.png)

here is the preview; the title is supposed to be centered.

![image](https://user-images.githubusercontent.com/4046547/83325399-47744480-a2af-11ea-860c-beeabc43a5a1.png)

**Comment by Kneesnap** [comment]
Out of curiosity, is there any reason it's 1.0.0 466? that's a pretty
special version, just curious if it was used for a particular reason.

**Comment by somebody1234** [comment]
no idea, but this game *was* abandoned in like 2015 fwiw

**Comment by VladiStep** [comment]
This will be fixed in 0.4.0.3 release.
_(Closed by #717)_
