### ISSUE TITLE
GMS 2.3 Beta failing with UMT

### ISSUE THREAD

**Issue by relma2** [krzys-h/UndertaleModTool#300]
Hi,
I'm trying to open a game called [Roseblight (https://aplovestudio.itch.io/roseblight) in UMT, and the creator recently switched to... I believe **Beta GMS 2.3**...
![image](https://user-images.githubusercontent.com/9358770/85913621-386bae00-b7eb-11ea-8f62-56e5f778c0e2.png)
And this is the error message I get when trying to open the file. Is there a way to remedy this?

**Comment by Grossley** [comment]
GMS 2.3 is very different from GMS2 internally and is not currently supported by UndertaleModTool.

**Comment by Grossley** [comment]
So the short answer is no but the long answer is maybe it will be supported in the future. Sorry about that.

**Comment by colinator27** [comment]
Yeah, it's not a major priority at the moment, but there has been a little bit of work to support it already, though incomplete (it's not in the releases yet, either).

**Comment by colinator27** [comment]
Well, some more work has been done on GMS 2.3, and this game now loads properly as of https://github.com/krzys-h/UndertaleModTool/commit/38471260b99ec453e6ed2d767d59d593ae372dbc! A bunch of the code still won't decompile, however.

**Comment by Grossley** [comment]
The issue of loading 2.3+ games, unrelated to the mask issue, has probably been resolved through recent commits, but if the problem still persists, you may reopen the issue with more information on the issue.
