### ISSUE TITLE
import texture script

### ISSUE THREAD

**Issue by yous0me** [krzys-h/UndertaleModTool#303]
Hi guys
I need a new script to import texture because when I import them by these scripts  [here](https://github.com/krzys-h/UndertaleModTool/issues/92) it counts up  01.png - 02.png... and search for them in data.win 
but textures don't have numbers -like 01.png- they have names  
![Bigproblem](https://user-images.githubusercontent.com/68918488/88700336-35791b80-d111-11ea-96bc-06f94b49e339.png)

**Comment by Mc-muffin** [comment]
Don't use those scripts, use the ImportGraphics scripts (V2 recommended for big imports) which are supplied inside the "Experimental Scripts" folder that come with the tool.
