### ISSUE TITLE
Objects gets funky by editing the capacity or rotations UTMT issue

### ISSUE THREAD

**Issue by fireahmedgamerYT** [krzys-h/UndertaleModTool#308]
When editing size to be wider or taller will make objects move faster and the room editir will not show its true cordinates except to reopen the room or resizing to smaller at any point will make the object moves in the editor moves slower and same

**Comment by Grossley** [comment]
This is an already known issue.

**Comment by fireahmedgamerYT** [comment]
> This is an already known issue. As far as I know there is no easy way to resolve this for the time being. I am sorry.

Oh thanks i hope you all find a way from this issue

**Comment by Jacky720** [comment]
This was fixed by #717.
