### ISSUE TITLE
UTMT crash

### ISSUE THREAD

**Issue by fireahmedgamerYT** [krzys-h/UndertaleModTool#309]
Sometimes removing something like functions that are used by another code or an embedded texture crash the undertale mod tool

**Comment by Grossley** [comment]
There's not enough information to do anything.

**Comment by fireahmedgamerYT** [comment]
> There's not enough information to do anything.

Oof im so sorry should i create new issue or edit this

**Comment by Grossley** [comment]
Can you provide more information as to what specifically causes the crash?

**Comment by fireahmedgamerYT** [comment]
> Can you provide more information as to what specifically causes the crash?

Done.

**Comment by Miepee** [comment]
@fireahmedgamerYT You still barely posted info so it's not exactly clear what your issue was. Can you check if the latest version still has those issues?
