### ISSUE TITLE
Sprite saving

### ISSUE THREAD

**Issue by fireahmedgamerYT** [krzys-h/UndertaleModTool#310]
While dev my mod i kept putting lots of new sprites for lots of random projects untill then someday when i was saving the game it got me an issue and prevented the game from saving also if i removed a texture page item will not effect the sprite then when i reopen the data win it tells me that there's missing values and will prevent the data win from loading in the tool that destroys the project.

**Comment by Grossley** [comment]
This is probably an issue with Import Graphics that has been resolved through better error checking. If this is not the case, feel free to reopen the issue with more information regarding what specifically causes the problem.
