### ISSUE TITLE
Why new release uses old BorderEnabler script?

### ISSUE THREAD

**Issue by omerakgoz34** [krzys-h/UndertaleModTool#317]
![Screenshot_125](https://user-images.githubusercontent.com/49201485/91493431-fb419c00-e8bf-11ea-88e6-a61182fc59c4.png)

--> #304 :(

**Comment by Kneesnap** [comment]
It looks like the textures are missing, I don't see any evidence based on
this that it's an old version of the script.

**Comment by omerakgoz34** [comment]
@Kneesnap 
This issue happens only when opening the data.win file with file explorer.
![Screenshot_126](https://user-images.githubusercontent.com/49201485/91494398-72c3fb00-e8c1-11ea-8298-2797276572a1.png)

I fixed this issue a month ago and merged into master but it doesn't exist in new release :/

**Comment by omerakgoz34** [comment]
And I also added to [scoop](https://scoop.sh) games repo 
https://github.com/Calinou/scoop-games/blob/master/bucket/undertale-mod-tool.json 
:D

**Comment by colinator27** [comment]
Sorry, I accidentally used the wrong file, the ZIP is reuploaded now.

**Comment by Kneesnap** [comment]
Most likely it's because it runs UTMT with a different current directory
than where UTMT is located, so it's looking for the files with the base
directory of the game instead of UTMT

**Comment by omerakgoz34** [comment]
Yes that's right :D
