### ISSUE TITLE
About release versioning...

### ISSUE THREAD

**Issue by omerakgoz34** [krzys-h/UndertaleModTool#318]
https://github.com/Calinou/scoop-games/pull/149#issuecomment-683729490

I think this is a good idea 😉

**Comment by Grossley** [comment]
If we made a new tag for every minor update and change it would result in an excessive number of releases that add relatively little. Especially with revisions to experimental scripts, which happens fairly often, and do not constitute an actual change to the tool itself. I'm sorry that your system isn't working as well as it should. Hope you figure it out.

**Comment by colinator27** [comment]
Whoops, I had no idea that would be an issue. Thanks for letting us know. Experimental scripts are going to be included in the project itself from now on, to prevent this from needing to happen in the first place.
