### ISSUE TITLE
"Export all frames" should export all frames as big as the sprite's actual size (with Padding)

### ISSUE THREAD

**Issue by LilAlienBeepBoop** [krzys-h/UndertaleModTool#320]
For example, if there's some transparent pixels around a sprite, it will exported without them.
This unfortunately makes the frames of most animations export at different sizes, meaning that they don't align properly.
It would be more convenient to export them with padding, especially if they're needed for a GIF or video _(hint, hint)_.
And it would also be a more accurate representation of what they would look like in-game.

See this image attached that shows you what I'm talking about:
![image](https://user-images.githubusercontent.com/53340560/93661893-dbf0f580-fa9e-11ea-9476-dbdd7afc507c.png)

**Comment by Grossley** [comment]
This issue has been resolved and should be closed.

**Comment by colinator27** [comment]
This is added in 0.3.4 (via new experimental script, `ExportAllTexturesWithPadding.csx`), I'll be uploading its release in a moment.
