### ISSUE TITLE
RunSwitchOnPc script is missing something, BorderEnablerv1.11 script is missing

### ISSUE THREAD

**Issue by avengah** [krzys-h/UndertaleModTool#321]
Specifically, in the code section "gml_Object_obj_npc_room_Create_0", the OS check for the donation box in the rubbish dump is still present and I had to remove it manually. Also, the Switch version of the BorderEnabler script is not included and must be downloaded separately from the subreddit.

**Comment by Grossley** [comment]
Hello. The OS check not being included is an oversight. The script will be updated to disable that OS check. However, the BorderEnabler for NXTALE script will not be integrated in the script as that is outside the scope of the script, similarly to how all other scripts included with UndertaleModTool do not additionally run the regular BorderEnabler for PC script. Additionally, the BorderEnabler for NXTALE script has been reported to cause issues bizarre issues on different screen resolutions, and will not be included with the tool until at least those issues have been resolved.

**Comment by colinator27** [comment]
RunSwitchOnPC issue resolved in https://github.com/krzys-h/UndertaleModTool/commit/57986c8605112b502a6658fa1956300af4453b25, should we leave this open to track fixing BorderEnabler?

**Comment by avengah** [comment]
Thanks. I just noticed something else; it's not a big deal but I thought I should mention it. The version of BorderEnablerv1.11.csx I downloaded from Reddit left an os check intact in gml_Object_obj_settingsmenu_Create_0. I had to manually change that one as well; before doing so, borders 11 and 12 could not be selected even if they were unlocked in undertale.ini.

**Comment by Grossley** [comment]
Please provide the script in question so that I can patch that for you.

**Comment by avengah** [comment]
[BorderEnablerv1.11.csx.txt](https://github.com/krzys-h/UndertaleModTool/files/5322492/BorderEnablerv1.11.csx.txt)

Thanks!

**Comment by Grossley** [comment]
Resolved
