### ISSUE TITLE
Typing "2+=4" into the decompiled code editor causes the tool to crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#324]
Typing "2+=4" into the decompiled code editor causes the tool to crash

**Comment by BenjaminUrquhart** [comment]
Stacktrace: https://hasteb.in/onojozan.css

**Comment by Kneesnap** [comment]
Why would you ever type this LOL

**Comment by BenjaminUrquhart** [comment]
It doesn't really matter, it shouldn't cause a full crash

**Comment by Grossley** [comment]
> It doesn't really matter, it shouldn't cause a full crash

This

**Comment by Kneesnap** [comment]
Right, it definitely shouldn't cause a crash, but I think it's funny that
we found this bug at all.

**Comment by fireahmedgamerYT** [comment]
Keep in mind that im who posted this

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/5c3ca61ff01b82c4582fca3d57890e3422496c69
