### ISSUE TITLE
Undertale v1.0 issues in UndertaleModTool v0.3.4.2

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#325]
Attempting to decompile ``gml_Object_OBJ_WRITER_Draw_0`` in Undertale 1.0 causes the program to lock up.
Exporting all code results in a extremely huge file size for the code and eventually results in extreme and abnormal ram usage
![image](https://user-images.githubusercontent.com/42724744/97727994-4037a980-1a8e-11eb-9189-b83bf56a9618.png)
![image](https://user-images.githubusercontent.com/42724744/97728089-5ba2b480-1a8e-11eb-821f-a19045cf8c42.png)

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/05891a0d4829362f427255a8e61ca8f9273d22d9
