### ISSUE TITLE
Disable some compiler optimizations on older versions of Undertale. 

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#329]
Apparently "x = x" is optimized out of the code automatically by the compiler. However, this is in Undertale 1.0's code, and so clearly was not optimized out in that version. This optimization should be ignored when editing Undertale 1.0's decompiled code. For example, "x = x" is in ``gml_Object_blt_handbullet1_Collision_758`` in Undertale 1.0 (bytecode 14, GMS versions less than or equal to 1.4.1567). 

Also, in Undertale 1.001 (bytecode 15 GMS versions less than 1.4.1763), ``gml_Object_obj_face_floweytalk_Create_0`` does not optimize out the "real" function and so this should also be ignored for this and older versions:
```
event_inherited()
image_speed = 0.25
if (global.faceemotion == 0 && sprite_index != real(166))
    sprite_index = real(166)
if (global.faceemotion == 1 && sprite_index != real(170))
    sprite_index = real(170)
if (global.faceemotion == 2 && sprite_index != real(171))
    sprite_index = real(171)
if (global.faceemotion == 3 && sprite_index != real(172))
    sprite_index = real(172)
if (global.faceemotion == 4 && sprite_index != real(179))
    sprite_index = real(179)
if (global.faceemotion == 5 && sprite_index != real(175))
    sprite_index = real(175)
```

**Comment by Kneesnap** [comment]
I really think it's a stretch to try and accurately emulate the compiler
exactly for all versions which were used.

**Comment by Grossley** [comment]
There is a basic expectation by many (myself included) that the code should be at least recompilable to what it shows in the UMT editor. Furthermore, there aren't that many changes like this, and even if there were it should be possible to implement them as they are discovered. Writing this off as "too much" is frankly silly considering that support for these versions were added in the first place.

**Comment by Kneesnap** [comment]
I don't think you understand the magnitude of how many changes there are,
and how much work it would to figure out/replace them all.

**Comment by Grossley** [comment]
I looked at the relevant changes regarding Undertale. They were few and are specified in the issue. Other changes besides the ones I mentioned in the issue are outside of the scope of the issue. This issue is not about replicating every decompiler change for every version as that would be out of scope. This is specifically about what is mentioned in the issue.

**Comment by Kneesnap** [comment]
This was a response to your previous comment.

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/65cddf569a78cf98e45fa783c83d8076dee28a0e, courtesy of @Grossley of course
