### ISSUE TITLE
Errors out on Deltarune (AUDO chunk)

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#33]
Time to dig. https://www.deltarune.com/

Throws an error on the sound chunk 
![image](https://user-images.githubusercontent.com/3047793/47803697-74dec200-dd09-11e8-9270-ec1aa12e83ac.png)

**Comment by krzys-h** [comment]
Already noticed!

https://www.reddit.com/r/Underminers/comments/9syjq6/survey_program_windows_englishexe/e8sjni4

Probably related to the existence of audiogroups1.dat

(if you do anything with this, please remenber about the no spoilers for 24h rule)

**Comment by NarryG** [comment]
Yeah I know. I bypassed it for now and I'm only bringing stuff up in the speedrunning community

**Comment by PoroCYon** [comment]
Works with Altar.NET, so it's not really related, as Altar.NET doesn't even know about GMS2.

About `audiogroups1.dat`: [d579374c](https://gitlab.com/PoroCYon/Altar.NET/commit/d579374c5d748d61c682768b0e40ecc9f73cabca).

**Comment by krzys-h** [comment]
@PoroCYon UndertaleModTool in general tries to resolve these numeric IDs to actual objects and that fails because it doesn't see the stuff that should come from audiogroups1.dat

**Comment by krzys-h** [comment]
Preliminary support implemented in de5279db97fcbfadfa7d3a1f6525f22b397c01f8
