### ISSUE TITLE
StackOverflowException on Decompiling Deltarune Code 

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#34]
gml_Object_obj_kingcutscene_Step_0

Process is terminated due to StackOverflowException.
An unhandled exception of type 'System.StackOverflowException' occurred in UndertaleModLib.dll

**Comment by krzys-h** [comment]
I think it's literally overflowing the stack because of how deep the block tree in that file is. Wow. I'm gonna have to refactor that.
