### ISSUE TITLE
Borders wont appear

### ISSUE THREAD

**Issue by MrBenichi** [krzys-h/UndertaleModTool#343]
hello so the borders wont appear its just a black void
![image](https://user-images.githubusercontent.com/63652565/101793678-1d7dc380-3b17-11eb-8503-a4940b1d708f.png)

**Comment by nkrapivin** [comment]
1) Did you enable them in settings?
2) Are you sure the script did import borders properly?

**Comment by MrBenichi** [comment]
> 1. Did you enable them in settings?
> 2. Are you sure the script did import borders properly?

1> No i didnt enable them in settings
2> I dont know if it imported them properly

**Comment by nkrapivin** [comment]
> > 1. Did you enable them in settings?
> > 2. Are you sure the script did import borders properly?
> 
> 1> No i didnt enable them in settings
> 2> I dont know if it imported them properly

Then enable them?????????????????????????

**Comment by MrBenichi** [comment]
> > > 1. Did you enable them in settings?
> > > 2. Are you sure the script did import borders properly?
> > 
> > 
> > 1> No i didnt enable them in settings
> > 2> I dont know if it imported them properly
> 
> Then enable them?????????????????????????

oh you meant enable them in scripts? since i ran the script.
