### ISSUE TITLE
Unknown variable local.alarm[0]

### ISSUE THREAD

**Issue by nkrapivin** [krzys-h/UndertaleModTool#344]
This code will make the decompiler crash:
```
var dummy;
dummy.alarm[0] = 1111;
```
With this error:
![image](https://user-images.githubusercontent.com/33228822/102015447-6fc01e00-3d7d-11eb-975b-520185dfdf12.png)

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/d8ad8ab12f6a633ceeb0f29fcbc34eb0e0387739
