### ISSUE TITLE
String padding load error for GMS 2.3.1+ games

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#353]
String padding load error for GMS 2.3.1+ games

**Comment by Everspace** [comment]
More annoyingly, it's a lot of the warning dialogue so you have to hold enter to make it through all the popups. The tools still work for say, extracting textures/sprites which is what I was upto.

It would be nice to minimize these repeat warnings, since knowing 1 is not working is enough.

**Comment by Grossley** [comment]
Resolved
