### ISSUE TITLE
UTMT makes incorrect assumptions when creating new room layers

### ISSUE THREAD

**Issue by BenjaminUrquhart** [krzys-h/UndertaleModTool#355]
The room editor assumes the last room in the room list will have the highest layer id (see https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/Editors/UndertaleRoomEditor.xaml.cs#L434). However, this assumption is invalidated once new layers are added, meaning multiple layers will share the same id. This can lead to the game hard crashing or not responding under certain circumstances.

Video (triggered by suspending and reactivating all objects a few times, then debug restarting the game. Can also be triggered by leaving the room):  

https://user-images.githubusercontent.com/24701883/103180875-0e617a00-4868-11eb-83c6-8549ebdf9650.mp4

**Comment by BenjaminUrquhart** [comment]
I've manually updated the layer ids and it does indeed fix the issue.

**Comment by colinator27** [comment]
Fixed via #356
