### ISSUE TITLE
Edited strings not saving

### ISSUE THREAD

**Issue by Delphren-Phox** [krzys-h/UndertaleModTool#361]
When i modify a strings content and save, when i reload the file it is back to the previous value. and loading the game has the original text too

**Comment by BenjaminUrquhart** [comment]
Did you click out of the string textbox?

**Comment by Grossley** [comment]
Further information is needed to confirm this is actually a bug. Will be closing for now, but if you provide more information about the issue at hand, you may reopen it in the future.
