### ISSUE TITLE
Not compatible with MegaMaker 1.7

### ISSUE THREAD

**Issue by Jace1313** [krzys-h/UndertaleModTool#364]
Says it in the title. Please update it

**Comment by BenjaminUrquhart** [comment]
There's still quite a bit more work that has to be done to properly support Gamemaker 2.3+ iirc. It should happen eventually, but don't hold your breath.

**Comment by Grossley** [comment]
Probably resolved

**Comment by Grossley** [comment]
Confirmed to be resolved
