### ISSUE TITLE
Searching inside all code files

### ISSUE THREAD

**Issue by Kugge** [krzys-h/UndertaleModTool#366]
Hello ! Sometimes it's hard to find the code that change a certain variable, so I was wondering if there's a way to search inside all UndertaleCodes, it's easier to found interesting code or keywords

**Comment by BenjaminUrquhart** [comment]
You can use the [deltarune script viewer](https://cdn.discordapp.com/attachments/617135933782884368/655578870799663114/undertalemodtool-script-viewer.rar) and replace the `decompiled` folder with your decompilation of Undertale.

**Comment by Kugge** [comment]
> You can use the [deltarune script viewer](https://cdn.discordapp.com/attachments/617135933782884368/655578870799663114/undertalemodtool-script-viewer.rar) and replace the `decompiled` folder with your decompilation of Undertale.

It works ! I'm working on a random game, I've used "ExportCode" script to replace decompiled folder and it works fine.
Thanks.
