### ISSUE TITLE
Issue with a game

### ISSUE THREAD

**Issue by KadeDev** [krzys-h/UndertaleModTool#368]
The game https://benedique.itch.io/chainsaw-dance fails to load.

![image](https://user-images.githubusercontent.com/26305836/105083144-5e87c280-5a49-11eb-8d9d-3a837bd70a6f.png)

**Comment by BenjaminUrquhart** [comment]
This game is using unsupported GMS features. There is a __**read-only**__ of UTMT that you can use to extract sprites and stuff, but you will not be able to make changes to the game. If you wish, I can link it.

**Comment by KadeDev** [comment]
> This game is using unsupported GMS features. There is a ****read-only**** of UTMT that you can use to extract sprites and stuff, but you will not be able to make changes to the game. If you wish, I can link it.

What type of unsupported features? I'm curious.

**Comment by Grossley** [comment]
Animation curves and the like are not supported by UndertaleModTool and will cause this error.

**Comment by KadeDev** [comment]
> Animation curves and the like are not supported by UndertaleModTool and will cause this error.

epic thank you, please alert me when this is fixed.
