### ISSUE TITLE
Sprite causes BSOD

### ISSUE THREAD

**Issue by theEnderBoy785** [krzys-h/UndertaleModTool#370]
Every time I export a sprite, I'm unable to delete its folder. Then I try to delete the directory of that folder, and I always get a BSOD. Help! It's causing a glitch in the NTFS.sys file!

**Comment by piratesephiroth** [comment]
that sounds like a problem with your disk

**Comment by Kneesnap** [comment]
This does not sound like an issue in UTMT to me. Programs are not supposed
to have the ability to cause BSODs, that sounds more like some other issue.

**Comment by Grossley** [comment]
@theEnderBoy785 If this issue still persists, please reopen the issue with a status update. For now, since it sounds like a personal problem with your computer, rather than with the tool, it will be closed.
