### ISSUE TITLE
UndertaleModTool crashes after installing DirectX

### ISSUE THREAD

**Issue by asgore-undertale** [krzys-h/UndertaleModTool#375]
heya,
I am using windows 7, the tool was working perfectly but after installing Microsoft DirectX the tool refuse to open.

**Comment by nkrapivin** [comment]
Hello.
What installer did you use to install/update(???) DirectX?
Can you run other apps that were made with the WPF UI framework? (there are lots of them)

**Comment by fireahmedgamerYT** [comment]
I had an issue like that in the past (while using Windows 7) so at what part does your UTMT crash at? As I remember it used to crash once loading the game.

**Comment by Grossley** [comment]
Not enough information to properly resolve this issue, closing.
