### ISSUE TITLE
Incorrect FONT chunk error when opening data.win file for SONIC.EXE

### ISSUE THREAD

**Issue by EdyDude** [krzys-h/UndertaleModTool#379]
It gave me the “Incorrect padding error” after opening data.win file for Sonic.exe V7.

**Comment by Grossley** [comment]
Please provide a link to the game, I think I dealt with this one before, but there's a lot of Sonic.exe fangames.

**Comment by Grossley** [comment]
I recall this game was bytecode 13 and not supported.

**Comment by EdyDude** [comment]
https://gamejolt.com/games/sonic-exe-the-game/16239

**Comment by colinator27** [comment]
Bytecode 13 is now implemented
