### ISSUE TITLE
Running scripts on Delta Rune's data.win prevents reopening

### ISSUE THREAD

**Issue by a2937** [krzys-h/UndertaleModTool#38]
I tried to add the toggle debug and F3 change room and room info to Delta Rune's data.win but once I did; the file cannot no longer be opened. 

Here is a capture of the error message. 

![capture](https://user-images.githubusercontent.com/9373245/47943364-1a419380-decc-11e8-8a1c-47e7a43bdda3.PNG)

**Comment by krzys-h** [comment]
Wait, I definitely did reopen my modified file multiple times and everything was fine.

Just loaded the data.win, ran DebugToggler and GoToRoom, saved and then reloaded and didn't get this error.

Are you sure you didn't like crash the program while saving or use some other tool that corrupted the paddings? UndertaleModTool is usually a lot strictier in that regard than the others.

**Comment by a2937** [comment]
It's possible the program may have crashed while I was saving, or some extra chucks were corrupted. The game still loads properly.
