### ISSUE TITLE
Unable to open Loop Hero v1.005, bytecodeversion 17

### ISSUE THREAD

**Issue by falcorr** [krzys-h/UndertaleModTool#380]
```
An error occurred while trying to load:
Expected 0 in animation curve point at ...
```

**Comment by Grossley** [comment]
Error in question:
![image](https://user-images.githubusercontent.com/42724744/110196861-2a4f4200-7dfc-11eb-97f5-af62df9d627a.png)

Q: I got this error which says "Expected 0 in animation curve point". 
A: This game uses new unsupported features. There does exist a build of UndertaleModTool which can read these kinds of games, but it is currently read only, and saving will most likely result in the destruction of the data.win file. Here it is: https://cdn.discordapp.com/attachments/569986944394592264/791432705618739230/Debug.rar

**Comment by Grossley** [comment]
Resolved
