### ISSUE TITLE
Request - Add support for resolving external strings for UT and DR 

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#39]
While this is specific to UT and DR, mapping strings to their respective localization is a bit of a pain. It'd be great if it was possible for the decompiler to have the ability to have the strings rather than the reference to the localization file.

There's two real approaches I can see to this.

Make it so the decompiler adds comments with the actual value
Make scripts to swap out the reference with the actual value

**Comment by krzys-h** [comment]
This is already supported for Undertale, the decompiler adds the localized string in a comment. It could be implemented for Deltarune as well, although the data would have to come from an external source unrelated to the data.win you are editing.

Also, somebody already made this as an external tool: https://mini.xkeeper.net/private/deltarune/d.php?f=gml_Script_scr_text.gml

**Comment by krzys-h** [comment]
Actually, it does that only on the UI side so the "batch decompile" option doesn't include that
