### ISSUE TITLE
Load error upon loading a sprite chunk

### ISSUE THREAD

**Issue by TrashBandatcoot** [krzys-h/UndertaleModTool#392]
![image](https://user-images.githubusercontent.com/49070403/111884563-ba77b480-89c2-11eb-86c3-861b121bc1a9.png)

The data.win doesn't open at all. Is there a quick fix for this outside of UTMT for now?

**Comment by Grossley** [comment]
Hello. Can you please send the data.win file so we can analyze what the problem is? Thank you.

**Comment by TrashBandatcoot** [comment]
Sure, but it's a retail game (specifically Antonball Deluxe), so I can't really send it without pirating the game for others.

**Comment by nkrapivin** [comment]
Are you sure this game wasn't made with new GMS2.3.1 or higher? If so, it is not supported by UndertaleModTool.
You may have better luck with the "2.3.1 read only build" in the Underminers Discord server.

**Comment by TrashBandatcoot** [comment]
It might be, I can check later, but an earlier version of the game did work, it just wouldn't save in UTMT.

**Comment by nkrapivin** [comment]
> but an earlier version of the game did work

I asked a person from the Antonball team, the newer version of the game switched to the newest GMS beta *and* YYC due to *reasons.*

I'm sorry.
