### ISSUE TITLE
Error when loading a certain file

### ISSUE THREAD

**Issue by Jace1313** [krzys-h/UndertaleModTool#393]
When I load the Mega Man Maker file in the new version, I get this error:
"An error occurred while trying to load: Expected SEQN version 1 at 009407D4 while reading chunk SEQN"
HOW DO I FIX THIS?

**Comment by Jace1313** [comment]
Like seriously, how do I?

**Comment by nkrapivin** [comment]
Sorry, this game seems to be using new GMS2.3.1 or newer, which is currently not supported by UndertaleModTool.
Because, it's ***Undertale***ModTool.
You can try the "2.3.1 read only build" from the Discord server, but it's read only, it cannot write new 2.3.1 files properly.

**Comment by Grossley** [comment]
Duplicate of #364
