### ISSUE TITLE
Null file in extension editor causes crash

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#394]

**Comment by Grossley** [comment]
https://user-images.githubusercontent.com/42724744/111920359-b8a60380-8a4b-11eb-9bae-408eb3bce20b.mp4

**Comment by Grossley** [comment]
@nkrapivin Please review this when you are able to

**Comment by fireahmedgamerYT** [comment]
Actually, all I done was removing it not opening it...

**Comment by nkrapivin** [comment]
Please look at #396.

**Comment by Grossley** [comment]
Resolved in #396, closing
