### ISSUE TITLE
Loop Hero v1.012 - Failed to find audio group file (UMT v0.3.5.6)

### ISSUE THREAD

**Issue by Jcat4609** [krzys-h/UndertaleModTool#397]
Hey there krzys-h,

I know this isn't a definitive Loop Hero extractor, to immediately set the table. However, the debug build (v0.3.5.6) that we got our hands on worked absolutely divinely for sprites!

There is a bit of an issue with extracting audio, however.
When using the experimental "ExportAllSounds.csx", all of the audio clips end up being extracted as 44bytes, no matter if they're wav or ogg.

The builtin "ExportAllSounds.csx" doesn't actually write any audio files, either.

Finally, attempting to play the sound inside the tool returns a "Failed to find audio group file" which is a bit of a shame.

My apologies for not being able to provide any assistance with the coding side of things.

Thank you deeply for your time, and stay safe.

**Comment by Grossley** [comment]
> attempting to play the sound inside the tool returns a "Failed to find audio group file" which is a bit of a shame

Please make sure the audio group file is in the same directory as the data.win file.

**Comment by Jcat4609** [comment]
I'm absolutely stupid. Thank you a ton Grossley!

Closing due to bug fixed; for any future browsers, please remember to actually put the audiogroup*.dat files with the data.win file.
