### ISSUE TITLE
REQUEST - Add TTFFonts script but for DeltaRune

### ISSUE THREAD

**Issue by Eleiber** [krzys-h/UndertaleModTool#40]
I am trying to do a translation to the spanish, so I need to add some characters like: "´", "¡" and "¿". So I modify a bit the TTFFonts to make it work good with Deltarune, but I don't know how to add the DotumChe font.
![image](https://user-images.githubusercontent.com/13054092/47958309-4b3ec880-df9f-11e8-8c50-22008a9b8843.png)
I already checked and yes, I have the DotumChe.ttf file in my SURVEY_PROGRAM folder, but it just doesn't works, it is the only font that is not working for me for DeltaRune.

**Comment by D3fau4** [comment]
I recommend you better draw them with Photoshop, take less time

**Comment by krzys-h** [comment]
It's going to be a bit more complicated than that because previously I used a terrible hack to force the IDs to be what the game expects and it's not going to work on deltarune because I think I've seen it use font_add_sprite-ext itself. It should be possible to hook into the new translation system to do replacements though.

**Comment by Eleiber** [comment]
But what is the best option? Is it not possible to do with that script? I really would appreciate to know how to that.

**Comment by krzys-h** [comment]
It's not possible to easily do what that script did in Deltarune, it needs to be completly rewritten. @D3fau4 is talking about adding the characters manually, which still works

**Comment by Eleiber** [comment]
> For what it's worth. I applied the TTF script on top of Deltarune and it "works" but the line-height and letter-spacing are messed up. So I assume it's safer to edit the font sprites :\ (see screenshot below)
> ![unknown](https://user-images.githubusercontent.com/1409924/47970070-580dfb80-e035-11e8-8be3-0cb314e68649.png)
> 
> EDIT: nevermind the sizing is messed up too
> ![screen shot 2018-11-04 at 1 31 55 pm](https://user-images.githubusercontent.com/1409924/47970146-39f4cb00-e036-11e8-9b27-f5540600d979.png)

That happened to me, you only have to modify the size of the font in the TTF script.

**Comment by eramdam** [comment]
@Eleiber Ah, neat. I ended up re-creating spritesheets and glyphs map in the meantime 🙈

**Comment by NotedChord** [comment]
wingding.ttf like used in dark world

**Comment by AsrielOver** [comment]
una pregunta me puedes decir como modificar los TTFONTS para añadir la á é í ó ú y la ñ ?

**Comment by LinXP** [comment]
@krzys-h 
https://github.com/krzys-h/UndertaleModTool/blob/5b036f3fba8c265fc8c2ef62283f4a23e1506153/UndertaleModLib/Models/UndertaleFont.cs#L49
signed

**Comment by krzys-h** [comment]
@LinXP yeah, noticed that long ago and forgot to change it. Please make separate issues for things like this, I'll get lost if we keep putting multiple things into one.

`.DisplayName` is in quotes because you are looking at an UndertaleString object representing a STRG entry, to access the value you should do `.DisplayName.Content`

**Comment by colinator27** [comment]
(by the way that "offset" signed int is fixed in #76 now)

**Comment by LinXP** [comment]
@colinator27  uint is still displayed in the editor
http://i.prntscr.com/hpUxapmOQESFpIkL6emr_Q.png

**Comment by colinator27** [comment]
I didn't update any editors, but it's an int, not a short?

**Comment by krzys-h** [comment]
@colinator27 looks like it should be a short then, I guess?

**Comment by colinator27** [comment]
I guess we can assume the list always exists, making it a short...

**Comment by krzys-h** [comment]
Sounds like a good idea

**Comment by LinXP** [comment]
Yep, is short.. after him comes list of kerning

**Comment by Grossley** [comment]
This is currently available from #128, and therefore this issue is fixed. Closing.
