### ISSUE TITLE
Make the room viewer/editor easier to work with.

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#408]
Opening and seeing a room like this
![grafik](https://user-images.githubusercontent.com/38186597/114034036-1e80f080-987e-11eb-9722-098e7959ebad.png)
Is not easy nor fun to work with.

I'd suggest to have a certain fixed zoom, and then offer vertical and horizontal scroll bars in order to navigate in the room.

**Comment by Jacky720** [comment]
The specific issue of zooming was resolved by #717.
