### ISSUE TITLE
REQUEST - Import glyphs from .font.gmx file option

### ISSUE THREAD

**Issue by Eleiber** [krzys-h/UndertaleModTool#42]
Well, I am still trying to do a translation so I need some characters that aren't in the game, so I am modifying every font to ascii from game maker and then trying to replace every old font to the ascii ones, but add every glyph manually is a lot of work, and I see you can see the actually glyphs from the raw code of the .font.gmx file, and it would be good to have an option to do that automatically.

**Comment by krzys-h** [comment]
That would be useful

Also see #20 for CSV import/export scripts, you should be able to get that to work by doing some text replacements on the gmx file.

**Comment by Eleiber** [comment]
I don't know what I did, but using that script and the TTFFonts script now I have a data.win where all the fonts works. 🤔 

Thanks!

**Comment by Kneesnap** [comment]
This should be resolved with https://github.com/krzys-h/UndertaleModTool/issues/20 even if it won't use .gmx
