### ISSUE TITLE
a error while loading sprts of pizza tower april 2021 build

### ISSUE THREAD

**Issue by TheGodLoser** [krzys-h/UndertaleModTool#424]
![uh](https://user-images.githubusercontent.com/82720495/115119437-a2d32200-9fa8-11eb-966e-0f1c9b9df59f.png)
while it was reading the sprts it gave me a error

**Comment by TheGodLoser** [comment]
idk why it did that

**Comment by Grossley** [comment]
Most likely already resolved and comitted, but no release exists of it yet, release will be forthcoming in the future

**Comment by TheGodLoser** [comment]
> Most likely already resolved and comitted, but no release exists of it yet, release will be forthcoming in the future

ok.
