### ISSUE TITLE
add .gml to the game

### ISSUE THREAD

**Issue by D3fau4** [krzys-h/UndertaleModTool#43]
Hello again, I'm here to ask you a question, we need to add some scripts in .gml format to the game (deltarune) right now we are adding it manually but it is very heavy, if you could give us An example of scripts to add it would be appreciated

**Comment by KardchCode** [comment]
I'm working with him, like he said wee need to add scripts and functions, I know there is a manual method but we would like to automatize the process using the same script (.csx). And well if gml code could be implemented as well  in the assembler that will be really awesome, but the main problem is adding new scripts to the game w/o doing manual GUI work

**Comment by krzys-h** [comment]
Adding GML directly would probably require writing a whole compiler - maybe one day, but not any time soon, even the decompiler is not finished yet.

I may add something that creates variable and function references automatically so that you can just copy-paste code from another compiled project though, this should help make it less manual.

**Comment by KardchCode** [comment]
Sorry for asking twice, but is there any way of adding additional code/functions/scripts/strings to the game itself without using the GUI? I revised the code and the SampleScripts but I've seen nothing so I'm probablly missing something.
Anyways thanks for your time in advance @krzys-h !

**Comment by krzys-h** [comment]
There sure is! MixMod is probably the most complete example, although it's quite complex. All of the EnsureDefined things are basically 'add this if it doesn't exist yet'. This is just a quirk of how variables and functions work in GMS. For anything else, just use .Add on the relevant collection.

That reminds me, I have an unreleased sample on my harddrive that adds a room. That should help you a bit, I'll publish it in a moment.

**Comment by KardchCode** [comment]
Omg thank you so much!

**Comment by colinator27** [comment]
I actually just got started writing a GML compiler for this now. I got the lexical analysis stage fully completed now, and am working on parsing the tokens and generating (text) assembly that can be assembled with the existing assembler. It'll probably take a while to complete, but I'm working on it... Thankfully, I'm able to analyze the normal compiler itself to make sure I don't miss anything.

I'll probably put it online once it's done or operable in any form. Like in the first version it may support limited syntax, but I guess we'll see.

**Comment by colinator27** [comment]
By the way it includes the entire list of builtin variables to make life easier, so you are able to use things like `c_red` and access global properties like `view_current`. There's literally a big file (1223 lines long) that set dictionaries for all the different types of builtins and their properties (I didn't write it all on my own, of course, I just used some RegEx magic on the original compiler's code).

**Comment by colinator27** [comment]
So currently, for some example code, I just tested injecting a bit of code generated from my compiler into Deltarune. It only shows a small set of what I've implemented, but I'm happy to see it actually run...

The GML for the code is this:
```
global.currentsong[0] = snd_init("forest.ogg");
i = get_integer("Times to repeat?", 1);
global.currentsong[1] = mus_loop_ext(global.currentsong[0], 0.5, 0.7);
repeat(i)
{
    show_message("Ha!");
}
snd_free_all();
```

The assembly generated is this, which I used the editor to insert to a place in game initialization:
```
push.s "forest.ogg"
conv.s.v
call.i snd_init(argc=1)
pushi.e -5
pushi.e 0
pop.v.v [array]currentsong
pushi.e 1
conv.i.v
push.s "Times to repeat?"
conv.s.v
call.i get_integer(argc=2)
pop.v.v self.i
push.d 0.7
conv.d.v
push.d 0.5
conv.d.v
pushi.e -5
pushi.e 0
push.v [array]currentsong
call.i mus_loop_ext(argc=3)
pushi.e -5
pushi.e 1
pop.v.v [array]currentsong
push.v self.i
conv.v.i
dup.i 0
push.i 0
cmp.i.i LTE
bt l_1
l_0: push.s "Ha!"
conv.s.v
call.i show_message(argc=1)
popz.v
push.i 1
sub.i.i
dup.i 0
conv.i.b
bt l_0
l_1: popz.i
call.i snd_free_all(argc=0)
popz.v
```

Not sure if I should begin actually tracking it/pushing it yet. Mainly it's currently lacking a few loops/statements (switch and do...while), and incrementing/decrementing (`++`/`--`). I may be missing something else though.

**Comment by colinator27** [comment]
I've been pretty busy lately, but for whenever I find the time to integrate this into the UI (I have it coded in the backend right now): how should code be modified and recompiled back to assembly? Should there be some separate window that opens, or should you be able to modify the code directly from the `Decompiled` tab? The only problem with that is making sure the decompiled code complies with GML syntax completely.

**Comment by colinator27** [comment]
Compiler is now almost completely stable and integrated in this fork: https://github.com/Kneesnap/UndertaleModTool

If you want to try it out, you can use that for now. Do note that some obscure-ish bugs are still being spotted and fixed as of right now.

**Comment by Kneesnap** [comment]
Resolved?
