### ISSUE TITLE
Reading beyond end of stream

### ISSUE THREAD

**Issue by AceKiron** [krzys-h/UndertaleModTool#437]
![image](https://user-images.githubusercontent.com/39498818/116701536-4ddfd480-a9c8-11eb-86f8-833154ad6b0c.png)
It happened while trying to open the data.win file of a GameMaker Studio 2 demo project

**Comment by Grossley** [comment]
Can you provide a link to the demo please?

**Comment by BenjaminUrquhart** [comment]
This sample opens just fine with the master branch, so likely the problem has already been resolved.

**Comment by AceKiron** [comment]
Looking at the commits history of this repo, I see now that that might be true.
But could any of you please add it to [the releases](https://github.com/krzys-h/UndertaleModTool/releases)? I don't have enough storage to install Visual Studio

**Comment by Grossley** [comment]
An official release will happen in the future when all of the features we have been designing are ready

**Comment by AceKiron** [comment]
Could you just build it and set it to me then? I don't have enough storage to install whole Visual Studio :/

**Comment by Grossley** [comment]
> Could you just build it and send it to me then? I don't have enough storage to install whole Visual Studio :/

Please refer to the previous comment. A new release will occur (UndertaleModTool 0.3.5.9+) when it is ready. Closing 

Link to previous comment: https://github.com/krzys-h/UndertaleModTool/issues/437#issuecomment-830287679
