### ISSUE TITLE
exported png files are a litil bit mesed up

### ISSUE THREAD

**Issue by MichaelHinrichs** [krzys-h/UndertaleModTool#44]
some sprite's edges (usualy the ones farthest in the 4 cardnal directions) will be... extended, I guess? this can result in a lot of black boxes surrounding the sprites.

**Comment by krzys-h** [comment]
Could you give me an example of a sprite where this happens?

**Comment by MichaelHinrichs** [comment]
Were DOESN'T it happen? Nearly every sprite is affected. here are some examples.
![undertale fuckups](https://user-images.githubusercontent.com/37460517/48665329-1be58c80-ea72-11e8-935a-1a88af995fd9.png)

**Comment by colinator27** [comment]
That's how GameMaker texture pages are generated. There's nothing wrong with it.

**Comment by krzys-h** [comment]
Yeah, I thought you are saying #29 is back. The whole texture sheet is supposed to have these, it's how GMS generates it and the tool is just exporting it as it is. If you use the actual sprite exporter, it cuts out only the part it's supposed to take, and the game does the same.
