### ISSUE TITLE
"&" and "|" replace "&&" and "||" in < bytecode 14 games, causing Import GML to fail

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#447]
![image](https://user-images.githubusercontent.com/42724744/117763242-5792e480-b1df-11eb-8f73-4fce08eee72f.png)

**Comment by Grossley** [comment]
This decompilation is most likely invalid as these would indicate these are bitwise operations, which is not the case in this game: http://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/401_04_expressions.html

**Comment by Grossley** [comment]
A code with this issue: gml_Object_Eggman_Step_0

**Comment by Grossley** [comment]
It's actually this game, not the other one: https://gamejolt.com/games/NBR_UIM/516580

**Comment by colinator27** [comment]
Fixed in https://github.com/krzys-h/UndertaleModTool/commit/f37ac05c7fc91ee5064b4d197e9942125ec0bc11
