### ISSUE TITLE
Include Nuget package in UTMT source to streamline compilation process

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#448]
I have been told that, when compiling, it is always needed to open the MainWindow.xaml first, wait for the invalid checkmark to appear, and then click Start so that it can finally be compiled. If the user clicks Start or Build without open that file, the compile will fail most of the time.

**Comment by Archie-osu** [comment]
Also never had this issue, building both the master and dark-mode branch works without even opening any file inside the solution.

**Comment by Miepee** [comment]
@ClickNinYT are you still having this issue?

**Comment by Grossley** [comment]
Not enough information to resolve this issue, closing.
