### ISSUE TITLE
Version for other platforms possible?

### ISSUE THREAD

**Issue by Boundarybreaker** [krzys-h/UndertaleModTool#45]
According to GitHub, this repo is 100% C#. That means that it'll only really work for Windows, and not for Mac or Linux. I know systems like MonoDevelop let you use C# multi-platform, but it'd still have trouble finding the files to decompile a GameMaker game from, yeah? Is it at all feasible to have UMT versions for other OSes or not?

**Comment by krzys-h** [comment]
See #5. Basically, UnderaleModTool started as my toy project to learn WPF which is a Windows framework not implemented in mono, I never expected it would grow to something that's actually quite usable, I would have probably chosen something else if I knew that. You should be able to get the core data.win reading/writing library (UndertaleModLib) to work just fine, but the whole UI would need to be rewritten.

On Linux you can get it to work using wine (see my comment in #5), no idea about Macs.

**Comment by krzys-h** [comment]
Also, note that UndertaleModTool can edit files for all platforms, just the tool itself won't run on them.

**Comment by CrackedP0t** [comment]
It was crashing for me when running in Wine - something to do with hardware acceleration. I fixed it by setting the registry value `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Avalon.Graphics\DisableHWAcceleration` to `1` as per https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings#disablehardwareacceleration .

**Comment by Grossley** [comment]
It is my understanding that this is a goal planned for the future.

**Comment by Grossley** [comment]
Since this is addressed as a future goal in #182 will this be closed?

**Comment by Kneesnap** [comment]
Yes.
