### ISSUE TITLE
REQUEST: Show ID for selected asset

### ISSUE THREAD

**Issue by JillCrungus** [krzys-h/UndertaleModTool#46]
It'd be great if we could actually see the numerical ID of assets (rooms, objects, etc.) when we have them selected to make it easier to search through the game's ridiculous object check scripts and such.

As far as I can tell the only way right now is manually counting which obviously not ideal.

**Comment by krzys-h** [comment]
It's been on a list of things I really need to add for a while.

Another option is something along the lines of `Data.Rooms.IndexOf(Selected as UndertaleRoom)` in the command window at the bottom (which is how I survived delaying it for so long :P)

**Comment by JillCrungus** [comment]
Man, I hadn't even NOTICED that you could type in that box.

**Comment by colinator27** [comment]
Wait, since when was that editable!?

**Comment by krzys-h** [comment]
@colinator27 since the first version ever :stuck_out_tongue:

Yeah, I know it's non-obvious and not documented in any way, I used it to test scripting early in development and ended up using it a lot more often than expected

**Comment by Kneesnap** [comment]
Implemented in https://github.com/krzys-h/UndertaleModTool/commit/e288f79ec4c39fed07485acc81295e1bbb37fcfd
