### ISSUE TITLE
Unable to decompile data.win

### ISSUE THREAD

**Issue by hungthitkhia** [krzys-h/UndertaleModTool#461]
When i open the data.win, this happened:
![image](https://user-images.githubusercontent.com/72916534/119814383-88c82000-bf14-11eb-8aa6-233b9a602e91.png)
What is wrong here?
Here is the link to the data.win: https://drive.google.com/file/d/1gtsVvCq3mCguNA66nFxeinZrI0TgdJdC/view?usp=sharing

**Comment by Archie-osu** [comment]
From the error message, it seems like the first 4 bytes of the data.win aren't 'FORM'. This most likely indicates a corrupted data.win file. Maybe try redownloading the game?

I'm not able to look at it right now, so wait for someone smarter than me.

**Comment by fireahmedgamerYT** [comment]
> From the error message, it seems like the first 4 bytes of the data.win aren't 'FORM'. This most likely indicates a corrupted data.win file. Maybe try redownloading the game?
> 
> I'm not able to look at it right now, so wait for someone smarter than me.

I agree, gonna see the data.win.

**Comment by fireahmedgamerYT** [comment]
The chunk FORM doesn't exist
I even tried running it using executable it didn't work. It crashed.

**Comment by Mc-muffin** [comment]
Please close this issue, the "data.win" isn't valid because it isn't a data.win and OP has been trolled.
The file is actually a video, change the extension to .wmv and prepare to get rickrolled, as such, this issue is invalid.
