### ISSUE TITLE
UndertaleModTool cannot load and save an unmodified copy of "Death's Gambit v1.2"

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#467]
The problem seems to be in "room_darknessfalls_extra" (room 338) which has a massive amount of null instances in "Compatibility_Instances_Depth_0". This makes me believe that the tool is having trouble actually loading the room properly since this data is unexpected and obviously wrong. 
![image](https://user-images.githubusercontent.com/42724744/120902329-9fe1ce80-c5f4-11eb-8320-aca4c641c9eb.png)

**Comment by Miepee** [comment]
@JohnnyonFlame can you retest please if this has been fixed?

**Comment by JohnnyonFlame** [comment]
@Miepee File now saves successfully, testing it required `git checkout 7094c547 -- UndertaleModLib/UndertaleChunks.cs` since breakage from a73a3a8d is still present.

**Comment by Miepee** [comment]
But since that's a duplicate of #833, this can be closed, right?

**Comment by JohnnyonFlame** [comment]
Guess so.
