### ISSUE TITLE
fix pizza tower april 2021 saving error

### ISSUE THREAD

**Issue by TheGodLoser** [krzys-h/UndertaleModTool#469]
while you save it auto gives you error please fix this
save error:
object reference not set to an instance of an object.
at 0139C304
(im using pre 0.4.0.0)
is it becuase chunk room or chunk form??
(also there is no screenshot)

**Comment by Miepee** [comment]
@TheGodLoser is this still an issue with action builds?

**Comment by Jacky720** [comment]
There is no way this is still an issue, there are people modding Pizza Tower right now having completely different issues.
