### ISSUE TITLE
fix for GEN8

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#47]
https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L45
Scale = 0x0010, // Scaling: Keep aspect
and new flags: DefaultCodeKind = 0x8000, LicenseExclusions = 0x10000

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L81-L82
time64_t DateTime   (8 bytes)
Example: 
hex: AA 3B E4 5B 00 00 00 00
string: 11/08/2018 13:35:38

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L84
uint ActiveTargets1

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L85
uint ActiveTargets2

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L86
uint FunctionClassifications1

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L87
uint FunctionClassifications2

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L88
int SteamAppId; // negative value

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L93
float GameSpeed

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L94
uint AllowStatistics; // Allow anonymouse statistics

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L95
byte GameGUID  // 16bytes  
Example:
HEX: 67 45 34 12 90 78 22 11 33 44 55 66 77 88 99 00
String: 12344567-7890-1122-3344-556677889900

**Comment by LinXP** [comment]
to colinator27, Can you write templates for 010 Editor? I can share my draft and finish it together.

**Comment by krzys-h** [comment]
@colinator27 I'll leave adding these for you then ;)

@LinXP I had a simple one for Hexinator when I was starting work on the tool. Getting everything to work correctly is going to be quite a bit of work though, especially for code where the entry length depends on some conditions, and chunks that have no entry count.
