### ISSUE TITLE
Playing a sound from the sounds menu crashes the program.

### ISSUE THREAD

**Issue by DrEngineer1** [krzys-h/UndertaleModTool#475]
There is no crash log or error, it just crashes with no error like nothing ever happened.

**Comment by BenjaminUrquhart** [comment]
Fixed in [bf1905b](https://github.com/krzys-h/UndertaleModTool/commit/bf1905b9e3bf9fee618ab386fa4a6a15b0fcc416)

**Comment by colinator27** [comment]
Yeah, that's been fixed since the release. If you want to get the fix immediately you can use the current latest version, which was automatically built here (downloads at the bottom of the page): https://github.com/krzys-h/UndertaleModTool/actions/runs/962168062
