### ISSUE TITLE
fix for OPTN

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#48]
https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L216
uint MinValue;   // 2147483648 (Constant)

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L217
uint UnknownTwo;  // 2 (Constant)

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L218
int64 OptionsFlag  (8bytes)

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L220
Scale

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L221
WindowColour

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L222
ColorDepth

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L223
Resolution

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L224
Frequency

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L225
Sync_Vertex

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L226
Priority

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L227
SplashBackImage

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L228
SplashFrontImage

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L229
SplashLoadImage

https://github.com/krzys-h/UndertaleModTool/blob/aa97bb3be3b6e3a47e475a28a7ab2fcb6f52392d/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L230
LoadAlpha

**Comment by krzys-h** [comment]
These were already added in #62
