### ISSUE TITLE
Cant save edited code

### ISSUE THREAD

**Issue by LinkZeldasGuard** [krzys-h/UndertaleModTool#480]
Im modding Undertale, everything works fine except, (I want to make an own translation into german) when I go in the code section and then in the Script-Text to edit the Textboxes, i can change the text but when i press on "Decompiled" it just resets to the original text. When I dont compile and just press on File -> Save it saves, I put the saved data.win in my Undertale files but when I go in the game or just re-open the data.win, everything is reset. Thats it.

**Comment by BenjaminUrquhart** [comment]
Make sure you’re actually editing the strings and not the comments next to `scr_gettext`

**Comment by LinkZeldasGuard** [comment]
Sorry if i seem dumb, thats because I am, this is my first time modding with UMT... But, what are "Comments"? (I know what the word comments means, but not what is defined with it in UMT)

**Comment by Jacky720** [comment]
In code, comments are parts of the code that the program completely ignores. They are commonly used to document what different parts of the code do without directly affecting it. In the latest version of Undertale (and UndertaleModTool), most dialogue appears like so:
`global.msg[0] = scr_gettext("SCR_TEXT_291") // \W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/`

Everything after the `//` is a comment. It is only generated by the UMT decompiler for convenience, as the real code (`global.msg[0] = scr_gettext("SCR_TEXT_291")`) is not especially readable. Therefore, **editing the string as it appears here will not work.**

There are three solutions.

1. Edit the `textdata_en` script instead, which contains the real strings, e.g:
`ds_map_add(global.text_data_en, "SCR_TEXT_291", "\W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/")`
2. Remove the `scr_gettext` invocation:
`global.msg[0] = "* Your message here!/"`
3. Go back to an older version of Undertale, without Japanese localization (1.001 code depicted):
`global.msg[0] = "\W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/"`

After that, recompile the code by clicking outside of the editable box, then save the data.win.

**Comment by LinkZeldasGuard** [comment]
> 
> 
> In code, comments are parts of the code that the program completely ignores. They are commonly used to document what different parts of the code do without directly affecting it. In the latest version of Undertale (and UndertaleModTool), most dialogue appears like so:
> `global.msg[0] = scr_gettext("SCR_TEXT_291") // \W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/`
> 
> Everything after the `//` is a comment. It is only generated by the UMT decompiler for convenience, as the real code (`global.msg[0] = scr_gettext("SCR_TEXT_291")`) is not especially readable. Therefore, **editing the string as it appears here will not work.**
> 
> There are three solutions.
> 
>     1. Edit the `textdata_en` script instead, which contains the real strings, e.g:
>        `ds_map_add(global.text_data_en, "SCR_TEXT_291", "\W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/")`
> 
>     2. Remove the `scr_gettext` invocation:
>        `global.msg[0] = "* Your message here!/"`
> 
>     3. Go back to an older version of Undertale, without Japanese localization (1.001 code depicted):
>        `global.msg[0] = "\W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/"`
> 
> 
> After that, recompile the code by clicking outside of the editable box, then save the data.win.

Sank Yoo :3 Thats it. I used a reference tutorial that was from older versions so it didnt work now. Thanks for your help!
