### ISSUE TITLE
How do I open .exe files?

### ISSUE THREAD

**Issue by SirCub** [krzys-h/UndertaleModTool#484]
someone by the name of ReinLynxPSI was able to open his game: Supra Smash Bross Mayday, which was an .exe file and not a data.win with UMT. Is this a dev thing or can you open .exe files in some way? I can tell he used the exe file because while making Version 8 his computer broke, therefore losing all of the files for it.

**Comment by Grossley** [comment]
Please provide a link to the game in question

**Comment by SirCub** [comment]
> Please provide a link to the game in question

Here's the link, the version in question is "Supra Smash Bross- Legacy Edition" https://gamejolt.com/games/SmashBross/32144

**Comment by Grossley** [comment]
I downloaded this version 
![image](https://user-images.githubusercontent.com/42724744/125504276-8eb93afd-c689-4541-a66c-ad75a3a9d629.png)
and it appears as if this EXE is a self-extracting executable. This means it is basically a ZIP file with all of the game's contents in it, including data.win, music, the real EXE file, and other assets. After extracting the contents using 7zip or another archive program like WinRAR it can then be opened and modified in UndertaleModTool.

**Comment by SirCub** [comment]
> I downloaded this version
> ![image](https://user-images.githubusercontent.com/42724744/125504276-8eb93afd-c689-4541-a66c-ad75a3a9d629.png)
> and it appears as if this EXE is a self-extracting executable. This means it is basically a ZIP file with all of the game's contents in it, including data.win, music, the real EXE file, and other assets. After extracting the contents using 7zip or another archive program like WinRAR it can then be opened and modified in UndertaleModTool.

Hm, that's strange. The last time I played this version, I'm pretty sure it was an exe file. Thanks for the help!

**Comment by Grossley** [comment]
It is an EXE file, but if you rename it to a ZIP file you can extract its contents like a ZIP file. Glad I could help you out!

**Comment by OPkokakola** [comment]
and if the .exe seems to be unpacked, but there is no data.win, but there is only .data .enigma1 .enigma2 .mydata, etc.

**Comment by Jacky720** [comment]
In that case, you should check that the game was made with GameMaker: Studio, and try UTMT's "ExtractEmbeddedDataFile" script.

**Comment by OPkokakola** [comment]
> In that case, you should check that the game was made with GameMaker: Studio, and try UTMT's "ExtractEmbeddedDataFile" script.

Thanks, it worked, but how do I then save the modified data.win file so that it works as a whole again
