### ISSUE TITLE
Hangs when loading into the code editor on long scripts

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#49]
Whenever I try to load into the editor on a long script, the program hangs like mad.

**Comment by krzys-h** [comment]
I know, it's because of all the syntax highlighting, WPF doesn't seem to handle that too well. There is a threshold above which it's disabled automatically, I could try lowering it

**Comment by NarryG** [comment]
Well it's not even the overview. It's when I actually go into edit mode. The syntax highlighting is disabled on the script in question (obj_readable_room1) but it takes like five minutes to load in.

**Comment by krzys-h** [comment]
I just read that setting `TextWrapping="NoWrap"` can give a huge performance boost, and we don't need text wrap anyway. Might be worth a try.

**Comment by krzys-h** [comment]
I just read that setting `TextWrapping="NoWrap"` can give a huge performance boost, and we don't need text wrap anyway. Might be worth a try.

**Comment by krzys-h** [comment]
Well, It's slow, but it's not taking 5 minutes for me, more like 5 seconds. I think that's unavoidable with large scripts. Do you have any script that really takes that long?

**Comment by Grossley** [comment]
I believe this has been resolved with the newer UndertaleModTool updates. Can it be confirmed whether this issue can be closed?

**Comment by Kneesnap** [comment]
Confirmed. Closed.
