### ISSUE TITLE
Error in scripts 'ExportFontData.csx' and 'ImportFontData.csx'

### ISSUE THREAD

**Issue by SileNTViP** [krzys-h/UndertaleModTool#494]
After script 'ExportFontData.csx' using script 'ImportFontData.csx' cause error with 'length' error in string 59: string spriteName = stripped.Substring(0, lastUnderscore);
because char '_' not found in export data.

**Comment by Miepee** [comment]
Bumping this because I've seen it happen multiple times lately.

**Comment by Archie-osu** [comment]
Isn't this due to bad naming?

**Comment by Miepee** [comment]
Not sure, I didn't look much into the scripts. I just know that there were a lot of people in the server which reported the issue lately.

**Comment by SileNTViP** [comment]
Error into this lines:
>            int lastUnderscore = stripped.LastIndexOf('_');
>            string spriteName = stripped.Substring(0, lastUnderscore);

my changes in script:
>            texturePageItem.TexturePage = texture;
>            Data.TexturePageItems.Add(texturePageItem);
>            string spriteName = Path.GetFileNameWithoutExtension(n.Texture.Source);
>
>            UndertaleFont font = null;
>            font = Data.Fonts.ByName(spriteName);
>
>            if(font == null)
>            {
>                UndertaleString fontUTString = Data.Strings.MakeString(spriteName);
>                UndertaleFont newFont = new UndertaleFont();
>                newFont.Name = fontUTString;`

**Comment by Miepee** [comment]
Or in a proper patch format:
```diff
            texturePageItem.TexturePage = texture;
            Data.TexturePageItems.Add(texturePageItem);
-           string stripped = Path.GetFileNameWithoutExtension(n.Texture.Source);
-           int lastUnderscore = stripped.LastIndexOf('_');
-           string spriteName = stripped.Substring(0, lastUnderscore);
+           string spriteName = Path.GetFileNameWithoutExtension(n.Texture.Source);

            UndertaleFont font = null;
            font = Data.Fonts.ByName(stripped);

**Comment by SileNTViP** [comment]
> Or in a proper patch format:
> 
> ```diff
>             texturePageItem.TexturePage = texture;
>             Data.TexturePageItems.Add(texturePageItem);
> -           string stripped = Path.GetFileNameWithoutExtension(n.Texture.Source);
> -           int lastUnderscore = stripped.LastIndexOf('_');
> -           string spriteName = stripped.Substring(0, lastUnderscore);
> +           string spriteName = Path.GetFileNameWithoutExtension(n.Texture.Source);
> 
>             UndertaleFont font = null;
>             font = Data.Fonts.ByName(stripped); 
> ```
> 
> That said tho, i'm not exactly sure why the script searched for an underscore in the first place. Does it break anything if that's removed?

You remove "string stripped" from script. But in script "stripped" used in lines:
> font = Data.Fonts.ByName(stripped);
> UndertaleString fontUTString = Data.Strings.MakeString(stripped);
