### ISSUE TITLE
0.4.0-pre3: ExportAllSpritesWithPadding.csx not found

### ISSUE THREAD

**Issue by gurgalex** [krzys-h/UndertaleModTool#496]
scripts -> Unpack Assets -> ExportAllSprites.csx.
Select "No" for "Export all sprites unpadded?"

This error occurs
![image](https://user-images.githubusercontent.com/28968644/126880106-b0904d43-ff92-4975-975a-8a1b2b7f4e3a.png)

The `HelperScript` folder isn't present
![image](https://user-images.githubusercontent.com/28968644/126880154-202a9788-fab3-4f48-b390-21c0a2530a92.png)

It is present in the extracted zip
![image](https://user-images.githubusercontent.com/28968644/126880215-7e01b2cf-9883-4407-80a7-13be7754ac32.png)

**Comment by Grossley** [comment]
Please extract UndertaleModTool from the archive before running it, it will not function properly if you do not do that.

**Comment by Grossley** [comment]
This is not the cause of this issue.
