### ISSUE TITLE
Two questions.

### ISSUE THREAD

**Issue by GachaBoi** [krzys-h/UndertaleModTool#50]
1.I would love to edit Kris' sprite to look like me,but I've only gotten as far as to export the sprite. Every time I edit the sprite,it doesn't allow me to save it. I've tried Paint and Paint 3D.

2.In order to truly put myself in the game,I would have to Kris' name to my name. I've tried looking through the "scripts" section,but I can't seem to find what I'm looking for.(I also kinda wanna make Ralsei a girl,lol.)

Any help on either of these questions would be great. Thanks :)

**Comment by colinator27** [comment]
To answer your first question, editing the sprite file and not re-importing won't do anything. 

The easiest way is to edit the embedded texture itself, and you can easily import/export that. However, MS Paint does not support transparency so I would recommend something else.

Not exactly necessary, but the way to arbitrarily add new sprites is a bit harder I believe. You need to probably create a new texture page by making a new embedded texture, importing the texture PNG you made (make sure the dimensions are a power of two, like 256x256 or 1024x1024), and then make a texture entry which points to your updated sprite on the embedded texture. Though you could put them all on one texture and make texture entries for each image on it (which are referred to by the sprites).

**Comment by krzys-h** [comment]
The problem with direct editing of sprites is the transparency-removing magic that GMS2 does and even the possibility that the sprite is scaled in relation to what is actually stored in the big sprite sheet. I could not think of any good way to handle these issues without some crappy workarounds so I made the sprites export-only for now, you need to edit the sheets manually if you want to change them.

**Comment by GachaBoi** [comment]
> The problem with direct editing of sprites is the transparency-removing magic that GMS2 does and even the possibility that the sprite is scaled in relation to what is actually stored in the big sprite sheet. I could not think of any good way to handle these issues without some crappy workarounds so I made the sprites export-only for now, you need to edit the sheets manually if you want to change them.

Thanks for the reply! Could you explain how to edit the sheets?

**Comment by colinator27** [comment]
Each sprite has a list of texture entries (viewable and navigable in the editor), and you can use those to figure out where the frames are for them. If I remember correctly, it should make the sprite appear in full alpha while the rest of the page appears mostly transparent?

**Comment by krzys-h** [comment]
Exactly, go to the sprite, double click the `(TexturePageItem)` in the Textures list and it will open a page with the selected fragment highlighted. You can also read out the exact X/Y coordinates at the top. To find the actual spritesheet file from here, just double click on `(EmbeddedTexture)`
