### ISSUE TITLE
How to import font files edited in gamemaker studio 2 into the undertale mod tool?

### ISSUE THREAD

**Issue by AnXing233** [krzys-h/UndertaleModTool#501]
I edited some font files in gamemaker studio 2, but there is a PNG file and a .yy file in the "fonts" folder in the source folder.

How do I import fonts in undertalemodtool? 

If there are related script files, thank you so much! =）(I don't know how to edit the script.)

**Comment by Grossley** [comment]
Compile the game in GameMaker Studio 2 and then copy the font from the game you built into your original game.

**Comment by AnXing233** [comment]
Do I need to decompile it into a GMS2 project?
 How to do it?

**Comment by Grossley** [comment]
Compile the game and then use the copy font script to copy the font into the game data file using UndertaleModTool

**Comment by AnXing233** [comment]
Font script? which one?

**Comment by Grossley** [comment]
I recommend you join the Discord server so we can discuss your issue in real time with other people who do this sort of task all the time

https://discord.gg/RxXpdwJ

**Comment by AnXing233** [comment]
it's joined.
