### ISSUE TITLE
Lack of CTRL+Z memory

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#505]
The moment you click outside the code window and your changes get saved, you can't undo them with CTRL + Z anymore. UMT should be able to remember changes in some sort of change cache.

**Comment by colinator27** [comment]
Undo stack is now properly managed when compiling code and assembling by https://github.com/krzys-h/UndertaleModTool/commit/c616441a720ff26a0b0da55c40f7d3a82e2ad9fe
