### ISSUE TITLE
EnableDebug doesn't do anything

### ISSUE THREAD

**Issue by DrRainbowCreeper** [krzys-h/UndertaleModTool#509]
I ran EnableDebug cause- well, you know why. But for me, it did absolutely nothing. Yes, i am sure that the steam API file is gone, what am i doing wrong/ could i be doing wrong? I really want to enable debug!

**Comment by Archie-osu** [comment]
Did you save the data file?

**Comment by DrRainbowCreeper** [comment]
Oop thx

**Comment by DrRainbowCreeper** [comment]
> Did you save the data file?

Oop thx

**Comment by Archie-osu** [comment]
Please close the issue if you solved it, so we don't clog these up :wink:
