### ISSUE TITLE
GML inline array literal doesn't decompile correctly

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#51]
This isn't a major concern right now, but this can be fixed eventually.

What I'm referring to is something like this:
```
abc = [1, 2, 3, 4, 5];
```
This is a new syntactical sugar introduced in GMS2 I believe, though it may have been added to older versions like gml_pragma was.

What this converts to is a strange function call to `@@NewGMLArray@@`. It's some internal function that does what its name says. Specifically, it creates an array given its arguments as values. The bytecode for that example would be this:
```
00000: pushi.e 5
00001: conv.i.v
00002: pushi.e 4
00003: conv.i.v
00004: pushi.e 3
00005: conv.i.v
00006: pushi.e 2
00007: conv.i.v
00008: pushi.e 1
00009: conv.i.v
00010: call.i @@NewGMLArray@@(argc=5)
00012: pop.v.v self.abc
```

The decompiler currently thinks that it is
```
self.abc = (1, 2, 3, 4, 5)
```
...which is pretty close, just with parentheses instead of brackets. However, the editor allows you to click on the space before the "array literal" and that crashes it.

**Comment by krzys-h** [comment]
It's probably just the syntax highlighter trying to interpret "stringname"@stringid as a clickable thing
