### ISSUE TITLE
Add "Compile" GUI button to code editor UI

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#517]
Title

**Comment by Archie-osu** [comment]
Didn't it already auto-compile it?

**Comment by Grossley** [comment]
> Doesn't it already auto-compile it?

This is for user's sake, who may not intuit that CTRL+K or switching to a different asset already compiles the code. Often people edit the code and immediately save and run it without actually compiling it. This button should resolve said issue @Archie-osu

**Comment by Archie-osu** [comment]
I see - though I don't see the issue for a separate button - why not recompile all modified code entries on save? Would do away with an extra button (you could pop up a message box like "hey, you have unsaved code entries; do you wanna save them?") and prevent people from forgetting to click it.
