### ISSUE TITLE
dup.l 0 sometimes appears instead of dup.i 1

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#52]
This is some magic optimization that abuses the way the GMS runner stores the stack, it duplicates one 64-bit value instead of two 32-bit ones. This causes decompilation problems because we use the C# Stack<> which is obviously implemented differently.

Doesn't seem to happen in neither Undertale or Deltarune, discovered by @colinator27 in some other game, see https://github.com/krzys-h/UndertaleModTool/issues/27#issuecomment-435694723

**Comment by colinator27** [comment]
Also, perhaps the decompiler can simply translate `dup.l 0` into `dup.i 1`, because I believe they're functionally equivalent?

**Comment by colinator27** [comment]
Finally introduced a fix for this on my local code, and it works just fine! Just multiplies the number of iterations on the dup instruction by 2 if the type is Int64, to also account for dup.l 1 in case that exists or something.
