### ISSUE TITLE
An error occurred while trying to load: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by QuantumNoisemaker** [krzys-h/UndertaleModTool#520]
Was messing around with trying to extract a non-deltarune/undertale game, and ran into this issue. Assuming the file was too large: file size 2,444,982 kb.

**Comment by Archie-osu** [comment]
What is the game name?

**Comment by QuantumNoisemaker** [comment]
[Secret Care Cafe](https://rarealexturan.itch.io/secretcarecafe/devlog/284216/secret-care-cafe-063-release-notes-and-downloads) - heads up, has a nsfw mode

**Comment by Archie-osu** [comment]
I'll look at it (for research on why UMT fails to open it) when I get from work, in about an hour.

**Comment by QuantumNoisemaker** [comment]
Sounds good, thanks for looking into it.

**Comment by Archie-osu** [comment]
So to update, we found the issue, but fixing it will take some time, as you hit a CRT limitation 😅

**Comment by QuantumNoisemaker** [comment]
Dang, was hoping the limit I was hitting wasn't too deep in the architecture, Gotta love finding edge cases. And what does CRT mean in this context? C runtime?

**Comment by Archie-osu** [comment]
> 
> 
> Dang, was hoping the limit I was hitting wasn't too deep in the architecture. Gotta love finding edge cases. And what does CRT mean in this context? C runtime?

The C runtime, yes. It can only support arrays of 2147483647 elements at max (which is true even with ``operator new`` in languages such as C++, though you can just ``malloc`` there). In C#, there is no way to work around this beside splitting the data.win into multiple arrays, which would require a lot of work as far as I know.

**Comment by cyrix22** [comment]
Good thing i searched before posting. Came across the same problem and i hope its fixable, maybe not immediately but i'm hoping its not impossible.

**Comment by QuantumNoisemaker** [comment]
> > Dang, was hoping the limit I was hitting wasn't too deep in the architecture. Gotta love finding edge cases. And what does CRT mean in this context? C runtime?
> 
> The C runtime, yes. It can only support arrays of 2147483647 elements at max (which is true even with `operator new` in languages such as C++, though you can just `malloc` there). In C#, there is no way to work around this beside splitting the data.win into multiple arrays, which would require a lot of work as far as I know.

Thanks for the additional context! To clarify, is the limit with the total array size being larger than 2 GB, or with the elements in the array exceeding 4,294,967,295? I ask because I've read through a few [threads](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/92dca591-ca23-4ca0-b77d-748d4b337d8c/the-size-of-the-array-exceeds-the-limits-addressing?forum=csharpgeneral) where this error message pops up in regards to the former (exceeding 2 GB) and not the latter (exceeding the total number of elements).

If it is the case that the error is caused by the array exceeding 2 GB, then the fix could be very simple; just enable [setgcAllowVeryLargeObjects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element) in the runtime config. Only caveat is if the program uses any unsafe code that assumes arrays will always be less than 2 GB in size (see the warning on the setgcAllowVeryLargeObjects page, the famed buffer overrun could rear its head here). 

To note: I used 4,294,967,295 instead of 2147483647 above because, according to the [documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element), [UInt32.MaxValue](https://docs.microsoft.com/en-us/dotnet/api/system.uint32.maxvalue?view=net-5.0) and not Int32.MaxValue is the maximum number of elements in an array.

**Comment by Archie-osu** [comment]
I tried that flag on my own fork, but it doesn't work.
Hidden in the "Remarks" section is a reason why: 
> The maximum size in any single dimension is 2,147,483,591 (0x7FFFFFC7) for byte arrays and arrays of single-byte structures, and 2,146,435,071 (0X7FEFFFFF) for arrays containing other types.

UMT stores the data file as bytes, not as a larger type, which would allow storing more data per array element.

**Comment by QuantumNoisemaker** [comment]
> I tried that flag on my own fork, but it doesn't work.
> Hidden in the "Remarks" section is a reason why:
> 
> > The maximum size in any single dimension is 2,147,483,591 (0x7FFFFFC7) for byte arrays and arrays of single-byte structures, and 2,146,435,071 (0X7FEFFFFF) for arrays containing other types.
> 
> UMT stores the data file as bytes, not as a larger type, which would allow storing more data per array element.

Dang, so it wasn't the total array size or the standard element limit, but the byte array limit. That's quite a pain. Thanks for looking into it and going into the specifics. Out of curiosity, what part of the project handles this process (assuming Decompiler.cs, but could be wrong). If I have some free time I may make a fork and see if I can replace the array with a database without bricking everything (obviously much easier said than done).

**Comment by Archie-osu** [comment]
Should be a memory allocation somewhere at the very heart of the tool, the decompiler and other modules just use the ``Data`` variable.

Last time I look I remember it being something like UndertaleCode.cs, or maybe the window code for clicking on "File -> Open".
