### ISSUE TITLE
Default Application

### ISSUE THREAD

**Issue by SaySayTakamura** [krzys-h/UndertaleModTool#523]
Hello, sorry for bothering but, how do i remove the app as default application (now all my .win files are marked to open with it)

**Comment by Jacky720** [comment]
Does [this](https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-default-apps-to-open-files/091079d9-11fa-4d9e-b992-abed1bacae01) help? It seems Windows isn't really built to remove default apps.

If you need help with step 5 in the link, I can explain in more detail.

**Comment by SaySayTakamura** [comment]
> Does [this](https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-default-apps-to-open-files/091079d9-11fa-4d9e-b992-abed1bacae01) help? It seems Windows isn't really built to remove default apps.
> 
> If you need help with step 5 in the link, I can explain in more detail.

Hey man, thanks, will rest a bit and tomorrow will give it a try and give you a answet thank you ;3.

**Comment by SaySayTakamura** [comment]
> 
> 
> Does [this](https://answers.microsoft.com/en-us/windows/forum/all/how-to-remove-default-apps-to-open-files/091079d9-11fa-4d9e-b992-abed1bacae01) help? It seems Windows isn't really built to remove default apps.
> 
> If you need help with step 5 in the link, I can explain in more detail.

Yeah man, sorry for bothering again but can you help me with step 5?

**Comment by Archie-osu** [comment]
The guide is broken - see the "Choose default apps by file type" entry in Windows's settings.

https://imgur.com/a/NtubMyf

**Comment by SaySayTakamura** [comment]
> The guide is broken - see the "Choose default apps by file type" entry in Windows's settings.
> 
> https://imgur.com/a/NtubMyf

It's there i am going, and i can't choose it besided windows store.

It says "No application installed for this filetype" or anything like that.

**Comment by SaySayTakamura** [comment]
After some time got it solved, thanks.
