### ISSUE TITLE
Remove automatic file associations

### ISSUE THREAD

**Issue by Archie-osu** [krzys-h/UndertaleModTool#525]
This is unnecessary behavior which overwrites existing user preferences without asking for user confirmation.

I propose the automatic extension association be removed, along with adding a checkbox in the settings (the state of which would be saved to some persistent location). The checkbox should be unchecked by default, with changes to the file associations only applying IF the user themselves mark the checkbox as active.

This setting should, if possible, work even through UMT updates (say, if I checked it in 0.4.0.0, future versions like 0.4.0.1 should already know it's checked).

**Comment by Grossley** [comment]
I disagree with this remedy, this is an uncommon problem and such a solution would break many people’s workflows, including mine. If anything it should be opt-out, not opt-in. Marking issue as wont fix and closing.
