### ISSUE TITLE
Can't run latest git master build - Please extract, when it is already extracted

### ISSUE THREAD

**Issue by gurgalex** [krzys-h/UndertaleModTool#526]
Used the 64 bit version artifact
https://github.com/krzys-h/UndertaleModTool/actions/runs/1156290244

zip extract warning message
![image](https://user-images.githubusercontent.com/28968644/130664380-59adbbf2-263f-4fd2-9194-fdacdb946ed1.png)

my folder extracted to
![image](https://user-images.githubusercontent.com/28968644/130664409-4a1f9354-fab8-4678-a5d8-783a55a0fda5.png)

**Comment by Grossley** [comment]
@gurgalex Fixed in fdb3edf91d1164df3d4eafaaba40c211d7635e87, closing.
