### ISSUE TITLE
Rounding errors when reassembling

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#53]
Not sure there is much that can be done about it, but I'll mention this here anyway since the goal of this project was to never do unintended modifications on the bytecode level
This instruction (from Deltarune, if you want to check yourself):
```
003C9904 00048: push.d 31.4159265358979
```
Originally is encoded as:
```
00 00 00 C0  5E 38 55 29 7A 6A 3F 40
```
but after disassembling and reassembling turns into:
```
00 00 00 C0  55 38 55 29 7A 6A 3F 40
```

**Comment by Kneesnap** [comment]
What script is this in?

**Comment by Kneesnap** [comment]
scr_selectionmatrix

**Comment by Grossley** [comment]
> 
> 
> What script is this in?

I'll look right now.

**Comment by Kneesnap** [comment]
Interesting. v1.00 PC. Code: scr_selectionmatrix.

When decompiled and recompiled, it produces the proper bytes.
When re-assembled as-is, it produces the improper bytes.

**Comment by Kneesnap** [comment]
Oddly, upon loading the win after saving, it loads the proper assembly.

**Comment by colinator27** [comment]
This was fixed at some point it seems. Tested on scr_selectionmatrix, it seems it has an extra digit of precision now.
