### ISSUE TITLE
ImportGraphics_Full uses incorrect directory 

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#536]
ImportGraphics_Full uses this directory ``C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.9\Packager\Textures`` which it should not be using. However "ImportGraphics_Full" is mostly obsolete anyways. Making it harder to use or removing it is an acceptable fix along with fixing the issue at hand with this script.

**Comment by Miepee** [comment]
Should this be closed in favour of #690
