### ISSUE TITLE
game maker 2.3 support 

### ISSUE THREAD

**Issue by GabiLikesCatz** [krzys-h/UndertaleModTool#538]
game maker 2.3 support needs some working (also i know they're working on it)
![sad face](https://user-images.githubusercontent.com/87230506/133384727-4a44e601-087c-4012-843e-faa9e947de01.PNG)

**Comment by BenjaminUrquhart** [comment]
We are aware. In the meantime, use the `ExportAndConvert_2_3_ASM` script to view such code.

**Comment by GabiLikesCatz** [comment]
thanks

**Comment by GabiLikesCatz** [comment]
thank you
