### ISSUE TITLE
Deltarune Chapter 1 and 2  Release Load Error (Both Itch and Steam)

### ISSUE THREAD

**Issue by FoxyMangleBreegull** [krzys-h/UndertaleModTool#542]
The data file keeps giving an error when I try to open it and I can't figure out why:
![image](https://user-images.githubusercontent.com/90941928/133866234-341b810e-2d8a-475b-8c26-e7f25795cb93.png)

**Comment by Archie-osu** [comment]
Use the prerelease. It doesn't have this issue.

**Comment by star14ms** [comment]
Try to use x64 instead x86
-> https://github.com/krzys-h/UndertaleModTool/releases/download/0.4.0.0-pre3/UndertaleModTool-0.4.0.0-pre3-x64.zip

**Comment by LukeSaward1** [comment]
This is because DR Chapter 1&2 is a GMS 2.3 game, and GMS2.3 doesn't have much support in UTMT as of right now.

**Comment by Grossley** [comment]
Fixed in 0.4.0 release 01
