### ISSUE TITLE
Deltarune Chapter 2's data.win can't load

### ISSUE THREAD

**Issue by Poketoonix** [krzys-h/UndertaleModTool#546]
It can't even read the first file of it

**Comment by Jacky720** [comment]
What version of the tool are you using?

**Comment by Archie-osu** [comment]
Use the prerelease, it doesn't have this issue.

**Comment by FartMaster57** [comment]
> Use the prerelease, it doesn't have this issue.

Which prerelease?
![image](https://user-images.githubusercontent.com/58342249/133906435-4908d5b2-452b-4984-8ae1-a2ee3d9a0c75.png)

**Comment by Grossley** [comment]
Resolved in 0.4.0 first release
