### ISSUE TITLE
Problem with the graphics

### ISSUE THREAD

**Issue by Nosarms** [krzys-h/UndertaleModTool#549]
Hello, I just installed the lastest release of Undertale ModTool, but a lot of rooms aren't loaded well. How can I change that ?

![image](https://user-images.githubusercontent.com/62297045/133919827-3962e392-c1ab-4363-922e-0045b7130bbd.png)

**Comment by SlayerIbn** [comment]
there's incomplete sprites because is not part of the room, that's graphics are apart
