### ISSUE TITLE
[Not sure where to put this, just a small thing you may already know] Missing functions from list

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#55]
The asset resolving function list is also missing collision functions like `place_meeting(x, y, obj)`.
I guess you can either do that now, resolve this issue, or resolve the issue now and TODO it. The only reason I made this was so that you know.

**Comment by krzys-h** [comment]
Oh, thanks. I was so tired of writing this list that I didn't bother double-checking if there is anything I missed :P
I'll add it in a moment

**Comment by krzys-h** [comment]
Added, let me know if you find anything else

By the way, are you working on any editors right now? I think I'll try to get the layers to display in the editor after I'm done with this.

**Comment by colinator27** [comment]
Yes, I'm currently working on a few editors that I changed some variable names and stuff on (not the room editor though). However technically my code is stuck at version 0.1.15, so I'll try to merge/update it before I push anything.

The biggest thing I'm working on at the moment is the Compiler, which I'm nearly done with the parser stage for (just need to implement optimization and some post-processing), and then I need to actually write most of the bytecode text writer.

**Comment by krzys-h** [comment]
@colinator27 how hard would it be to do a pull request with just the editor changes and not the whole compiler yet? I'm working on room editor right now and it would be nice to finally finish all the GMS2 stuff.

**Comment by colinator27** [comment]
I'll see if I can just make a commit excluding the files I added...
