### ISSUE TITLE
Debug Enabler crashes the game (latest UMT release)

### ISSUE THREAD

**Issue by AndrewIdot** [krzys-h/UndertaleModTool#551]
![image](https://user-images.githubusercontent.com/78974994/133930974-95c4b8b9-ebed-4292-b9e8-8bba1c74592f.png)

**Comment by Dobby233Liu** [comment]
What game is this?
If a GMS2.3 warning popped up, DebugEnabler probably won't work on your game for now.

**Comment by Archie-osu** [comment]
> 
> 
> What game is this?
> If a GMS2.3 warning popped up, DebugEnabler probably won't work on your game for now.

Judging from the error message, this is DELTARUNE Chapter 2. Use the modded data.win linked in the Discord.

**Comment by Grossley** [comment]
> > What game is this?
> > If a GMS2.3 warning popped up, DebugEnabler probably won't work on your game for now.
> 
> Judging from the error message, this is DELTARUNE Chapter 2. Use the modded data.win linked in the Discord.

Please make a patch for the debug enabling feature.

**Comment by AndrewIdot** [comment]
> Judging from the error message, this is DELTARUNE Chapter 2. Use the modded data.win linked in the Discord.
In what channel is the modded data.win? Can't seem to find it.

**Comment by Archie-osu** [comment]
It's pinned in the Chapter 2 data mining channel.

**Comment by Grossley** [comment]
This script is now disabled for Deltarune chapter 2, closing.
