### ISSUE TITLE
UndertaleEmbeddedTextures are too bright for me to see certain details

### ISSUE THREAD

**Issue by ToughSun14** [krzys-h/UndertaleModTool#554]
The png format in UTMT when viewing embedded texture sheets is a bit too bright. I can't see certain things when viewing the texture sheet in the tool (ex: font characters always blend into the background). Might I suggest changing the checkerboard background to something a bit darker so these things can be seen more easily without having to export the whole texture sheet?

**Comment by Miepee** [comment]
Duplicate of #117
