### ISSUE TITLE
How do i enable debug mode on deltarune

### ISSUE THREAD

**Issue by pbyen1234** [krzys-h/UndertaleModTool#57]
i keep taking all kinds of files into the deltarune folder and i click f12 when the game opens and i try everything you can in debug mode but nothing happens.. ive tried to put debug toggler in my folder. ive tried putting GoToRoom in my folder... ive tried so much! please someone help.

**Comment by colinator27** [comment]
If I understand what you're saying, you only moved the script files into the game folder? That won't do it. What you need to do is this: (works for other scripts too)

1) Open the `data.win` file from the game with the editor (`File -> Open`).
2) Near the top-left of the window (the context menu), click `Scripts -> Run builtin script -> ` and select the script file you want to run (it must be in the "Scripts" folder), in this case `DebugToggler.csx`.
3) If you want to make a backup of the `data.win` file, do so now.
4) Save to the `data.win` file, overwriting it with the changes made (the scripts change the game data, and you have to actually save it!).
5) Play the game with modified changes! If it still doesn't work, make sure you followed the steps exactly and that you saved to the proper `data.win` file (the one with the EXE that runs the game), because otherwise it will not work. Also, it *must* be *exactly* "data.win", at least for Windows. The GameMaker runner will not recognize it otherwise.

**Comment by krzys-h** [comment]
Yup, @colinator27 said it all. If you still have issues, please reopen.

**Comment by pbyen1234** [comment]
what editor??

**Comment by pbyen1234** [comment]
noob your not even helping!! IM GIVING A BAD REVIEW BYE 
![image](https://user-images.githubusercontent.com/44971844/48364896-eb84a380-e6a9-11e8-9c1e-e2ab94d05ca4.png)
![image](https://user-images.githubusercontent.com/44971844/48364898-eb84a380-e6a9-11e8-9117-cb4ec2904adf.png)
![image](https://user-images.githubusercontent.com/44971844/48364899-eb84a380-e6a9-11e8-8c32-438c92d600ad.png)

**Comment by pbyen1234** [comment]
![image](https://user-images.githubusercontent.com/44971844/48364936-ff300a00-e6a9-11e8-9120-d06ee590f1e7.png)
![image](https://user-images.githubusercontent.com/44971844/48364937-ffc8a080-e6a9-11e8-9074-16dfae38b318.png)
![image](https://user-images.githubusercontent.com/44971844/48364938-ffc8a080-e6a9-11e8-9d8f-1faf6f0a3fa7.png)
![image](https://user-images.githubusercontent.com/44971844/48364939-ffc8a080-e6a9-11e8-98dc-3ad65c9a5403.png)
![image](https://user-images.githubusercontent.com/44971844/48364940-ffc8a080-e6a9-11e8-8a64-e521fa31a702.png)
![image](https://user-images.githubusercontent.com/44971844/48364941-ffc8a080-e6a9-11e8-9b5a-86fc3be69e08.png)
![image](https://user-images.githubusercontent.com/44971844/48364942-ffc8a080-e6a9-11e8-948f-becf3ec923b0.png)
![image](https://user-images.githubusercontent.com/44971844/48364943-ffc8a080-e6a9-11e8-9457-b2d0ae2513b2.png)
![image](https://user-images.githubusercontent.com/44971844/48364944-00613700-e6aa-11e8-8080-b4db6b33197a.png)
![image](https://user-images.githubusercontent.com/44971844/48364945-00613700-e6aa-11e8-9791-5fabdc237b15.png)
![image](https://user-images.githubusercontent.com/44971844/48364946-00613700-e6aa-11e8-8579-72b3cc5d10c7.png)
![image](https://user-images.githubusercontent.com/44971844/48364947-00613700-e6aa-11e8-8396-d864295aef44.png)
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by colinator27** [comment]
...I'm sorry? We were trying to help... and how would you leave a review in the first place...
