### ISSUE TITLE
; Duplicate code entry; cannot edit here.

### ISSUE THREAD

**Issue by Kiffolisk** [krzys-h/UndertaleModTool#572]
I've been trying to edit some Deltarune Chapter 2 scripts, and some scripts don't seem to be editable without the disassembler (which is a pain to work with in this case, because I can't see if I edited the code correctly).
Only this appears:
`; Duplicate code entry; cannot edit here.`

What do I do?

**Comment by ZorroMundoYT** [comment]
it's not the decompiler's fault, it's gamemaker studio 2 new bytecode system, which, makes that the scripts are protected (bytecode 17) so you can't do much until undertalemodtool changes that

**Comment by krzys-h** [comment]
Edit the scipt with `GlobalScript` in the name instead. The `gms23-methods` branch and #561 adds a better message for this. The `Script` entry in GMS2.3 is just a pointer to a particular address within the `GlobalScript` code.
