### ISSUE TITLE
Non-consistent out of memory exception

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#573]
I ran UndertaleModTool 7 times, performing the same operation once in the command box, and then attempted to save, and it only successfully saved once.

**Comment by Archie-osu** [comment]
What was the operation, what game?

**Comment by Grossley** [comment]
Deltarune chapter 2, ``Data.GMS2_2_2_302 = false;``

**Comment by Grossley** [comment]
This appears to only occur on "AnyCPU" when running in Visual Studio

**Comment by Archie-osu** [comment]
And apparently only occurs for some people, as I've been unable to reproduce it even after two hours of trying.

**Comment by Grossley** [comment]
Use on real hardware not in VM

**Comment by DillyzThe1** [comment]
I can confirm that this is an issue, as I always get this error when saving. 
And on top of that, I can't even edit or view the decompiled Deltarune Chapter 2 code.

(I'm on Windows 10, running right off the hardware.)

**Comment by VladiStep** [comment]
It's still relevant.

That's because assemblies for scripts can't be unloaded from memory (at least there's no way that I would aware of), see this issue - https://github.com/dotnet/roslyn/issues/41722
