### ISSUE TITLE
Corrupted decompiled code (Deltarune Chapter 2)

### ISSUE THREAD

**Issue by orangegatogaming** [krzys-h/UndertaleModTool#580]
When trying to de-compile the code of `gml_Object_obj_time_Step_1` it gives corrupted code, i tried to remove the corrupted code, now it compiles successfully but it crashes the game with the error:

```
############################################################################################
ERROR in
action number 1
of  Step Event1
for object obj_time:

trying to index a variable which is not an array
at gml_Object_obj_time_Step_1
############################################################################################
gml_Object_obj_time_Step_1 (line -1)
```
Thanks toby for the helpful line... anyways i found that the loop on line 206 (keyboard checks) are causing that crash, if i remove that loop it doesn't crash but i can't use the keyboard (debug keys still work), and i found that "global.input_k" isn't a list,  but why is it trying to index it? Not touching the code helps, but i want to add debug keys, i know how, but i can't because of this error. (I apologize if i formatted this wrong, and for the godly english)

**Comment by TheRektafire** [comment]
I'm getting this error too when I tried to add a chapter to the chapter select, I got an error in the step event even though I didn't edit it that's the exact same, removing the keyboard check fixed it there but then I got another error in another file I can't view the code for because of the whole "duplicate code entry" error from issue #583 :/

**Comment by Jacky720** [comment]
This issue appears to have been resolved; obj_time_Step_1 now decompiles correctly and recompiles sufficiently (to avoid crashing, at the least).

**Comment by Grossley** [comment]
> This issue appears to have been resolved; obj_time_Step_1 now decompiles correctly and recompiles sufficiently (to avoid crashing, at the least).

Closing as it is resolved.
