### ISSUE TITLE
gml_GlobalScripts have nothing but a method call; gml_Scripts are marked as duplicates

### ISSUE THREAD

**Issue by GiovanH** [krzys-h/UndertaleModTool#583]
![image](https://user-images.githubusercontent.com/6759280/134601039-2af7342e-be70-4f21-b7b6-935f50b852e5.png)

![image](https://user-images.githubusercontent.com/6759280/134601034-b243ea71-3240-4c48-9272-b5af3755f8bb.png)

In this example, `gml_Script_c_soundplay_wait` points to `method(-1, gml_Script_c_soundplay_wait)`, which seems self-referential? It's definitely [a lookup](https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Variable_Functions/method.htm), but UMT doesn't seem to be able to find what's being looked up here.

It almost seems like the editor is getting these backwards? I.e. gml_GlobalScript is the "duplicate" one the editor is trying to mask, and gml_Script is the real one that should be decompilable.

**Comment by GiovanH** [comment]
Oh, I see what's happened here. This was fixed in a non-master branch but even though the fix wasn't merged to master the issue was closed.

**Comment by Grossley** [comment]
Covered by #556
