### ISSUE TITLE
Decompile certain disassembly specially

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#595]
This
```
push.l 1
pop.v.l self.type
```
decompiles as ``type = 1`` when it should decompile as ``type = (1 << 0)``.

**Comment by Archie-osu** [comment]
What'd be the reason for this?
In my opinion it makes the disassembly harder to read (until you learn that ``(n << 0) == n``).

**Comment by Grossley** [comment]
> What'd be the reason for this?
> In my opinion it makes the disassembly harder to read (until you learn that `(n << 0) == n`).

This issue is not about modifying disassembly output, it's about modifying decompiler output.

**Comment by Grossley** [comment]
And the reason is that ``type = 1`` is not an accurate decompilation of the disassembly.
