### ISSUE TITLE
New Chapter 2 debug manager does not appear in builds

### ISSUE THREAD

**Issue by Jacky720** [krzys-h/UndertaleModTool#598]
I downloaded the latest Github Actions build (4 hours ago), and the Ch2 Debug script (20 hours ago, appears on master) was not included. Maybe because it has a space in the name?

**Comment by Grossley** [comment]
The script was included in source but the build actions cannot see it, it needs to be linked up to be included in build artifact.

**Comment by Dobby233Liu** [comment]
The file wasn't added in the csproj file so it isn't packed with the build

**Comment by Dobby233Liu** [comment]
The file isn't packed with the build because it wasn't added to the project (sorry for double posting)
