### ISSUE TITLE
Decompiler resolves switch statements as if-elses, resulting in unreadable code

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#6]
Toby has said before he's not a programmer, and when you look at the code you realize that quickly. The most notorious issue (that he's actually commented on) is SCR_Text being one giant switch statement. 
Previous tools which supported decompiling (such as GMDSam) would decompile the main text script and other similar scripts into large switch statements.
The decompiler here outputs an if-else block so long it hangs if you scroll down on SCR_TEXT.

GMDSam could determine if-else blocks and switch statements apart so there has to be some form of identifier in the code.

**Comment by krzys-h** [comment]
There is no 'identifier' - all decompilation tools are based on heuristics and guessing. I did look into it a bit already, using the "DUP" instruction before ifs seems to be giving it away.

**Comment by NarryG** [comment]
I'd argue an instruction acts as an identifier, but that'd just be arguing semantics.

**Comment by krzys-h** [comment]
Just noticed another thing that can be used to detect switch statements - they always use BT for conditional jumps, while normal ifs always use BF

**Comment by krzys-h** [comment]
Done!
![image](https://user-images.githubusercontent.com/1517255/48351165-b5cfc280-e689-11e8-8c60-682ce3581cfb.png)
