### ISSUE TITLE
Automatically sort font glyphs

### ISSUE THREAD

**Issue by daohieu61** [krzys-h/UndertaleModTool#60]
I'm making a Vietnamese translation for Deltarune. The problem is some of my added characters don't display on the game text. For example, when I type "à á ả ã ạ", the text only displays "à á ã ạ", which means that it doesn't recognize character "ả" at charcode 7843.
What I've done:
-Extended character range to 32-10000
-Created a new font sprite sheet
-Aligned new character positions and texture range
-Saved the changes (of course)
![image](https://user-images.githubusercontent.com/20887516/48427820-37b01080-e79c-11e8-975d-ce50a9bed215.png)
![image](https://user-images.githubusercontent.com/20887516/48426667-cc653f00-e799-11e8-9a41-e82468f0f1b6.png)
![image](https://user-images.githubusercontent.com/20887516/48426739-f28adf00-e799-11e8-97f6-2cc0f8a1fcf7.png)
![image](https://user-images.githubusercontent.com/20887516/48427415-3fbb8080-e79b-11e8-9bb2-5ee8cc1ec69b.png)
![image](https://user-images.githubusercontent.com/20887516/48427599-b2c4f700-e79b-11e8-911e-3b1315a1e116.png)

**Comment by krzys-h** [comment]
According to https://github.com/krzys-h/UndertaleModTool/issues/8#issuecomment-423516750, you need to put the characters in ascending order for them to work

**Comment by daohieu61** [comment]
> According to [#8 (comment)](https://github.com/krzys-h/UndertaleModTool/issues/8#issuecomment-423516750), you need to put the characters in ascending order for them to work

Oh, so that was the problem. Then, could you add a sort function please? I can't seem to rearrange them so erasing all characters would be quite troublesome. Thank you.

**Comment by krzys-h** [comment]
Sure, that would be helpful

**Comment by krzys-h** [comment]
Added in 0.1.19

**Comment by BreakinBenny** [comment]
I'm late, but I can see this is one great contribution to Deltarune's localization. We should mix this with the Germanic letters.
