### ISSUE TITLE
Add support for using the GM:S 2 runner (and debugger, maybe?)

### ISSUE THREAD

**Issue by uglycoal** [krzys-h/UndertaleModTool#61]
GameMaker studio 2 is installed in C:\Program Files\GameMaker Studio 2 and when im using this path in settings of the program, it doesn't affect it at all.
Yet few times it was opening in gm:s 2, but it was showing error report with scr_84_load_map_json file, and i had to abort it
if you have any idea about that problems, i would appreciate your help! thanks

**Comment by krzys-h** [comment]
Using GM:S 2 install directory is not supported, but you don't need it. Looks like you tried to put the data.win file in a directory other than the one the game came in - that won't work, it still needs to be next to the .exe file and any additional files the game may try to load (music, translations etc.)

**Comment by uglycoal** [comment]
Yes, this fixed it! Game can be opened through this program, yet its not opening in GM:S 2 if i save data. win file in the same place, but if i save it somewhere else its opening, but im getting this
![default](https://user-images.githubusercontent.com/41569944/48489850-03d4f980-e835-11e8-8588-ad1c62102828.PNG)

**Comment by krzys-h** [comment]
Yeah, that is to be expected if you save it somewhere else. It can have a different name, but needs to be in the same directory as the game.
This exact error message is just Toby not handling `lang/lang_en.json` not existing properly. Even if that worked, you would not have the music files so the music wouldn't play.

**Comment by krzys-h** [comment]
You could never load the game into GMS directly, GMS is only used for the runner .exe if you want to directly run a game without its own .exe file (e.g. a data file from a Switch/PS4) or the debugger (which I haven't really tried in a long time)

**Comment by NarryG** [comment]
I'd love debugger support as I'm trying to create an autosplitter for Deltarune speedruns and I'm lazy and don't want to find the memory addresses by hand.

**Comment by Grossley** [comment]
Resolved
