### ISSUE TITLE
Fixing a link in the README

### ISSUE THREAD

**Issue by iiviigames** [krzys-h/UndertaleModTool#612]
[Right here](https://github.com/krzys-h/UndertaleModTool#special-thanks) on the readme page, the second link down, `https://github.com/donkeybonks/acolyte/wiki/Bytecode`, is no longer available. 

I went and grabbed an archival page of it though, so if you just throw this link in place of what you have, it will work just like it should! Here ya go!

`https://web.archive.org/web/20191126144953if_/https://github.com/donkeybonks/acolyte/wiki/Bytecode`

**Comment by Grossley** [comment]
Fixed!
