### ISSUE TITLE
"Error writing assembly code" on "gml_GlobalScript_scr_save" (Chapter 2)

### ISSUE THREAD

**Issue by VladiStep** [krzys-h/UndertaleModTool#619]
When I trying to modify "**gml_GlobalScript_scr_save**" (for example, added "_draw_text(0, 0, "test")_") and compile it, error appears:
"**Error writing assembly code.
Malformed variable store. Around line 1, column 1**."

**Comment by nkrapivin** [comment]
The GMS 2.3 support is not complete yet, things may break, your incident is one of them.

**Comment by 32th-System** [comment]
Indeed. I am having the same error and what it's having issue with is the way the function is declared
```gml
scr_debug_fullheal = function()
```
For now, a way around this is to edit the disassembly

**Comment by Jacky720** [comment]
With functional script compilation in addition to the workaround above, this issue should be closed.
