### ISSUE TITLE
Not letting me load Deltarune. (Chapter 2)

### ISSUE THREAD

**Issue by KirbzXDD** [krzys-h/UndertaleModTool#620]
When I try to load deltarune, it gives me an error, I've tried both the itch.io and steam versions, but I always get the same error, here's a screenshot.
![image](https://user-images.githubusercontent.com/82032395/135765613-c6c4c2aa-c7dd-4ed5-86f8-2b2123f1379d.png)

**Comment by Archie-osu** [comment]
Use the up-to-date release.

**Comment by KirbzXDD** [comment]
@Archie-osu Thanks! I was using the most recent version, but I decided reinstall deltarune and the tool, and for  some reason it started working! I'm going to close this thread now as I've got it working.
