### ISSUE TITLE
Is there ever gonna be a Linux build?

### ISSUE THREAD

**Issue by Kiffolisk** [krzys-h/UndertaleModTool#621]
Yes, I know, this uses XAML which doesn't really work with Linux, but is there any way that this will be ported to a UI library that supports Linux?

If not, is there any way to use this program with Wine or whatever else?

**Comment by Jacky720** [comment]
0.4 should work with Wine, yes.

**Comment by Kiffolisk** [comment]
Nice, I'm gonna try then.

**Comment by Kiffolisk** [comment]
Works. I had to download the "NetBundled" one.

**Comment by Kiffolisk** [comment]
Nevermind, I get a "Call to unimplemented function KERNEL32.dll.InitializeContext" error, but I at least got it opened.
