### ISSUE TITLE
Suggestion: Add a ch2_scene21_loop_fix script, which removes the "global.flag[307] = 1" thing

### ISSUE THREAD

**Issue by OhioInvadesUSA** [krzys-h/UndertaleModTool#631]
In gml_Object_obj_ch2_scene21_loop_Step_0, line 71: the text global.flag[307] = 1 can be found. Removing it causing a Susie plush to appear in Susie's room (if the gift was given to Susie).

**Comment by Grossley** [comment]
More information needed to work on this issue.

**Comment by Dobby233Liu** [comment]
I think people should be able to do this themselves.
(Note: This issue is about Deltarune Chapter 2)

**Comment by OhioInvadesUSA** [comment]
> More information needed to work on this issue.

In gml_Object_obj_ch2_scene21_loop_Step_0, line 71: the text global.flag[307] = 1 can be found. Removing it causing a Susie plush to appear in Susie's room (if the gift was given to Susie).

**Comment by Jacky720** [comment]
This issue should be closed, as it does not need to be addressed by a script and it was resolved in v1.08 anyway.
