### ISSUE TITLE
Script suggestion: UT Switch for PC formatter

### ISSUE THREAD

**Issue by wertercatt** [krzys-h/UndertaleModTool#64]
Requested features:

Updated BorderEnabler code to work with the new format
Disable Interpolation (because it's just not good to look at on PC)
Patch OSFlavor checks for Switch-exclusive content to accept PC

**Comment by wertercatt** [comment]
I've already gotten the switch-exclusive content working and interpolation disabled in my own customized NXTale build. The main issue is that I don't know how to convert that into a script.

**Comment by Grossley** [comment]
Here are the steps to formatting any NXTALE version for PC. Hopefully this will speed up the process to create the script which should then be added as a SampleScript in UndertaleModTool: 

Add the following files into your Undertale directory: 'mus_mewmew.ogg', 'mus_sfx_dogseal.ogg', and the Deltarune PC runner executable. 

The script should edit the following: 
1. "gml_Object_obj_time_Draw_77":  Under "Disassembly", change the line that reads "00002: pushi.e 3" to "00002: pushi.e 1". This will disable interpolation and make your game look really good when running on the PC.
2. "gml_Object_obj_kitchenchecker_Create_0": Under "Disassembly", change the line that reads "00092: pushi.e 4" to "00092: pushi.e 1". This will disable the first OS check for the Dog Shrine.
3. "gml_Object_obj_kitchenchecker_Alarm_2": Under "Disassembly", change the line that reads "00091: pushi.e 4" to "00091: pushi.e 1". This will disable the second OS check for the Dog Shrine. 

This seems like it would be a relatively simple script compared to others. Please look into it. :)

**Comment by Kneesnap** [comment]
A script has been added for this in https://github.com/krzys-h/UndertaleModTool/commit/6b4d8c852582aab63e9bb77f5a09443d7b77fce3
