### ISSUE TITLE
UT Mod Tool not activating debug mode on UT 1.08

### ISSUE THREAD

**Issue by Helisonbr** [krzys-h/UndertaleModTool#648]
i used the undertale mod tool 4.0.1 to activate debug mode on undertale 1.08 and it said it was done, but when i open the game there is not debug mode

**Comment by Archie-osu** [comment]
Did you save the file?

**Comment by Helisonbr** [comment]
Yes i did saved the data.win

**Comment by Archie-osu** [comment]
What script did you use? DebugToggler or EnableDebug?

**Comment by Helisonbr** [comment]
Enable Debug

**Comment by VladiStep** [comment]
Can confirm. Only "_DebugToggler.csx_" is working.

**Comment by Archie-osu** [comment]
Just checked and the issue seems to be in EnableDebug.csx writing ``global.debug = false`` instead of ``global.debug = true``.
![issue](https://user-images.githubusercontent.com/61205459/137627496-53cd060c-2ffe-44be-ad2d-01850f660904.png)

**Comment by Archie-osu** [comment]
The fault seems to be in the ``ReplaceTextInGML`` function. Manually running it with the UMT console also has no effect. I even tried replacing `` = 0`` with `` = false``, still no change is made.

**Comment by avengah** [comment]
It can be partially fixed by editing the script and changing "global.debug = 0" and "global.debug = 1" to false and true, respectively, but no matter whether you click Yes or No, it always runs the same code (i.e. once fixed, it will always enable debug, never disable it). The selection part is broken and always has been.

**Comment by Grossley** [comment]
> It can be partially fixed by editing the script and changing "global.debug = 0" and "global.debug = 1" to false and true, respectively, but no matter whether you click Yes or No, it always runs the same code (i.e. once fixed, it will always enable debug, never disable it). The selection part is broken and always has been. If you were already viewing SCR.GAMESTART when you run the script, you have to refresh the script for the change to be seen.

This has already been fixed, it just has not been put in a new release.
