### ISSUE TITLE
Feature Request: Search for code where a variable is used.

### ISSUE THREAD

**Issue by wertercatt** [krzys-h/UndertaleModTool#65]
For example, searching for where global.OSFlavor or self.os_type are used to easily locate platform checks would be convenient when attempting to enable console content on PC.

**Comment by krzys-h** [comment]
Definitely useful, and sounds doable

(but untli I get around to it, just do a batch decompile and run a search in the files)

**Comment by Grossley** [comment]
Implemented through "Search.csx", closing
