### ISSUE TITLE
SpriteType.Spine fix

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#66]
https://github.com/krzys-h/UndertaleModTool/blob/1c8cf194373a426f84579bcd4e5baa3d595e1459/UndertaleModLib/Models/UndertaleSprite.cs#L272
after add padding:  Align3 (reader);

https://github.com/krzys-h/UndertaleModTool/blob/1c8cf194373a426f84579bcd4e5baa3d595e1459/UndertaleModLib/Models/UndertaleSprite.cs#L282-L297
I think it should be moved here. Since SpriteType.Spine does not need CollisionMasks
https://github.com/krzys-h/UndertaleModTool/blob/1c8cf194373a426f84579bcd4e5baa3d595e1459/UndertaleModLib/Models/UndertaleSprite.cs#L221

**Comment by krzys-h** [comment]
ping @colinator27

**Comment by colinator27** [comment]
Ah, I completely overlooked the collision masks at the end. I'll push a fix soon.

**Comment by colinator27** [comment]
Fixed in the latest commit of #63.

**Comment by krzys-h** [comment]
92c732637099f1c179b01253aca8e9d53f5bc905

**Comment by LinXP** [comment]
@colinator27 https://github.com/krzys-h/UndertaleModTool/blob/ebf920f481f49121d8c857cc82e44d5adce2712b/UndertaleModLib/Models/UndertaleSprite.cs#L279
after this line comes padding, need add "Align3(reader);"
otherwise there will be an error
http://i.prntscr.com/Ak3IVddeS_ORT0X5FcYMSw.png

**Comment by colinator27** [comment]
Are you sure? I can't find any evidence of this in the code, and it should be aligned to 4 anyway...

**Comment by colinator27** [comment]
Oh, wait, I think it may exist, just that it doesn't need to be done there explicitly. You see, I added a "pre-padding" object to the code, and it runs before an object is serialized. This is what is done for sprites: https://github.com/krzys-h/UndertaleModTool/blob/ebf920f481f49121d8c857cc82e44d5adce2712b/UndertaleModLib/Models/UndertaleSprite.cs#L394-L402

Though this may make you think that the last sprite will not get the padding, the chunk itself will also align.

**Comment by krzys-h** [comment]
The error @LinXP posted seems to suggest that you tried to read a pointer to RoomOrderEntry as a pointer to TexturePageItem

Given that RoomOrderEntry is at the beginning, I guess you tried to accidentaly read a resource ID as a pointer.

**Comment by krzys-h** [comment]
Also note that you may have missed it because trying to read a pointer to an invalid location may give you an empty object if no object was ever read at that location because I don't think I ever added an exception for that case...

**Comment by LinXP** [comment]
@krzys-h , @colinator27 uploaded here examples with bytecode 17  
It is primarily interested deathsgambit
https://mega.nz/#F!HfxXwS5B!N_-Zfy_pgNp9KXLn3NO7RQ

**Comment by LinXP** [comment]
I in the template for the 010 editor implemented the calculation of padding in this way
```
int CalcPadding(int AlignSize)
    {
    local int PaddingSize;
    PaddingSize = AlignSize - (FTell() % AlignSize);
    if (PaddingSize == AlignSize)  {PaddingSize = 0;}
    return PaddingSize;
}
```
can and you implement a universal function for this

**Comment by colinator27** [comment]
Just realized that I forgot a *really* important line to actually unserialize the padding... It was only serializing it........

**Comment by colinator27** [comment]
Yeah, I fixed it in https://github.com/krzys-h/UndertaleModTool/commit/b63a470d3da49864db8fcbd463bb6fcc861af076.
