### ISSUE TITLE
"<object>.<variable> += <value>" compiles incorrectly

### ISSUE THREAD

**Issue by Agent517** [krzys-h/UndertaleModTool#676]
For whatever reason, editing code that contains something like this:
![](https://cdn.discordapp.com/attachments/895464367083094056/905294178609684500/unknown.png)
Results in it being compiled like this:
![](https://cdn.discordapp.com/attachments/895464367083094056/905294235320848424/unknown.png)
When it should be something like this: 
![](https://cdn.discordapp.com/attachments/548983945241559066/905783622194315284/unknown.png)
All screenshots were taken from `gml_Object_obj_ch2_scene21_loop_Step_0`.

**Comment by BenjaminUrquhart** [comment]
This is a known 2.3 compiler(?) issue.

**Comment by Jacky720** [comment]
This has been fixed.
