### ISSUE TITLE
Can we make a option of settings that disables Autocomplete?

### ISSUE THREAD

**Issue by RTFTR** [krzys-h/UndertaleModTool#682]
Deltarune becomes unstable when a step event is edited by UTMT's AutoComplete function.
I think we need a option that disables Autocomplete function.

**Comment by Grossley** [comment]
What AutoComplete function? I am not aware of what you are talking about.

**Comment by RTFTR** [comment]
> What AutoComplete function? I am not aware of what you are talking about.

Like, when we click anywhere after editing codes, UTMT re-edits the codes again and it sometimes makes error

**Comment by Grossley** [comment]
That's not autocomplete, that's the compiler compiling your code. Also decompiled code editing is not fully supported for Deltarune chapter 2. Therefore the remedy you're asking for does not make sense. You should have received a warning about it upon loading the game. And the proper problem to be fixed (making the compiler more compatible) is already an issue here on GitHub. Marking as invalid and closing.
