### ISSUE TITLE
Assembly readability

### ISSUE THREAD

**Issue by Jacky720** [krzys-h/UndertaleModTool#689]
Reading assembly in UndertaleModTool would be much easier (especially for beginners) if some sort of indicator (perhaps a newline, perhaps not since that's already used to indicate labels) was inserted after `pop` commands.

**Comment by colinator27** [comment]
Yeah, there's definitely two major problems with this. First is the one you already mentioned (new blocks are already indicated with newlines), and second is that pop instructions aren't always in the "intuitive" assignment form (and there's even pop.e.v which doesn't store anything at all, though that would be easy to exclude).

**Comment by Archie-osu** [comment]
I agree with Colin about it just causing confusion between blocks and pops, not to mention that this could be very unintuitive too (imagine seeing all the empty lines for the first time looking at GM assembly!)
