### ISSUE TITLE
Improper access to "dotnet" directory while using ImportGraphics

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#690]
![unknown](https://user-images.githubusercontent.com/42724744/141863994-8cfac429-bf03-41c3-bcbe-f4d0ff2db2b4.png)

**Comment by VladiStep** [comment]
I can't find the version of _"ImportGraphics.csx"_ that has this particular line of code.

**Comment by Kneesnap** [comment]
It sounds to me like the problem is that the working directory is somewhere
that can't be accessed without admin perms. It fails because it doesn't
have access.

**Comment by Grossley** [comment]
This is the improper working directory, the problem is that the working directory is wrong, it not having access is a consequence of this.

**Comment by VladiStep** [comment]
After 15 days, I found out that is actually "ImportGraphics_Full_Repack.csx", not "ImportGraphics.csx"...

**Comment by Grossley** [comment]
ImportGraphics_Full uses this directory ``C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.9\Packager\Textures`` which it should not be using. However "ImportGraphics_Full" is mostly obsolete anyways. Making it harder to use or removing it is an acceptable fix along with fixing the issue at hand with this script.
