### ISSUE TITLE
Doesn't work on the latest version if Stoneshard (unknown chunk FEDS)

### ISSUE THREAD

**Issue by IVENEND** [krzys-h/UndertaleModTool#697]
when loading the data.win of latest version of Stoneshard, an error occruds:
https://i.imgur.com/0mTyGK7.png

**Comment by Jacky720** [comment]
Support for FEDS (in the sense of not immediately crashing) is already on the master branch and [latest GitHub Actions builds](https://youtu.be/hXMF53lWqpk?t=109).

**Comment by Miepee** [comment]
@IVENEND is this still an issue?

**Comment by Miepee** [comment]
@Jacky720 IIRC you have Stoneshard as well, can you test this?
