### ISSUE TITLE
Graphviz not always properly closed

### ISSUE THREAD

**Issue by NarryG** [krzys-h/UndertaleModTool#7]
Not 100% sure what I did to cause it, but I just found dot.exe running utilizing a full thread minutes after I quit the tool (and at least an hour after I last used the graph).  Should probably spawn it as a child so if the main tool dies it comes along with it.

**Comment by krzys-h** [comment]
The graph view was just a quick hack to show something I have done with command line tools earlier inside the tool, I used some random library to run dot for me. Rewriting it shouldn't be hard though, it is just spawning one process and redirecting the stdin/stdout.

One thing I noticed causes weird stuff to happen: don't close the loading dialogs with the "X" button... :P

**Comment by PoroCYon** [comment]
[Seems to be a bug in the library](https://github.com/JamieDixon/GraphViz-C-Sharp-Wrapper/blob/master/src/GraphVizWrapper/GraphGeneration.cs#L128), it's not properly killing the process.

**Comment by Kneesnap** [comment]
Seems to not be an issue with UTMT.
