### ISSUE TITLE
DirectoryCopy error

### ISSUE THREAD

**Issue by Eidamiino** [krzys-h/UndertaleModTool#704]
Seemingly out of nowhere this popup started showing up when loading windata. The only thing I noticed it directly breaking is that in the game preview (F5) there's no music, only sfx. It may also be why my custom characters don't work, but that may be a different problem. 
![Výstřižek](https://user-images.githubusercontent.com/80248491/144587861-2c87d323-9168-450c-b3f9-9fc0772b30d6.PNG)

**Comment by Dobby233Liu** [comment]
extract the tool zip you downloaded

**Comment by Dobby233Liu** [comment]
epic close

**Comment by Dobby233Liu** [comment]
did you fix it

**Comment by Eidamiino** [comment]
> did you fix it

yea thanks for the help, forgot to reply
