### ISSUE TITLE
api-ms-whatever error

### ISSUE THREAD

**Issue by Troll212420** [krzys-h/UndertaleModTool#711]
pls help
https://i.imgur.com/zpRtrEx.png
(sorry for it not being english)

**Comment by Dobby233Liu** [comment]
i suggest to try reinstalling a unmodified copy of windows, since your installation looks broken. i think some tools may be able to install these crt runtimes tho

**Comment by Miepee** [comment]
@Troll212420 do you stil have that issue with 0.4.0.4 / the cutting edge builds?

**Comment by Grossley** [comment]
Resolved.
