### ISSUE TITLE
Import folder naming is not obvious

### ISSUE THREAD

**Issue by Jacky720** [krzys-h/UndertaleModTool#715]
When running ImportGraphics.csx on v0.4.0.2, UndertaleModTool requires the selected folder be named according to what is being imported, and gives a cryptic error if it is not. It should be more lenient, probably by asking what asset type the folder contains in a prompt.

**Comment by VladiStep** [comment]
You mean the  _"\*folder name\* is in an incorrectly-named folder."_ error?

**Comment by Jacky720** [comment]
Yes.
