### ISSUE TITLE
Adding a Battle

### ISSUE THREAD

**Issue by jckspde** [krzys-h/UndertaleModTool#716]
I'm trying to add a fight to the pacifist run. My idea is when you meet Sans, he tells you that you're going to go up against Asgore, so he's going to "give you a warm-up" before fighting. I don't know how to make this happen though because I don't understand code.

**Comment by Jacky720** [comment]
This is not an issue with the tool. For help with learning to mod, might I suggest [PierRoulette's tutorials](https://www.youtube.com/playlist?list=PLTZJJRPYg1wJMS6VMPKAjOlX9Ee6gbvpP), the [GameMaker manual](https://docs.yoyogames.com/), or the [Underminers Discord server](https://discord.gg/KFDwxz9zaV)?

**Comment by jckspde** [comment]
Oh, okay thanks for the suggestion!
