### ISSUE TITLE
New load error discovered when opening "data.win" of the fangame "Rayman ReDesigner"

### ISSUE THREAD

**Issue by FroztySeven** [krzys-h/UndertaleModTool#722]
This game was made with the current information from it's developer
```
Gamemaker Studio 2
IDE v2.3.7.606 Steam
Runtime v2.3.7.476
Format: YYC
```

Possible cause of issue:
`A recent addition of a new layer type in recent gamemaker studio 2 releases was used`

Undertale Mod Tool version v0.4.0.2 was used!
![unknown](https://user-images.githubusercontent.com/20623800/149194320-0334d56c-e6c5-4639-9041-3992dd7ae08a.png)

**Comment by craftersshaft** [comment]
bumping, same issue happens in the Furquest Demo

**Comment by Miepee** [comment]
@craftersshaft or @FroztySeven can you try again on 4.0.4 / the cutting edge builds?
https://github.com/krzys-h/UndertaleModTool/actions/workflows/publish_gui.yml

This *should* be solved now.

**Comment by FroztySeven** [comment]
I can conform, this issue has been solved with the newest version of the tool.
No more errors
