### ISSUE TITLE
Something is missing for running UTMT as a dotnet standalone application

### ISSUE THREAD

**Issue by vanfanel** [krzys-h/UndertaleModTool#731]
Hi there!

I am trying to run UTMT as a standalone DOTNET application on GNU/Linux (since DOTNET 5.0, it's possible to do so with DOTNET apps, no need for Wine to run these).

The problem is that the UTMT seems to be missing a setting:
```

manuel@hp15db0:~/Downloads/Undertaler6$ dotnet UndertaleModTool.exe 
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/manuel/Downloads/Undertaler6/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/manuel/Downloads/Undertaler6/UndertaleModTool.runtimeconfig.json' did not specify a framework.
  - If this should be a framework-dependent app, specify the appropriate framework in '/home/manuel/Downloads/Undertaler6/UndertaleModTool.runtimeconfig.json'.
```

So, looking at  `UndertaleModTool.runtimeconfig.json` I see it contains:

```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "includedFrameworks": [
      {   
        "name": "Microsoft.NETCore.App",
        "version": "5.0.13"
      },  
      {   
        "name": "Microsoft.WindowsDesktop.App",
        "version": "5.0.13"
      }   
    ]   
  }
}
```
So, what is it missing??

Thanks!

**Comment by Dobby233Liu** [comment]
I think UMT uses WPF, which is Windows only, so you still need Wine.
Also random acoording to this [SO answer](https://stackoverflow.com/a/56063289), the builds in Releases are built only for Windows, so of course a Linux compatible version of the hostpolicy lib will be not present, so you get the error, I think you may want to build UMT yourself if you really want to run it the dotnet CLI way

**Comment by Grossley** [comment]
Adding to what Dobby233Liu said, there is also UndertaleModCLI which may be more useful for such an attempt.

**Comment by Dobby233Liu** [comment]
> Windows is required to build **Windows desktop applications.**

From this error you can see UMT is explictly marked as Windows-only, so now I don't think it will build for Linux and run on Linux natively, though if you want to try here's the command
```bash
dotnet publish UndertaleModTool -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=false --output build
```
The command is literally copied from https://github.com/krzys-h/UndertaleModTool/blob/master/.github/workflows/build_net_nonbundled.yml#L26 , just that the RID is changed to linux-x64

**Comment by vanfanel** [comment]
@Dobby233Liu Thanks! Sadly, that line doesn't make it build either:
```

manuel@hp15db0:~/src/UndertaleModTool$ /usr/local/bin/dotnet publish UndertaleModTool -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=false --output build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/snap/dotnet-sdk/152/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1100: Windows is required to build Windows desktop applications. [/home/manuel/src/UndertaleModTool/UndertaleModTool/UndertaleModTool.csproj]                                                                                                                                 
manuel@hp15db0:~/src/UndertaleModTool$
```

I would use WINE, but UTMT crashes when opening big (~99MB) data files, or when saving any size of data files...

**Comment by Miepee** [comment]
WINE is unsupported for the GUI version of UMT. And due to the GUI needing WPF, you won't be able to compile it or run it on other OS other than Windows.

I have heard that the NSF build of the current versions run better, which you could try.

Otherwise, the only other solution would be to use UMTCli.
