### ISSUE TITLE
An Error occurred while trying to load：Read unknown at 00033BF8 while reading chunk ACRV 

### ISSUE THREAD

**Issue by Cxxw233** [krzys-h/UndertaleModTool#746]
![7a94119fb2796885](https://user-images.githubusercontent.com/97384510/153746264-8eb1dd4b-8ecf-4293-9222-835692021504.png)
An error occurred while trying to open
（game was a year ago)
尝试打开时出现了错误
游戏是一年前的游戏

**Comment by Dobby233Liu** [comment]
Weird, was the game obfuscated in any way?

**Comment by Cxxw233** [comment]
maybe，thank you very much（my English not good）
I'll try something else

**Comment by Cxxw233** [comment]
but this is the latest version

**Comment by Archie-osu** [comment]
What's the game called?
