### ISSUE TITLE
another error during loading data

### ISSUE THREAD

**Issue by donsoyer** [krzys-h/UndertaleModTool#750]
![MWSnap 2022-02-16, 14_01_16](https://user-images.githubusercontent.com/96090807/154270008-7e5b3d47-f398-4d30-a58b-2a9590586da9.png)
![MWSnap 2022-02-16, 14_02_27](https://user-images.githubusercontent.com/96090807/154270051-5e5f667e-1c24-422f-8bd2-e3cff67842ec.png)

**Comment by Jacky720** [comment]
What game is this, and what version of UndertaleModTool?

**Comment by Miepee** [comment]
Don't know which game @donsoyer had here, but I had my fair share of games which had similar errors:
- sandbox-dig
- colony-warfare
- dropship
- pirate-pit

just to name a few. They can all be found on gm48.net
