### ISSUE TITLE
how to import non-embedded sprites?

### ISSUE THREAD

**Issue by server-ok** [krzys-h/UndertaleModTool#753]
i exported with ExportAllSprites.csx and edited some sprites. How to import it back?

**Comment by Jacky720** [comment]
Put the edited sprites in a folder named "Sprites", then select that folder with ImportGraphics.csx.

**Comment by server-ok** [comment]
> Put the edited sprites in a folder named "Sprites", then select that folder with ImportGraphics.csx.

tysm!
