### ISSUE TITLE
Version 1.08 onwards ((i assume) GameMaker Studio 2022.1) gives these two errors

### ISSUE THREAD

**Issue by itsEmax64** [krzys-h/UndertaleModTool#761]
![image](https://user-images.githubusercontent.com/89655578/155493057-0e56169d-ca92-4466-b1f5-a2d261ae59e9.png)
![image](https://user-images.githubusercontent.com/89655578/155493080-ddea671f-320c-446b-a457-0f10a0f64431.png)

**Comment by Jacky720** [comment]
This is fixed on master, and on the [automatic GitHub Actions builds](https://nightly.link/krzys-h/UndertaleModTool/workflows/build_net/master/win_x64.zip) from it.
