### ISSUE TITLE
New Update Deltarune Loading Error

### ISSUE THREAD

**Issue by SteveSkyWarrior** [krzys-h/UndertaleModTool#763]
The mod tool seems to be unable to load the new version of the game. The version released 2 days ago at the writing of this.

**Comment by Jacky720** [comment]
This is fixed on master, and on the [automatic GitHub Actions builds](https://nightly.link/krzys-h/UndertaleModTool/workflows/build_net/master/win_x64.zip) from it.

**Comment by Grossley** [comment]
Fixed in 0.4.0.3
