### ISSUE TITLE
New Room editor feature is already bugeed.

### ISSUE THREAD

**Issue by ToughSun14** [krzys-h/UndertaleModTool#765]
So, recently, a new commit was made to the source code, and one thing that was improved is the room viewer, but it appears to already be bugged. For anything that uses a sprite as a visual marker, instead of simply drawing the target position and size for the asset's sprite, it draws its source position and size, meaning other sprites can unnecessarily overlap into it. An example of this can be found in room_torhouse. The tile for "bg_torhouse_fg" overlaps into other sprites on its texture page.
![room_torhouse](https://user-images.githubusercontent.com/51935642/155727880-a528b9aa-e6ca-41d2-9156-611f5baad752.png)
Addendum: Did some experimenting with previews, turns out if a sprite asset has multiple frames, the room viewer can only draw frame 0, even if the asset is set to a different frame.

**Comment by VladiStep** [comment]
I don't understand the first part - what's exactly wrong with this room? Could you highlight it on the picture?
And about sprite instance frame index - I just didn't noticed that it has "frame index" property, it will be fixed in the next pull request.

**Comment by ToughSun14** [comment]
![155727880-a528b9aa-e6ca-41d2-9156-611f5baad752](https://user-images.githubusercontent.com/51935642/155741406-c8a4bd78-d513-43cb-8b9f-5f0f82b436fe.png)
I've highlighted the issue in red.

**Comment by ToughSun14** [comment]
Well, it is the latest version of Deltarune, but it's also the latest commit to the master branch.

**Comment by VladiStep** [comment]
I think problem is simply that it doesn't use margin properties of sprite (`MarginLeft`, `MarginRight`, `MarginTop`, `MarginBottom`).

**Comment by ToughSun14** [comment]
Hmm, good point. Kinda lines up with my guess where instead of using the target position variables to draw the sprite, it uses the source position variables.

**Comment by VladiStep** [comment]
Actually, it was "bugged" from the beginning _(at least from September 2018)_.
