### ISSUE TITLE
Issue with ImportFontData.csx

### ISSUE THREAD

**Issue by far5193** [krzys-h/UndertaleModTool#771]
When I try to import font data it gives me this error (I'm using v0.4.0.3):
![bug](https://user-images.githubusercontent.com/69575145/155839816-f54b3024-3b8f-4d1c-9faa-6723d1043db6.png)

It seems that instead of reading the file \Export_Fonts\glyphs_fnt_mainbig.csv it's trying to read \Export_Fontsglyphs_fnt_mainbig.csv (missing the "\\").

I had a similar issue with ExportAllStrings, exporting the file as folderstrings.txt instead of a strings.txt file inside the folder.

**Comment by xitieshiz2** [comment]
Same issue with you, waiting for a fix
It's really...funny

**Comment by Miepee** [comment]
Since it likely got lost in the discord channel:
Does this script work? (you can execute it with scripts -> other...)
https://cdn.discordapp.com/attachments/568950566122946580/957703861768953916/ImportFontData.csx

If it does, I'll do a PR for it later. It changes the following:
```diff
- string sourcePath = importFolder;
+ string sourcePath = importFolder + "/";
```

**Comment by far5193** [comment]
> Since it likely got lost in the discord channel: Does this script work? (you can execute it with scripts -> other...) https://cdn.discordapp.com/attachments/568950566122946580/957703861768953916/ImportFontData.csx
> 
> If it does, I'll do a PR for it later. It changes the following:
> 
> ```diff
> - string sourcePath = importFolder;
> + string sourcePath = importFolder + "/";
> ```

Yes, it works for me.
