### ISSUE TITLE
[arch linux] images don't show up

### ISSUE THREAD

**Issue by OwOstrich** [krzys-h/UndertaleModTool#778]
i'm using the NSF build, when i try to look at a sprite all it shows is a blank box. i have to export the sprite in order to see what it is, which gets really annoying as i have to do it for every single sprite i want to look at and i have to export it _again_ if i want to check if the sprite import actually worked the way i want it to.

**Comment by Grossley** [comment]
Linux is not officially supported for UndertaleModTool, use at your own risk.

**Comment by Miepee** [comment]
Note to this:
If WINE has different behaviour than Windows, then this is a WINE issue and should be reported at <https://bugs.winehq.org/> instead.
