### ISSUE TITLE
Font model might need updating.

### ISSUE THREAD

**Issue by ToughSun14** [krzys-h/UndertaleModTool#781]
So, recently I was testing out some new stuff in my GMS2 project, but after doing some experimenting with fonts, I got a error I haven't seen before. Maybe someone can take a look into this and update the font model code to account for this error?
![2022-03-09 (3)](https://user-images.githubusercontent.com/51935642/157558781-5f5d5a6c-bcb3-4941-ac0b-a0507816f7dd.jpg)

**Comment by Grossley** [comment]
Please send the data file you were attempting to load.

**Comment by ToughSun14** [comment]
Okay, here it is:
[https://mega.nz/file/OjZwwbbB#FLCgPYH7HpmZl8oXCi0vhXSTxp-yXTmuxL1lNiOHcFE](url)
