### ISSUE TITLE
"Parameter is not valid" crash when attempting to load certain rooms in the editor. 

### ISSUE THREAD

**Issue by Jesright73** [krzys-h/UndertaleModTool#782]
Attempting to load certain rooms in the editor results in a crash, displaying a "Parameter is not valid" error message that doesn't fit on screen.

**Game:** The Horde v1 (a mod for AM2R)

**Rooms affected:** 

- rm_a0h04
- rm_a0h07
- rm_a2c06
- rm_a3h05
- rm_a3a20
- rm_a3a23
- rm_a0h21
- rm_a4b02b
- rm_a5h01
- rm_a6a18
- rm_a3a23c
- rm_a9a1
- rm_a3a28
- rm_a5h09
- rm_a3a29

_Does not occur with AM2R base game. Unable to replicate with any other game._

**Undertale Modding Tool version:** All builds with commit be524cd60bf6defb6c26559e01c9c5f8ab2d6efe.
Crash does not occur in any build before that commit.

**OS:** Windows 10 21H1

[crash.txt](https://github.com/krzys-h/UndertaleModTool/files/8226882/crash.txt)
![image](https://user-images.githubusercontent.com/79653967/157740159-e5adfb4a-3cb6-4cd7-8979-7b65b37016b0.png)

**Comment by VladiStep** [comment]
According to the crash log, probably there are some tiles with invalid width/height *(zero/negative)*.
I didn't add a check for that when room editor improvements were made.
I'll add this to the PR with other room editor fixes.

**Comment by VladiStep** [comment]
@Jesright73, could you try it again, but with the latest UTMT commit build?
You can either try to update UTMT with _"Update to latest commit"_ button in the settings, or download it from [here](https://nightly.link/krzys-h/UndertaleModTool/workflows/build_net/master/win_x64.zip) separately.

**Comment by Jesright73** [comment]
@VladiStep It works, no more crashing.
