### ISSUE TITLE
Opening big .win files.

### ISSUE THREAD

**Issue by SileNTViP** [krzys-h/UndertaleModTool#786]
Hi.
When i try to open data.win (3.313.250.304 bytes) error: System.OverflowException: "Array dimensions exceeded supported range." in file BufferBinaryReader.cs buffer = new byte[Length];

**Comment by Archie-osu** [comment]
Hi, what game is the data.win from?

**Comment by SileNTViP** [comment]
> Hi, what game is the data.win from?

Secret Care Cafe 0.7.11 public :D 18+

**Comment by Archie-osu** [comment]
Oh it's this game again, oh dear.

**Comment by SileNTViP** [comment]
> Oh it's this game again, oh dear.

Need to change fonts and translate strings on other language.

**Comment by Miepee** [comment]
Duplicate of #520 ?
