### ISSUE TITLE
Will You Snail? Not working. 

### ISSUE THREAD

**Issue by mandar1jn** [krzys-h/UndertaleModTool#788]
Will You Snail is currently not working with byte misalignment errors. 
![8F460F7D-4CCF-476D-8451-B828E98677FF](https://user-images.githubusercontent.com/49076509/158686907-56e821f1-9b1f-49c2-ba7d-abd8fd06cf38.png)
![DF7BF45E-7E19-4F2A-82FE-894B2E770375](https://user-images.githubusercontent.com/49076509/158686909-50ecc1d5-c11b-4876-b967-2920e88060f7.png)
Above are some examples of the errors. If you can give me a way to come into contact I’d be happy to provide the .win file. but only that file.

**Comment by Grossley** [comment]
Issue reproduced.

**Comment by Eltend** [comment]
You need a special version of it here:

https://github.com/Jacky720/UndertaleModTool/suites/5699234081/artifacts/187726395

**Comment by mandar1jn** [comment]
@Eltend I’m aware. I’m one of the people who found the fix

**Comment by Eltend** [comment]
ok you also need to activate the sandbox beta

**Comment by mandar1jn** [comment]
@Eltend I know... I'm still one of the guys who originally found the fix to get UMT to work on the sandbox branch...
