### ISSUE TITLE
Font offset issue when serializing

### ISSUE THREAD

**Issue by mandar1jn** [krzys-h/UndertaleModTool#792]
Yesterday, Jonas Tyroller released a VM build of will you snail. Because of this, we have been frantically trying to get UMT to work with it. Issues #788 seems to be fixed by [this](https://github.com/krzys-h/UndertaleModTool/commit/84e15d51df8c600963b80a70ec91450f426b856d). Yet we still can't get WYS to run even though UMT does not give any warnings except the maybe unsupported warning. While analyzing different versions of data.win and offset maps, @cgytrus and I noticed misalignment takes place with the first mention of fonts. @cgytrus also noticed bytes seemed to be offset by 4. This lined up with [this](https://github.com/krzys-h/UndertaleModTool/commit/84e15d51df8c600963b80a70ec91450f426b856d) fix again. Which seems to only manage the loading and not serializing back to file. We are currently trying to work on a fix.

**Comment by mandar1jn** [comment]
[offset map when exported without any changes](https://cdn.discordapp.com/attachments/945754440831475754/954010047879446538/data.win.offsetmap.txt)
[offset map of original data.win](https://github.com/krzys-h/UndertaleModTool/commit/84e15d51df8c600963b80a70ec91450f426b856d)

**Comment by mandar1jn** [comment]
update: we managed to get it working. @cgytrus is working on a commit right now

**Comment by Jacky720** [comment]
Did you figure out what the value actually is, or hardcode it? Thanks a lot in either case.

**Comment by cgytrus** [comment]
just hardcoded, i just made it write 0 in the same place the deserializer skips over that 0

**Comment by Miepee** [comment]
Was also fixed by #793
