### ISSUE TITLE
Unable to save anything in Grapple Dog

### ISSUE THREAD

**Issue by IsaGoodFriend** [krzys-h/UndertaleModTool#796]
Trying to mod Grapple Dog, but it throws an error every time I try to save it
![image](https://user-images.githubusercontent.com/42853091/159103371-2db9df53-78d2-420a-8056-4f591ed043bc.png)

**Comment by Archie-osu** [comment]
Hi, are you using the latest release or even better the latest commit?

**Comment by TrashBandatcoot** [comment]
I get the same error message, using the latest commit.

![image](https://user-images.githubusercontent.com/49070403/159656896-5b607930-109b-4481-94e7-f08c47a20df8.png)

**Comment by IsaGoodFriend** [comment]
I've just tested it now on the most recent commit and it still has the issue

**Comment by Miepee** [comment]
Game is paid, and currently no maintainers have access to it. So here are a couple ideas thrown around:
- Can you compile UMT from source and check where exactly the error occurs?
- Can you check which GM:S version it is, and whether the textures use QOI(+BZIP2)?

If any help or real-time chat is needed , feel free to drop by in the discord server.

**Comment by IsaGoodFriend** [comment]
The textures use QOI.  I did some digging around the compression code, and I was wondering why you multiply by 48 instead of 4 here.  I removed the * 12 part of the code and it fixes the bug

![image](https://user-images.githubusercontent.com/42853091/164070163-258c12b2-defc-4847-885d-5d5ca3f9a4d7.png)

**Comment by Miepee** [comment]
@colinator27 is this another part of the stuff that you fixed in DogScepter that you wanted to port over to UMT?

**Comment by colinator27** [comment]
> @colinator27 is this another part of the stuff that you fixed in DogScepter that you wanted to port over to UMT?

Yes, that `* 12` can probably just be removed. Might want extra padding instead of just `+ 4` though, to be safe with the header size, though.

**Comment by TrashBandatcoot** [comment]
Have these changes been pushed yet?

**Comment by Miepee** [comment]
Nope

**Comment by Miepee** [comment]
This issue should have been fixed now.
Can anyone of you test this?

**Comment by TrashBandatcoot** [comment]
Confirmed it saves!
![image](https://user-images.githubusercontent.com/49070403/168020838-cf65e0ce-93e0-4659-8b35-b3107412cc9f.png)
