### ISSUE TITLE
How can I add new characters to the game.win

### ISSUE THREAD

**Issue by D3fau4** [krzys-h/UndertaleModTool#8]
please, it would be great if you added support to the nintendo switch version

**Comment by krzys-h** [comment]
Actually, the Nintendo Switch release should be already able to load (or at least the Japanese release @NarryG was testing yesterday), just not save yet. I'm working on that though.

**Comment by Mc-muffin** [comment]
How are you trying to add them? Last time I checked they need to be placed according to their places in the UTF-8 chart (wich is ¡ ¿ Á É Í Ñ Ó Ú Ü á é í ñ ó ú ü )

**Comment by D3fau4** [comment]
> How are you trying to add them? Last time I checked they need to be placed according to their places in the UTF-8 chart (wich is ¡ ¿ Á É Í Ñ Ó Ú Ü á é í ñ ó ú ü )

but how?

**Comment by D3fau4** [comment]
> How are you trying to add them? Last time I checked they need to be placed according to their places in the UTF-8 chart (wich is ¡ ¿ Á É Í Ñ Ó Ú Ü á é í ñ ó ú ü )

We have modified the sprites by adding the characters and adding the coordinates of each letter to the character tables. But it does not work for anything.

**Comment by Mc-muffin** [comment]
That's weird, may I see a screenshot?

**Comment by D3fau4** [comment]
> That's weird, may I see a screenshot?

![captura_de_pantalla_2018-09-20_a_las_14 00 23](https://user-images.githubusercontent.com/19638408/45837666-1ab50f00-bd10-11e8-8c77-2065d5c30a70.png)
![captura_de_pantalla_2018-09-20_a_las_13 57 20-1](https://user-images.githubusercontent.com/19638408/45837667-1ab50f00-bd10-11e8-9c37-8c1d92692beb.png)
![captura_de_pantalla_2018-09-20_a_las_15 14 00](https://user-images.githubusercontent.com/19638408/45837668-1b4da580-bd10-11e8-95a9-2244c4d599de.png)
![captura_de_pantalla_2018-09-20_a_las_13 43 37](https://user-images.githubusercontent.com/19638408/45837669-1b4da580-bd10-11e8-9855-d75db04f24ca.png)
everything is made with Photoshop

**Comment by Mc-muffin** [comment]
Okay I did it! (It's the switch version, don't be fooled by the PC launcher)

![image](https://user-images.githubusercontent.com/8714476/45880277-110dc480-bd6d-11e8-9421-fc1849888d88.png)


Before you jump into conclusions, no those are not Kana characters (just look like them), I just used them to avoid doing image editing :P Here's proof:

![image](https://user-images.githubusercontent.com/8714476/45880107-77461780-bd6c-11e8-86e1-466690c58c29.png)

In this case the accented characters were replaced with the Japanese syllabary, (あぁいぃえぇうぅ etc) but yours will be the correct accented characters from your edited texture.


**The process:**
Well, just input the characters in ascending order!  I took the liberty to add the (Ü/ü) to the listing, I don't know if you even use it in the translation but if you don't, simply skip it's character number. So, to fix it replace your previous ordering:

Your number order | Character| Correct number order | Character
----------------------|-----------|-------------------------|-----------
225| á | 161 | ¡
233| é|191 |¿
237|í|193|Á
243|ó|201|É
250|ú|205|Í
193|Á|209|Ñ
201|É|211|Ó
205|Í|218|Ú
211|Ó|220|Ü
218|Ú|225|á
241|ñ|233|é
191|¿|237|í
161|¡|241|ñ
209|Ñ|243|ó
 N/A|N/A|250|ú
 N/A|N/A|252|ü

As I said it needed to be in the same order as they appear on the UTF-8 character table. 
And that would be it, if another problem arise just ask.

¡Espero que funcione!

**Comment by D3fau4** [comment]
> Okay I did it! (It's the switch version, don't be fooled by the PC launcher)
> 
> ![image](https://user-images.githubusercontent.com/8714476/45880277-110dc480-bd6d-11e8-9421-fc1849888d88.png)
> 
> Before you jump into conclusions, no those are not Kana characters (just look like them), I just used them to avoid doing image editing :P Here's proof:
> 
> ![image](https://user-images.githubusercontent.com/8714476/45880107-77461780-bd6c-11e8-86e1-466690c58c29.png)
> 
> In this case the accented characters were replaced with the Japanese syllabary, (あぁいぃえぇうぅ etc) but yours will be the correct accented characters from your edited texture.
> 
> **The process:**
> Well, just input the characters in ascending order! I took the liberty to add the (Ü/ü) to the listing, I don't know if you even use it in the translation but if you don't, simply skip it's character number. So, to fix it replace your previous ordering:
> 
> Your number order	Character	Correct number order	Character
> 225	á	161	¡
> 233	é	191	¿
> 237	í	193	Á
> 243	ó	201	É
> 250	ú	205	Í
> 193	Á	209	Ñ
> 201	É	211	Ó
> 205	Í	218	Ú
> 211	Ó	220	Ü
> 218	Ú	225	á
> 241	ñ	233	é
> 191	¿	237	í
> 161	¡	241	ñ
> 209	Ñ	243	ó
> N/A	N/A	250	ú
> N/A	N/A	252	ü
> NOTE: I think it's obvious, but it doesn't hurt to say it, you don't need to redo the texture, just input the characters and their coordinates in the correct order.
> 
> As I said it needed to be in the same order as they appear on the UTF-8 character table.
> And that would be it, if another problem arise just ask.
> 
> ¡Espero que funcione!

ahora el problemas que las letras se ponen gigantes no se porque

**Comment by krzys-h** [comment]
Thanks for your research! I will add that to the wiki soon, I'm not sure this fits with all the format docs but it needs to be written down somewhere.

I may add a "font wizard" later which would take care of all of this for you, including rendering the characters into the texture so you don't have to edit it yourself. I was even thinking about making a mod that would make creationof user-contributed translations easier (you would have an online editor with preview, the game would auto-update from that and handle all font stuff for you, since I'm pretty sure you CAN add fonts at runtime in GML)

**Comment by krzys-h** [comment]
Thanks for your research! I will add that to the wiki soon, I'm not sure this fits with all the format docs but it needs to be written down somewhere.

I may add a "font wizard" later which would take care of all of this for you, including rendering the characters into the texture so you don't have to edit it yourself. I was even thinking about making a mod that would make creationof user-contributed translations easier (you would have an online editor with preview, the game would auto-update from that and handle all font stuff for you, since I'm pretty sure you CAN add fonts at runtime in GML)

**Comment by krzys-h** [comment]
https://docs.yoyogames.com/source/dadiospice/002_reference/game%20assets/fonts/font_add.html
Wait, you can even load a standard .ttf file?!
Yeah, I'm definitely going to try implementing that soon, would make your life so much easier

**Comment by krzys-h** [comment]
I promised so I made it: [this script](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/SampleScripts/TTFFonts.csx) will make the game load fonts from TTF files in the current directory instead of using the embedded textures.

You will have to find all the fonts yourself as I cannot host them here for licensing reasons. Especially DotumChe is questionable, as online you can find it only as a paid font. You can get it for free though by downloading the Korean font pack which is an [optional feature of Windows 10](https://docs.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts). You will need a tool that can extract the ttf file from a ttc package too, FontForge should do.

Note that some of these fonts don't have accented characters anyway so it may be not as useful as I thought... but the main game font 8bitoperator_jve seems to have some! And Comic Sans and Papyrus are likely to have a bunch for many languages too. Other fonts are not really used that much, so you could probably live without accented charecters in them.

**Comment by D3fau4** [comment]
thank you very much, thanks to you I can continue with the translation into Spanish

**Comment by costelabr17** [comment]
hi i have same issue a @D3fau4  i need to add this charectes on my portuguese brazilian translate 
ÁáÂâÀàÅåÃãÄäÆæÉéÊêÈèËëÍíÎîÌìÏïÓóÔôÒòÕõÖöÚúÛûùÙÜüÇçÑñÝý¿
but i don't know how someone please can help me to finish my work? i don't have much experience is my first work in translation

**Comment by Mc-muffin** [comment]
@costelabr17 Did you figured it out already or do you still need help?

**Comment by costelabr17** [comment]
No, i'm at same point, no have ideia to make it works 

> @costelabr17 Did you figured it out already or do you still need help?

**Comment by Mc-muffin** [comment]
~Okay, I'll make you a tutorial!~

I ended up making an easier method that the one depicted originally in the tutorial, so I'll save you the work:
I assume you are translating Deltarune, so download this: [Export_fonts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937730/Export_fonts.zip) (**extract** it anywhere easy to spot) and this: [fontScripts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937624/fontScripts.zip) extract this one inside ``[UTMT folder]/SampleScripts``

Now open Deltarune's ``data.win`` and run the ``fntimport`` script, a window will pop-out asking you to select a folder, select the ``Export_fonts`` folder you **extracted** earlier, enjoy!


## How-To
If you want to know how I did this here's the aforementioned tutorial, it's a little involved

There are two ways of adding fonts, the "automated" one or the manual way (I won't describe the manual way here):
## The "automated" way:
Currently the easiest and quickest way to add missing glyphs

You'll need:
- GameMaker: Studio 1.4 or GM: S 2, doesn't matter
- A font (`.ttf` or `.otf`) installed in your system that has the characters you need
- Undertale Mod Tool & the game's data.win
- These font import & export scripts [fontScripts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937624/fontScripts.zip) (heavily based from the Sprite export & import scripts, all credits to the creator/s) extract it inside ``[UTMT folder]/SampleScripts``
- Some free time

### for GameMaker 1.4
#### Step 1 - Set-Up:
Create a new project
![image](https://user-images.githubusercontent.com/8714476/70396880-edb74f80-19da-11ea-8e06-90301dd4be66.png)
The name (2) is optional, can be anything

Now create a new room, for that right click the `Rooms` folder at the left and click on `Create Room` 
![image](https://user-images.githubusercontent.com/8714476/70396925-5d2d3f00-19db-11ea-991b-ae4235606fbb.png)
A new window will pop-up, close it we don't need it

#### Step 2 - Font creation & addin Characters:
The same way you created a new Room, create a new font 
![image](https://user-images.githubusercontent.com/8714476/70396958-c57c2080-19db-11ea-81c4-e7cc7e3f93f4.png)

You'll be presented with this window
![image](https://user-images.githubusercontent.com/8714476/70396969-dcbb0e00-19db-11ea-8b3a-05230a520bba.png)

To add characters click on the ``+`` at the bottom
![image](https://user-images.githubusercontent.com/8714476/70397020-78e51500-19dc-11ea-9bc6-7e5cb1b70d26.png)

Upon clicking``+`` you'll be presented this window
![image](https://user-images.githubusercontent.com/8714476/70397069-eabd5e80-19dc-11ea-8fc6-598f451f9353.png)

Here you put the characters you need in the box (1) and then click on Ok (2)
![image](https://user-images.githubusercontent.com/8714476/70397050-c6618200-19dc-11ea-9e44-e3083e25e4c1.png)

You know you did it correctly if you see the added characters in the previous window
![image](https://user-images.githubusercontent.com/8714476/70397105-3d971600-19dd-11ea-9439-5d355288eb1e.png)

Now, for the info on the left:
![image](https://user-images.githubusercontent.com/8714476/70397145-b39b7d00-19dd-11ea-85cb-65d2ee27ec42.png)
You can source it from Undertale Mod Tool:
![image](https://user-images.githubusercontent.com/8714476/70397184-05440780-19de-11ea-9b7c-391ef0d6577a.png)

Result:
![image](https://user-images.githubusercontent.com/8714476/70397540-1e01ec80-19e1-11ea-99da-536e899b2657.png)
In the ``Font`` field all your system fonts will be displayed, so make sure you have the fonts that you need installed!
(Always Un-tick "High-Quality" to get pixellated fonts)
After that just click Ok to save the changes (you can repeat this step to add the remainig fonts now)

#### Step 3 - Getting the fonts:
Now run the project:
![image](https://user-images.githubusercontent.com/8714476/70397278-f0b43f00-19de-11ea-98c9-28803ca4e162.png)
A blank game window should open, close it, we don't need it

Now go the GameMaker temp, directory (you can check where it is by checking File>Preferences>Temp Directory) and open the ``.win`` file with UndertaleModTool and checking the fonts that it has
![image](https://user-images.githubusercontent.com/8714476/70397558-615c5b00-19e1-11ea-897b-54dc3c122849.png)
Success!

Now use the fntexport script from earlier
![image](https://user-images.githubusercontent.com/8714476/70397580-86e96480-19e1-11ea-8bac-80208aaedf02.png)
the files will be in the same folder of the data.win, inside a folder called ``Export_fonts``

#### Step 4 - Replacing the fonts:
Open the ``data.win`` in which you are going to apply the modified fonts (Deltarune in this example) and now select the ``fntimport`` script
![image](https://user-images.githubusercontent.com/8714476/70397908-31fb1d80-19e4-11ea-9229-a59b0ecbdc2b.png)
a window will pop-up asking you to select a folder, select the ``Export_fonts`` folder that the ``fntexport`` script created earlier

You are done! Now repeat the process with the remaining fonts.

**Comment by costelabr17** [comment]
Man thank you so much for this!!!!!

**Comment by costelabr17** [comment]
> ~Okay, I'll make you a tutorial!~
> 
> I ended up making an easier method that the one depicted originally in the tutorial, so I'll save you the work:
> I assume you are translating Deltarune, so download this: [Export_fonts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937730/Export_fonts.zip) (**extract** it anywhere easy to spot) and this: [fontScripts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937624/fontScripts.zip) extract this one inside `[UTMT folder]/SampleScripts`
> 
> Now open Deltarune's `data.win` and run the `fntimport` script, a window will pop-out asking you to select a folder, select the `Export_fonts` folder you **extracted** earlier, enjoy!
> 
> ## How-To
> If you want to know how I did this here's the aforementioned tutorial, it's a little involved
> 
> There are two ways of adding fonts, the "automated" one or the manual way (I won't describe the manual way here):
> 
> ## The "automated" way:
> Currently the easiest and quickest way to add missing glyphs
> 
> You'll need:
> 
> * GameMaker: Studio 1.4 or GM: S 2, doesn't matter
> * A font (`.ttf` or `.otf`) installed in your system that has the characters you need
> * Undertale Mod Tool & the game's data.win
> * These font import & export scripts [fontScripts.zip](https://github.com/krzys-h/UndertaleModTool/files/3937624/fontScripts.zip) (heavily based from the Sprite export & import scripts, all credits to the creator/s) extract it inside `[UTMT folder]/SampleScripts`
> * Some free time
> 
> ### for GameMaker 1.4
> #### Step 1 - Set-Up:
> Create a new project
> ![image](https://user-images.githubusercontent.com/8714476/70396880-edb74f80-19da-11ea-8e06-90301dd4be66.png)
> The name (2) is optional, can be anything
> 
> Now create a new room, for that right click the `Rooms` folder at the left and click on `Create Room`
> ![image](https://user-images.githubusercontent.com/8714476/70396925-5d2d3f00-19db-11ea-991b-ae4235606fbb.png)
> A new window will pop-up, close it we don't need it
> 
> #### Step 2 - Font creation & addin Characters:
> The same way you created a new Room, create a new font
> ![image](https://user-images.githubusercontent.com/8714476/70396958-c57c2080-19db-11ea-81c4-e7cc7e3f93f4.png)
> 
> You'll be presented with this window
> ![image](https://user-images.githubusercontent.com/8714476/70396969-dcbb0e00-19db-11ea-8b3a-05230a520bba.png)
> 
> To add characters click on the `+` at the bottom
> ![image](https://user-images.githubusercontent.com/8714476/70397020-78e51500-19dc-11ea-9bc6-7e5cb1b70d26.png)
> 
> Upon clicking`+` you'll be presented this window
> ![image](https://user-images.githubusercontent.com/8714476/70397069-eabd5e80-19dc-11ea-8fc6-598f451f9353.png)
> 
> Here you put the characters you need in the box (1) and then click on Ok (2)
> ![image](https://user-images.githubusercontent.com/8714476/70397050-c6618200-19dc-11ea-9e44-e3083e25e4c1.png)
> 
> You know you did it correctly if you see the added characters in the previous window
> ![image](https://user-images.githubusercontent.com/8714476/70397105-3d971600-19dd-11ea-9439-5d355288eb1e.png)
> 
> Now, for the info on the left:
> ![image](https://user-images.githubusercontent.com/8714476/70397145-b39b7d00-19dd-11ea-85cb-65d2ee27ec42.png)
> You can source it from Undertale Mod Tool:
> ![image](https://user-images.githubusercontent.com/8714476/70397184-05440780-19de-11ea-9b7c-391ef0d6577a.png)
> 
> Result:
> ![image](https://user-images.githubusercontent.com/8714476/70397540-1e01ec80-19e1-11ea-99da-536e899b2657.png)
> In the `Font` field all your system fonts will be displayed, so make sure you have the fonts that you need installed!
> (Always Un-tick "High-Quality" to get pixellated fonts)
> After that just click Ok to save the changes (you can repeat this step to add the remainig fonts now)
> 
> #### Step 3 - Getting the fonts:
> Now run the project:
> ![image](https://user-images.githubusercontent.com/8714476/70397278-f0b43f00-19de-11ea-98c9-28803ca4e162.png)
> A blank game window should open, close it, we don't need it
> 
> Now go the GameMaker temp, directory (you can check where it is by checking File>Preferences>Temp Directory) and open the `.win` file with UndertaleModTool and checking the fonts that it has
> ![image](https://user-images.githubusercontent.com/8714476/70397558-615c5b00-19e1-11ea-897b-54dc3c122849.png)
> Success!
> 
> Now use the fntexport script from earlier
> ![image](https://user-images.githubusercontent.com/8714476/70397580-86e96480-19e1-11ea-8bac-80208aaedf02.png)
> the files will be in the same folder of the data.win, inside a folder called `Export_fonts`
> 
> #### Step 4 - Replacing the fonts:
> Open the `data.win` in which you are going to apply the modified fonts (Deltarune in this example) and now select the `fntimport` script
> ![image](https://user-images.githubusercontent.com/8714476/70397908-31fb1d80-19e4-11ea-9229-a59b0ecbdc2b.png)
> a window will pop-up asking you to select a folder, select the `Export_fonts` folder that the `fntexport` script created earlier
> 
> You are done! Now repeat the process with the remaining fonts.

man i'ts awesome tuto thank you so much, i will make Deltarune translation too, i on 60%, this method will work too ?

**Comment by costelabr17** [comment]
Thank you so much for this amazing tutorial, this steps works with Deltarune too?

**Comment by BreakinBenny** [comment]
I'm willing to bet this can also be done _without_ GMS.

**Comment by costelabr17** [comment]
Strange is font import and export scripts shows errors to me, maybe have diff with game win from switch version to The PC version, i am working with nx version

**Comment by Mc-muffin** [comment]
@costelabr17 Show me the errors and I'll see if I can fix them, also this should work with everything, you just need to get the fonts xd the pre-done ones I left at the start are for Deltarune actually :p

**Comment by Mc-muffin** [comment]
@BreakinBenny Actually, it can be done without it, but it would have to be completely manual (right now at least) so for adding many characters to a font (for example Korean characters) it would take waaaay too long. if you want an automated version the scripts from my answer are almost that it just need a rasterizer for the fonts and then the definition generator.

**Comment by costelabr17** [comment]
![20191209_181811](https://user-images.githubusercontent.com/43475497/70474100-bca94e80-1ab0-11ea-9b2c-af778ffa6481.jpg)


![20191209_181845](https://user-images.githubusercontent.com/43475497/70474139-d34fa580-1ab0-11ea-8ba7-bf2919de2738.jpg)

**Comment by costelabr17** [comment]
first error shows when i try EXPORT fonts from game.win Deltarune or Undertale:

TextureWorkes not contain definition to "Cleanup" and is not possible find any method of extension "Cleanup" who acept the first argument of "TextureWorker" type. ( you are forgetting to use a directive or assembly reference )

second erro when try use IMPORT:

The name "PromptChooseDirectory" does not exist in the current context

**Comment by Mc-muffin** [comment]
I think you are using an outdated version of UTMT, try with this one: [UndertaleModTool-bac5a61587.zip](https://cdn.discordapp.com/attachments/589826508957286400/647299414695870475/UndertaleModTool-bac5a61587.zip)

**Comment by costelabr17** [comment]
> I think you are using an outdated version of UTMT, try with this one: [UndertaleModTool-bac5a61587.zip](https://cdn.discordapp.com/attachments/589826508957286400/647299414695870475/UndertaleModTool-bac5a61587.zip)

Same error with this version too

**Comment by Grossley** [comment]
You probably did not actually load the new version, rather instead clicking on the data.win, which would be aliased to the old version. The new version would work with at least one of the directories. @costelabr17 I would love to help you more in a more immediate fashion. If you come to our Discord server I will be able to help you much more immediately. Could you do that?

**Comment by Mc-muffin** [comment]
@costelabr17 Yeah, try opening the new Undertale Mod Tool first, and then loading the data.win

**Comment by costelabr17** [comment]
@Mc-muffin  same error

**Comment by costelabr17** [comment]
if you need i can uploded game.win files from switch Undertale and Deltarune

**Comment by Mc-muffin** [comment]
The problem seems to be within your installation of UTMT tho, anyways you can't share them here, do you have Discord? That way I can add the modified fonts for you if you still have the error message poping out

**Comment by costelabr17** [comment]
> The problem seems to be within your installation of UTMT tho, anyways you can't share them here, do you have Discord? That way I can add the modified fonts for you if you still have the error message poping out

Of course bro, i can send to you in discord my discord Nick is Costelabr#0829 add me or send me your nick please. And again thank you so much for the help, now i can finalize my translation

**Comment by Cmeldo** [comment]
How I can do it in game maker 2?

**Comment by Cmeldo** [comment]
@Mc-muffin  how I can do it now in game maker 2?

**Comment by Archie-osu** [comment]
> 
> 
> @Mc-muffin how I can do it now in game maker 2?

Please make a new issue. This is a very old one on top of being solved.

**Comment by ericasof** [comment]
@Mc-muffin Hello! I'm translating the introduction of deltarune into Portuguese for a uni project and used the method you said about using UndertaleModTool and I added the fonts and it was working fine, but when I get to the Dark World for some reason it stops working? When I'm in the closet scene it's still working but as soon as I interact with something in the Dark World blank spaces start appearing again instead of the new characters... Do you think you could help me with this? Because I really have no idea why this would happen. Thank you in advance!

**Comment by Jacky720** [comment]
Since the Dark World runs at a higher resolution than the Light World (makes combat appear smoother), I believe it uses a separate font file.

**Comment by ericasof** [comment]
> Since the Dark World runs at a higher resolution than the Light World (makes combat appear smoother), I believe it uses a separate font file.

Thank you! So how would I go about resolving this?

**Comment by ericasof** [comment]
> @Mc-muffin Hello! I'm translating the introduction of deltarune into Portuguese for a uni project and used the method you said about using UndertaleModTool and I added the fonts and it was working fine, but when I get to the Dark World for some reason it stops working? When I'm in the closet scene it's still working but as soon as I interact with something in the Dark World blank spaces start appearing again instead of the new characters... Do you think you could help me with this? Because I really have no idea why this would happen. Thank you in advance!

@Mc-muffin I figured out what the problem is, in the files you asked us to download, you didn't include the font mainbig! However when I try doing your step-by-step of how you did it it does not work.

**Comment by kamnanrock** [comment]
I finished change in-game font. But, when I run my game with my language (Thai language), it show my homeland language like this. How can I fixed it???
![ภาพหน้าจอ (321)](https://user-images.githubusercontent.com/103934565/163799420-648fc8e9-a21d-4b18-997b-85ddd5f16c36.png)
