### ISSUE TITLE
Adding a Tiles/Assets Layer doesn't work

### ISSUE THREAD

**Issue by Agent517** [krzys-h/UndertaleModTool#802]
Steps to reproduce:
1. Open any GMS 2.3+ (GMS2+ if adding a Tiles layer) game and select any room.
2. Right click the Layers tab in the room editor, and select either "New Assets layer" or "New Tiles layer".
3. The tool will immediately crash with this error if Tiles layer was selected:
![Screenshot 2022-03-22 152648](https://user-images.githubusercontent.com/87152256/159560346-4e9a3bae-787d-44f0-9666-91be8957a653.png)
If Assets layer was selected...
4. Attempt to save the game.
The tool throws this error:
![Screenshot 2022-03-22 135635](https://user-images.githubusercontent.com/87152256/159560190-7f558763-0656-46e3-8ce2-28c292224e94.png)

**Comment by VladiStep** [comment]
What version of UndertaleModTool is this?

**Comment by Agent517** [comment]
0.4.0.4, I tried both the single file version and the NSF version and the error appeared to be the same.
