### ISSUE TITLE
when ever i try to open the program it closes with out my input.

### ISSUE THREAD

**Issue by higbigmig** [krzys-h/UndertaleModTool#816]

**Comment by BenjaminUrquhart** [comment]
Elaborate

**Comment by higbigmig** [comment]
> 

i open folder
i find .exe
program opens
closes instantly
when the window doesn't close its just a black box
(bonus question: do i need gamemaker for it to work???)

**Comment by Jacky720** [comment]
You do not need GameMaker for it to work. What is your operating system?

**Comment by higbigmig** [comment]
> You do not need GameMaker for it to work. What is your operating system?

windows 10, why?

**Comment by NyakoFox** [comment]
> closes instantly when the window doesn't close its just a black box

I assume they accidentally downloaded the CLI version

**Comment by higbigmig** [comment]
> > closes instantly when the window doesn't close its just a black box
> 
> I assume they accidentally downloaded the CLI version

…god damn it 
WHICH VERSION DO I DOWNLOAD THEN
