### ISSUE TITLE
An error ocurred while trying to load , Unable to cast Object of type ´layer´ to type ´layer effcet data´

### ISSUE THREAD

**Issue by MrSpacetime** [krzys-h/UndertaleModTool#825]
I got this error when i wanted to mod a game from ElPichón called 4-1-1992 , could someone help me? 
![image](https://user-images.githubusercontent.com/103225464/162336938-637cf1cb-1a93-4bc9-9740-ae20814083da.png)

**Comment by Jacky720** [comment]
You could try the [cutting-edge builds](https://nightly.link/krzys-h/UndertaleModTool/workflows/build_net/master/win_x64.zip).

**Comment by MrSpacetime** [comment]
i will , and ill tell you if it works

**Comment by MrSpacetime** [comment]
> You could try the [cutting-edge builds](https://nightly.link/krzys-h/UndertaleModTool/workflows/build_net/master/win_x64.zip).

Sadly it didnt work , i got a different error this time
![image](https://user-images.githubusercontent.com/103225464/162338387-bb278c91-9901-4507-a21e-00dc8e81cd96.png)

**Comment by MrSpacetime** [comment]
?

**Comment by Miepee** [comment]
Duplicate of #722 ?

**Comment by Miepee** [comment]
@MrSpacetime can you try again?

**Comment by TheKitBoi** [comment]
None of the New GUI Builds fixes the issue

**Comment by Mr-Unown** [comment]
This definitely is a result of the filter effect layers

**Comment by MrSpacetime** [comment]
Welp i tried everything , i think ill just wait

**Comment by EdyDude** [comment]
Same
