### ISSUE TITLE
Disc Room failing on UTMT

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#828]
![image](https://user-images.githubusercontent.com/38186597/162584120-fd55750c-8f44-4186-9de5-5a72dd14611b.png)
GOG version of Disc Room
Tested on commit dc006f0

**Comment by JohnnyonFlame** [comment]
fwiw, I commented out the Mask padding entirely, and the game apparently serializes correctly. Maybe there are versions out in the wild where there's no padding?

**Comment by Miepee** [comment]
Actually, this is apparently a duplicate of #338

**Comment by IntangibleMatter** [comment]
> fwiw, I commented out the Mask padding entirely, and the game apparently serializes correctly. Maybe there are versions out in the wild where there's no padding?

Can you elaborate? I'm trying to decomp Disc Room but I can't figure out how to do this properly. Just commenting out the contents of (or calls to) `ReadMaskData` doesn't work and breaks things in a new way
