### ISSUE TITLE
an error occurs when loading the archive

### ISSUE THREAD

**Issue by r545n** [krzys-h/UndertaleModTool#83]
An error occurs when loading the archive. She looks like this:
![3](https://user-images.githubusercontent.com/45150485/48677010-9fd96a80-eb7f-11e8-8608-c09da8dc2d9d.PNG)

**Comment by r545n** [comment]
> Этот подтекст, но он, казалось, открылся в quickBMS. Может быть, это из - за того, что они перевели на другой язык?

yea

**Comment by krzys-h** [comment]
Yeah, probably. Many other tools are known to generate files that contain slight errors that are ignored by the GMS runner, but are handled more strictly by UndertaleModTool to avoid data loss. There is no way to open such files at the moment other than to revert to the unmodified version.

**Comment by r545n** [comment]
well thanks, I will try to think of something else
