### ISSUE TITLE
Death's Gambit (original ver) regression

### ISSUE THREAD

**Issue by Miepee** [krzys-h/UndertaleModTool#833]
[Death Gambit (original version)](https://steamcommunity.com/app/356650/discussions/0/2960544821834837966/) regressed.
![image](https://user-images.githubusercontent.com/38186597/162973408-1e6ae568-b8ea-4be8-bb2c-f04256c68093.png)

Broke somewhere between dc006f0ec68e2fb6a10cf47b939b014a8b20762e and 4eaf7164fea3f7bbe086bdcf074ab4fe4b7a5014

**Comment by Miepee** [comment]
@JohnnyonFlame bisected, caused by a73a3a8d1103

**Comment by JohnnyonFlame** [comment]
`git checkout a73a3a8d -- UndertaleModLib/UndertaleChunks.cs` still has the breakage present
`git checkout a73a3a8d -- UndertaleModLib/UndertaleChunks.cs` fixes the issue

**Comment by Miepee** [comment]
your second line has a typo I think

**Comment by Miepee** [comment]
Is now also affecting Death's Gambit v1.2
