### ISSUE TITLE
Double-clicking audio file pops up new window except welcome screen.

### ISSUE THREAD

**Issue by sparskakyl** [krzys-h/UndertaleModTool#84]
This tbh...

![Screenshot](https://user-images.githubusercontent.com/40243009/48718077-91885e80-ec12-11e8-8fae-f4e7498e393c.png)

**Comment by krzys-h** [comment]
It should load the detached `audiogroup1.dat` file in the second instance. Do you have both files in the same directory? Does it show any errors? What is the path to the directory with the files, does it have any suspicious characters that could be breaking something?
