### ISSUE TITLE
Unable to save changes when making a new room

### ISSUE THREAD

**Issue by Cmdpro** [krzys-h/UndertaleModTool#846]
Im trying to mod a game but whenever i make a room and add an instances layer and an object this error shows up
This is a blank game that it also happens on, both games are 2.3 so it is probally a 2.3 problem
![Screenshot (161)](https://user-images.githubusercontent.com/73263645/164162648-ced219b0-247c-431b-8489-3faaec33cb94.png)
[blank-game.zip](https://github.com/krzys-h/UndertaleModTool/files/8518724/blank-game.zip)
![Screenshot (162)](https://user-images.githubusercontent.com/73263645/164162655-f77a3c27-1f22-499e-a515-81a22704c5c1.png)

My UndertaleModTool version is 0.4.0.4

**Comment by Cmdpro** [comment]
im gonna try again but with more info

**Comment by Miepee** [comment]
Can you attach a zip of a test data.win file?

**Comment by Jacky720** [comment]
Well, if it is no longer crashing just on adding the instance, only on saving, by the second screenshot... It seems like a legitimate error. The instance definition is empty, and it needs to not be.

**Comment by Cmdpro** [comment]
> Can you attach a zip of a test data.win file?

blank-game.zip it happens on, for testing using the data.win in there will work
