### ISSUE TITLE
Add GUI editors for EMBI and TGIN

### ISSUE THREAD

**Issue by krzys-h** [krzys-h/UndertaleModTool#86]
ping @colinator27 @LinXP

**Comment by Kneesnap** [comment]
Example game with TGIN and EMBI: Fromto VM. However, it seems TGIN already has an editor.

**Comment by Kneesnap** [comment]
Implemented in https://github.com/krzys-h/UndertaleModTool/commit/0018c2d4a57f8a192cafd7a84c0e50c5396db923
