### ISSUE TITLE
So uh this happens. (Save Error) (Solved, close)

### ISSUE THREAD

**Issue by 07conicNuts** [krzys-h/UndertaleModTool#861]
![image](https://user-images.githubusercontent.com/100186539/165343393-381c5ef2-e60b-4440-8d29-4fd10031c7fd.png)

**Comment by Jacky720** [comment]
Try moving your Undertale files out of the Program Files directory, since that requires administrator access to modify. Or just run UndertaleModTool as administrator.

**Comment by 07conicNuts** [comment]
> Try moving your Undertale files out of the Program Files directory, since that requires administrator access to modify. Or just run UndertaleModTool as administrator.

Hey, thank you. It works!
