### ISSUE TITLE
Error saving "new game"

### ISSUE THREAD

**Issue by LinXP** [krzys-h/UndertaleModTool#87]
I know that this is a joke, but if you create a new game and try to save it, it will cause an error.
http://i.prntscr.com/5WOx8YLcT9OFfRxn-HOgVg.png

**Comment by colinator27** [comment]
Whoops, that's my fault... I know exactly what's going wrong.

**Comment by colinator27** [comment]
However the way to fix it is debatable. Should we make `WriteUndertaleObject` do a null check, or should we somehow initialize those objects to a non-null value?

**Comment by krzys-h** [comment]
WriteUndertaleObjectPointer should handle nulls if I remember correctly. WriteUndertaleObject makes no sense on a null value - UndertaleResourceById should always be initialised (to allow assigning to the .Resource field in editors, I actually broke that when refactoring the code and fixed it later) and I can't think of any other case where you would want to call it on a null value.

**Comment by colinator27** [comment]
https://github.com/krzys-h/UndertaleModTool/blob/831d61e1c5b8429339f6fa76af122373bf492714/UndertaleModLib/Models/UndertaleGeneralInfo.cs#L216-L218

These are null by default, and I directly call `WriteUndertaleObject`. That's the cause of this.

**Comment by krzys-h** [comment]
These should be initialized to empty TextureEntry items instead - otherwise, you won't be able to assign to BackImage.Texture in the editor for them.

**Comment by krzys-h** [comment]
@colinator27 I had to fix one more thing in the EXTN chunk, it works now

**Comment by colinator27** [comment]
Oh, didn't notice that either...

**Comment by colinator27** [comment]
I should probably run those tests from now on...
