### ISSUE TITLE
Decompiling takes forever… or never happens

### ISSUE THREAD

**Issue by BreakinBenny** [krzys-h/UndertaleModTool#91]
When I choose the tab for decompiled code, the loading bar says it's decompiling and it can take a while on complex scripts...

But nothing happens. I didn't have this problem prior to v0.1.19 (I update when there's a new version of this available). What happened? Does this version of UndertaleModTool not agree with my Windows 10 64-bit machine or is there something that interferes with the application trying to show me decompiled GameMaker code?

**Comment by krzys-h** [comment]
What file are you trying to open? Nothing like that happens for me on either Undertale or Deltarune

**Comment by BreakinBenny** [comment]
I've tried opening the global scripts, the goner maker thing, and even the oneI could go on forever trying them all and not get any other result than a Sonic '06 loading that hangs itself instead of successfully loading.

I've also been in gml_Object_DEVICE_MENU_Draw_0 and its siblings in prior versions, but now I can't open that shit up.

**Comment by krzys-h** [comment]
It sure works for me, and loads in less than a second. Does the progress bar still animate, or is it stuck in place? Try to also give as much relevant system details as you can, I have absolutely no idea what could be causing this

**Comment by BreakinBenny** [comment]
The progress bar animates, but it refuses to show me the decompiled code. Here are my specs: 
![windows system](https://user-images.githubusercontent.com/4566768/48871802-8c7c0880-ede6-11e8-8969-b32178a254e4.jpg)

…And my graphics card is a Geforce GTX 960. (It's really funny how earlier versions of UndertaleModTool worked perfectly for this machine of mine, but all of a sudden it goes "NOPE")

**Comment by BreakinBenny** [comment]
Surprisingly, this works flawlessly when I use a HP Elitebook 2560p after just installing Deltarune and getting the UndertaleModTool... I can't even be certain what other things are required to show decompiled code. I don't want to be forced to mod from a computer I use when not at home!

**Comment by krzys-h** [comment]
That's really strange, there must be something wrong with your system, I've never seen anything like this happen. The only reason this could be happening is if the decompiling thread dies without throwing an exception or something.

You can also try File > Batch decompile, maybe that works?

**Comment by BreakinBenny** [comment]
Batch decompile worked, and I can open the GML files. That's... pretty comforting, to say the least.

**Comment by krzys-h** [comment]
That's... very strange considering that the code is almost the same for both of them. Wbsolutely no idea what is going on, but glad you got it kinda sorted out. You shouldn't run into any other problems because the Decompiled tab is view-only anyway (at least for now)
