### ISSUE TITLE
Bug: Padding Error while trying to load when reading a TXTR

### ISSUE THREAD

**Issue by realdoomsboygaming** [krzys-h/UndertaleModTool#917]
### Describe the bug

When trying to load new data.win file from the game Lost Nova, consistent misalignments occur and end with an error. Image provided.
![image](https://user-images.githubusercontent.com/105606471/168490088-2663d2fb-f7db-4698-850d-6ef4399c6dde.png)
I don't know if I'm legally allowed to post the data.win but I'll attach it for easier debugging. 
[https://drive.google.com/file/d/1JnI5h7JMz_Kw3_9nG8ylvVtceCPTjH8h/view?usp=sharing](https://drive.google.com/file/d/1JnI5h7JMz_Kw3_9nG8ylvVtceCPTjH8h/view?usp=sharing)

### Reproducing steps

1. open the latest version 4.04 
2. Select the data.win 
3. Massive string of errors

### Setup Details

1. Use the Latest 4.04 version.
2. Windows 10 x64 Latest Update as of writing
3. Game: Lost Nova 
4. Steam Page Link: [https://store.steampowered.com/app/1603410/Lost_Nova/](https://store.steampowered.com/app/1603410/Lost_Nova/)

**Comment by Jacky720** [comment]
It works for me, on [bleeding edge builds](https://nightly.link/krzys-h/UndertaleModTool/workflows/publish_gui/master/windows-latest-isBundled-true-isSingleFile-true.zip) of the tool. Takes a good while, but it works. Can you try that?

**Comment by Miepee** [comment]
Can also confirm that the data file loads in fine on action builds.
(Heres another link for actions, but those you can only download via a GH account https://github.com/krzys-h/UndertaleModTool/actions/workflows/publish_gui.yml)

**Comment by Grossley** [comment]
This issue is already resolved in commits past this release.
