### ISSUE TITLE
Add batch export and import for all resources

### ISSUE THREAD

**Issue by Small-Miao** [krzys-h/UndertaleModTool#92]
Add Export all sprite sound audio

**Comment by krzys-h** [comment]
Although this was never the main goal if this tool, it definiteky would be nice to have

**Comment by krzys-h** [comment]
Although this was never the main goal if this tool, it definiteky would be nice to have

**Comment by nixxo** [comment]
@Small-Miao script to export textures if you need it #119

**Comment by krzys-h** [comment]
There a are a couple scripts that can help you before this is implemented:
* Textures: https://github.com/krzys-h/UndertaleModTool/issues/119#issue-388940305
* Strings: https://github.com/krzys-h/UndertaleModTool/issues/26#issuecomment-425741706
* Font glyphs: https://github.com/krzys-h/UndertaleModTool/issues/20#issuecomment-426373612

**Comment by Kneesnap** [comment]
Added some exporters in https://github.com/krzys-h/UndertaleModTool/commit/f725572a2c1da7d2708716e8e6684e3373239df8

Will add fonts later.
