### ISSUE TITLE
Decompiler doesn't seem to know the difference between logical and bitwise negation

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#93]
I think you're already aware, but if you look at the code, sometimes you can find a `~instance_exists(...)` or something like that. However, that is not technically correct. There's a detectable difference between `~` and `!` (that should usually be `!instance_exists(...)`).

This is what a logical negation (`!`) looks like. It has the conversion to boolean before it if necessary as well:
```
conv.v.b
not.b
```

This is what bitwise negation (`~`) looks like. Here, it converts to an integer instead of a boolean, which makes sense:
```
conv.v.i
not.i
```

I'm basically just suggesting that the decompiler checks for either Int32 or Boolean in the `not` instruction, and represents it accordingly.

**Comment by colinator27** [comment]
By the way, there is also an issue with negation. This code, for example:
```
push.v self.abc
neg.v
pop.v.v self.abc
```

That decompiles with some kind of weird type cast...
```
self.abc = (variable)(- self.abc)
```

**Comment by colinator27** [comment]
Oh, I forgot an important detail that I just noticed in the compiler. Basically, bitwise negation can *also* be `not.l`, because it also uses Int64 numbers apparently.

**Comment by colinator27** [comment]
Oh, I also forgot another important detail! Apparently bitwise negation can ***also*** be `not.b`, however, at that point it is literally the same as logical negation I think.

**Comment by krzys-h** [comment]
This sounds right, thanks

**Comment by krzys-h** [comment]
Does `not.v` ever appear? That is the only one that would be probably tough to handle, as then it would depend on the variable type I guess...?

**Comment by colinator27** [comment]
Doesn't seem like it, from looking at the compiler.

**Comment by colinator27** [comment]
It would actually become the two first examples I gave on my first comment, depending on if it uses bitwise or logical negation.
