### ISSUE TITLE
Opening a game built with GameMaker runtime 2022.5.0.8 fails in two(?) ways (2022.5 unsupported?)

### ISSUE THREAD

**Issue by Dobby233Liu** [krzys-h/UndertaleModTool#945]
### Describe the bug

When you build a game with GM runtime version 2022.5.0.8, and attempt to open the built data file with UMT, the loading usually fails. Unusually, different things may happen depending on the game:
If the game has no sprites, the game loads without error, and if the game has only one (empty) sprite, I get this error:
![image](https://user-images.githubusercontent.com/28653235/170844739-ae8f2436-62a9-4bd5-b638-a04db2f3a636.png)
```
An error occured while trying to load:
BZip2 input stream bad block header
at 00000D08 while reading object UndertaleModLib.Models.UndertaleEmbeddedTexture+TexData in chuck TXTR
```
If the game has at least one object (or when a kind-of complex game is loaded), I get this error:
![error with apmrrpg](https://cdn.discordapp.com/attachments/568950566122946580/980042827977351208/unknown.png)
```
An error occured while trying to load:
Invalid value for resource ID (UndertaleChuckSPRT): -100
at 0002C0C0 while reading object UndertaleModLib.UndertaleResourceById[[UndertaleModLib.Models.UndertaleSprite, <scary assembly info>]],[[UndertaleModLib.Models.UndertaleChuckSPRT, <scary assembly info>]]
at 0002C0C0 while reading object UndertaleModLib.Models.UndertaleGameObject
while reading item 1 of 13 in a list of UndertaleModLib.Models.UndertaleGameObject in chuck OBJT
```
I have a feeling that those are different bugs, but I'm not sure if I should split this into two issues.

### Reproducing steps

1. Open a 2022.5 game, or one of the `.win` files attached below
2. See error

### Setup Details

1. UndertaleModTool version: `v:89c7ace (master)`
2. Operating system: Windows 11 build 22000.675
3. GameMaker game: I will attach `.win` files below (remove the `.txt` suffix), I also have a complex test case that I posted in `#tool-development` of Underminers server
	- Dummy game with one sprite: [umttest.win.txt](https://github.com/krzys-h/UndertaleModTool/files/8792282/umttest.win.txt)
 	- Dummy game with one sprite and one object: [umttest.win.txt](https://github.com/krzys-h/UndertaleModTool/files/8792283/umttest.win.txt)

**Comment by Miepee** [comment]
Affects Rabbit Knight as well https://m36games.itch.io/rabbit-knight

**Comment by MarijnKneppersSMC** [comment]
Also affects a private WYS beta
