### ISSUE TITLE
"popenv" doesn't seem to disassemble/decompile correctly when returning early

### ISSUE THREAD

**Issue by colinator27** [krzys-h/UndertaleModTool#95]
Take this code, for example:
```gml
with (12)
{
	i = "stuff"
	i = "abc"
	i = "123"
	exit;
	i = 1;
}
```
That disassembles as this (look at 00014):
```
00000: pushi.e 12
00001: pushenv 00019
00002: push.s "stuff"@3
00004: pop.v.s self.i
00006: push.s "abc"@5
00008: pop.v.s self.i
00010: push.s "123"@6
00012: pop.v.s self.i
00014: popenv -1048562
00015: exit.i
00016: pushi.e 1
00017: pop.v.i self.i
00019: popenv 00002
```
You see, when the code returns out of a with statement, it needs to clean up. So, it pops the environment stack so that code is executed in the correct context when it returns. This also happens with switch statements, but in that case, it pops off/discards the duplicated value (that gets checked against).

The problem is, it seems that the compiler tries to write an instruction that seems something like `popenv.d.e` instead of using relative addresses like it does everywhere else.. I'm not exactly sure on what it actually is, because the values change...

The example code I gave decompiles as this, which isn't right:
```
with(12)
{
    self.i = "stuff"
    self.i = "abc"
    self.i = "123"
}
return
self.i = 1
```
(by the way, trying to edit the instructions will cause it to fail to reassemble, due to the negative number most likely)

The main reason I'm worried about this is because I was implementing the code for these kinds of things in the GML compiler for the tool, and I have no idea how to represent those kinds of popenv instructions. And because it's a decompiler problem.

**Comment by krzys-h** [comment]
This "popenv" is issue #90, I guess it would decompile fine if we knew how to handle that, so I guess I'll just close this and track it there.
I think thanks to this example I finally see what is going on: you have ONE pushenv and TWO popenvs, which is a situation I never expected to have

**Comment by colinator27** [comment]
Oh, okay.

**Comment by krzys-h** [comment]
Changed my mind, reopening this for decomiler support :P

**Comment by krzys-h** [comment]
That was way easier than I expected

**Comment by krzys-h** [comment]
Your assembly now decompiles to
```gml
with(12)
{
    self.i = "stuff"
    self.i = "abc"
    self.i = "123"
    return
    self.i = 1
}
```
which is correct

**Comment by colinator27** [comment]
Wow, that was pretty quick. Good job.
