### ISSUE TITLE
fonts_import is not working

### ISSUE THREAD

**Issue by 21-ko** [krzys-h/UndertaleModTool#950]
### Describe the bug

No response

### Reproducing steps

1. Open .csv
2. no response

### Setup Details

UndertaleModTool_v0.4.0.4
windows10
gamemaker2

**Comment by Miepee** [comment]
Duplicate of #494 
Has been fixed since #920

**Comment by 21-ko** [comment]
> If I read this correctly, this is a duplicate of #494 and has been fixed since #920

Thank you. The problem is solved
