### ISSUE TITLE
Multiple errors when compiling in Visual Studio

### ISSUE THREAD

**Issue by ToughSun14** [krzys-h/UndertaleModTool#969]
### Describe the bug

Recently, I have had a lot of errors pop up when trying to compile the latest commit to this tool in Visual Studio. I'm not sure why this happens, but it's been happening for a while with a lot of recent commits. I even tried some advice from Grossley and "cleaning" the project files, but still some errors popped up.
Here is the compile log pre-clean with an error list attached: 
[UTMT_compile_log_pre-clean.txt](https://github.com/krzys-h/UndertaleModTool/files/8886940/UTMT_compile_log_pre-clean.txt)
And here is the log post-clean: 
[UTMT_compile_log.txt](https://github.com/krzys-h/UndertaleModTool/files/8886941/UTMT_compile_log.txt)
If anyone has any idea on how to fix this, please comment down below.

### Reproducing steps

(no steps can be provided as I have no idea if this happens for anyone else)

### Setup Details

The only real "detail" I can provide is I was using Visual Studio 2022 Community Edition to compile UMT.

**Comment by Miepee** [comment]
@ToughSun14 Install `git`, or comment out this line: https://github.com/krzys-h/UndertaleModTool/blob/d676dcc9d8074e038cdbe60d18bdbb1da30a85ef/UndertaleModLib/UndertaleModLib.csproj#L47

**Comment by Miepee** [comment]
I made a PR that fixes the need for the two described workarounds above. Feel free to try to compile that and see if it works
(clone `https://github.com/Miepee/UndertaleModTool.git`, after that checkout to branch `gitFix`)
