### ISSUE TITLE
"e__VW.XView" replaces values in decompiler when it shouldn't be there

### ISSUE THREAD

**Issue by warestarstuff** [krzys-h/UndertaleModTool#97]
An example is best needed to demonstrate this. In scr_encountersetup of Deltarune, the decompiler will show this for the first two lines
```
self.xx = __view_get(e__VW.XView, 0)
self.yy = __view_get(e__VW.YView, 0)
```
however, if you look in the disassembly code, you will see that the first line is SUPPOSED to read `self.xx = __view_get(0, 0)` instead of how it looks in the decompiler. As for the second line, it should read `self.yy = __view_get(1, 0)`

There are other examples of this happening in scripts, for example Deltarune's __view_get script

**Comment by colinator27** [comment]
This is done on purpose, with type inference added recently... You see, `e__VW` is an enum used in the `__view_get` function (a compatibility script that GameMaker makes when converting from GM:S 1.4 to GMS2). `XView` is 0, and `YView` is 1. It's perfectly fine.

**Comment by Myriachan** [comment]
Where does `e__VW` get defined?  The enum would be fine if the definition were available to the compiler somehow.

**Comment by krzys-h** [comment]
GMS2 generates these enums in some script file automatically when you import a GMS1 game. All enum definitions are obviously lost during compilation and replaced with just numbers. I couldn't find any proper documentation of these online and can't get the script itself without a GMS2 license, but this is what the original code looked like (just google for the constant name)
