### ISSUE TITLE
Load Error with Nomad Survival

### ISSUE THREAD

**Issue by ithinkandicode** [krzys-h/UndertaleModTool#982]
### Describe the bug

Can't load data.win for the game "Nomad Survival"

Data.win file: [data.win - Nomad Suvival.zip](https://github.com/krzys-h/UndertaleModTool/files/8912991/data.win.-.Nomad.Suvival.zip)

<img width="589" alt="ns-1" src="https://user-images.githubusercontent.com/43499897/173924272-f3ea27cb-43a3-4529-aa14-1e55cade2def.PNG">
<img width="320" alt="ns-2" src="https://user-images.githubusercontent.com/43499897/173924286-3b857115-5552-4624-9006-9f431bae053d.PNG">

### Reproducing steps

- Open the game's data.win file.
- Warning dialog box is shown immediately.
- Error dialog box is shown next.

### Setup Details

Latest UMT (0.4.0.4)

**Comment by Jacky720** [comment]
Please try updating to the [bleeding-edge builds](https://github.com/krzys-h/UndertaleModTool/releases/tag/bleeding-edge). You want GUI Windows single file true.

**Comment by Jacky720** [comment]
Cannot reproduce with commit 4c403c14dfdd761dbdccf5a879bfd868a95295fd, UndertaleModCli.
