### ISSUE TITLE
Closing the tab for a code entry does not allow it to be reopened by clicking or pressing enter on the selected entry without switching what entry is highlighted

### ISSUE THREAD

**Issue by Grossley** [krzys-h/UndertaleModTool#989]
### Describe the bug

Closing the tab for a code entry does not allow it to be reopened by clicking or pressing enter on the selected entry without switching what entry is highlighted. This makes it slightly cumbersome to reopen accidentally closed tabs.

### Reproducing steps

1. Open a code entry in a new tab.
2. Close the tab.
3. Attempt to reopen it via the sidebar.

### Setup Details

Commit 16fd4f54ef42f14f4783e3be9c0233b8eeeab5bb
Windows 11
Deltarune Chapter One (2018) windows English version.

**Comment by VladiStep** [comment]
Not only the code entry, but any type of object
