### ISSUE TITLE
Issue with undertale room layers

### ISSUE THREAD

**Issue by TheDellPC** [krzys-h/UndertaleModTool#99]
Starting from the recent Deltarune updates added (Began on update 0.1.19) , the mod tool expects a layer to be selected if adding a new object into the room. Since the undertale rooms work differently, it is now impossible to edit a room properly.
![capture](https://user-images.githubusercontent.com/33402641/49118946-a2188480-f263-11e8-95c1-f99b849b9ac5.PNG)

**Comment by krzys-h** [comment]
Thanks, I was trying to not break the Undertale side of things but apparently didn't even test it, I'll try to fix this soon
