### ISSUE TITLE
when ever i open undertale mode tale is crashes and says "undertalemod tool is not responding"

### ISSUE THREAD

**Issue by Scoileddoessomething** [krzys-h/UndertaleModTool#991]
### Describe the bug

i have a win7 64 bit with .net framewok 4.6.1 installed

### Reproducing steps

1.open undertale mod tool
2 that happens

### Setup Details

i used the newest version 
win 7 64 bit .net framework 4.6.1 installed
undertale and launching it normally

**Comment by Scoileddoessomething** [comment]
1 i will try that out 
2 idk 
3 0.4.0.4  single file

**Comment by Scoileddoessomething** [comment]
1 oh ok 
2 i will look
3 ok

**Comment by Scoileddoessomething** [comment]
i dont have the latest update

**Comment by Scoileddoessomething** [comment]
i downloaded a microsoft windows 7 update and the bleeding edge and its still now working

**Comment by Scoileddoessomething** [comment]
not*

**Comment by VladiStep** [comment]
What kind of update did you download exactly?
And is your Windows 7 has "Service Pack 1" ?
Press `Win` and `Pause` key simultaneously, and it will open the window which should have (or not have) "Service Pack 1" there.

**Comment by Scoileddoessomething** [comment]
I have service Pack 1
